### ISSUE TITLE
Add menu / keyboard shortcut to Quit LBRY app

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1002]
## The Issue
During the last refactor, looks like we lost the ability (at least on Windows/Linux) to completely quit the LBRY app from a menu/keyboard shortcut.  To quit the app right now, users need to right click on the tray icon > Quit.  

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by ykris45** [comment]
#1202

**Comment by tzarebczan** [comment]
Fixed in https://github.com/lbryio/lbry-app/pull/1202
