### ISSUE TITLE
Don't allow dark mode with automatic night mode enabled

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1005]
## The Issue
If you enable automatic night mode, the theme selection should not allow the dark theme to be chosen as it overrides the setting.  Not sure about disabling the theme selection completely - right now it makes sense because there is only 1 option, but in the future when we have more, a user may want theme X and have night mode enabled.

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
Probably better to disable the night mode setting once the dark theme has been selected than to disable the theme if night mode is selected.

**Comment by seanyesmunt** [comment]
Fixed in #1006
