### ISSUE TITLE
Install fails on Lubuntu 16.04.3 LTS

### ISSUE THREAD

**Issue by lbrydocs** [lbryio/lbry-app#1008]
I have a Lubuntu 16.04.3 LTS virtual machine I am using for testing LBRY repos. I did a git clone of this repo as root and ran the following:

DEPS=true ./build.sh
~ much stuff that works fine ~
Successfully installed virtualenv-15.1.0
/root/lbry-app/build/install_deps.sh: line 91: -E: command not found

Examining install_deps.sh I see sudo in the mix, don't know what -E option does:

if ! cmd_exists node; then
  if $LINUX; then
    curl -sL https://deb.nodesource.com/setup_8.x | $SUDO -E bash -
    $INSTALL nodejs
  elif $OSX; then
    brew install node
  else
    echo "node required"
    exit 1
  fi
fi

From the man page:

-E, --preserve-env
Indicates to the security policy that the user wishes to preserve their existing environment variables. The security policy may return an error if the user does not have permission to preserve the environment.

Is this failing because it assumes the install would be launched by a non-root user?

**Comment by lbrydocs** [comment]
Removing the -E and starting the process again does lead to a functional install of LBRY.

**Comment by liamcardenas** [comment]
Hi @lbrydocs, thanks for logging this. What happens when you try to install it without `DEPS=true`?

**Comment by tzarebczan** [comment]
@lbrydocs did you get a chance to look into this Liam's last comment? I don't think you should be cloning as root.

**Comment by lbrydocs** [comment]
Oh, sorry, I got distracted by a nice big ball of yarn. I will try this again tonight or tomorrow.

**Comment by tzarebczan** [comment]
Don't think this is an issue anymore, see new build instructions.
