### ISSUE TITLE
Claimed Reward But There's No Transaction into balance

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-app#102]
_Moved from https://github.com/lbryio/lbry/issues/628_

I have claim reward but no transaction to my balance 
![dont get reward](https://cloud.githubusercontent.com/assets/16890609/25513121/09737baa-2bfd-11e7-8618-7b9e1acd4053.png)
![dont get reward 1](https://cloud.githubusercontent.com/assets/16890609/25513134/19e47c1e-2bfd-11e7-810f-8787eb4ac978.png)
![console error](https://cloud.githubusercontent.com/assets/16890609/25513143/23d822ac-2bfd-11e7-8193-6988492911ea.png)

version 10.0rc6
Windows 7 64-bit

I think the http 400 bad request is significant here?

Slack user `gapracoolz`

**Comment by alexliebowitz** [comment]
@kauffj: you built most of the front end for rewards--is there something super obvious here, like it's treating 400s the same as success? If not, I'll look into it.

**Comment by kauffj** [comment]
I don't think there's a systemic issue here or we'd be hearing more of it. 

If you want to look into it more, ask garphacoolz for his app id, but otherwise going to close this.
