### ISSUE TITLE
Unable to reopen closed LBRY App window in macOS

### ISSUE THREAD

**Issue by Jeremy1026** [lbryio/lbry-app#1021]
## The Issue
After closing the LBRY App window by clicking the red circle in macOS It isn't possible to reopen the window without quitting the application, either by right clicking in the dock and choosing quit, or by giving the LBRY App focus and using Command+Q. Then relaunching the application.

### Steps to reproduce
1. Close the application window.
2. Attempt to reopen the application window.

### Expected behaviour
There should be a way to reload the application window without having to fully quit the application.

### Actual behaviour
The application has to be fully quit and relaunched to have the application become visible again.

## System Configuration
- Operating system: macOS High Sierra (10.13.3)

**Comment by seanyesmunt** [comment]
Fixed by https://github.com/lbryio/lbry-app/pull/1042
