### ISSUE TITLE
7pA6CSSR9zEpJiPkNYTejLeSzvoAtE85

### ISSUE THREAD

**Issue by golfjang011** [lbryio/lbry-app#1026]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
@golfjang011 was this submitted in error? Please let us know how we can help. Closing this for now.
