### ISSUE TITLE
Add startup-troubleshooting FAQ URL to daemon error screen

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1027]
## The Issue
I think it would be helpful to add a hyperlink to https://lbry.io/faq/startup-troubleshooting (or just the URL if hyperlink not possible) to the error screen when the daemon can't start up properly:
![daemonexited](https://user-images.githubusercontent.com/8120721/36334221-88120b6e-1349-11e8-8441-64033d463931.png)

This would be helpful to new app users who have trouble starting up and to existing users who may be having issues connecting to the LBRY network. If we have wallet or server issues that prevent users from starting up, we can put a notice up at the top of the [FAQ](https://lbry.io/faq/startup-troubleshooting) with the latest status. We could also possibly share the https://status.lbry.io on the FAQ.  

### Expected behaviour
Users should be pointed to a resource where they can find more information. If it's a network issue on our end, they would now be notified. 

### Actual behaviour
User is told an error was encountered 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by btzr-io** [comment]
Hyperlink not supported :disappointed: 
> Sorry to say that this is not supported. I'd recommend building your own dialog - or adding the feature to the current dialog implementation in Electron, a PR is always welcome!

https://github.com/electron/electron/issues/7111#issuecomment-245460389
