### ISSUE TITLE
Add Rewards FAQ to LBRY app

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1029]
## The Issue
Add link to Rewards FAQ (https://lbry.io/faq/rewards) in areas that mention rewards.

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by LavRadis** [comment]
looks interesting. i'll see if i can figure it out.

**Comment by tzarebczan** [comment]
One possibility: ![rewards](https://user-images.githubusercontent.com/8120721/36569501-13cc92b2-17fc-11e8-8246-ccb5fb25030e.png)

But now that I think about it, it makes it seems like it says "Rewards?" haha. Maybe something similar to shapeshift where it's underneath the text. 

Would need to be added to the Rewards screen as well, "Rewards are for human beings only. You'll have to prove you're one of us before you can claim any rewards. Read our FAQ [here](https://lbry.io/faq/rewards)"

**Comment by tzarebczan** [comment]
@seanyesmunt would adding something like this now cause you headaches in upstream redesign changes/ Should we hold off? I could see us adding a few more links to other FAQs throughout the app.

**Comment by LavRadis** [comment]
Rewards are mentioned two times as summary in the wallet, one time as a separate tab and one time as "invite" rewards. Isn't it better to have them more centralized and not everywhere?

**Comment by tzarebczan** [comment]
@LavRadis it's mentioned once in overview and once in get credits (rewards are another way to get credits), separate tab to actually list them and a separate tab for invites. How would you consolidate this? Probably not the right place for this discussion. Feel free to open a new ticket with a suggestion.

**Comment by ykris45** [comment]
@tzarebczan im finished

**Comment by ykris45** [comment]
#1041

**Comment by tzarebczan** [comment]
@ykris45 I'll let @seanyesmunt / @liamcardenas make the call on this since it may affect re-design changes per https://github.com/lbryio/lbry-app/issues/1029#issuecomment-367857134

**Comment by seanyesmunt** [comment]
Whoops. Missed this. I don't think it will hurt to add this now. Checking out your PR @ykris45

**Comment by ykris45** [comment]
@tzarebczan can it be closed.. 
@seanyesmunt thanks guys
