### ISSUE TITLE
Check channel is available before publishing, otherwise publish fails(app says it succeeds)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1031]
## The Issue
Currently, if you try to publish something to a newly created channel that's not yet confirmed, you'll run into https://github.com/lbryio/lbry/issues/893. The app shows that the publish was created successfully when in reality it fails. 

Waiting to confirm that this behavior is accurate, and if so, the app should check that the channel is available in channel_list (formally channe_list_mine) to ensure that it has been confirmed and is usable.  The API does return a 500 with an exception in this case.

### Steps to reproduce
1. Create new channel
2. Publish right after creating channel (before channel is confirmed)
3. Publish does not show in Published area and log file shows it failed

### Expected behaviour
Don't allow publishing until the channel is confirmed

### Actual behaviour
Can publish right away, publish never goes through. 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by liamcardenas** [comment]
we can use the 500 error to indicate that the user should try again soon, but what if it is another issue not related to the channel? we wouldnt want to say try again soon, if it is actually a different source of the error, no?

**Comment by tzarebczan** [comment]
Agreed, it could fail for other reasons, even if we check the exception message. 

To do this safely, we should have the daemon return a specific message/exception that indicates the channel is pending confirmation, right?

**Comment by liamcardenas** [comment]
Yes, I think that would be best

**Comment by tzarebczan** [comment]
@liamcardenas - I think this will be the best we'll get for the next version of the daemon. So it's either we don't do anything and the user will think the publish succeeded but it will never show up, or we ask them to try again, and if this problem persists, go to https://lbry.io/faq/support.

**Comment by daovist** [comment]
I tried to reproduce this situation many times but it kinda worked for me. It gave me the incorrect message that the file had been added, but less than a second later I got an error message:

`The following error occurred when attempting to publish your file: Cannot publish using channel @muhflair`

I waited a minute and hit Publish again and it went fine. The error could be more specific as you've mentioned above.

**Comment by kauffj** [comment]
@tzarebczan do you know what ticket on lbryio/lbry is the root cause of this issue?

**Comment by tzarebczan** [comment]
@kauffj Originally https://github.com/lbryio/lbry/issues/893 and then I opened one on Lbryum-server per Jack - https://github.com/lbryio/lbryum-server/issues/53

**Comment by tzarebczan** [comment]
@daovist that's the correct (current) behavior you are experiencing - the daemon will return that error if the channel isn't confirmed in a block. If you try again later and it is confirmed, it will go through. Not sure when the issues referenced in my previous comment will be addressed, which is why I opened this ticket to check if the channel is in a block (which means it's in channel_list). Not sure exactly what we should be telling the user, but I think it's better than just erroring out.

**Comment by tzarebczan** [comment]
This will be fixed by: https://github.com/lbryio/lbry-app/pull/1481
