### ISSUE TITLE
[redesign] implement dark mode

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-app#1034]
This will include cleaning up all the color variables/removing what we don't need

**Comment by btzr-io** [comment]
@seanyesmunt Do you need any help with this ? 
I'm currently fixing the dark theme on `redesign` just to see how will look :eyes: 

BTW `redesign` is looking awesome :+1:

**Comment by seanyesmunt** [comment]
Yeah if you are interested I would love some help with this! Colors across the `redesign` branch are missing a lot of stuff. I was planning on working on this last so feel free to make a PR to `redesign` if you would like!

You can check out http://lbry.zzk.fr/explore to get an idea of the new dark mode colors.

**Comment by seanyesmunt** [comment]
@btzr-io I think currently there are a fair bit of color variables that aren't being used. Feel free to delete those/rename any that are confusing.

I know I've used color variables instead of a specific element variables as I've been working on this just to save some time. Ex:
```
.btn {
  background-color: var(--color-primary);
}
```
which should be something like
```
.btn {
  background-color: var(--button-background);
}
```

Same for `color: var(--color-black)` instead of `color: var(--text-color)`

Let me know if you have any questions!
