### ISSUE TITLE
Pressing 'OK' on 20 free credits dialog did not close it.

### ISSUE THREAD

**Issue by Rob-pw** [lbryio/lbry-app#105]
"So I’ve earned my 20 free credits, and now I can’t exit the final screen… I press “OK” and it’s not registering…"
"Clicking “OK” didn’t close the overlay. Restarting the program bypassed it. Credits remained."

Courtesy of @cardiff

**Comment by alexliebowitz** [comment]
Thanks. Also noted by @lyoshenka [here](https://github.com/lbryio/lbry-app/issues/101) and fixed in [this PR](https://github.com/lbryio/lbry-app/pull/108).
