### ISSUE TITLE
Eliminate or severely reduce typing timeout to trigger search

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-app#1052]
Obviously, many people are still confused about how to search.

I'm still not ready to fully cave on this, but it's clear there is a problem.

As a starting place, let's try eliminating the timeout to transition the user to the search page. As soon as they type, take them there. We may want to still delay subsequent searches for performance reasons (sending a search on every keypress will trigger a lot of XHR requests).

**Comment by tzarebczan** [comment]
Think this is addressed in the redesign.
