### ISSUE TITLE
Switch Back to node-keytar

### ISSUE THREAD

**Issue by IGassmann** [lbryio/lbry-app#1055]
The project dependency `node-keytar` has recently merged https://github.com/atom/node-keytar/pull/67. The fork `keytar-prebuild` is now unnecessary for https://github.com/lbryio/lbry-app/commit/aeb43ff1a06f06624d7c110bb37a1fff6039c806.

**Comment by tzarebczan** [comment]
Wonder if this behavior will persist: https://github.com/lbryio/lbry-app/issues/386#issuecomment-367030074
