### ISSUE TITLE
Can't create a new identity 

### ISSUE THREAD

**Issue by bobmcdouble3** [lbryio/lbry-app#106]
## The Issue
When ever I try to create a new identity, it says "Unable to create channel due to an internal error." I have tried with a bunch of usernames!

### Steps to reproduce
1. Goto the publish tab
2. Under identity, click new identity 
3. Fill out the rest, then click "Create Identity", it will not work

### Expected behaviour
This should create my username/identity

### Actual behaviour
It says "Unable to create channel due to an internal error."

## System Configuration
- LBRY Daemon version: 0.10.0rc15
- LBRY App version: 2.7.21
- LBRY Installation ID: ???
- Operating system: Ubuntu-16.04-xenial

**Comment by alexliebowitz** [comment]
I can't duplicate either on the latest RC or a dev build. Do you have any errors in your JS console? If you can copy and paste or send a screenshot, that would help me figure out what's different between my installation and yours. (Easiest way to get to the dev tools is just right click anywhere on the page -> Inspect Element.)

**Comment by kauffj** [comment]
I believe this is fixed.
