### ISSUE TITLE
Record subscriptions in internal-apis

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-app#1065]
- [ ] (3) Do estimate
- [ ] Add some catch so existing subscriptions are not lost
- [ ] Add (un)subscribe endpoint that accepts multiple subscriptions
- [ ] Add fetch all subscriptions endpoint
- [ ] Make sure users dont lose their current subscriptions when this goes live

**Comment by lyoshenka** [comment]
This is also a duplicate of lbryio/internal-apis#238

238 also says that users should be emailed when new content is available in channels they subscribe to. I'm guessing that's a separate issue. Are you planning to do that afterwards?

**Comment by kauffj** [comment]
It'd be very good to just get the bare minimum endpoint up here, we're losing information we'll never get back without it. The bare minimum endpoint is likely < 2 hours of work (if you know internal-apis already).

**Comment by seanyesmunt** [comment]
Starting on this

**Comment by tzarebczan** [comment]
@seanyesmunt was everything completed in https://github.com/lbryio/internal-apis/pull/314 ? Can we close this?

**Comment by seanyesmunt** [comment]
Yes that can be closed.
