### ISSUE TITLE
Move authentication and analytics as early as feasible in run process

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-app#1073]
Currently all analytics and authentication functions happen after the daemon is ready. Specifically, they happen in `doDaemonReady()`.

It'd be good if this set up could happen before the daemon is ready, so we can learn about the number of users that run the app and get frustrated or close it before the daemon is ever ready.

**Comment by liamcardenas** [comment]
I don't think there is a limit how early we can move these, for the simple reason that we can collect information, store it, and then log it once analytics/authentication become available.

**Comment by kauffj** [comment]
@liamcardenas that wouldn't solve the problem of people closing the app before it gets to that step.

**Comment by liamcardenas** [comment]
Good point, in that case, assuming we can't get analytics to load at startup, we can log via the api/rest.

**Comment by kauffj** [comment]
All that I want to happen to consider this ticket completed is for `doAuthenticate` to be called as soon as the daemon has launched, but before it is ready (i.e. as soon as `lbry.status()` returns). 

Ideally we wouldn't block the call to `doAuthenticate()` for the daemon to be responding, but I don't believe there is a way to get the daemon install id without it being responsive.
