### ISSUE TITLE
tell user that turning off diagnostic makes them ineligible for rewards

### ISSUE THREAD

**Issue by liamcardenas** [lbryio/lbry-app#1089]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
A really simple fix for now would be to just add a message in the label on
the settings page. That should be added before the release

**Comment by LavRadis** [comment]
Something like this:

<section className="card">
          <div className="card__content">
            <h4>{__('Share Diagnostic Data')}</h4>
          </div>
          <div className="card__content">
            <FormRow
              type="checkbox"
              onChange={this.onShareDataChange.bind(this)}
              defaultChecked={daemonSettings.share_usage_data}
              label={__(
                'Help make LBRY better by contributing analytics and diagnostic data about my usage'
	      helper={__(
                'If you disable the sharing of diagnostic data, you will not be eligible to receive LBRY rewards.  '
              )}
            />
          </div>
        </section>

I didn't want to make PR since my previous PR is still under review and I still don't have local dev version.

**Comment by tzarebczan** [comment]
When a user tries to claim the reward and it fails due to the setting, they should be alerted to it.

**Comment by tzarebczan** [comment]
Fixed in https://github.com/lbryio/lbry-app/pull/1116
