### ISSUE TITLE
Lbry

### ISSUE THREAD

**Issue by lekhanh121** [lbryio/lbry-app#1098]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
@lekhanh121 can we help you with something? If you require assistance with the LBRY app, please send us an email to help@lbry.io or visit us in #help on [Discord](https://chat.lbry.io)
