### ISSUE TITLE
Setup lifecycle for push builds in build.lbry.io/app

### ISSUE THREAD

**Issue by IGassmann** [lbryio/lbry-app#1102]
Every push build is kept in [http://build.lbry.io/app/](http://build.lbry.io/app/). Old builds aren't being used anymore so no need to keep them. The exception is [http://build.lbry.io/app/release/](http://build.lbry.io/app/release/). **This folder should not be deleted.** It's being used for app updates.

**Comment by nikooo777** [comment]
done!
