### ISSUE TITLE
Sort by Title doesn't work correctly in some instances

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1115]
## The Issue
See image below when sorting by title. I've seen this on another machine and @jsigwart has also noticed it.

<img width="489" alt="title sort" src="https://user-images.githubusercontent.com/8120721/37541536-5f9711fe-2931-11e8-82af-9012f210216c.PNG">

### Steps to reproduce
1. download a few items
2. sort by title
3. check result

## System Configuration

 

- LBRY Daemon version: 0.19.0
- LBRY App version: 0.21rc4

- LBRY Installation ID:
- Operating system:

**Comment by liamcardenas** [comment]
@tzarebczan any idea in what instances this doesn't work? I last touched that code and last time I checked, it did work

**Comment by tzarebczan** [comment]
@liamcardenas didn't get into the details, but you can see some of the claims from the screenshot above to reproduce. Starwars and Ripple claims are out of order.

**Comment by kauffj** [comment]
@liamcardenas I _think_ the problem may stem from missing metadata. Check the case where a piece of content has no title and it falls back to the URL name.

**Comment by kauffj** [comment]
@tzarebczan if you could update ticket with the exact URIs from a failure case that would be helpful.

**Comment by btzr-io** [comment]
A good example of  failure case: `lbry://audio#be63b86b4794b7cd83e9da8b8005836c342a2b5c`
claim_name: `audio`, title: `Rainy Mood`
