### ISSUE TITLE
Improper behavior of the search bar

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry-app#112]
## The Issue
When searching for content, if CTRL+a is pressed to select the whole search term before the search is complete, when the search completes the selection is lost
### Steps to reproduce
1. search anything
2. immediately proceed to step 3
3. press CTRL+a and type anything

### Expected behaviour
any term written before should be replaced with the new inserted text and a new search should be started

### Actual behaviour
when the search completes, if you had typed ctrl+a but not yet typed a letter, the search terms are removed and reinserted thus losing the selection.
an user will probably not notice until finding out they appended the new search term instead of replacing it.

## System Configuration

 

```
{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "build": "rc",
    "ip": "193.246.121.22",
    "lbrynet_version": "0.10.3rc1",
    "lbryschema_version": "0.0.4",
    "lbryum_version": "2.7.21",
    "os_release": "4.8.0-51-generic",
    "os_system": "Linux",
    "platform": "Linux-4.8.0-51-generic-x86_64-with-Ubuntu-16.10-yakkety",
    "processor": "x86_64",
    "python_version": "2.7.12"
  }
}
```

**Comment by kauffj** [comment]
This is fixed.
