### ISSUE TITLE
Abandoning deposit on update

### ISSUE THREAD

**Issue by oakey22** [lbryio/lbry-app#117]
## The Issue
When updating a claim the deposit is returned to the wallet as if it is a new claim and the old one is abandoned. If you  enter 10 LBC when you have a previous claim of 500, the 500 gets returned and 10 is deducted.

### Steps to reproduce
1. Make claim on lbry://anyurlhere
2.Update claim for lbry://anyurlhere

### Expected behaviour
Should update claim and not abandon the old one and not return the deposit.

### Actual behaviour
Returning original deposit even on an update

## System Configuration

{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "build": "rc",
    "ip": "86.145.xx.xxx",
    "lbrynet_version": "0.10.3rc1",
    "lbryschema_version": "0.0.4",
    "lbryum_version": "2.7.21",
    "os_release": "4.4.0-75-generic",
    "os_system": "Linux",
    "platform": "Linux-4.4.0-75-generic-x86_64-with-Ubuntu-16.04-xenial",
    "processor": "x86_64",
    "python_version": "2.7.12"

- LBRY App version: 0.10.0
- Operating system: Linux Ubuntu 16.04

**Comment by kaykurokawa** [comment]
This is the expected behavior for updates. 
Amounts stored in the claim before the update should be returned to you, if you update the claim amount to be more than the previous claim.

**Comment by oakey22** [comment]
The problem is when you only have say 10 LBC in your wallet and you have a claim already of 100LBC it will not let you update it to 100 LBC as you do not have over 100 in your account, you have to set an amount that lower which is silly.

**Comment by kauffj** [comment]
@kaykurokawa and @oakey22 I think you're both right. Kay is speaking of things at the API level, where this is probably proper behavior, but we need to improve this at the app level, where this is clearly a UX issue.

**Comment by kaykurokawa** [comment]
I can confirm that if you lack the LBC in your wallet but have enough in a claim, it will not let you update. 

This is a bug in lbrynet where the app is being overzealous in checking for amounts. There is support in lbryum to let you update by using the amount already contained in a claim.

**Comment by tzarebczan** [comment]
@kaykurokowa @finer9 is this on the list of features / to do?

**Comment by kauffj** [comment]
I don't think anything can be done here without a change to lbrynet, so I moved it there: https://github.com/lbryio/lbry/issues/748
