### ISSUE TITLE
Slow response of "Choose limit" at [Max Purchase Price] page when switching between "No limit" and "Choose limit"

### ISSUE THREAD

**Issue by namujan78** [lbryio/lbry-app#1176]
## The Issue
Slow response of "Choose limit" at [Max Purchase Price] page when switching between "No limit" and "Choose limit": "Choose limit" change to "Limit to xxxx LBRY or USD" for some seconds or not changed... and same for vice versa.

### Steps to reproduce
1. Go to [SETTINGS] page
2. Switch between "No limit" and "Choose limit" for some times (twice or more)

### Expected behaviour
"Choose limit" will change to "Limit to xxxx LBRY or USD" or vice versa immediately.
It should work correctly as "Single-click purchasing of content less than..." at below "Purchase Confirmations" parts. The switching is very smooth.

### Actual behaviour
"Choose limit" change to "Limit to xxxx LBRY or USD" for some seconds or not changed... and same for vice versa.

## System Configuration
- LBRY Daemon version: 0.19.1
- LBRY App version: 0.21.2
- LBRY Installation ID: N/A
- Operating system: Windows (Windows-10-10.0.16299)
- Wallet (lbryum): 3.2.0

## Anything Else
It should work correctly as "Single-click purchasing of content less than..." at below "Purchase Confirmations" parts. The switching is very smooth.

## Screenshots
N/A

**Comment by btzr-io** [comment]
@tzarebczan also fixed ( I can't recreate this issue on master)

**Comment by tzarebczan** [comment]
@btzr-io thanks!

**Comment by tzarebczan** [comment]
@namujan78 I invited you to our early testers group so you can try this out in the redesign.

**Comment by namujan78** [comment]
@tzarebczan Where I can find out the invitation?
By the way, this issue seem was fixed in "App | 0.21.3"

**Comment by btzr-io** [comment]
@namujan78 See the `#early-testing` channel on `discord`
