### ISSUE TITLE
[redux] Credit amount showing as 0

### ISSUE THREAD

**Issue by MaxiBoether** [lbryio/lbry-app#119]
## The Issue

When using the redux branch of the client, my LBC amount in the header is shown as 0 even though I've got more credits which are shown correctly when using the latest master branch sourcecode. Both are built by myself, so that can't be the issue.

### Steps to reproduce
1. Use master branch client, get some credits.
2. Switch to redux branch.
3. Check credit amount

### Expected behaviour
Show the same LBC amount on both versions

### Actual behaviour
220 LBC vs 0 LBC

**Comment by kauffj** [comment]
Redux branch is a WIP and there are many known issues. Appreciate the well done bug report, but they're not necessary for this branch at this time. We'll have a draft release of redux coming out fairly soon, though.

**Comment by MaxiBoether** [comment]
Only reason I posted it here was because Mathew Waller on Slack told me to raise an issue on Github about this one. But whatever, if you don't want it that's fine too :)

**Comment by kauffj** [comment]
Thanks, I'll let him know.

@lyoshenka maybe we should consider some kind of tag to indicate whether or not we want public feedback/issues on a branch?
