### ISSUE TITLE
Mac: Black screen after maximizing LBRY and then closing

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1200]
## The Issue
On Mac, if you maximize the LBRY app window and then click the close button, you end up with a black screen with no way of bringing LBRY back up. On 0.20.0, the window would just disappear without a way to bring it back up. 

Possibly related: https://github.com/electron/electron/issues/6033

### Steps to reproduce
1. Maximize Window
2. Close the window
3. Blackscreen

### Expected behaviour
Window show close to tray

### Actual behaviour
Black screen

## System Configuration

 

- LBRY Daemon version: 0.19.1
- LBRY App version: 0.21.2
- LBRY Installation ID:
- Operating system: Mac

**Comment by miikkatu** [comment]
One solution would be to disable the close action (cmd+W) when the window is in fullscreen mode. At least Discord Mac app behaves like this as well.

The code to be changed would be in src/main/createWindow.js in window.on('close'... part.

`
if (!window.isFullScreen()) {
  window.hide();
}`

**Comment by miikkatu** [comment]
There was a better solution, and a pull request (#1235) was made.
