### ISSUE TITLE
Publish: Description section is confusing

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1201]
## The Issue
When publishing, the title/thumbnail/description section is grouped and you need to scroll to add a description - this is confusing it's not clear that you need to scroll down

![des](https://content.screencast.com/users/thomas.zarebczan/folders/Snagit/media/305a088b-2a12-4af9-b12d-55ab3b65bad8/03.28.2018-13.14.png)

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
Already created an issue for this one

**Comment by seanyesmunt** [comment]
#1195

**Comment by tzarebczan** [comment]
@seanyesmunt my bad, I should check those first :p
