### ISSUE TITLE
Search query to address errors out

### ISSUE THREAD

**Issue by daovist** [lbryio/lbry-app#1208]
This applies to the redesign.

## The Issue

When I search and click for search results, it works fine. But when I search and click the address I get ReferenceError: normalizeURI is not defined

### Steps to reproduce
1. enter query in search bar
2. click first option: lbry://[search_query]

### Expected behaviour
Display content or not-found

### Actual behaviour
App crashes

## System Configuration

 

    "build": "release",
    "lbrynet_version": "0.19.1",
    "lbryschema_version": "0.0.15",
    "lbryum_version": "3.2.0",
    "os_release": "4.13.0-37-generic",
    "os_system": "Linux",
    "platform": "Linux-4.13.0-37-generic-x86_64-with-Ubuntu-16.04-xenial",
    "processor": "x86_64",
    "python_version": "2.7.12"

## Screenshots

![redesign search bug](https://user-images.githubusercontent.com/34498824/38099654-31410dec-3349-11e8-96e4-eab29177eba6.png)

**Comment by tzarebczan** [comment]
@daovist, Sean is aware, I filed a similar issue here: https://github.com/lbryio/lbry-app/issues/1204
