### ISSUE TITLE
Button spacing on LBC required modal

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1209]
## The Issue
The buttons are too close together, see below. The blue/yellow shaded LBC amounts seem a bit off also - LBC value is not centered and the oval is not inline with the text. 

Also, the white button on white background is hard to see (I'll open a separate issue for this) 

![spacing](https://user-images.githubusercontent.com/8120721/38102279-c54e4a8e-3350-11e8-9ea4-19bbe1e9869a.png)

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
Mildly cleaned up in this #1288 but can use some more styling
