### ISSUE TITLE
Publish - choose price section

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1210]
## The Issue
1) The price option is shown even when the "Free" option is selected

2) When setting a price, clicking the down arrow clears out the field and adds a '5' place holder

3) Cannot type 0: i.e. 0.01, or even .01

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by ykris45** [comment]
https://github.com/lbryio/lbry-app/pull/1232
