### ISSUE TITLE
Task launches but user interface does not appear [Win]

### ISSUE THREAD

**Issue by h3298** [lbryio/lbry-app#1214]
**Win7 64 bit - LBRY App version: 0.21.2
no errors logged in Event Viewer**

**Comment by tzarebczan** [comment]
@h3298 does the lbrynet-daemon.exe task launch too? Can you see if there are any log files? https://lbry.io/faq/how-to-find-lbry-log-file

Are you running any antivirus/firewall software? I test on Windows 7 64 bit last week and it worked fine. Come over to #help on https://chat.lbry.io and we can try to work this out.

**Comment by h3298** [comment]
> does the lbrynet-daemon.exe task launch too?
  
**NO**

> https://lbry.io/faq/how-to-find-lbry-log-file
> %localappdata%\lbry\lbrynet (or %appdata%\lbrynet if you originally installed v0.14 or earlier)

**%localappdata%** is valid in explorer on Win 7 but **%localappdata%\lbry\lbrynet** is not existing
(and I did **not** install 0.14 or earlier)

"**cd %appdata%\lbry**" is valid in terminal.  "**%appdata%\lbry**" does **not** work in Explorer on Win 7 SP2.
("no items match your search")

The path exists -  "**C:\Users\me\AppData\Roaming\LBRY**" but the directory is empty (0 files)

> Are you running any antivirus/firewall software?

 **NO**

> Come over to #help on https://chat.lbry.io and we can try to work this out.

I did use chat but no one responded.  What are the normal business hours? (UTC)

**Comment by tzarebczan** [comment]
I think someone did respond to you in the #help channel if I recall. Feel free to DM me there directly at @jiggytom and we'll take a look.
