### ISSUE TITLE
Cannot edit metadata only (without reuploading new file)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1219]
## The Issue
If you try to edit a claim without selecting a source file, you get: `Error message: no source provided to publish`. I believe we need to pass the source information which includes source, source type, version and content type which are all available in file_list and claim_list_mine. When editing, a file may not necessarily be in file_list, so claim_list_mine would be the safest bet here. 

```
"sources":  {
      "source": "ae8e94d9d1090c32216e29a2e0e576f02f241b3b72769da5e11191ba2680f1c8c58b8841a6dd7dc8b2c6e655b1df288c",
      "sourceType": "lbry_sd_hash",
      "version": "_0_0_1",
      "contentType":"image/jpeg"
```
### Steps to Reproduce
1.
2.
3.

### Expected Behaviour
Tell us what should happen.

### Actual Behaviour
Tell us what happens instead.

### Suggested Solutions
Tell us your suggested solutions if you have any.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
@seanyesmunt can edit now, but the file stays in pending mode.

**Comment by seanyesmunt** [comment]
Closing this. I will create a new one just for pending

**Comment by tzarebczan** [comment]
Reopening..this is happening agian
