### ISSUE TITLE
Fix or remove tipping on channels

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1227]
## The Issue
A tip button was added to channel pages in the redesign but it doesn't work properly. If it's not too much effort, we should fix it and if not, we should remove it. 

To fix: modal needs to be updated - no need to mention a piece of content because it's the channel being tipped. Also, should say the channel name instead of anonymous. 

![channeltip](https://user-images.githubusercontent.com/8120721/38150530-55ed184a-342d-11e8-9ddd-5c18adbe3e63.png)

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
Just removed it for now
