### ISSUE TITLE
share diagnostic data doesnt wrap to small screen

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry-app#1228]
## The Issue
some word doesnt wrap on small screen , for example : if user have 1024*768 screen resulution . 

### Expected Behaviour
would be nice its supported many monitor resulution

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

## Screenshots

![image](https://user-images.githubusercontent.com/26609573/38152049-f444e754-348f-11e8-9e28-dcfefd523074.png)

**Comment by miikkatu** [comment]
Suggested fix is in the PR referenced above.
