### ISSUE TITLE
cannot upload or download

### ISSUE THREAD

**Issue by iateadonut** [lbryio/lbry-app#123]
## The Issue
I cannot upload or download, but can resolve.

### Steps to reproduce
1.
If i do this:
lbrynet-cli resolve uri=what
{
  "claim": {
    "address": "bMavvzXG2XT5GRK4kgQCFop1B5XvHRJPye",
    "amount": "1",

I receive the feedback no problem.

But when I try to 'get', I get a timeout error:
lbrynet-cli get uri=what    
{
  "error": "Timeout"
}

same with other methods for downloading:
lbrynet-cli blob_get blob_hash=c37676385d73f6e15802744d7c994c2858cf0766bbec0f4ba5468861e6f4b51a483a2795d85da916e9082f4231099837
ERROR: Blob (c37676385d73f6e15802) download timed out

i'm using the linux 10.2 version on ubuntu 16.04.

I've also tried to upload using the GUI version.  The GUI version also cannot download, and when I tried to upload, it took money for my lbry://name but I was not able to upload.

## System Configuration

 

For the GUI, clicking on 'HELP' did not bring me to a help page so I don't have the version info.

for the daemon:

lbrynet-cli version
{
  "build": "release",
  "ip": "210.183.116.40",
  "lbrynet_version": "0.10.2",
  "lbryschema_version": "0.0.4",
  "lbryum_version": "2.7.21",
  "os_release": "4.4.0-47-generic",
  "os_system": "Linux",
  "platform": "Linux-4.4.0-47-generic-x86_64-with-LinuxMint-18-sarah",
  "processor": "x86_64",
  "python_version": "2.7.12"
}

**Comment by tzarebczan** [comment]
Is this related to your other issue where it might be a firewall problem? If so, can you close this one.
