### ISSUE TITLE
format of message when diagnostics disabled 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1230]
## The Issue
See below - goes to a new line and Settings is not formatted. 
![diag](https://user-images.githubusercontent.com/8120721/38152905-f536853a-3437-11e8-8172-d9256f3f795e.png)
Old:
![diag2](https://user-images.githubusercontent.com/8120721/38152908-f910592e-3437-11e8-92e4-5cf860eb7322.png)

### Suggested Solutions
Tell us your suggested solutions if you have any.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by ykris45** [comment]
https://github.com/lbryio/lbry-app/pull/1212 see my closed PR sir @tzarebczan

**Comment by tzarebczan** [comment]
Thx, missed that one!

**Comment by ykris45** [comment]
you welcome . can you reopen my Close pr sir

**Comment by tzarebczan** [comment]
Sean said he already fixed it in his...

**Comment by tzarebczan** [comment]
Confirmed fixed!
