### ISSUE TITLE
App opens to state when it was closed 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1231]
## The Issue
When opening the app (after a full shutdown), it goes back to the last state/area you were in (i.e. if you were in the wallet, it will re-open into the wallet). We discussed this briefly on Friday and don't want that to be the default behavior - it should always open to the explore page.

I think this is what is messing with opening of hyperlinks when the app is closed. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
@seanyesmunt @tzarebczan I'm not sold that it should always go to Explore. I think the closest analog application to LBRY is a web browser. Chrome retains the last page(s) I was on when closed, and exhibits this behavior even when on settings (e.g. if I have a single tab open on settings and quit chrome, chrome will be back on settings when re-opened).

**Comment by tzarebczan** [comment]
An option would work too!

**Comment by tzarebczan** [comment]
Closing for now, it's currently working as expected.
