### ISSUE TITLE
Make featured content badge red

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1250]
## The Issue
We used to have a red rocket, so now we should make the badge red to make it stand out a bit more. 
![badge](https://user-images.githubusercontent.com/8120721/38217799-98187846-369d-11e8-9d01-301c03d5ef57.png)

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by ykris45** [comment]
@tzarebczan im finished.hehe
