### ISSUE TITLE
Alignment on Transaction page

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1253]
## The Issue
The alignment between Show and the dropdown is off and the dropdown styling seems too plain.

![alignment](https://user-images.githubusercontent.com/8120721/38218463-e816bb80-369f-11e8-8a59-246ee81d45eb.png)

Also on unlock/trashcan icon: https://www.screencast.com/t/ZJxJuNuUi

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
Reopening: https://www.screencast.com/t/GXRyyvzcUWTn

**Comment by btzr-io** [comment]
Fixed on master
