### ISSUE TITLE
Paginated search results

### ISSUE THREAD

**Issue by jsigwart** [lbryio/lbry-app#1261]
## The Issue
Any search returns exactly 10 results. I would like to have the ability to see more than 10 results, and for the results to be paginated with navigation to move forward and backwards through the pages of results. 

## System Configuration

- LBRY Daemon version: 0.19.1
- LBRY App version: 0.21.2
- LBRY Installation ID: 5eFxsAfhBFTKA5byNFVkGL5Lu5owWzQFthzKjRkxN2iUzWh2XNKLJAiv82mxAcq3AU
- Operating system: Mac OS X 15.6.0

{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "build": "release",
    "ip": "xx.xx.xx.xx",
    "lbrynet_version": "0.19.1",
    "lbryschema_version": "0.0.15",
    "lbryum_version": "3.2.0",
    "os_release": "15.6.0",
    "os_system": "Darwin",
    "platform": "Darwin-15.6.0-x86_64-i386-64bit",
    "processor": "i386",
    "python_version": "2.7.13"
  }
}

**Comment by kauffj** [comment]
Did we lose this feature? It used to page

**Comment by tzarebczan** [comment]
I don't think we ever showed more than 10 results on search. This is something @seanyesmunt is aware of .

**Comment by tzarebczan** [comment]
Thanks @tiger5226, was just about to post here too haha. Bonus points for you, thanks for following up!

**Comment by tiger5226** [comment]
The changes for lighthouse are now live and pagination is working from the api. 

However, in testing the app our original expectations are true. The app does not support pagination in search results. Excited to get this in the app! Search is soooo much better now, and users are missing out because they can only discover the tip of the iceberg(10 results). Go app team!!

**Comment by tzarebczan** [comment]
With the setting for # of search results, we don't believe we need pagination. @tiger5226 what do you think?

**Comment by tiger5226** [comment]
I think it is much less important, but probably a nice to have. If you want to see 1000k results the loading of that will take a minute. Pagination allows for faster iteration of results. It is more of a formality now though. Happy to close this for now until we get through some of the more important issues. We can reopen if this  becomes more important.
