### ISSUE TITLE
File page controls are easy to miss / unclear

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1272]
## The Issue
The app redesign has file controls for download, opening in background, removing and reporting are now in the top right of the screen. They are easy to miss and may be confusing in terms of function to new users. A mouseover would definitely help, unless we just want to add text. 

![file controls](https://user-images.githubusercontent.com/8120721/38318936-95bf199e-37fe-11e8-9941-a9f0d8448004.jpg)

### Expected Behaviour
Tell us what should happen.

### Actual Behaviour
Tell us what happens instead.

### Suggested Solutions
Tell us your suggested solutions if you have any.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by miikkatu** [comment]
A suggested solution (with screenshots) is in this pull request.
