### ISSUE TITLE
Add flair to the snackbar to go along with the redesign

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1279]
## The Issue
Snackbar stayed the same, we should add some flair to it! 

![snackbar](https://user-images.githubusercontent.com/8120721/38335588-c6f9deee-382c-11e8-9f50-8b0e6282bef5.jpg)

@nizuka3 thoughts? 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by miikkatu** [comment]
PR #1313 has a suggested implementation.

**Comment by tzarebczan** [comment]
Closed via https://github.com/lbryio/lbry-app/pull/1313
