### ISSUE TITLE
"Put something here" links to claim instead of Publish page

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1284]
## The Issue
When searching a URL that is unused, you are told "put something here" which links to the URL. This should go to the Publish page with the URL filled in. The old app would go to Publish, but not fill in the URL. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by miikkatu** [comment]
A pull request was added to address this issue.

**Comment by tzarebczan** [comment]
Fixed in #1303
