### ISSUE TITLE
Claim option missing in Invites screen

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1290]
## The Issue
The claim option is missing, see below.
![invites](https://user-images.githubusercontent.com/8120721/38379682-73cce3b2-38cf-11e8-8944-0cabca3f595b.jpg)

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
In my case, my reward invite was already claimed.

**Comment by seanyesmunt** [comment]
Discussed with Tom on slack. Fairly certain this is because he claimed more than one invite. It should work with one (I see it).

Worth coming back to when we add support for multiple invites

**Comment by seanyesmunt** [comment]
Going to close it for now.
