### ISSUE TITLE
file not downloading when stream initiated in app

### ISSUE THREAD

**Issue by maximumplank** [lbryio/lbry-app#130]
## The Issue
When attempting to stream a video, the download appears to hang before any data is received. A file is created in the download directory but it sits at 0 bytes.

### Steps to reproduce
1. launch lbrynet-daemon (lbrynet-daemon-v0.10.3rc4)
2. launch lbry app (LBRY_0.10.0_amd64)
3. navigate from discover page to video content page
4. press play

### Expected behaviour
video should begin downloading in daemon and playing after ~30s

### Actual behaviour
Download begins but no data is received. The daemon reports the download is proceeding, sending a message every second "lbrynet.lbrynet_daemon.Downloader:78 Downloading stream data (### seconds)." The '###' counts up from 1 second until it hits 180, at which time the download times out and the daemon reports we already have the file. After some time (180 seconds?) the loading screen in the browser changes to contain the following message: "Started 1 - capital. - Pillsbury Boy.mp4, got 0/29 blobs, stream status: running"

After navigating away from the content page and back, "0% Complete" is displayed where the "Download" link normally sits, and I'm greeted with the "Started 1 - capital. - Pillsbury Boy.mp4, got 0/29 blobs, stream status: running" message within seconds of pressing play.

The file is indeed present in the download directory, but sized at 0 bytes. 

## System Configuration
{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "build": "rc",
    "ip": "73.158.155.244",
    "lbrynet_version": "0.10.3rc4",
    "lbryschema_version": "0.0.4",
    "lbryum_version": "2.7.22",
    "os_release": "4.4.0-78-generic",
    "os_system": "Linux",
    "platform": "Linux-4.4.0-78-generic-x86_64-with-Ubuntu-16.04-xenial",
    "processor": "x86_64",
    "python_version": "2.7.12"
  }
}

- LBRY Daemon version: v0.10.3rc4
- LBRY App version: LBRY_0.10.0
- LBRY Installation ID: unsure
- Operating system: Ubuntu 16.04
(just noticed the 10.1rc1 release is available for the app, will attempt to reproduce on new release)

## Anything Else
Unsure if related, this is the state of my daemon after the preceding events: http://imgur.com/dhVo2eN

## Screenshots
See http://imgur.com/a/Hg5SV for illustrative screenshots. It's more than one or two but I wanted to capture the state of the client both during and after the problem first occurred.

**Comment by maximumplank** [comment]
getting similar behavior on LBRY_10.1rc1:

when starting the daemon the connection to the file in question (pillsburyboy) is initialized. However an error is thrown by EncryptedFileManager ~80ms before this happens. Could be unrelated, EFM appears to be working fine 24ms before the pillsburyboy DL is initialized.
http://imgur.com/HvYFKHA
Missing from that screenshot is a message ~140ms later:
2017-05-22 12:45:49,876 INFO     lbrynet.lbryfilemanager.EncryptedFileDownloader:32: lbry://pillsburyboy (2771b9) is unknown

And here's what happens when pressing play to start the stream in the browser:
http://imgur.com/qihHkcr

On the browser side of things everything is the same as reported above except now the message "Downloading stream... not long left now!" has replaced the loading screen message containing info about number of blobs downloaded.

**Comment by tzarebczan** [comment]
Can you try again on the latest version?

**Comment by tzarebczan** [comment]
What's the URI for the claim.. I'll try it here too

**Comment by maximumplank** [comment]
This is no longer happening in the 0.12 release.

**Comment by tzarebczan** [comment]
Please close the issue.
