### ISSUE TITLE
can't start on windows

### ISSUE THREAD

**Issue by LittleSecretary** [lbryio/lbry-app#1300]
Follow the tutorial  1.Clone this repository，2.Run $ yarn。There was a mistakeke 
Error: E:\Program Files\nodejs\node.exe exited with code 1
Error output:
prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info looking for local prebuild @ prebuilds\keytar-v4.2.1-electron-v57-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\Administrator\AppData\Roaming\npm-cache\_prebuilds\https-github.com-atom-node-keytar-releases-download-v4.2.1-keytar-v4.2.1-electron-v57-win32-x64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ C:\Users\Administrator\AppData\Roaming\npm-cache\_prebuilds\https-github.com-atom-node-keytar-releases-download-v4.2.1-keytar-v4.2.1-electron-v57-win32-x64.tar.gz
prebuild-install info unpack resolved to E:\lbry-app\node_modules\keytar\build\Release\keytar.node
prebuild-install WARN install The specified module could not be found.
prebuild-install WARN install \\?\E:\lbry-app\node_modules\keytar\build\Release\keytar.node
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.3 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'E:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\lbry-app\\node_modules\\keytar\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Administrator\\.electron-gyp\\iojs-1.8.4\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Administrator\\.electron-gyp\\iojs-1.8.4',
gyp info spawn args   '-Dnode_gyp_dir=E:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Administrator\\.electron-gyp\\iojs-1.8.4\\<(target_arch)\\iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=E:\\lbry-app\\node_modules\\keytar',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'E:\\lbry-app\\node_modules\\keytar\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "E:\\Program Files\\nodejs\\node.exe" "E:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\lbry-app\node_modules\keytar
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: C:\\WINDOWS\\system32\\cmd.exe
Arguments: /d /s /c prebuild-install || node-gyp rebuild
Directory: E:\\lbry-app\
ode_modules\\keytar
Output:
".

    at ChildProcess.childProcess.once.code (E:\lbry-app\node_modules\electron-builder-lib\node_modules\builder-util\src\util.ts:251:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
From previous event:
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at E:\lbry-app\node_modules\electron-builder-lib\src\util\yarn.ts:149:27
From previous event:
    at rebuild (E:\lbry-app\node_modules\electron-builder-lib\out\util\yarn.js:233:18)
    at E:\lbry-app\node_modules\electron-builder-lib\src\util\yarn.ts:20:11
From previous event:
    at installOrRebuild (E:\lbry-app\node_modules\electron-builder-lib\out\util\yarn.js:68:17)
    at E:\lbry-app\node_modules\electron-builder\src\cli\install-app-deps.ts:57:5
    at Generator.next (<anonymous>)
From previous event:
    at installAppDeps (E:\lbry-app\node_modules\electron-builder\out\cli\install-app-deps.js:174:17)
    at then (E:\lbry-app\node_modules\electron-builder\src\cli\cli.ts:43:10)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.args [as handler] (E:\lbry-app\node_modules\electron-builder\src\cli\cli.ts:43:10)
    at Object.runCommand (E:\lbry-app\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (E:\lbry-app\node_modules\yargs\yargs.js:1014:30)
    at Object.get [as argv] (E:\lbry-app\node_modules\yargs\yargs.js:957:21)
    at Object.<anonymous> (E:\lbry-app\node_modules\electron-builder\src\cli\cli.ts:28:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: C:\\WINDOWS\\system32\\cmd.exe
Arguments: /d /s /c electron-builder install-app-deps && node build/downloadDaemon.js
Directory: E:\\lbry-app
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "E:\\lbry-app\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

I can't find out where the problem lies，Request help。
- LBRY App version:0.21.2

**Comment by tzarebczan** [comment]
Sorry to hear you are having trouble! We recently were made aware of a bug that may require running the below command as administrator. After running it, open up a new cmd prompt and try again. 

`npm install --global --production windows-build-tools`

**Comment by ykris45** [comment]
after install this windows build tools make sure you install keytar prebuild - use code npm install keytar-prebuild and run yarn again. make sure you set npm confog set strict-ssl false

**Comment by ykris45** [comment]
$ NODE_TLS_REJECT_UNAUTHORIZED=0

**Comment by ykris45** [comment]
just add @tzarebczan comment on above. make sure install windows build tools via cmd on administrator mode..

**Comment by tzarebczan** [comment]
@LittleSecretary please let us know if that worked, closing the ticket for now. The readme has been updated to include the command I recommended.
