### ISSUE TITLE
m4v showing as an application in the app

### ISSUE THREAD

**Issue by oakey22** [lbryio/lbry-app#1302]
lbry://one was uploaded with an m4v file after being re-encoded with handbrake. This was showing as an application in the app when it is an Apple media file.

see picture below thanks to Mibo for highlighting this.
![capture](https://user-images.githubusercontent.com/22527575/38465751-bfce0a08-3b17-11e8-96e1-fb6c48431faf.png)

**Comment by oakey22** [comment]
i have uploaded the m4v file to 
lbry://happyworkingsong-enchanted-hollyoakey-lz5zl0vslc4#00a7f5fe1523d1e1264c29b4ada6e060d9d30f35

**Comment by btzr-io** [comment]
Related issue: https://github.com/lbryio/lbry-app/issues/863

**Comment by btzr-io** [comment]
@oakey22 what's the `mimetype` from the original  file ?

**Comment by tzarebczan** [comment]
@btzr-io how do you find the mimetype? Might be able to download the file  from lbry://happyworkingsong-enchanted-hollyoakey-lz5zl0vslc4#00a7f5fe1523d1e1264c29b4ada6e060d9d30f35 to check.

**Comment by tzarebczan** [comment]
Closing in favor of #863
