### ISSUE TITLE
App-side changes to allow reward changes without app-side changes

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-app#1329]
1. Display the rewards in the order returned by api.lbry.io rather than the app-coded order.
1. Look for a reward property on an individual reward called `reward_notification` that is displayed to the user when they earn a reward.
1. Have a fall-back notification when a `reward_notificaiton` isn't provided (e.g. "You earned a %s LBC reward).

**Comment by tzarebczan** [comment]
The API side changes can be seen here: https://github.com/lbryio/internal-apis/pull/294

The API now returns the description and notification text:

```
"success": true,
  "error": null,
  "data": [
    {
      "id": 73950,
      "reward_type": "new_user",
      "reward_amount": 3,
      "transaction_id": "ed633e1d1000dd748948de95dc60bfaaa3f7defd49f39ad44c2ceffc769ee615",
      "created_at": "2017-07-25T04:43:21Z",
      "updated_at": "2017-12-23T06:21:43Z",
      "reward_version": null,
      "reward_title": "Your First Nickel",
      "reward_description": "A welcome bonus and thank you for your contribution to content freedom.",
      "reward_notification": "You earned 3 LBC new user reward."
    },
    {
      "id": 77407,
      "reward_type": "first_stream",
      "reward_amount": 2,
      "transaction_id": "ebe63acdf81c604ca6c1cb8de0fd0611064aa483efcb38c506df05c66954e381",
      "created_at": "2017-07-25T18:53:41Z",
      "updated_at": "2017-12-23T06:21:43Z",
      "reward_version": null,
      "reward_title": "Go for a Stream",
      "reward_description": "Just press play on something. Anything at all. Yep, even that one. Everybody's doing it.",
      "reward_notification": "You earned 2 LBC for streaming your first video."
```

**Comment by tzarebczan** [comment]
@daovist this could be another one to take a look at.  Epic is here: https://github.com/lbryio/lbry-app/issues/1328

**Comment by kauffj** [comment]
@daovist this is a strong candidate to knock out. Likely only a few hours work.

@tzarebczan I'm tagging this release blocker as I don't want to have to wait another month to be able to create new rewards without waiting on app releases.
