### ISSUE TITLE
TX Send Miscalculation

### ISSUE THREAD

**Issue by alph43oss** [lbryio/lbry-app#133]
## The Issue
The calculation on balances right after a transfer (send) is way off  (sometimes account shows negative 10s/100s of lbc), then balance is corrected after a few seconds.

It looks like its subtracting  2x the withdrawal value from current balance for initial calc.

## System Configuration

 

- LBRY App version: v0.10.1rc1
- Operating system: Windows 10

## Anything Else

:)

**Comment by kauffj** [comment]
This is a bug in the daemon. I believe it is filed [here](https://github.com/lbryio/lbry/issues/611).

**Comment by nikooo777** [comment]
I'd like to rise this issue again.
I know it's a daemon bug but I believe the UX is quite ruined by this bug as well, check this out: https://scrn.storni.info/Send_or_Receive_LBRY_Credits_2017-12-23_14-09-1809.png

Would you consider, as temporary solution, limiting the balance to positive numbers? I don't think the wallet will ever be allowed to be sub 0 anyway.

**Comment by tzarebczan** [comment]
https://github.com/lbryio/lbry-app/issues/873
