### ISSUE TITLE
Make sure README and other docs conform to docs spec

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-app#1330]
https://docs.google.com/document/d/1zBi8BifeRslhUPkDrb0lK4-OSjMPnkcNAxRduAwuvvo/edit

**Comment by kauffj** [comment]
When this is done, please add a section that is titled something like "Resetting your Packages" that explains what to do if `yarn xxx` isn't working after a `git pull/merge`. Presumably this is just trash all node modules and then run `yarn` again.

**Comment by kauffj** [comment]
Please also add a section that explains lbryio/lbry-redux and suggested workflow for making redux changes.

**Comment by seanyesmunt** [comment]
https://github.com/lbryio/lbry-app/pull/1476

**Comment by tzarebczan** [comment]
@seanyesmunt safe to close?
