### ISSUE TITLE
Formatting on upgrade prompt

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1331]
## The Issue
Related to the issue found during this PR: https://github.com/lbryio/lbry-app/pull/1229, see image. We may need @IGassmann 's help in testing this. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
I left a comment on it. All that needs to be added is `button="link"`
