### ISSUE TITLE
App scaling adjustments

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1334]
## The Issue
See below for screenshot of how the app looks on 2560x1440 full screen - I think the scaling should be turned down a bit or allow the user an option via the app. If I open up the console/resize, it does look much better.  Sean suggested a max width setting could help here. 

![scaling 1](https://user-images.githubusercontent.com/8120721/38872962-948bd62e-4222-11e8-8302-edb3e99188cb.png)
![scaling 2](https://user-images.githubusercontent.com/8120721/38872990-ab0fee9e-4222-11e8-8a5a-d4aef393251d.png)

### Suggested Solutions
Tell us your suggested solutions if you have any.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
Some side by side shots: https://www.screencast.com/t/o1os8zD1mTpl https://www.screencast.com/t/BxS4YrF0

**Comment by tzarebczan** [comment]
Other notes:
Other text areas like balance/left sidebar seem too large 
search box is small compared to other areas.

**Comment by ceoger** [comment]
this is the max resize that the app adapts, does not resize any further, can it be a little more smaller? this was obtained on a 1920x1080 Res, screenshot below:

https://cdn.discordapp.com/attachments/377895389992321064/445811902178787328/sz.JPG
