### ISSUE TITLE
Markdown preview setting broken

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1336]
## The Issue
See below, when clicking preview, both the original and preview are shown on top of each other. 

![md preview 1](https://user-images.githubusercontent.com/8120721/38874733-c8d6ec3a-4226-11e8-9c0a-3ee229e774d5.jpg)

![md 2](https://user-images.githubusercontent.com/8120721/38874734-ca538e38-4226-11e8-81fe-0dbae3a026c0.jpg)

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by btzr-io** [comment]
@tzarebczan Fixed on redesign

**Comment by tzarebczan** [comment]
Fixed in master, thanks @btzr-io !
