### ISSUE TITLE
Images are not resized to fit description area

### ISSUE THREAD

**Issue by m160** [lbryio/lbry-app#1337]
## The Issue
When having a high resolution image in the description it exceeds the borders of the description area so  only a part of the image can be seen.

### Steps to Reproduce
1. Add a high resolution image to the description
2. Preview/publish

### Suggested Solutions
The image should be automatically resized to fit the borders of the description area.

## Screenshots
![capture 1](https://user-images.githubusercontent.com/34570404/38874312-124d1f52-4258-11e8-9af3-6a9a883969e2.PNG)

**Comment by tzarebczan** [comment]
I'll consider this closed because it's going to be working better on the app redesign: 
[redeisgn](https://content.screencast.com/users/thomas.zarebczan/folders/Snagit/media/1cf8d21e-2248-4223-a955-32de69a97773/04.17.2018-09.20.png)
