### ISSUE TITLE
"This is disabled" in quickstart

### ISSUE THREAD

**Issue by Collinthegeek** [lbryio/lbry-app#134]
### Steps to reproduce
1. https://lbry.io/quickstart/credits#new-developer
2. Paste generated wallet adress

### Expected behaviour
Credits should be transferred

### Actual behaviour
"This is disabled" error appears

## System Configuration

N/A

## Screenshots

![lbc](https://cloud.githubusercontent.com/assets/2424846/26438871/23739d20-40eb-11e7-9b07-924cf187b95a.png)

**Comment by kauffj** [comment]
Sorry about that @Collinthegeek, we'll get that patched up. If it's not working by EOD tomorrow, please ping me and I'll send you something manually.

**Comment by Collinthegeek** [comment]
@kauffj Sorry I haven't had a chance to try again until now, This time I get "This reward requires a confirmed email address." I authorized with github and I don't have any email about a confirmation.

**Comment by lyoshenka** [comment]
@Collinthegeek we ended up disabling this reward again because its too easy to abuse. If Jeremy hasn't sent you credits yet, I can send you some as well (I'm `grin` in slack)
