### ISSUE TITLE
Change Lbry. to LBRY on startup screen

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1340]
## The Issue
Change to uppercase LBRY on the startup page. 

Is it used anywhere else? 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
Already done

**Comment by seanyesmunt** [comment]
The android app is the one with Lbry.
