### ISSUE TITLE
Invites tile says "0 credits"

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-app#1342]
![](https://i.imgur.com/eKxiRHZ.png)

**Comment by tzarebczan** [comment]
@lyoshenka did you already claim the 1 invite reward allowed? This would be expected as the max is 1. It may be coming back the the rewards api, so if we still want it to show 3 (even though it can't be claimed until some point in the future), the fix would be there.

Might also be related to https://github.com/lbryio/lbry-app/issues/829

**Comment by lyoshenka** [comment]
Oh, I forgot I can earn rewards for inviting people. I was like "oh great, its free to invite ppl..."

**Comment by tzarebczan** [comment]
@lyoshenka do you think we should fix this on the internal APIs so that it still shows the correct # of credits? It may even be an app bug related to #829

**Comment by tzarebczan** [comment]
We removed the # of credits for now in the redesign.
