### ISSUE TITLE
Long URLs cut off in search/URL bar

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1346]
## The Issue
See below - this would mainly happen when accessing content through a channel page / downloads/pubish page for content that as a channel + a longer than normal claim name. 

![long url](https://user-images.githubusercontent.com/8120721/38910965-29683090-429a-11e8-8019-dcd8ce2a5560.jpg)

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by Invariant-Change** [comment]
This can now be closed :)
