### ISSUE TITLE
Claim data not shown on duplicate name

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1358]
## The Issue
There are 2 claimis on @ColinsLastStand that have the same name, and the channel page won't show them, and neither will the show page. It does resolve correctly and works in the previous app version Previous version shows the `contentURL#claim_id`, new version shows `channelname#claim_id/contentURL` in the URL.  Not sure which way we want to go, but I like the idea of having the channel name. Can it show the ContentURL in the address bar but use the contentURL+claim_id in the background? 

![colins 2](https://user-images.githubusercontent.com/8120721/38966475-7b90c718-4350-11e8-8253-395a33a1f101.jpg)

![colins1](https://user-images.githubusercontent.com/8120721/38966391-02bb41ba-4350-11e8-8681-c35a340f2094.jpg)

Claim as shown in new version: lbry://@ColinsLastStand#4533e7ff2db6519ba5639f102d0de9cadecef84d/colin-s-last-stand-fireside-chats

Content claims: 
lbry://colin-s-last-stand-fireside-chats#a73cd3f2608e04ca2dfed599ac460c20bdba4e90
lbry://colin-s-last-stand-fireside-chats#0d984928f5a798b6864ea6ae36558c6f8a1ebd0e

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
Changing to remove the channel name fixes it. Ideally this should have the channel name in it though.
