### ISSUE TITLE
Green screen

### ISSUE THREAD

**Issue by raympie1977** [lbryio/lbry-app#1363]
when starting up the LBRY app, I only get a green screen. nothing more. I updated it to the latest version. It does try to connect, but not sure if it does

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble. What OS are you on? Running any anti virus / firewall software?

If you press ctrl shift i to bring up the Dev console, are there any errors? 

Also, check out https://lbry.io/faq/unable-to-stream

**Comment by raympie1977** [comment]
Mac os. Worked since today

Groetjes,
Raymond

Op 22 apr. 2018 om 18:31 heeft Thomas Zarebczan <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Sorry to hear about the trouble. What OS are you on? Running any anti virus / firewall software?

If you press ctrl shift i to bring up the Dev console, are there any errors?

Also, check out https://lbry.io/faq/unable-to-stream

**Comment by raympie1977** [comment]
________________________________
Van: Thomas Zarebczan <notifications@github.com>
Verzonden: zondag 22 april 2018 17:19:56
Aan: lbryio/lbry-app
CC: raympie1977; Author
Onderwerp: Re: [lbryio/lbry-app] Green screen (#1363)


Have you tried rebooting your pc?

Can you also send me your log file if that doesn't work: lbry.io/faq/how-to-find-lbry-log-file

**Comment by tzarebczan** [comment]
@raympie1977 I'm going to close this issue - please send your logs to hello@lbry.io if you continue to have problems.
