### ISSUE TITLE
Every time I run the client I get the "welcome to lbry" message

### ISSUE THREAD

**Issue by intnick** [lbryio/lbry-app#137]
## The Issue
Every time I run the client I get the "welcome to lbry" message
### Steps to reproduce
1. Run the client (current mater branch)
2. Welcome to LBRY modal window appears
3.

### Expected behaviour
Tell us what should happen
It should be shown only once, every other time I open the app it shouldn't be there

### Actual behaviour
Tell us what happens instead

## System Configuration

 

- LBRY Daemon version: 0.10.3  "lbryum_version": "2.7.22"
- LBRY App version: Current Master branch (10.1)
- LBRY Installation ID: 
- Operating system: Linux-4.8.0-52-generic-x86_64-with-Ubuntu-16.04-xenial

**Comment by kauffj** [comment]
This is fixed in latest release.
