### ISSUE TITLE
Autoupdate does not trigger Ubuntu Software Center

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1378]
## The Issue
When upgrading from 0.21.2 to 0.21.2, the update downloads successfully to the tmp folder but nothing happens after clicking "Begin Upgrade". Tried this on 16.04 and 17.10. Sean confirmed too. This may not be worth looking into if we are moving to snap files. 

Even if it were triggered, Ubuntu Software center rarely works when updating/installing deb files. If anyone is having trouble with this, use the terminal instead: sudo dpkg -i pathtodeb.deb

See old discussion here: 
https://github.com/lbryio/lbry-app/issues/438#issuecomment-322465156

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
#1376 is related, or at least it probably makes sense to tackle these at the same time.

**Comment by tzarebczan** [comment]
Fixed in : https://github.com/lbryio/lbry-app/pull/1648
