### ISSUE TITLE
Text/HTML files don't display correctly in-app anymore

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1379]
## The Issue
See below for lbry://test-text#964c747b2619baf700775974370b9d7c19110c3b. Had to highlight the text to see anything.  We should make sure this works in Dark mode as well. HTML is having a similar problem, see claims lbry://two - ten 

![text file type](https://user-images.githubusercontent.com/8120721/39162942-1dc86a38-4746-11e8-8cd6-43eb3939ca59.jpg)

side by side:
![html2](https://user-images.githubusercontent.com/8120721/39195451-df3ab74a-47ad-11e8-8f80-5879e636e598.jpg)

full screen:

![html](https://user-images.githubusercontent.com/8120721/39195302-8b17813e-47ad-11e8-8840-c721bb3f80bc.jpg)

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by DiSae** [comment]
In addition to the above I would like to add: When using light mode and selecting text in the app, you can't see it anymore. See screenshot.
![text invisible](https://user-images.githubusercontent.com/31828724/39177247-043389ea-47af-11e8-9e4e-1f3b450fab4b.png)

**Comment by tzarebczan** [comment]
@DiSae thank you, we are aware of that recent snafu. It will be cleaned up in our redesign. If you want to see a preview of it, check out https://design.lbry.io
