### ISSUE TITLE
Yarn isn't pulling in latest lbry-redux changes

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-app#1382]
## The Issue
Sometimes the `yarn` command isn't pulling in the latest `lbry-redux` changes. I've had to clear everything out and then use `npm i` to get it to work. Pretty sure it's something with `yarn`'s global cache

### Steps to Reproduce
1. run `yarn`
2. merge a PR into `lbry-redux`
3. run `yarn` again
4. see that it isn't up to date

### Expected Behaviour
It should pull the latest files

**Comment by btzr-io** [comment]
``` Shell
rm -r node_modules && yarn cache clean && yarn
```

**Comment by seanyesmunt** [comment]
Nice. We should probably just add this as a script. Maybe `clean`?

**Comment by btzr-io** [comment]
`install:clean` ? 
I'm not good with names :upside_down_face:

**Comment by IGassmann** [comment]
More information here https://github.com/yarnpkg/yarn/issues/4722

**Comment by btzr-io** [comment]
> :warning: If yarn is installing the wrong versions of any dependencies, run the following:
```  
$yarn cache clean
$yarn
```
> :point_up: add the --pure-lockfile argument to yarn to ensure you install all dependencies exactly as specified in the current yarn.lock file.

https://github.com/Paratii-Video/paratii-portal/blob/edeaa072e98850969bb1747f448944b57e7bd784/README.md#installing

**Comment by tzarebczan** [comment]
@seanyesmunt should we leave this open until we can find out a more automated process to run the commands? Or open a new issue for that?

**Comment by seanyesmunt** [comment]
Lets just keep this one open

**Comment by seanyesmunt** [comment]
Closing this. We now clear the yarn cache for `lbry-redux` on every install.
