### ISSUE TITLE
Move all modal types to use lbry-redux

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-app#1384]
## The Issue
A few places are still using `constants/modal_types` for modal strings in the app. These should all be moved over to `lbry-redux`
ex: https://github.com/lbryio/lbry-app/blob/master/src/renderer/modal/modalRouter/view.jsx#L23

### Expected Behaviour
All modal types should be added to the `lbry-redux` repo and pulled from there

### Actual Behaviour
Some are using `lbry-redux` others are using the constants in the app

### Suggested Solutions
Copy all the constants in `src/rendered/constants/modal_types` to here https://github.com/lbryio/lbry-redux/blob/master/src/constants/modal_types.js

Then change the import statements inside the app

**Comment by kauffj** [comment]
@seanyesmunt @akinwale should these become `notification_types` rather than `modal_types` given the refactoring of lbry-redux notification methodology?

**Comment by dan1d** [comment]
Sorry to bother, but this one shouldn't be closed when it was merged?

**Comment by seanyesmunt** [comment]
Guess I missed your message @kauffj 

Probably. They are passed in as `notificationId`.

**Comment by seanyesmunt** [comment]
And yes @dan1d. I just saw this was still open.

I'll leave it open for now since we are still discussing.

**Comment by tzarebczan** [comment]
@seanyesmunt were all these moved?

**Comment by kauffj** [comment]
It's conceivable, likely even, that applications will desire their own notifications independent from those used cross-platform. If that case doesn't exist yet, it's probably fine to wait until it does, but it's something to consider when designing the pattern used here.

**Comment by seanyesmunt** [comment]
Whoops missed this. Yeah the app is using lbry-redux for all notifications

**Comment by tzarebczan** [comment]
This is all in lbry-redux now
