### ISSUE TITLE
Add fetching/processing message to subscriptions

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1387]
## The Issue
When adding your first subscription or when the subscriptions page is refreshing, you don't get a visual indicator that something is happening. 

![subscribe 3](https://user-images.githubusercontent.com/8120721/39268611-5533b9ec-489e-11e8-8c61-8fcf892d87dc.jpg)

### Steps to Reproduce
1. Clear all subscriptions
2. Subscribe to something
3.

### Expected Behaviour
fetching/processing message

### Actual Behaviour
nada

### Suggested Solutions
fetching/processing message

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
Will be fixed by https://github.com/lbryio/lbry-app/pull/1424
