### ISSUE TITLE
pop up screen to claim reward, then msg that it's been claimed

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#140]
## The Issue
on each start, get pop up to claim credits, then have to wait for it to fail with a message that says reward has been claimed
### Steps to reproduce
1. open lbry v11
2. get message
3.

### Expected behaviour
reward message should not appear

### Actual behaviour
open lbry without any messages

## System Configuration

 

- LBRY Daemon version: 
- LBRY App version: v11
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
Fixed in latest release.

**Comment by tzarebczan** [comment]
Thanks!
