### ISSUE TITLE
Play when clicking anywhere on thumbnail, play with spacebar

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1404]
## The Issue
In the previous app design, you could click anywhere on the thumbnail to start playing/downloading but now you have to click the play button. Also, pressing space would start playing/downloading, but now it does not. 
![click play](https://user-images.githubusercontent.com/8120721/39333929-b6e24cb2-497a-11e8-95b3-e6f8d06ba8f2.jpg)

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
Working on this
