### ISSUE TITLE
Channels not available in Publish page

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1405]
## The Issue
Channels aren't populated in the Publish screen dropdown, this must have happened recently because it was working a few iterations ago. The channel_list call returns channels correctly. 

### Steps to Reproduce
1. create a channel
2. refresh app
3. go to publish, check channel dropdown

### Expected Behaviour
Tell us what should happen.

### Actual Behaviour
Tell us what happens instead.

### Suggested Solutions
Tell us your suggested solutions if you have any.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
Should be fixed
