### ISSUE TITLE
Featured Content Email Link

### ISSUE THREAD

**Issue by impshum** [lbryio/lbry-app#1408]
## The Issue

Featured content link in email sending to wrong/empty location.
Current link leads to lbry://davidpakman not lbry://@davidpakman

### Steps to Reproduce
1. Click link in email
2. N/A
3. N/A

### Expected Behaviour
Correct location.

### Actual Behaviour
Wrong location

## System Configuration
iMail

   "build": "release",
    "lbrynet_version": "0.19.1",
    "lbryschema_version": "0.0.15",
    "lbryum_version": "3.2.0",
    "os_release": "17.5.0",
    "os_system": "Darwin",
    "platform": "Darwin-17.5.0-x86_64-i386-64bit",
    "processor": "i386",
    "python_version": "2.7.13"

**Comment by tzarebczan** [comment]
I replied on Discord - this is a known bug with the Safari browser on Mac because it removes the @ before we can do anything about it. We may be able to do some workaround down the road, but it's not really an app issue. Try with Chrome or Firefox, should work.
