### ISSUE TITLE
"PRICE" text is visible when content thumbnail has not loaded yet

### ISSUE THREAD

**Issue by LavRadis** [lbryio/lbry-app#1427]
## The Issue

When the app is loading and/or content thumbnails with actual price information have not loaded yet you can see the "PRICE" text in the top right corner of each content field. It just looks bad when you see a bunch of empty squares and PRICE displayed all over the screen.    

### Steps to Reproduce
1. You can see it while the thumbnails are loading in any app section 
2.
3.

### Expected Behaviour
The PRICE text should not be displayed. 

## System Configuration

- LBRY Daemon version: 0.19.1
- LBRY App version: 0.22.0-rc.3
- LBRY Installation ID: 7tYN144rHXrspzJG9xLP28fi1JztXnbpKro6DBJEQyzBmXTyDgqRLfYsUvHYFVmMe2
- Operating system: win 10

Here is the screenshot, I was to slow to catch all the fields empty. It takes some 10 seconds on my side to load up.

## Screenshots

![price text](https://user-images.githubusercontent.com/10566738/39540000-ac77f54e-4e41-11e8-881e-3875c4751c16.jpg)

**Comment by tzarebczan** [comment]
Thanks for filing this, looks like @miikkatu already put a fix in :)

**Comment by tzarebczan** [comment]
Reopening as the PR was reverted.
