### ISSUE TITLE
New Search/Address bar could be confusing for new users

### ISSUE THREAD

**Issue by LavRadis** [lbryio/lbry-app#1428]
## The Issue
New unified search and address bar could be confusing for new users since it only has helper text (and icon) related to search functionality. 

### Suggested Solutions
Improve the helper text and possibly change the icon. Text should make clear that the lbry:// address should be entered. Something like:  "Enter LBRY URL here or search..." 

- LBRY Daemon version: 0.19.1
- LBRY App version: 	0.22.0-rc.3
- LBRY Installation ID: 7tYN144rHXrspzJG9xLP28fi1JztXnbpKro6DBJEQyzBmXTyDgqRLfYsUvHYFVmMe2
- Operating system: win 10

**Comment by tzarebczan** [comment]
It also shows lbry:// when typing a word, but new users may not know this is a LBRY URL.
