### ISSUE TITLE
Security should be more aggressive on DevTools.

### ISSUE THREAD

**Issue by ICTman1076** [lbryio/lbry-app#1430]
## The Issue

Security on the new LBRY app is, in my opinion, too tame, and allows people to get fooled by scammers/attackers easily. In this issue I will outline what happens at the moment, and what I think should happen.

This is one of two issues submitted that are linked. This one is related to the DevTools. The other is issue #1429.

### Steps to Reproduce

1. In the app, press Ctrl-Shift-I
2. Click on console tab.

### How I think it should behave

In the console, it should be made clear that pasting unknown code into it is potentially dangerous. Discord handles this well - https://ictman.tk/img/020518_01-46-53.png. If you want to implement something like this, then [this StackOverflow question](https://stackoverflow.com/questions/22155879/how-do-i-create-formatted-javascript-console-log-messages) may help

### Actual Behaviour

Nothing.

## System Configuration

N/A, since this change should be for all systems. The only piece of information you may need about this is that I have the latest beta "redesign" build.

Let me know if you want any more information. Thanks!

**Comment by kauffj** [comment]
Thanks @ICTman1076 this is a great idea! If you have any interest in completing this yourself, we'd be happy to bounty.

**Comment by tiger5226** [comment]
Thats an awesome warning message +1 Discord

**Comment by tzarebczan** [comment]
This is fixed in : https://github.com/lbryio/lbry-app/pull/1500
