### ISSUE TITLE
Use channel id instead of name when publishing

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1433]
## The Issue
In order to allow channel + claim creation in the same block, we should be using the channel id instead of the channel name when publishing with channel data. See syntax: https://lbryio.github.io/lbry/cli/#publish

See comments here: https://github.com/lbryio/lbry/issues/893#issuecomment-386050685

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
@tzarebczan you could also try this

**Comment by tzarebczan** [comment]
@seanyesmunt @kauffj I did take a brief look into it and it would require redux changes post redesign, which means re-work required pre-redesign. @seanyesmunt let me know and I can walk you through it, maybe there's an easier way, but I didn't see the channel id as an available field (I could be mistaken though).

**Comment by tzarebczan** [comment]
@daovist Maybe you want to take a look at this one? I can explain to you what's happen now vs how we want it to work.

**Comment by daovist** [comment]
I am working on this issue.

**Comment by tzarebczan** [comment]
Fixed in https://github.com/lbryio/lbry-app/pull/1481
