### ISSUE TITLE
Claiming a reward doesn't trigger a visual feedback

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry-app#1436]
## The Issue
In the new app, when a reward is claimed nothing happens. You get the reward and it eventually shows up on your balance, but you don't get a popup or anything indicating that everything went well.
### Steps to Reproduce
1. Run app
2. Get a reward
3. Watch nothing happen

### Expected Behaviour
A popup or something should inform the user about the claimed reward

### Actual Behaviour
Nothing happens

### Suggested Solutions
investigate why the popup isn't triggered anymore

## System Configuration

- LBRY Daemon version: super hacked latest version
- LBRY App version: master
- LBRY Installation ID: locally run
- Operating system: Ubuntu 18.04

**Comment by tzarebczan** [comment]
Can confirm this is happening to me as well. Besides this problem, I often run into an issue where I won't get any snackbars (not even for copying addresses) until the app is restarted. Another user reported not being able to click the delete button on a video either (until restarted).

**Comment by tzarebczan** [comment]
could be related:
```
Uncaught (in promise) Error: Actions may not have an undefined "type" property. Have you misspelled a constant?
    at Object.performAction (<anonymous>:1:40951)
    at liftAction (<anonymous>:1:34377)
    at dispatch (<anonymous>:1:38408)
    at eval (store.js?aefd:42)
    at C:\Users\tom\Desktop\lbry-app\node_modules\redux-thunk\lib\index.js:14
    at dispatch (C:\Users\tom\Desktop\lbry-app\node_modules\redux\lib\applyMiddleware.js:45)
    at success (rewards.js?fe35:64)
    at <anonymous> 
```

**Comment by LavRadis** [comment]
yes, I reported this issue several times and the delete button issue.
