### ISSUE TITLE
Confirmation for external links

### ISSUE THREAD

**Issue by btzr-io** [lbryio/lbry-app#1442]
## The Issue

Once https://github.com/lbryio/lbry-app/pull/1441 is merged external links on description would be more noticeable and easy to click, so we should add a confirmation modal to let the user know the danger of `phishing` attacks.

### Steps to Reproduce
1. Go to a claim page.
2. Click a link on the description.

### Expected Behaviour
Confirmation modal:

> ### :warning: Warning
> `Link:` http://duck.com/redirect?phishing=true
> This link leads to an external website. Blah...

### Actual Behaviour
Nothing...

**Comment by kauffj** [comment]
Great idea @btzr-io!

**Comment by tzarebczan** [comment]
@btzr-io would this be an issue you want to work on? 

How's this sound?
"This link leads to an external website. LBRY Inc is not responsible for its content, click OK to proceed at your own risk."

**Comment by tzarebczan** [comment]
Closing, working as expected based on #1441
