### ISSUE TITLE
Autocomplete search results - show URLs as direct input in live search

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1454]
## The Issue
Spoke to @seanyesmunt about this last week - when we return autocomplete results, the returned URLs are not shown as direct URLs, but rather as search terms. 

Lighthouse discusison on autocompelte search results: https://github.com/lbryio/lighthouse/issues/55#issuecomment-387094505

### Steps to Reproduce
1. Type in "url" in search bar
2. Notice first search result is a URL, but it takes you to search

### Expected Behaviour
Tell us what should happen.

### Actual Behaviour
Tell us what happens instead.

### Suggested Solutions
Tell us your suggested solutions if you have any.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
working on this

**Comment by seanyesmunt** [comment]
Will be fixed with https://github.com/lbryio/lbry-redux/pull/25
