### ISSUE TITLE
Can type in unfocused fields while publishing without selecting file

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1456]
## The Issue
When going to the publish screen, the select file area is in focus and the rest of the screen is grayed out, but you can still go into most of the fields and type (blocked from Title/thumbnail, but rest work, even dropdowns). If we intend to force users to select a file first, we should not allow typing anywhere else on the publish form.

### Steps to Reproduce
1. Click publish, don't select a file
2. Scroll down to description or claim name
3. You can type

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
Test tab selection too

**Comment by tzarebczan** [comment]
@seanyesmunt another thing to consider is that we still rely on the Publish screen for the channel creation process, which is now even more hidden because you need to select a file first (what if I want to create a channel without publishing? )

**Comment by tzarebczan** [comment]
Fixed in: https://github.com/lbryio/lbry-app/pull/1659
