### ISSUE TITLE
published tab doesn't show previously published content on v0.11 (page completes loading)

### ISSUE THREAD

**Issue by maximumplank** [lbryio/lbry-app#146]
## The Issue
Instead of displaying published content, 'Published' tab says "It looks like you haven't published anything to LBRY yet. Go share your beautiful cats with the world!"

### Steps to reproduce
1. open LBRY browser
2. navigate to published tab (folder icon in top right -> Published)

### Expected behaviour
Should display a list of published content

### Actual behaviour
displays "It looks like you haven't published anything to LBRY yet. Go share your beautiful cats with the world!" with inline link to publish page

## System Configuration

- LBRY App version: 0.11
"id": null,
  "jsonrpc": "2.0",
  "result": {
    "build": "rc",
    "ip": "73.158.155.244",
    "lbrynet_version": "0.10.3rc4",
    "lbryschema_version": "0.0.4",
    "lbryum_version": "2.7.22",
    "os_release": "4.4.0-78-generic",
    "os_system": "Linux",
    "platform": "Linux-4.4.0-78-generic-x86_64-with-Ubuntu-16.04-xenial",
    "processor": "x86_64",
    "python_version": "2.7.12"

## Anything Else
Published content can be viewed/accessed through rpc calls to the client, see screenshots

## Screenshots
published content: https://supload.com/H18MlL8ZZ
view in browser: https://supload.com/B1USx8L-Z

**Comment by maximumplank** [comment]
similar to https://github.com/lbryio/lbry-app/issues/139, but in that case the published page would not finish loading. in this case the browser affirms (incorrectly) that no published content exists.

**Comment by kauffj** [comment]
@maximumplank I was unable to reproduce this, even when switching wallets. If this is still happening for you, can you run the API commands `file_list` and `claim_list_mine` via the CLI? Then paste the output here or email me at jeremy@lbry.io. Thanks!

**Comment by maximumplank** [comment]
This is no longer happening on v0.12 of the app. Great job guys!
