### ISSUE TITLE
double click to full screen would be a nice feature

### ISSUE THREAD

**Issue by ceoger** [lbryio/lbry-app#1463]
## The Issue
a click plays a video, and another click pauses the video, so double click pauses and plays instead of opening full screen, same issue with the pre-design 

### Steps to Reproduce
1. Play any video
2. Double click
3. video will pause and resume

### Expected Behaviour
double click should open full screen mode
### Actual Behaviour
 instead it pauses and plays

### Suggested Solutions
double click to full screen would be a nice feature

## System Configuration

- LBRY Daemon version: 0.19.1
- LBRY App version:  0.22.0-rc.8
- LBRY Installation ID: 3cXLZiAWXwwJbv4fjhbXVgFtaBuUiFQM7afXmFYu5ss1chD1WCpxGUp8aW68gjeNRC
- Operating system: Windows 10

**Comment by tzarebczan** [comment]
Thanks for submitting @ceoger, sent you some LBC on Discord for the suggestion! We'll need to explore the media player to see if this is possible.

**Comment by tzarebczan** [comment]
Implemented in https://github.com/lbryio/lbry-app/issues/1498
