### ISSUE TITLE
Rewards look grayed out

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1466]
## The Issue
This happened to myself and a community member last week and just recently for @nikooo777 , see below. It's not currently happening and not sure how to reproduce. 

me:
![screenshot-2018-5-4 drafts 49 - thomas zarebczan gmail com - gmail](https://user-images.githubusercontent.com/8120721/39843666-16aa3d28-53ba-11e8-88b8-679b573ee585.png)
Niko:
![niko](https://scrn.storni.info/2018-05-09_18-32-05-170098766.png)

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by dan1d** [comment]
Hi @tzarebczan 

Currently I have an that I can  reproduce this bug, I see the rewards cards greyed out.
I've figured what's the issue but I'm not entirely sure what's the best approach to fix this:
on this file  `src/renderer/page/rewards/view.jsx`
```

This code is the one that puts the gray layout on top of the rewards:
const isNotEligible =
      !user || !user.primary_email || !user.has_verified_email || !user.is_identity_verified; // I have all of them except is_identity_verified which is false so it returns true !, so I'm not elegible for rewards and that code add the class card--disabled.

    return (
      <div
        className={classnames('card__list--rewards', {
          'card--disabled': isNotEligible,
        })}
      >
        {rewards.map(reward => <RewardTile key={reward.reward_type} reward={reward} />)}
      </div>
    );
```

So then why I can claim rewards if I'm not elegible?, I think  there is a header notice to let me know what's going on, on the same file the method: `renderPageHeader`  has this conditional to render a message but if the criteria is not meet then it render nothing, which is happening to me:

`if (user && !user.is_reward_approved && daemonSettings.share_usage_data) {`

so I've debugged my user and I see `user.is_reward_approved` returns true, and negated by `!` its changes to false, how can I be approved and take the rewards if the property `user.is_identity_verified` is false. I don't know which conditional change, I've removed `!user.is_identity_verified` on the first part of this code and I don't see the layout greyed out anymore.

**Comment by tzarebczan** [comment]
@dan1d great work on the debugging! I'm pretty sure we want to use user.is_reward_approved instead of is_identity_verified to check for rewards eligibility. is_identity verified only applies to the credit card verification method, but we also have phone verification, youtube, and manual overrides - all of which are encompassed under is_reward_approved.

**Comment by dan1d** [comment]
@tzarebczan  Thanks for the clarification, I've pushed my fix and was already merged :+1:
