### ISSUE TITLE
LBRY's Payment Claim Feature Unclear

### ISSUE THREAD

**Issue by Postizdev** [lbryio/lbry-app#1468]
First issue:
When you are uploading a video, getting your own username or getting your own url, it is unclear the bare minimum next to 0 you can deposit to claim either of these features within the app (thanks to @jiggytom at discord for putting this on his radar)

It would be nice if you could make it clear that the bare minimum is 0.0001 LTC as people would be turned away if they feel the would have to spend huge chunks of money just to use the app.

Of course this is optional but on Bitflyer when you are inputting your bitcoins it tells you how much you are spending in USD.

Second issue:
Since the LBRY player doesn't support many video formats at the moment, just a temporary sticky telling users what they support at the time would be nice as it would save people a lot of headache.

**Comment by tzarebczan** [comment]
Thanks for opening the issue and the suggestions! Sent you a tip and reply on Discord:  In the redesign the min will be changed to 0.1  by default and there is a link to the naming FAQ which explains the rest. And we'll get a link to the publish guide which speaks to formatting. Users can really publish any format they want, they can always be opened externally (so we don't want to discourage uploading other formats either). The publisher experience does need a larger overhaul, something we will focus on later this year.

Closing this as it's related to https://github.com/lbryio/lbry-app/issues/528
