### ISSUE TITLE
"This email is already in use" when trying to login/access the desktop app

### ISSUE THREAD

**Issue by ajthemacboy** [lbryio/lbry-app#147]
## The Issue
See here: https://drive.google.com/a/eyestra.in/uc?id=0B6AmcbVDdoMsRmdoaWpjM2ViYTg

### Steps to reproduce
1. Download the client
2. Try to login with an email that has already been accepted for early access

### Expected behaviour
When I enter my email, I should not receive an error and should be allowed into the app

### Actual behaviour
There is an error and I can't login

## System Configuration
- LBRY App version: 0.11.3
- Operating system: Windows 10

**Comment by tzarebczan** [comment]
It was designed as a one time use code. Please close.

**Comment by kauffj** [comment]
This is a real issue in that @ajthemacboy should be able to get into the app. @lyoshenka is working on fixing this.

**Comment by MitchellKiah** [comment]
I can verify that this is still an issue.

LBRY App Version 0.11.6
Operating system: Ubuntu 17.04

**Comment by lyoshenka** [comment]
This should be fixed in the latest release (https://github.com/lbryio/lbry-app/releases/tag/v0.11.8). Please give that a try. Reopen this issue if you're still seeing the error.
