### ISSUE TITLE
No Content Found While Channel Is Loading

### ISSUE THREAD

**Issue by ceoger** [lbryio/lbry-app#1471]
## The Issue
No Content Found While Channel Is Loading
### Steps to Reproduce
1. Open Any channel
2. Wait while it's loading
3. You get a message no content found, and in a moment the contents will be showing, load is very sow

### Expected Behaviour
At least "please wait" or "loading" is a good assurance

### Actual Behaviour
Instead, you get a message no content found whiles content maybe loading

### Suggested Solutions
User should get a message like fetching content or loading not "no data found" before displaying results

## System Configuration

- LBRY Daemon version: 0.19.3
- LBRY App version: 0.21.4
- LBRY Installation ID: 3cXLZiAWXwwJbv4fjhbXVgFtaBuUiFQM7afXmFYu5ss1chD1WCpxGUp8aW68gjeNRC
- Operating system:

**Comment by tzarebczan** [comment]
@ceoger can you provide a screenshot or more details of when this happens? Is it when you access new channels?

Are you talking about the screen that shows before it says "fetching content"? I don't see a message about no content found

**Comment by tzarebczan** [comment]
This should be much improved in the redesign + updated daemon, please reopen if it's still happening.
