### ISSUE TITLE
price cutting off for paid contents

### ISSUE THREAD

**Issue by ceoger** [lbryio/lbry-app#1478]
## The Issue
during confirmation to pay to access the content, sometimes the "lbc" is separated from the amount making it barely unreadable
### Steps to Reproduce
1. look for a paid content
2. Try paying to access the cotent
3. The confirmation message comes up and the price cuts off

### Expected Behaviour
the LBC + Amount should be together

### Actual Behaviour
price cuts off

### Suggested Solutions
Tell us your suggested solutions if you have any.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

## Anything Else

https://cdn.discordapp.com/attachments/377895389992321064/445932802819489813/the_writing_for_the_10_lbc_is_split_and_makes_it_barely_readable.JPG

https://cdn.discordapp.com/attachments/377895389992321064/445932850689212426/this_is_better.JPG

**Comment by tzarebczan** [comment]
Thanks for filing this, good find. I did run across the same issue last week.
