### ISSUE TITLE
Snackbars randomly stop working / can't delete content

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1488]
## The Issue
I've run into this a few times and @daovist recently did as well: snackbar notificiations cease to work. Easiest place to test if the wallet send/receive page by sending yourself credits. Refreshing the app fixes it. Not sure how to reproduce.

Another user had reported something similar on the show page - he was unable to click the delete button (could click, but not action), until a restart. 

Sean is aware and will keep an eye out. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
@tzarebczan @daovist dumping relevant and/or all Redux state once this happens may be helpful to debugging this.

**Comment by tzarebczan** [comment]
Found the root cause - it's the rewards snackbar that's missing display type, which causes the rest of the notifications to get backed up. Thanks @seanyesmunt for showing me how to debug this!

@daovist did you run into this during your reward changes/testing? Sent you a DM on Slack

https://www.screencast.com/t/TwAaDv1f7

**Comment by tzarebczan** [comment]
closed by https://github.com/lbryio/lbry-app/pull/1493
