### ISSUE TITLE
Search, Autocomplete gaps

### ISSUE THREAD

**Issue by tiger5226** [lbryio/lbry-app#1496]
I reviewed the app redesign and how it is using auto complete. I think it might be being misused. The expectations from a user is probably the following:

- When I type, I see suggested search terms that complete my thought. 
  - if I am starting with an `@` then I expect it to complete the claim name, just as in any browser that I start with `http://` or `www` and it suggests the site I am trying to visit, otherwise I am looking for search suggestions not exact pages. 
- When I click the enter button that is what I am searching. Currently, it tries to take me to a specific claim which obviously doesn't exist because I am searching not going to a specific claim. 
  - If it starts with an `@` I am trying to go to a specific claim or channel.
  - If not then I am trying perform a search not going to a claim. 
  - I should not have to type, then click a row in the list to perform a search.

I think these main points are the default expectations of a user.

**Comment by tzarebczan** [comment]
One I the reasons we want the default the enter behavior to go to the exact claim is to showcase lbry:// URLs. Maybe we should check to see if the term entered is an actual URL before defaulting to that behavior? Otherwise, why would anyone want to go to a claim that doesn't exist (this would the 2ndary behavior if a user clicked it).

**Comment by tiger5226** [comment]
Yeah we should be able to regex it before assuming we want to go to an exact url. Otherwise it is a search.

**Comment by tiger5226** [comment]
I did check the code and it appears to be going to a url if it is one word and search if there are two words or more.

**Comment by tiger5226** [comment]
I wonder if it would be performant to just try to resolve the url on enter, and if not, perform a search instead. This way there is no questioning whether it is a valid url or not. This would probably be the idea scenario.

**Comment by seanyesmunt** [comment]
I'm not sure what we would gain from resolving on enter? Do you mean resolve, then if nothing is at that uri, fallback and do a search?

**Comment by tiger5226** [comment]
thats exactly what I mean. It is uber annoying that it defaults to a URI that doesn't exist

**Comment by seanyesmunt** [comment]
Gotcha. I like that idea

**Comment by tiger5226** [comment]
closed in favor of the more specific [issue](https://github.com/lbryio/lbry-app/issues/1699) that addresses the problem as described above.
