### ISSUE TITLE
 Show page quirk with certain file types when no thumbnail set

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1503]
## The Issue
I uploaded a zip file without a thumbnail, and the show page looks like this (just navigating to it, not clicking anything). This may happen with other file types, not exactly sure. It works fine when there is a thumbnail. This particular URL is : lbry://ScreenToGif12-50-45590#f8866c585e39d26f87039547e0c51b2614280eb0
![thumbbroken](https://user-images.githubusercontent.com/8120721/40427145-deb19306-5e6a-11e8-8181-37109533c4a9.jpg)

### Expected Behaviour
Show blank placeholder if the thumbnail doesn't exist. 

### Actual Behaviour
see above
## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
@seanyesmunt whoops, just noticed you removed release blocker. I'd agree if this is a more complicated fix, but it's a pretty big regression from the previous version.

**Comment by seanyesmunt** [comment]
Whoops. Didn't mean to. It should be a simple fix.

**Comment by seanyesmunt** [comment]
Working on this
