### ISSUE TITLE
Need to click modal confirmations twice

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1515]
## The Issue
Noticed I need to click modal confirmations twice when they pop up. First noticed when purchasing content and also on an upgrade notice.

This is on master as of 5/24 

### Steps to Reproduce
1. Purchase some content (see lbry://@juggling)
2. Notice you need to click the modal confirmation twice before it disappears 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
Working on this

**Comment by tzarebczan** [comment]
This is fixed on the file page.
