### ISSUE TITLE
Update Bug Reports narrative to include user feedback/suggestions

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1537]
## The Issue
Updating the Bug Report functionality to include a feedback/suggestions narrative will allow users to submit recommendations/feedback through the app.  

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by Bentley912** [comment]
Hey. Id like to take a stab at this. 

I have a few questions. Am i addig a new function in the lbry-redux code and also making some changes to the /'/report' component? If so, I cloned the lbry-redux repo and did not find the `Lbry.report_bug` in that code. Where is it in the code ?

**Comment by tzarebczan** [comment]
@Bentley912 we plan to eventually replace the Lbry.report_bug call (this is actually in the lbrynet-daemon, not in redux) so it's okay to reuse the same form/call for this request at the moment. So it's mainly just wording that needs to be adjusted in a few places. 

Thanks for taking a shot at this!

**Comment by kauffj** [comment]
@tzarebczan if we're going to work on this I'd really like to kill `lbry.report_bug` as it shouldn't exist.

Do we want these to go straight into the help desk?

**Comment by tzarebczan** [comment]
@kauffj we discussed using the helpscout api in the ticket here: https://github.com/lbryio/lbry-app/issues/1078

But regardless of how it's sent, I think these changes are separate.

**Comment by Bentley912** [comment]
Ok. So, for now, I'll just change the language up a bit. When we get all that straightened out, Ill implement the helpscout from the API. Cool?

**Comment by kauffj** [comment]
Sounds good, thanks and welcome @Bentley912!

**Comment by Bentley912** [comment]
@tzarebczan does this need to be added to the Changelog? It is a very minor change.

**Comment by tzarebczan** [comment]
Yep, we should always have a change log. Check out the previous entries for proper format.

**Comment by tzarebczan** [comment]
FIxed in https://github.com/lbryio/lbry-app/commit/ddf1397a2816d9ccfe7a64f444465c7cee87c127
