### ISSUE TITLE
UI improvement: Autoplay function needs better icon and description

### ISSUE THREAD

**Issue by LavRadis** [lbryio/lbry-app#1539]
## The Issue
The new "Autoplay" function sticks out of the UI design and looks out of place. It needs a better icon and placment.
It also needs some sort of explanation. I was confused about what it exactly does, so it could confuse other users with less experience.  
The explanation could be in the form of hover-over description and/or helper text in "Settings" 

## System Configuration

- LBRY Daemon version: 	0.19.3
- LBRY App version: 0.22.0-rc.9
- LBRY Installation ID: 7tYN144rHXrspzJG9xLP28fi1JztXnbpKro6DBJEQyzBmXTyDgqRLfYsUvHYFVmMe2
- Operating system: Windows (Windows-10-10.0.16299)

## Screenshots
![autoplay](https://user-images.githubusercontent.com/10566738/40865317-fa363b10-65f7-11e8-87e3-1a5f9fda7b0c.jpg)

**Comment by seanyesmunt** [comment]
I am thinking something like air bnb's map switch?
<img width="210" alt="screen shot 2018-06-03 at 3 50 42 pm" src="https://user-images.githubusercontent.com/16882830/40890552-fa0801b0-6745-11e8-9fd6-af232e990aba.png">

**Comment by seanyesmunt** [comment]
This will be a global input style to replace the checkbox. We can also add a tooltip for a larger description on this.

**Comment by tzarebczan** [comment]
We added the toggle, now just need the tool tip.

**Comment by seanyesmunt** [comment]
It's only if you hover over autoplay. I guess it should be if you hover
over any part of it

**Comment by tzarebczan** [comment]
Yep, that's what I tried first haha and didn't bother checking the label.

**Comment by tzarebczan** [comment]
This is fixed in the redesign, still looking for the exact placement though.
