### ISSUE TITLE
"extraneous params: transaction_id" when claiming a reward

### ISSUE THREAD

**Issue by 6ea86b96** [lbryio/lbry-app#154]
Seems like there might be some extra param whitelisting needed on the backend. This particular error occurred when clicking the button to claim the channel surfing reward on the rewards page.

![2017-05-29 at 13 51](https://cloud.githubusercontent.com/assets/20863631/26545321/34777f7c-4476-11e7-96a1-73dc6a08bce2.jpg)

**Comment by lyoshenka** [comment]
fixed
