### ISSUE TITLE
Partial failure to launch.

### ISSUE THREAD

**Issue by WayneTheJockRonson** [lbryio/lbry-app#1540]
## The Issue
LBRY app (windows 10 downloaded june 3 2018) launches, but then gets stuck on the "connecting, starting Daemon" screen forever.
### Steps to Reproduce
1.download and intall from webpage.
2.restart computer
3.attempt launch

### Expected Behaviour
The program should launched, then also be usable (obviosly).

### Actual Behaviour
Not much. A little loading bar. then a blank teal window for 30 years.
### Suggested Solutions
I'm not a Doctor.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
Please see https://lbry.io/startup-troubleshooting

If you continue to have issues, send us your logfile to help@lbry.io 

Https://lbry.io/faq/how-to-find-lbry-log-file
