### ISSUE TITLE
Redesign: NSFW content claim pages not masked/blocked

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1546]
## The Issue
In the redesign, you can still navigate to and download properly marked NSFW. The thumbnail does have the red image and note to go into settings on the Discover/channel pages, but you can still click on it to go to the claim page (should not be able to right?) and the claim page allows download/view (should not be able to unless setting is turned). 

Sample URL - see homepage or lbry://curl#bcd555ff11ec3084dc23d3b3b70ac7b93e6b3912

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
This is intentional. I am very much in favor of allowing people to navigate to the file page. I think the red color and description is enough of a warning. 

Interested in hearing others thoughts.

**Comment by tzarebczan** [comment]
Ah, now I do remember that conversation. @kauffj do you have a strong stance one way or another?

**Comment by kauffj** [comment]
@tzarebczan I have no opinion about this until my build is working again and I can actually see what we're talking about. I'm also archiving this thread, so please ping me again if you actually want an answer. Also, I trust @seanyesmunt, so we should do whatever he says.

(I do think, in time, it makes sense to evolve filtering from a binary option to a ternary of: on/blur/hide, but that'd be a new feature)
