### ISSUE TITLE
Highlighting doesn't work in video description box, links render as normal text

### ISSUE THREAD

**Issue by Feanor78** [lbryio/lbry-app#1548]
When writing the description for a video, highlighting does not work properly in the text entry box.  Also, when you put a link in the text, it renders as normal text in-app when published (i.e. no blue text or underlining happens).

**Comment by tzarebczan** [comment]
Per our convo, this is the same issue as https://github.com/lbryio/lbry-app/issues/1547 and the redesign has better link/markdown support.
