### ISSUE TITLE
Reward cannot be claimed messages when visiting rewards screen 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1555]
## The Issue
If you visit the rewards page after your first stream (not featured content) , it tries to claim the Watch Many Things reward and you get a "you haven't watched enough stuff yet" message. It also tries to claim the feature content reward and you get a 2nd message "you haven't watched a featured video from this time period yet". Users will. By confused as to why they are getting this message. 

We should fail silently on this check if we perform it automatically. 

### Steps to Reproduce
1. Stream soemthing on a new account that's not featured contnet
2. Visit the rewards page

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
I'm fairly certain this is a regression. Some places in code attempt to auto-check for those rewards but are supposed to swallow failures. @daovist is it is possible your latest reward improvements accidentally changed this?

**Comment by tzarebczan** [comment]
I don't think it's related to his latest changes... I remember seeing this a while ago but never reproduced it consistently until now.
