### ISSUE TITLE
Make it Easy For People to Find Their Log

### ISSUE THREAD

**Issue by Invariant-Change** [lbryio/lbry-app#1556]
Add a button to auto open log or log folder or both, so that users can send debugging information easier.

![image](https://user-images.githubusercontent.com/29914179/41013960-c1ff3f52-698b-11e8-9725-00566111aa92.png)

**Comment by seanyesmunt** [comment]
I really like this idea.

**Comment by Invariant-Change** [comment]
```js
<div className="card__actions">
            <Button
              button="primary"
              label={__('Open Log File')}
              icon={icons.MESSAGE}
              href="{log-location}"
            />
          </div>
```

[Code Location](https://github.com/lbryio/lbry-app/blob/d27308688b05759cea551ce8250d567a5254af6f/src/renderer/page/help/view.jsx)

**Comment by kauffj** [comment]
Agreed, this is a great idea @Invariant-Change!

The button should probably be somewhere else though. Either a standalone card, or in About?

**Comment by Invariant-Change** [comment]
As a separate section makes it easier to find. So I guess that is the best solution.

![image](https://user-images.githubusercontent.com/29914179/41045626-1337771c-69ec-11e8-91f7-098212bb1ce8.png)

**Comment by amitnndn** [comment]
I will take this up!

I had a couple of questions/clarifications - @kauffj @seanyesmunt 

* The log files location are mentioned in [this post](https://lbry.io/faq/how-to-find-lbry-log-file) and I am assuming that this is the right file. 
* I know that the electron shell plugin allows you to open external files that are on the file system, but it cannot open files with relative paths. Does anyone know how I can access properties like the user's home directory etc.?

**Comment by tzarebczan** [comment]
@amitnndn take a look at how we do this on the backup page: https://github.com/lbryio/lbry-app/blob/afaad1910e84d27140abaa696af53a985349c53d/src/renderer/page/backup/view.jsx

In this case, the setting is: `data_dir`

**Comment by amitnndn** [comment]
@tzarebczan Thank you! I will take a look at it.

**Comment by amitnndn** [comment]
#1600 I see that there is an issue opened, that is related to the changes in this issue. Can anybody with a Windows 10 system, click on the open log folder and let me know what folder it ends up opening? Thank you!

**Comment by tzarebczan** [comment]
On windows 10 and Mac, it opens to the parent folder of lbrynet, with it highlighted. Think you want to pass the logfile and have it open that folder.

**Comment by amitnndn** [comment]
@tzarebczan Is that happening when you click on 'Open Log Folder' or 'Open Log'?

**Comment by tzarebczan** [comment]
It's described in the issue. It happens when you click open log folder. Open log opens the logfile in notepad correctly.

**Comment by amitnndn** [comment]
Got it! 👍 A bit of a lag in my brain registering an Issue on a Friday night!!

**Comment by tzarebczan** [comment]
Closing this, https://github.com/lbryio/lbry-app/issues/1600 tracks latest issue.
