### ISSUE TITLE
App Error When Pending Update

### ISSUE THREAD

**Issue by Invariant-Change** [lbryio/lbry-app#1557]
The pending update created an error. After clicking OK, the app closed and Windows asked for permission for LBRY to make changes to the system. After relaunch the navigations bars were missing.

After closing the app and restarting, everything was OK again.

![image](https://user-images.githubusercontent.com/29914179/41015215-a48240f4-698c-11e8-8af5-3632014dc75a.png)
![image](https://user-images.githubusercontent.com/29914179/41015254-d301a2bc-698c-11e8-8479-5095255545d2.png)

**Comment by tzarebczan** [comment]
I think this was a hiccup on your end, haven't seen this from anyone else. Closing for now unless it pops up again

You can try reinstalling 0.21.5 and then upgrading again to see if it's reproducible.
