### ISSUE TITLE
Incorrect markdown preview on url with parentheses 

### ISSUE THREAD

**Issue by m160** [lbryio/lbry-app#1570]
## The Issue
The link in the markdown preview differs from published description when it's a parentheses in the url.

### Steps to Reproduce
1. Markdown text:
![capture1](https://user-images.githubusercontent.com/34570404/41202049-71c2d692-6cbb-11e8-98c5-73203f489618.PNG)

2. Markdown preview:
![capture2](https://user-images.githubusercontent.com/34570404/41202051-76a15e22-6cbb-11e8-9941-bf9ace47a975.PNG)

Here it's linking to https://en.wikipedia.org/wiki/Flying_monkeys_(psychology, without the last parentheses in the link so it directs to the incorrect url.

3. When published it renders correctly though:
![capture3](https://user-images.githubusercontent.com/34570404/41202052-799de6ae-6cbb-11e8-81cb-109943efd81b.PNG)

### Expected Behaviour
The markdown preview shouldn't differ from how it will actually appear

## System Configuration
- LBRY Daemon version: 0.19.3
- LBRY App version: 0.22.0-rc.9
- LBRY Installation ID: 2XLeCW8MRiQYbQvU57s3aFVvvGFqymwMuBngLZTL9qWHNazFkSauVgyq6Hdib8ieqr
- Operating system: Windows 10

## Anything Else
Another little thing I discovered was that tables don't preview correctly if there nothing in the last cell:
![capture4](https://user-images.githubusercontent.com/34570404/41202185-4b8a38a6-6cbd-11e8-9ec3-2ff5898ea2f8.PNG)

It should still be grey. It shows up correctly though:
![capture5](https://user-images.githubusercontent.com/34570404/41202187-4edaceee-6cbd-11e8-8582-0c4cb781078f.PNG)

Not huge issues, just nitpicking.

**Comment by kauffj** [comment]
Thanks @m160 - we like nitpicking

**Comment by btzr-io** [comment]
There is nothing we can do about the parenthesis:
> ### [Incorrect link parsing in preview mode #528](https://github.com/sparksuite/simplemde-markdown-editor/issues/528)

**Comment by btzr-io** [comment]
Also that's not the only problem with links, here is a full list of issues related:
https://github.com/markedjs/marked/issues/984

**Comment by btzr-io** [comment]
Possible solution (external fix):
https://github.com/RIP21/react-simplemde-editor/issues/47

**Comment by tiger5226** [comment]
solved and merged
