### ISSUE TITLE
Pass app version information to internal APIs

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1579]
## The Issue

`lbryio.authenticate` should be modified so that after a successful authentication is completed, additional system details are sent to a new endpoint.

- The new endpoint will be `/install/new` (and thus can be called `lbryio.call("install", "new")`). 
- It should be sent the following properties:
  - `app_id` (this is already sent to `/user/new`)
  - `app_version` (from package.json)
  - `daemon_version` (FROM THE DAEMON NOT FROM PACKAGE.JSON)
  - `operating_system` (Windows, Android, etc.)
  - `platform` (Windows 10, macOS 10.12, etc.)

Only the first two values, `app_id` and `app_version` are necessary to get this merged. If there is any trickiness with the later 3 values, please PR this without them.

Note: When running in dev mode, the version doesn't show correctly on the about page. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
Is this actually a release blocker?
