### ISSUE TITLE
LBRY is not working properly

### ISSUE THREAD

**Issue by kplesko** [lbryio/lbry-app#1588]
## The Issue
I've installed the latest version of LBRY (version 0.21.6) from deb package on my Ubuntu 16.04.1 distribution. LBRY app loads, but it cannot fetch any content on Discover tab (there is no error message, it's just trying and trying to fetch it, but without any success). I have access to my subscriptions on Subscriptions tab, but every video i try to open just opens a green screen on LBRY app. After that I can't do anything with the app and I need to restart it. I didn't have these problem with earlier versions. Also, search does not work for me at all. I am not sure if I'm doing it right. If I search for something generic (music, video, game), again the green screen appears and app is not usable.

### Steps to Reproduce
1. Click on any video or other content.

### Expected Behaviour
Video should start loading.

### Actual Behaviour
Green screen appears and the app is no longer usable. You can't do anything except clicking Quit in the menu in the tray.

## System Configuration
{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "build": "release",
    "ip": "93.142.76.85",
    "lbrynet_version": "0.19.3",
    "lbryschema_version": "0.0.15",
    "lbryum_version": "3.2.1",
    "os_release": "4.4.0-127-lowlatency",
    "os_system": "Linux",
    "platform": "Linux-4.4.0-127-lowlatency-x86_64-with-Ubuntu-16.04-xenial",
    "processor": "x86_64",
    "python_version": "2.7.12"
  }
}

- LBRY Daemon version: 0.19.3
- LBRY App version: 0.21.6
- LBRY Installation ID: 65GRvPUttmWb9RB7ZAnLctzpNz8nUsWs1xsRxqDSmpduBbfDQh2mBUovusc1uoP8Ab
- Operating system: Ubuntu 16.04.1

## Anything Else
I've rebooted my computer and reinstalled LBRY, I've cleared the cache in the LBRY app, but the behaviour did not change.

## Screenshots
![lbry 1 - fetch content never finishes](https://user-images.githubusercontent.com/32712528/41354527-82606490-6f1f-11e8-85a6-04d56227aa50.png)
![lbry 2 - green screen](https://user-images.githubusercontent.com/32712528/41354531-82bb89b0-6f1f-11e8-9d79-be6061b73132.png)

**Comment by tzarebczan** [comment]
@kplesko sorry to hear about the trouble. Can you bring up the developer control (ctrl shift I or from the developer menu) to see if there are any errors there.

Did you get a password prompt on startup? Lbry uses an authentication token to authorize the app for rewards and such... Possibly you declined that? You can check out https://lbry.io/faq/how-to-change-email on how to clean it out and possibly try again. 

Lastly if that doesn't turn up any clues, let's take a look at your log file: https://lbry.io/faq/how-to-find-lbry-log-file

**Comment by kplesko** [comment]
I've checked in Settings in Help tab.
Connected Email: None
Access Token: (empty)

![lbry 3 - email and access token](https://user-images.githubusercontent.com/32712528/41384239-ef6b7480-6f74-11e8-9197-d2d03a6a3c99.png)

I've never seen password prompt on startup of the app. I've never been asked to enter password. Here is the log file.
[lbrynet.log](https://github.com/lbryio/lbry-app/files/2100346/lbrynet.log)

**Comment by kplesko** [comment]
OK, I was reading through FAQ section on lbry.io and Github issues and realized what was the problem. It was not obvious, some clear error message was not provided by the app, but my gnome-keyring-daemon is not in my startup list and it is necessary for authentication, right?! After I've started gnome-keyring-daemon, everything works fine.

Thank you for your quick answer, it really helped me to find useful information. I now realize, I shouldn't have open an issue on Github, but rather send an e-mail. Sorry for that.

**Comment by tzarebczan** [comment]
I was actually just going to ask you to check that. If it's not already clear in the startup faq, I'll be sure to add this problem. It's harder to diagnose because of the lack of error, but the fetching content usually gives it away haha.

Hope you stick around, no problem about the issue... just glad you got it solved :)

If you'd like to test the new app with us, just give me a shout on chat.lbry.io (@jiggytom) and we'll get you setup with the redesign beta test.

**Comment by kauffj** [comment]
@tzarebczan can you open an issue to improve detection of this if one isn't open already? It's clear from @kplesko's experience that this is flawed UX.
