### ISSUE TITLE
upgrade prompt needs formatting/is unresponsive

### ISSUE THREAD

**Issue by daovist** [lbryio/lbry-app#1592]
related to issue #1536 

## The Issue

Upgrading a locally-built of the app on Linux shows upgrade prompt and it does not close. Clicking 'Skip' does nothing. Clicking 'Upgrade' eventually prompts a download after a minute+ wait.

Also, the formatting is off. There is an invisible link (white-on-white, I think) that takes a user to [the release page](https://github.com/lbryio/lbry-app/releases). Screenshot below.

### Steps to Reproduce
1. `yarn build`
2. `sudo dpkg -i LBRY...` 
3. `lbry`

### Expected Behaviour
Upgrade cleanly

### Actual Behaviour
Nothing

### Suggested Solutions
¯\_(ツ)_/¯

## System Configuration

- LBRY Daemon version:
- LBRY App version: 0.21.5 (manually changed in package.json to `yarn build` to debug)
- LBRY Installation ID:
- Operating system: Ubuntu 18.04

## Screenshots

![lbry leveled up](https://user-images.githubusercontent.com/34498824/41376086-29479f20-6f26-11e8-8716-c83951cd53ba.png)

**Comment by tzarebczan** [comment]
Also, the upgrade button doesn't work unless you click it like 5/10 times (and this only works sometimes), then you get a bunch of save prompts.

**Comment by tzarebczan** [comment]
This is due to 64 bit builds that we are doing in the redesign. File path is: Launching upgrade installer at /tmp/ar1h20/LBRY_0.21.6_amd64.deb

The file downloaded is LBRY_0.21.6.deb

**Comment by tzarebczan** [comment]
Another option is to open the folder instead of launching the file and give user better install instructions.

**Comment by tzarebczan** [comment]
@seanyesmunt do you want me to open a separate issue for the Deb path, or did you fix that?

**Comment by seanyesmunt** [comment]
Yeah we should open a separate issue for that one.
