### ISSUE TITLE
Cards not marked NSFW in Search (or don't display result at all?)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1610]
## The Issue
We do not mark tiles in search results as NSFW like we do in channels/discover page. Should we not show them at all if a user does not have NSFW turned on? 

![nsfw search](https://user-images.githubusercontent.com/8120721/41490326-896da2f4-70c1-11e8-9162-3ec286520b3e.jpg)

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tiger5226** [comment]
I believe I solved it with https://github.com/lbryio/lbry-app/pull/1617

<img width="1184" alt="screen shot 2018-06-16 at 12 46 50 pm" src="https://user-images.githubusercontent.com/3402064/41500654-e927ec84-7163-11e8-9417-9d467e5bc154.png">
