### ISSUE TITLE
Aspect ratio incorrect for cards on Search page

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1611]
## The Issue
Looks like the size is 156.25x100, which is a different aspect ratio than explore/file page cards.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tiger5226** [comment]
https://github.com/lbryio/lbry-app/pull/1595 made some updates here for this.

**Comment by tzarebczan** [comment]
part of https://github.com/lbryio/lbry-app/pull/1629

**Comment by tzarebczan** [comment]
Fixed in 1629.
