### ISSUE TITLE
Pass claim bid/fee as string instead of number

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1614]
## The Issue
If we upgrade to the latest daemon RC, we should pass the claim bid and fee as a string instead of number. 
See https://github.com/lbryio/lbry/issues/1251 / https://github.com/lbryio/lbry/commit/e7deecc7ce84a6139ce74f1bad4f124c55c1e62d

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
Why would a string be preferred to a number? Sounds like a daemon bug - is an app-side change actually necessary here?

**Comment by tzarebczan** [comment]
Was just going based off @eukreign 's Comment here https://github.com/lbryio/lbry/issues/1251#issuecomment-397492196

**Comment by eukreign** [comment]
Ideal would be an integer representing the amount in satoshis. If we're accepting decimals then string is better since there is no decimal type in JSON and a string would most accurately let user represent the decimal.

**Comment by kauffj** [comment]
I would disagree relatively strongly that passing as a string is the right solution to this. Can discuss on upcoming protocol meeting or in the office.

**Comment by tzarebczan** [comment]
No need anymore, the latest fix seems to work: https://github.com/lbryio/lbry/pull/1257
