### ISSUE TITLE
Your copy of LBRY is up to date in Help, but isn't! 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#162]
## The Issue
Help page shows my copy of LBRY is up to date, but a later release is available.  I was prompted upon startup, but clicked Skip. 
### Steps to reproduce
1. Prompted for LBRY update upon app startup, click Skip
2. Go to Help
3. Shows LBRY up to date

### Expected behaviour
Should show new version is available

### Actual behaviour
Shows up to date

## System Configuration

 

- LBRY Daemon version:
- LBRY App version: 0.11.6
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
Fixed
