### ISSUE TITLE
Claim ID merged with Transaction ID in Transaction History

### ISSUE THREAD

**Issue by Grayyyyy** [lbryio/lbry-app#1621]
## The Issue
The Transaction History doesn't put a limit on characters for the Claim ID, so it continues on to the Transaction ID, which makes the IDs look unclean.

### Steps to Reproduce
1. Go to Wallet
2. Go to Transactions
3. Look for one of your claims in the Transaction History

### Expected Behaviour
The Claim ID not merging with the Transaction ID.

### Actual Behaviour
The Claim ID merging with the Transaction ID.

### Suggested Solutions
Add a character limiter for the Claim ID, so instead of:
"352949632014099804987978969215341364248576n79eac31"
it would show as something like:
"352949632014099804987978969215...                       79eac31"

## System Configuration

![image](https://user-images.githubusercontent.com/37783688/41503195-acb5a2f8-7192-11e8-9980-6cfc5a2c6d93.png)

## Screenshots
![image](https://user-images.githubusercontent.com/37783688/41503189-60caa4a6-7192-11e8-9329-6b6c45690b8a.png)

**Comment by tzarebczan** [comment]
Fixed in: https://github.com/lbryio/lbry-app/pull/1694
