### ISSUE TITLE
LBRY update not working in Windows

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#163]
## The Issue
When prompted to upgrade in Windows, the installer does not run after download. 
### Steps to reproduce
1) run v11.6 and get prompt for upgrade
2) Download update
3) Run update 

### Expected behaviour
Installation file is executed or directory opens

### Actual behaviour
Nothing

Debugging -
Found 2 issues, 1) the LBRY file name for Windows is not consistent with what is downloaded, fixed here:
	    case 'win32':
	      return `LBRY.${version}.exe`;

The original has return `LBRY.Setup.${version}.exe`;

2) the upgradeDownloadPath variable points to the upgrade directory, not the file itself (not sure if the goal was to open the download dir, or open the exe). I tried pointing it to the file directly, but still, nothing is kicked off by:
function upgrade(event, installerPath) {
  app.on('quit', () => {
    console.log('Launching upgrade installer at', installerPath);
    // This gets triggered called after *all* other quit-related events, so
    // we'll only get here if we're fully prepared and quitting for real.
    openItem(installerPath);
  });

I was able to get a console.print in doStartUpgrade()  function (could not get console to print from main - so I'm assumming that the parameter is passed correctly):

debug with path: Launching upgrade installer at C:\Users\thoma\AppData\Local\Temp\CWx1v1
debug with file: C:\Users\thoma\AppData\Local\Temp\CWx1v1\LBRY_0.11.7.exe

Does this help:

shell

The shell api is an electron only api that you can use to shell execute a file at a given path, which will use the OS default application to open the file.

const {shell} = require('electron');
// Open a local file in the default app
shell.openItem('c:\\example.txt');

## System Configuration

 

- LBRY Daemon version:
- LBRY App version: .11.6
- LBRY Installation ID:
- Operating system:

**Comment by alexliebowitz** [comment]
I'm looking into this. The goal was to run the executable, but I believe openItem should work with both executables and directories (dirs open in Explorer). So it's weird that nothing at all is happening.

Upgrades were working on all three platforms until recently, so I would think this is a Redux issue, but you manually hacked in the full installer path and still nothing happened, so that's interesting. Will keep you posted.

**Comment by tzarebczan** [comment]
Like I said, I could not get the debug to work on the main.js side, that log was coming from bundle.js. So still not sure it's being passed correctly.  I'm a newbie, still learning :) 

Thanks for looking into it!

**Comment by kauffj** [comment]
@tzarebczan FYI, console statements from app/main.js will print to the actual console you use to launch the app.

**Comment by nikooo777** [comment]
reporting from slack:
@zentralsonne says

> Auto-update does not work
> After downloading the update and re-opening the application, the update message appears again and a cycle is obtained.
> Win 10.  Autoupdate from 0.11.7 to 0.11.8
> I'll try to download manually from git
> Manual update to 0.11.8 works normal.

**Comment by tzarebczan** [comment]
Yup, don't think this was worked on. Separate issue than the one mentioned in the change log.

**Comment by alexliebowitz** [comment]
Fixed in #176. Thanks for the heads up.

**Comment by alexliebowitz** [comment]
I think @ZentralSonne's problem is totally unrelated (and possibly fixed already? That kind of thing can happen if the wrong version is up on lbry.io). If it's still happening, we should make a new issue.

**Comment by finer9** [comment]
.11.9 is telling me I need to update - but is already current - Windows 10

**Comment by tzarebczan** [comment]
I'm on same version and Windows too, not seeing an update message. Restarted the app too.

**Comment by finer9** [comment]
I messed with my install_id - related?

**Comment by kauffj** [comment]
Same caching issue as before? Or try full uninstall / reinstall?

**Comment by polminer** [comment]
Porblem with manuall update.
Installed https://github.com/lbryio/lbry-app/releases/tag/v0.12.0rc3
this version.
But in Settings -HELP- About shows  old version
![2721](https://user-images.githubusercontent.com/26439658/26876192-a2f15a2c-4b8d-11e7-8a29-09f25bf0d758.png)

**Comment by kauffj** [comment]
@polminer above was just fixed, version reporting was wrong in RCs.

I don't think upgrading is currently broken, so I'm going to close this. Re-open if I'm wrong.
