### ISSUE TITLE
Add whatever magic "yarn cache clean lbry-redux" does to other yarn scripts and readme

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-app#1634]
I'm pretty sure I've spent several hours over the last few months on random bugs that were due to `lbry-redux` being out of date.

The instructions for [Resetting your Packages](https://github.com/lbryio/lbry-app#resetting-your-packages) do not actually work. They only work if you run `yarn clean` in between.

It would be good if the instructions made it clear how to do a full reset, and it'd also be good if whatever magic happens inside of `yarn clean` that actually allows `lbry-redux` to update happens in other places as well so that it, you know, actually updates.

**Comment by seanyesmunt** [comment]
Added in #1726
