### ISSUE TITLE
[feature-request] flatpak for wider linux distribution

### ISSUE THREAD

**Issue by CurtisLeeBolin** [lbryio/lbry-app#1644]
Please consider releasing a flatpack package so more linux distros can easily run LBRY.

More info at: https://flatpak.org/

**Comment by tzarebczan** [comment]
See previous discussion at https://github.com/lbryio/lbry-app/issues/570

We'll need to revisit snap vs app image at some point, but Linux is least used platform, so it's difficult to prioritize at the moment.

**Comment by CurtisLeeBolin** [comment]
@tzarebczan, thank you for your quick reply.

You mentioned the problem in your statement.  Yes, Linux adoption is low because it is only packaged for one distro.  You can't expect high adoption unless it is packaged for all distros and hosted on one of the package hub sites, flathub.org or appimage.github.io .  The hub sites are basically **free advertisement**.

Snap wouldn't be any better because it is so ubuntu centric. The project claims to work on many distros, but in reality, it and most packages are broken on other distros.  Their site claims Arch Linux support, but it is a third party AUR package that has a fatal error during compilation (I just tried it again to make sure this is still true).  I have tried snaps on many distros and always had trouble unless the distro was Ubuntu.

AppImage is fine.  The user must make the file executable and directly execute the file. Preference aside, this would be a great option. 

Flatpack would make it more visible and easier to install.  It would be directly searchable in the Gnome Software Center or just a simple click on the hub webpage would install the app.
