### ISSUE TITLE
Startup API flood

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry-app#165]
## The Issue
When starting the application, the API gets flooded to oblivion and never really starts. The console output suggests that there might be at least one race condition causing calls to be replayed more than once. Also no timeout between checks seems to be present.
### Steps to reproduce
1. make sure no daemon is running
2. start LBRY
3. _cry a little_

### Expected behaviour
LBRY app should open

### Actual behaviour
The daemon never actually starts and the app will fail to load

## System Configuration

```
{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "build": "release",
    "ip": "*************",
    "lbrynet_version": "0.10.3",
    "lbryschema_version": "0.0.4",
    "lbryum_version": "2.7.22",
    "os_release": "4.8.0-52-generic",
    "os_system": "Linux",
    "platform": "Linux-4.8.0-52-generic-x86_64-with-Ubuntu-16.10-yakkety",
    "processor": "x86_64",
    "python_version": "2.7.12"
  }
}
```

## Screenshots
not a screenshot but a video of the issue:

https://www.youtube.com/watch?v=Jr-RlXm-w1w

**Comment by nikooo777** [comment]
let me add one thing i just noticed:

after hitting close, a daemon appears to start

```
niko@niko-T440p:~/lbry$ ps x | grep lbry
21618 ?        Sl     0:03 /opt/LBRY/lbry
21622 ?        S      0:00 /opt/LBRY/lbry --type=zygote --no-sandbox
22346 ?        S      0:00 /opt/LBRY/resources/app/dist/lbrynet-daemon
22348 ?        Sl     0:00 /opt/LBRY/resources/app/dist/lbrynet-daemon
22360 pts/2    S+     0:00 grep --color=auto lbry
```

**Comment by kauffj** [comment]
Let me know if you see this again post 0.12.2.
