### ISSUE TITLE
Fade automatic dark mode text when dark themes selected

### ISSUE THREAD

**Issue by vv181** [lbryio/lbry-app#1658]
## The Issue
If we already choose the dark theme, try to make the "Automatic dark mode" text a little bit fading, so the user aware it can't be ticked.

### Expected Behaviour
Tell us what should happen.

### Actual Behaviour
Tell us what happens instead.

### Suggested Solutions
Tell us your suggested solutions if you have any.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

## Screenshots

https://media.discordapp.net/attachments/443408117057847298/459142345707880469/Screenshot_from_2018-06-21_06-43-40.png

**Comment by btzr-io** [comment]
Fixed and merged in master.
