### ISSUE TITLE
Error when entering authcode on latest build

### ISSUE THREAD

**Issue by finer9** [lbryio/lbry-app#166]
## The Issue
<img width="548" alt="auth" src="https://cloud.githubusercontent.com/assets/16390156/26659589/c96b9b98-463f-11e7-9f40-28d06c06b875.PNG">

### Steps to reproduce
1. Install 0.11.8
2. Enter email josh@lbry.io
3. Enter code 2ee7409fcbc1ae8ca3ba8c342847038c
 
### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## System Configuration

 

- LBRY Daemon version: 
- LBRY App version:
- LBRY Installation ID:
- Operating system: Win 10

**Comment by lyoshenka** [comment]
Fixed
