### ISSUE TITLE
Can't right click > paste into description on publish

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1664]
## The Issue
Can use ctrl-v, but right click doesn't work in Publish > Description. Might be worth looking into other parts of the app also. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by Invariant-Change** [comment]
The **description** area needs to be an **Input HTMLElement**. When I change the span to an input it works. However, it then requires restyling.

```html
<span class="cm-null cm-spell-error">This is the description text area, which is not an Input HTMLElement</span>
```
The code only lets the **context menu** work on **inputs**.
```js
  // If context menu is opened on Input
  if (isInput && value) {
    templates.push({
      label: 'Select All',
      accelerator: 'CmdOrCtrl+A',
      role: 'selectall',
    });
  }
```

See [contextMenu.js](https://github.com/lbryio/lbry-app/blob/ae93a0d95d9209ea40d897bba0fdfa7c1f08028a/src/renderer/util/contextMenu.js)

**Comment by btzr-io** [comment]
This requires a more complex fix :upside_down_face:  ^^
See https://github.com/RIP21/react-simplemde-editor/issues/67
