### ISSUE TITLE
publishes not updating - going into downloads instead

### ISSUE THREAD

**Issue by reillysmith** [lbryio/lbry-app#167]
## The Issue
Publishing Content is on network but not on my Publishes
### Steps to reproduce
1. Publish content
2. See it appear in Slack content feed. Click it.
3. Watch content. See it re-appear in your downloads as a new title, but never in your Publishes.

### Expected behaviour
Content should appear in Publishes

### Actual behaviour
Content does not appear in Publishes after being published; but if you watch it on the network, it will show up as a new Downloads item.

## System Configuration

 

- LBRY Daemon version: 0.10.3
- LBRY App version: 0.11.8
- LBRY Installation ID: 2rj8iPgKnXFVGwXpvAeBEg5shUEmf7brKLwHqeEJj87xg58i7QbkLkQ71NLB5np9ek
- Operating system: Mac OS X 15.6.0

## Screenshots

![content published](https://cloud.githubusercontent.com/assets/6074888/26662647/414b402e-463a-11e7-9a41-bbe869220ea5.png)
![downloads-page](https://cloud.githubusercontent.com/assets/6074888/26662648/414c88f8-463a-11e7-8564-1c455ed9a54e.png)
![publishes-page](https://cloud.githubusercontent.com/assets/6074888/26662646/414a7e32-463a-11e7-9fea-0d7a724f9729.png)

**Comment by reillysmith** [comment]
revised note: they appear to eventually go into Publishes upon reloading the app.

they were all filling downloads, and then switched to Publishes (the recently published items)

**Comment by reillysmith** [comment]
![screen shot 2017-05-31 at 7 58 49 pm](https://cloud.githubusercontent.com/assets/6074888/26662845/a085df44-463b-11e7-98b0-6b0c4e776959.png)

**Comment by kauffj** [comment]
This should be fixed in 0.13, though you may see duplicates.
