### ISSUE TITLE
Need features like auto flush downloaded videos after certain time period like after 1 day, 1 month

### ISSUE THREAD

**Issue by iamuditpatel** [lbryio/lbry-app#1672]
If the video is important need option that mark as favorite video.. so when flush happen your favorite video is not delete from your computer hard disks..

This is great help to our valuable user to free up unnecessary videos that they don't really want to store :)

This is just demo i created in my local application..

![flush after](https://user-images.githubusercontent.com/11346292/41740528-ef51a798-75b5-11e8-8ae2-83709876ac8c.PNG)

**Comment by tzarebczan** [comment]
We'd need protocol support for this: https://github.com/lbryio/lbry/issues/1171 and I'm not sure this would be the best way to implement something like that UX wise (and may be tough to implement on the protocol - what if it's not running - then it won't flush right?). Closing this for now.
