### ISSUE TITLE
Spellcheck Needs Restyling in Dark Theme

### ISSUE THREAD

**Issue by Invariant-Change** [lbryio/lbry-app#1675]
## Spellcheck Needs Restyling in Dark Theme

The **styles** for **spellcheck** are hard to see in the **dark theme**.

## CURRENT

```css
background: rgba(255,0,0,.15);
```

![image](https://user-images.githubusercontent.com/29914179/41782538-e1400226-767d-11e8-8c9d-29ffa2991177.png)

## NEW DARK

```css
    text-decoration: underline;
    text-decoration-color: #ff2727;
    text-decoration-style: dotted;
```

![image](https://user-images.githubusercontent.com/29914179/41782485-b9c4420c-767d-11e8-8d09-ccfb59203a6f.png)

## NEW LIGHT

![image](https://user-images.githubusercontent.com/29914179/41782781-88ddc41e-767e-11e8-9de0-080ea488c6bd.png)

**Comment by tzarebczan** [comment]
@Invariant-Change why not just submit a PR? You can literally edit that on the web interface :)

**Comment by Invariant-Change** [comment]
Because I'm too tired, but will tomorrow. I have matchsticks under my eyes atm. Haha!

There are several I can fix, but thought it's better to post them here until I can do them, just in case someone else can do them quicker.

**Comment by Invariant-Change** [comment]
The fix can be found here: https://github.com/lbryio/lbry-app/pull/1679
