### ISSUE TITLE
Documentation for Publish API needs extra info

### ISSUE THREAD

**Issue by 42degrees** [lbryio/lbry-app#1678]
Looking at the documentation at: https://lbryio.github.io/lbry/ for "publish" API (and CLI, presumably) the 'name' field apparently has limitations on what characters can be in the field, but these are not documented. I have discovered through trial and error that at least spaces and commas are not allowed.  I don't know yet if other characters are also disallowed.

**Comment by 42degrees** [comment]
After digging through the code in lbry/Daemon.py and lbryschema/uri.py I finally found the regular expression governing names is:
valid_name_char = "[a-zA-Z0-9\-]"

That is pretty limiting and really should be documented.

**Comment by tzarebczan** [comment]
Issue moved to [lbryio/lbry #1268](https://github.com/lbryio/lbry/issues/1268) via [**ZenHub**](https://www.zenhub.com/)
