### ISSUE TITLE
cmd-r to refresh causes app screen to go perma green

### ISSUE THREAD

**Issue by reillysmith** [lbryio/lbry-app#168]
### Steps to reproduce
1. cmd-R on keyboard while on a screen you'd like to reload
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## System Configuration

 

LBRY Daemon version: 0.10.3
LBRY App version: 0.11.8
LBRY Installation ID: 2rj8iPgKnXFVGwXpvAeBEg5shUEmf7brKLwHqeEJj87xg58i7QbkLkQ71NLB5np9ek
Operating system: Mac OS X 15.6.0

**Comment by lyoshenka** [comment]
This is a known issue that started happening when we switched to Redux, and we never fixed it. @alexliebowitz can you take a look at this next time you get a chance.

**Comment by kauffj** [comment]
Actually, this is supposed to work now.

**Comment by lyoshenka** [comment]
So it does!
