### ISSUE TITLE
Better channel loading transition

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#1681]
## The Issue
See below - the transition when loading a channel for the first time can be improved.
https://www.screencast.com/t/UbUYgfBQklb

Also, @seanyesmunt noticed it doesn't have lbry:// in the URL for channels. 

### Steps to Reproduce
1. load a channel
2.
3.

### Expected Behaviour
Tell us what should happen.

### Actual Behaviour
Tell us what happens instead.

### Suggested Solutions
Tell us your suggested solutions if you have any.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
Fixed in #1711
