### ISSUE TITLE
New tab in Chrome with lbry:// link

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#169]
## The Issue
When clicking a lbry:// link from slack, a new tab opens in Chrome and then immediately the app pops up. The blank tab in chrome is still there with LBRY://.  Any way to not have the tab pop up or have it close right after? 

### Steps to reproduce
1. Open lbry:// link from slack
2. link opens in new tab, LBRY launches
3. tab is blank with lbry://, but blank page

### Expected behaviour
tab should not open, or tab should close when app is launched

### Actual behaviour
tab stays open to blank page with lbry:// URI

## System Configuration
Haven't tried Firefox, but IE (Edge) opens the app directly without creating new tab. 
 

- LBRY Daemon version:
- LBRY App version: 0.11.8
- LBRY Installation ID:
- Operating system: Windows 10, Chrome Browser

**Comment by alexliebowitz** [comment]
Hmm, having trouble replicating. Are you using Slack with the desktop app, or in browser? With the desktop app, I get this dialog, and then it launches in LBRY:
<img width="481" alt="screen shot 2017-06-03 at 3 55 17 am" src="https://cloud.githubusercontent.com/assets/7283989/26751887/ddf0cccc-4811-11e7-886f-f2fcf8880d4f.png">

**Comment by tzarebczan** [comment]
Slack website on chrome. Yes, I've defaulted my links to open with lbry
app, so I don't see that warning /prompt anymore. When I click on a link,
it opens in a new tab and then launches lbry app. Wonder if it's some
chrome setting I have regarding tabs. I'll have to try it on a vm and Linux
too.

**Comment by tzarebczan** [comment]
So if I open the link directly from https://lbry.io/news/epicenter ( lbry://@Epicenter ) it doesn't open a new tab. But when opened from the slack channel (#content), it does. Odd. Should I close for now? Probably something to do with the way slack handles hyperlinks.

**Comment by alexliebowitz** [comment]
Yeah, let's close this. If the Slack desktop app is working and other sites are working, it has to be something with the Slack web app. We're registering the protocol handler in the standard way for Windows.
