### ISSUE TITLE
Git Clone Master App = 1.8.7 But User Downloaded App = 0.22.0

### ISSUE THREAD

**Issue by Invariant-Change** [lbryio/lbry-app#1707]
Git Clone Master App = 1.8.7 But User Downloaded App = 0.22.0

### Git Clone Master App

![image](https://user-images.githubusercontent.com/29914179/41982572-20b7a41e-7a6f-11e8-9dae-44e9d5e6cac0.png)

### User Downloaded App

![image](https://user-images.githubusercontent.com/29914179/41982578-2757ac2e-7a6f-11e8-9ea2-fbe8386dfc58.png)

**Comment by tzarebczan** [comment]
This has been happening for a while.. Probably to do with how we are reading the verison on he help page. It should come from package.json
