### ISSUE TITLE
Can't Edit Existing Claim if Deposit Value is Changed

### ISSUE THREAD

**Issue by Invariant-Change** [lbryio/lbry-app#1712]
If you click in to the **deposit area** and **change** the **value**, you can no longer **edit** unless you have that **entire value** in your wallet, which isn't necessary because you've already made your claim.

Solution to this can also be the solution to @tzarebczan's filed issue: https://github.com/lbryio/lbry-app/issues/634 

### Before Value Changed Then Changed Back
![image](https://user-images.githubusercontent.com/29914179/42040081-309f8022-7b32-11e8-9c98-2f8e174cee40.png)
### After Value Changed Then Changed Back
![image](https://user-images.githubusercontent.com/29914179/42040088-35867ce4-7b32-11e8-89e5-6c4ad10d4438.png)

**Comment by tzarebczan** [comment]
Ah, good point... Completly forgot about this when I made the ux enhancements.

@seanyesmunt do you think we can get the current claim deposit and add that to the balance for this simple check? I'll look into this.

**Comment by Invariant-Change** [comment]
Just noticed - Styling issue with "`I agree to the`" text in above screengrab,

**Comment by tzarebczan** [comment]
I'm not seeing the same in the prod version. But I think I saw something similar on another screen via Dev mode/master. Let me see if it's something to do with Dev mode, or a recent change.

**Comment by seanyesmunt** [comment]
Fixed in https://github.com/lbryio/lbry-app/pull/1725
