### ISSUE TITLE
Chanding Video URL During Edit Changes The Edit Button To Publish Giving An Error Message

### ISSUE THREAD

**Issue by ceoger** [lbryio/lbry-app#1714]
## The Issue
I tried editing a video i published and what happens is,  when i change the video url under "Where can people find this content" the edit button changes to publish giving error massage of  "no source provided to publish"  if this is suppose to be the case then how about (graying out the url under  "where can people find my video" when we want to edit)

### Steps to Reproduce
1. Go to publishes
2. Select any video previously published
3. Select edit
4. try changing the video url to another url
5. Right away, edit changes to publish
6. Click publish and you get the error message "no source provided to publish" 

### Expected Behaviour
Tell us what should happen.
We should be able to change URL without having to publish the file again, otherwise the option for changing url should be grayed out so we wont be able to modify that

### Actual Behaviour
the option to change url remains and when i change url, the edit changes to publish

### Suggested Solutions
if this is suppose to be the case then how about (graying out the url under  "where can people find my video" when we want to edit) otherwise the edit button should not change to publish after modifying video url

## System Configuration

- LBRY Daemon version: 0.20.2
- LBRY App version: 0.22.0
- LBRY Installation ID: 3cXLZiAWXwwJbv4fjhbXVgFtaBuUiFQM7afXmFYu5ss1chD1WCpxGUp8aW68gjeNRC
- Operating system: Windows (Windows-10-10.0.16299)

## Screenshots

example of graying out a url input
https://cdn.discordapp.com/attachments/377895389992321064/461808954297679882/unknown.png

https://cdn.discordapp.com/attachments/377895389992321064/461809010614730752/disable.JPG

**Comment by tzarebczan** [comment]
Nice find and thanks for filing! We should either grey out the claim name during edit, or if they change it, alert them to select a file.

**Comment by ceoger** [comment]
@tzarebczan alerting them to select a file, isn't it going to be a publish? maybe they do not want to publish the same file again just updating the url, so i think either an option to change url or no option to change at all. they they can publish the same file again and use the preferred url

**Comment by seanyesmunt** [comment]
This one is tricky. We use the old url to retrieve the previously published file. If you change the url I'm not sure how we would determine if this is an edit or a new publish.

I like the idea of just disabling the input on edit. Maybe next to it we can say `This is an edit so you can't change the url, to start a new publish click "here"` or something similar.

**Comment by ceoger** [comment]
@seanyesmunt 
 **I like the idea of just disabling the input on edit**. Maybe next to it we can say 
> This is an edit so you can't change the url, to start a new publish click "here"
 or something similar.

sounds like perfect :100:
