### ISSUE TITLE
"prove Humanity" more than once same wallet on multiple machines

### ISSUE THREAD

**Issue by misternils** [lbryio/lbry-app#1733]
## The Issue
I authenticated my wallet on one machine, and have installed LBRY on a second.  I loaded my wallet from backup, but it is now asking me again to verify my wallet.   I verified after the backup.  Funds are correct. 

### Steps to Reproduce
1. install on machine one
2. install on machine two
3. Verify (on machine two)

### Expected Behaviour
Recognize verification on any node. 

### Actual Behaviour
Asks for e-mail, and rewards are greyed out

### Suggested Solutions
Tell us your suggested solutions if you have any.

## System Configuration
App | 0.22.1
Daemon (lbrynet) | 0.20.3
Wallet (lbryum) | 3.2.3

**Comment by tzarebczan** [comment]
Please see https://lbry.io/faq/lbry-basics on how authentication/rewards work. You can only sign in with a single email on one device currently (we'll be changing this in the future). If you plan on running on 2 machines, simply don't sign in on the other or sign in with a different email but do not go through the rewards process (rewards are 1 per person/household).

It's also not advisable to run the same wallet on 2 machines at the moment.
