### ISSUE TITLE
[Feature Request] Bring Back Bank icon on wallet area and header area [Redesign]

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry-app#1744]
## The Issue
on lbry app old version have a bank icon instead on header and wallet section area, but on the newest app doesnt have this icon. would be nice on next release of LBRY App have this bank icon.. so it means will make Design of LBRY App looks more pretty.
 
### Steps to Reproduce
1. Open LBRY App
2. looks header on You Have 5 LBC ( there no bank Icon)
3. Click Wallet ( on the balance section there no bank icon)

### Suggested Solutions
please compare this design with https://design.lbry.io as nizuka made for preview redesigned of app

## System Configuration

- LBRY Daemon version: 0.20.3
- LBRY App version: 0.22.1
- LBRY Installation ID: AEAjZLbq4u2yi4gZvaoickQwUtGkcXiy6i7f1ADiim1CPLQKmYE
- Operating system: Windows (Windows-10-10.0.17134)

## Screenshots

![image](https://user-images.githubusercontent.com/26609573/42471121-cc0d3970-83e6-11e8-9a14-f839a11ff0d1.png)

**Comment by tzarebczan** [comment]
It was actually a really poor Library icon, and not a bank (but it was easier to call a bank icon because of how it looked haha). If we add anything to this, it would be: https://github.com/lbryio/lbry-app/issues/251
