### ISSUE TITLE
First Publish	10 LBC - cannot claim reward : transaction_id: Transaction ID is not for a publish

### ISSUE THREAD

**Issue by jbshirk** [lbryio/lbry-app#1746]
## The Issue
Claiming First Publish from rewards page generates message:
transaction_id: Transaction ID is not for a publish

### Steps to Reproduce /Actual Behaviour
1. Publish a file, wait for upload
2. go to rewards page, claim "first publish"
3. get confusing message

### Expected Behaviour
1. Publish a file, wait for upload
2. go to rewards page, claim "first publish"
3. see wallet balance increase by 10 LBC

### Suggested Solutions
Tell us your suggested solutions if you have any.

## System Configuration

App	0.22.1
Daemon (lbrynet)	0.20.3
Wallet (lbryum)	3.2.3

- LBRY Installation ID: ?
- Operating system: OSX 10.12.6

## Screenshots

![screen shot 2018-07-09 at 4 23 41 pm](https://user-images.githubusercontent.com/3949396/42475592-15b8012a-8399-11e8-8935-be0384f41e7d.png)
![screen shot 2018-07-09 at 4 24 25 pm](https://user-images.githubusercontent.com/3949396/42475613-23d041be-8399-11e8-9f6a-446dd69b8599.png)
![screen shot 2018-07-09 at 4 26 19 pm](https://user-images.githubusercontent.com/3949396/42475628-2b1d0d6c-8399-11e8-9797-ded9758cb267.png)

**Comment by tzarebczan** [comment]
@jbshirk sorry for your trouble. Do you recall if you published this file after being rewards approved? Have you changed the email connected in your LBRY app recently? These would be the 2 common reasons this could happen. 

Send me your LBRY connected email (Help > Connected Email) to help@lbry.io and we'll take a closer look. In the meantime, you can try restarting the application, publishing again, waiting a few minutes and try claiming again.

**Comment by jbshirk** [comment]
Yes. Other rewards worked on schedule.

**Comment by tzarebczan** [comment]
Did you by any chance remove the published file? Please send the email as specified earlier. 

If you want to help troubleshoot this, enter Dev mode by clicking ctrl shift i (side bar will open). Then go to the network tab. As soon as you click the button to claim the reward, there should be a network call made to our api server with some parameters like transaction  ID and wallet address. Please send those in the email. 

This must be some edge case as other users are claiming thier publish rewards.

If you don't want to or can't help troubleshoot, try publishing another item after a restart and claim again.

**Comment by jbshirk** [comment]
Did you by any chance remove the published file?  : no, it's still accessible locally.

**Comment by tzarebczan** [comment]
Communicating with @jbshirk over email to try this again when we take a closer look on our API side. Seems like an edge case as other users are able to claim their first publish reward. The app is sending all the data as expected.
