### ISSUE TITLE
Issue when clicking back while video playing

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#175]
## The Issue
The video keeps playing, but metadata is shown from whatever was in the previous screen
### Steps to reproduce
1. Go to video 1, then go to video 2
2. Play video 2, click back
3. metadata from 1 is shown, video 2 is playing

### Expected behaviour
video stops playing, 1 is shown

### Actual behaviour
Video 2 keeps playing

## System Configuration

 

- LBRY Daemon version:
- LBRY App version: 0.11.8
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
@tzarebczan I think this is fixed in 0.13, re-open if not.
