### ISSUE TITLE
Clicking the video player should pause the video

### ISSUE THREAD

**Issue by polminer** [lbryio/lbry-app#178]
## The Issue
The problem with the video player PAUSE.

### Expected behaviour
Start playing, when you click again on the screen - pause.

### Actual behaviour
if you click on the screen again, nothing happens, the video does not pause.

## System Configuration

daemon (lbrynet)	0.10.3
wallet (lbryum)	2.7.22
interface	0.11.9
Platform	Windows (Windows-10-10.0.14393)
Installation ID	8BrBaZkd2gjJCfWjrcQaW23238qnZthdK7hRku3CqvQRsuDHdhBjPRYwpaCpH6Cn6A

**Comment by filipnyquist** [comment]
I´m running:
daemon (lbrynet)	0.10.3
wallet (lbryum)	2.7.22
interface	0.11.9
Platform	Windows (Windows-10-10.0.15063)
and does not seem to have this problem

**Comment by kauffj** [comment]
Rolled into #311
