### ISSUE TITLE
Labels that are displayed as blocks cause confusing UX (example inside)

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-app#179]
Migrated from https://github.com/lbryio/lbry/issues/209

When my mouse is in the Fee area of Publish tab, if I click FEE, and input my amount, if i click away out of that box in a line parallel to the No Fee radio button, far to the right, it will select No Fee again

**Comment by lyoshenka** [comment]
Not sure if this is still an issue

**Comment by kauffj** [comment]
This issue isn't specific to publish, if labels have bounding containers larger than the text, this will cause other confusing issues.

**Comment by liamcardenas** [comment]
We are not able to replicate this, it was probably fixed in an update to the UI. If you are still seeing this feel free to reopen.
