### ISSUE TITLE
LBRY app does not upgrade properly on Ubuntu 16.10

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-app#18]
## The Issue

The upgrade process does not successfully update the installed version of LBRY app.

### Steps to reproduce
1. Run 0.9.0
2. Click "Upgrade" when the app runs
3. Watch as the updated version downloads successfully and the app closes
4. And then nothing else happens...

### Expected behaviour
At number 4 above, the app would re-open and be on 0.9.1.

### Actual behaviour
I have to re-open the app manually and it is still 0.9.0.

## System Configuration
- LBRY Daemon version: 0.9.0
- LBRY App version: 0.9.0rc15
- LBRY Installation ID: 62jf7sawDBFBKBJ6vQJ2
- Operating system: Ubuntu 16.10

**Comment by lyoshenka** [comment]
@alexliebowitz is this fixed?

**Comment by alexliebowitz** [comment]
When I run on the current master (https://github.com/lbryio/lbry-app/commit/a450d294ca6ccc692c3b27a650146572851799a4) it correctly launches the package manager with the new version. OTOH I don't remember actually changing anything to fix it.

@kauffj: can you see if it's currently happening for you? Easiest way to test with a dev install is to change [https://github.com/lbryio/lbry-app/blob/e83118a34b53bfbe191f8cb9d2ea8626e63d6aae/app/main.js#L58](this line) to `const upgradeAvailable = true;`

I wonder if we should add some way to force the upgrade screen to appear at runtime--a hidden method on the `lbry` object or something like that. That would make it easier to test the upgrade process in our CI builds in case there are bugs that are only showing up in release.

**Comment by maximumplank** [comment]
Had this happen when I was prompted to upgrade to 0.11 on Ubuntu 16.04

**Comment by kauffj** [comment]
@maximumplank this was broken in 0.11 for sure. Can you try downloading 0.11.3 and see if it upgrades you to 0.11.5 correctly?
