### ISSUE TITLE
When pausing a download, progress drops to zero

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-app#180]
Migrated from https://github.com/lbryio/lbry/issues/254

When attempting to pause a download, the progress drops to zero:

![image](https://zippy.gfycat.com/SilverUnripeImago.gif)

**Comment by kauffj** [comment]
That entire component shouldn't even exist right now.

**Comment by kauffj** [comment]
Indeed, it does not exist, and this is an old ticket with a tricky current date due to migration.
