### ISSUE TITLE
Updating an existing claim breaks the redux store

### ISSUE THREAD

**Issue by 6ea86b96** [lbryio/lbry-app#186]
### Steps to reproduce
1. Publish a file
2. Now publish another file at the same uri

### Expected behaviour

It should update or replace the existing claim and fileinfo

### Actual behaviour

We have 2 versions of the claim in the store, which breaks the downloaded/published pages and the new fileinfo isn't loaded.

**Comment by alexliebowitz** [comment]
@kauffj: I could take this one. It follows on naturally from the pre-fill stuff. Plus I'll be mucking around in the Redux logic where it stores the list of files to diagnose the bug I mentioned in #142.

**Comment by kauffj** [comment]
@alexliebowitz please do, and please mark yourself as assignee when you'd like to take ownership. Thanks1
