### ISSUE TITLE
Case sensitivity of channels/claims?

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#195]
Is it intended behavior that claims and channels are case sensitive? i.e. lbry://@oscopelabs <> lbry://@OSCOPELABS

**Comment by polminer** [comment]
I described this promlem earlier in slack channel. wiil find later and past here

**Comment by kauffj** [comment]
This was a poor design choice that needs to be fixed at the [blockchain level](https://github.com/lbryio/lbrycrd/issues/65).
