### ISSUE TITLE
No URI Handling

### ISSUE THREAD

**Issue by jobevers** [lbryio/lbry-app#2]
Currently the app doesn't do anything on `lbry://` uris.

**Comment by jobevers** [comment]
See

- http://electron.atom.io/docs/api/app/#appsetasdefaultprotocolclientprotocol-path-args-macos-windows
- https://github.com/electron-userland/electron-builder/wiki/Options#Protocol

**Comment by alexliebowitz** [comment]
@lyoshenka: Are you planning to work on this or just supervising it? I can own this, looks pretty small (at least in theory)

**Comment by lyoshenka** [comment]
Go for it

**Comment by alexliebowitz** [comment]
Fixed for Mac by #116 and Windows by #121. Linux still in progress (#122).

**Comment by alexliebowitz** [comment]
We decided to merge Linux (although there's an unrelated issue that means it doesn't work perfectly yet). So I'm marking this resolved.
