### ISSUE TITLE
UI unresponsive when accessing wallet on Ubuntu

### ISSUE THREAD

**Issue by maximumplank** [lbryio/lbry-app#205]
## The Issue
Sorry if this is confusing, it was strange to me as well. Refer to steps to reproduce if this doesn't make sense.
When accessing wallet functions with the browser, the UI fails to update when attempting to switch from the 'Overview' (default) tab to the 'Send' and 'Receive' tabs. Switching to the 'Rewards' tab works fine, as does switching from the 'Rewards' tab to the 'Overview' and 'Receive' tabs, but attempting to switch from the 'Rewards' tab to the 'Send' tab will cause the non-control bar portion of the UI to hang (the content portion). I need to restart the browser to access other pages. The control bar will still update, but clicking the buttons yields nothing

### Steps to reproduce
1. Launch browser
2. Open wallet functions (click balance in control bar)
3. Switch to 'Send' and 'Receive' tabs, no update to UI (control bar updates)
4. Switch to 'Rewards' tab, UI should update
5. Switch to 'Receive' tab, UI should update
6. Switch to 'Send' tab, no update to UI (control bar updates)
7. Switch back to 'Rewards' tab, then to 'Send' tab
8. Nothing I do will update the UI after this, but control bar still updates

### Expected behaviour
Tabs should switch without wonkyness

### Actual behaviour
Tabs in wallet fail to switch in a pattern without apparent logic, and one of these switches causes the browser UI to freeze

## System Configuration
app version: https://i.supload.com/rJYer6NMW.png

{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "build": "rc",
    "ip": "73.158.155.244",
    "lbrynet_version": "0.11.0rc1",
    "lbryschema_version": "0.0.6",
    "lbryum_version": "2.7.24",
    "os_release": "4.4.0-78-generic",
    "os_system": "Linux",
    "platform": "Linux-4.4.0-78-generic-x86_64-with-Ubuntu-16.04-xenial",
    "processor": "x86_64",
    "python_version": "2.7.12"
  }

## Anything Else
I'm still able to send LBC using RPC commands to the client, so nothing to panic about.

## Screenshots
screenshot after UI has become totally unresponsive (excluding control bar): https://i.supload.com/B1NeSTNMW.png

**Comment by tzarebczan** [comment]
Can you try the latest Rc? https://github.com/lbryio/lbry-app/issues/198 sounds like this issue that was recently fixed.

**Comment by maximumplank** [comment]
Sorry, thought I had updated. This appears to be un-wonked on 0.12.0-rc3. Although the client info in the help screen still indicated the interface is version 11.9. Is the interface version different from the release version on github?

Closing this, thanks.
