### ISSUE TITLE
Author Fields Blank - Suggest delete from UI, or re-add to Publish

### ISSUE THREAD

**Issue by reillysmith** [lbryio/lbry-app#208]
## The Issue
Author field needs to be removed as a metadata field, since it's no longer in publish process. Or, re-add it to publish process so copyright can properly auto-fill again.

### Steps to reproduce
1. Attempt to publish
2. Look at new content publishes which have empty Author fields.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

## Screenshots
![author-field](https://user-images.githubusercontent.com/6074888/26907933-1f86f83a-4bac-11e7-990e-ec6f86fca396.png)

**Comment by kauffj** [comment]
Will be fixed in 0.12.3.
