### ISSUE TITLE
App should indicate what content is featured / eligible for "Hot Right Now" award

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-app#211]
Otherwise people won't know what to watch to get the reward.

**Comment by kauffj** [comment]
Is there an endpoint for this?

**Comment by lyoshenka** [comment]
https://api.lbry.io/reward/list_featured

**Comment by lyoshenka** [comment]
@kauffj fixed?

**Comment by tzarebczan** [comment]
Yep, just checked it out in 0.14.2
