### ISSUE TITLE
LBRY will not open on Mac OS.

### ISSUE THREAD

**Issue by rcanolty** [lbryio/lbry-app#219]
## The Issue
LBRY will not open on Mac OS.

### Steps to reproduce
1. Got email from LBRY at 14:51 EST, clicked on MAC OS button to download latest app.
2. Opened .dmg and dragged LBRY to Applications folder.
3. Message says "The daemon has unexpectedly shutdown. Goodbye."

### Expected behaviour
should open

### Actual behaviour
does not open

## System Configuration

 
Version 0.11.9 (0.11.9.1072)

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
Can you:

1. Make sure no lbry processes are running
1. Run the application
1. Email `~/lbrynet/lbrynet.log` to jeremy@lbry.io

Thanks!

**Comment by kauffj** [comment]
And sorry it didn't work! :(

**Comment by tzarebczan** [comment]
@jackrobison - same issue as the guy on slack recently? db migration? 

@rcanolty did you have lbry installed previously?

**Comment by rcanolty** [comment]
i had lbry installed previously, when I put app in Applications folder, was asked if I wanted to replace old version, i said yes. i do not recall using lbry before, however (i may have just installed without opening).

**Comment by rcanolty** [comment]
I don't see this file. Terminal command "ls -a" shows me a hidden file .lbryum, but no .lbrynet.

**Comment by jackrobison** [comment]
on os x the lbrynet data folder is `~/Library/Application Support/LBRY` @kauffj 

https://lbry.io/faq/lbry-directories

**Comment by rcanolty** [comment]
Ah, got it. log file attached as text.
[lbrynet.txt](https://github.com/lbryio/lbry-app/files/1075212/lbrynet.txt)

**Comment by kauffj** [comment]
Looks like the issue is a failure for the `claim_ids` table to be corrected. We'll get this fixed.

Appreciate your help on this @rcanolty, if you send me or post a wallet address, happy to send you a tip.

(And if you can't get a wallet address until we fix this, you'll get a notification when this is closed.)

**Comment by jackrobison** [comment]
to manually bypass this, delete `blockchainname.db` and `db_revision` in the lbrynet data folder

**Comment by jackrobison** [comment]
@rcanolty what was the very first version you installed, or around when did you initially install it?

**Comment by rcanolty** [comment]
Not sure of first version number, but first email from LBRY was 2016 may 08.
Glad to help, I'd like to see this project succeed.

**Comment by kauffj** [comment]
While definitely a bug, this only affects a small number of old installs and may never get fixed.

Please contact help@lbry.io and reference this GitHub issue if you'd like assistance from our team in migrating and getting it running again.

**Comment by kauffj** [comment]
And sorry!

**Comment by rcanolty** [comment]
If the LBRY tip offer still stands, here is my address: bVxY4EtVtakjxhJqjVLX
632RsaQVci7nLs

​Looks like the project is doing well! Just joined the discord group.

Best,
Ryan​

**Comment by kauffj** [comment]
@rcanolty sent

**Comment by rcanolty** [comment]
ah, sorry, I went with rtc as my channel name, so @rtc? i also just learned
about discord tipbot, if that is easier.

**Comment by tzarebczan** [comment]
Ah, welcome to our Discord... We had some interactions yesterday :)

**Comment by rcanolty** [comment]
ah, just looked and it is there, so no worries. keep it up guys, this is
the project that got me into blockchain (better than cryptokitties.co !)
