### ISSUE TITLE
Bracket left open in the settings menu code on 0.12.0 rc7 

### ISSUE THREAD

**Issue by trickyhunter2017** [lbryio/lbry-app#220]
## The Issue
Someone left a bracket open in the settings menu code on 0.12.0 rc7 
It shows in the interface just above the 'SHARE DIAGNOSTIC DATA' box

### Steps to reproduce
1. Open LBRY app (Has been seen in Windows and Linux app)
2. Click the settings cog icon top right of app
3. Scroll to bottom of screen, bracket */] should be visable top left of the words 'Share Diagnostic Data'

### Expected behaviour
Shouldn't be visible

### Actual behaviour
Is visible

## System Configuration

<!-- For the app, this info is in the About section at the bottom of the Help page. 
     v0.12.0rc7 - Windows
     ABOUT doesn't work in this release candidate.  It just stays at looking up version info...forever

## Anything Else
Submit a bug report button doesn't work either.  That's why I'm reporting on github :D

**Comment by kauffj** [comment]
fixed in #6bfce16
