### ISSUE TITLE
Submit a Bug report not working in 0.12.0 rc7

### ISSUE THREAD

**Issue by trickyhunter2017** [lbryio/lbry-app#221]
## The Issue
Click the 'Submit a bug report' button in the help menu to report an issue.  Fill in description
click green 'Submit Report' button and nothing happens.    Has this been disabled on purpose?

### Steps to reproduce
1. Click the 'Submit a bug report' button in the help menu
2. Fill in description
3. click green 'Submit Report' button and nothing happens

### Expected behaviour
It should show some sort of notification that the report has been submitted

### Actual behaviour
It shows no change.  Click the button as many times as you like.  It doesn't do anything.

## System Configuration

 

- LBRY Daemon version: 0.11.0rc3
- LBRY App version: 0.12.0rc7
- LBRY Installation ID: 6y7x4ht2F8NAtarEz8RSEw8DkXYuaeUJGTLQ19UWt4nJjWNJzsk7spJS9RSkAGRVzP
- Operating system: Windows (Windows-10-10.0.14393)

**Comment by tzarebczan** [comment]
@kauffj is this disabled for a reason or a bug? Fix in next release tag if needs corrective action?

**Comment by kauffj** [comment]
This is fixed in master and will be fixed when 0.12.1 is released.
