### ISSUE TITLE
LBRY will not come forward after clicking LBRY Address 

### ISSUE THREAD

**Issue by LeRatton** [lbryio/lbry-app#224]
## The Issue
The LBRY App will not come forward when clicking on a LBRY address link (on a browser or on the Slack chat).

### Steps to reproduce
1.  Click on a LBRY Address Link (example lbry://dunkirk-trailer1) on a Mac OSx

### Expected behaviour 
Tell us what should happen

1. The app should come forward and open up the link. Similar to opening a web address or opening an application. It should come forward.

### Actual behaviour

Behavior 1 - If the App is open in the background: Clicking the link does direct the LBRY app to the address being opened. But the App remains in the background, does not bring it forward.

Behavior 1 - If the App is not open: Clicking the link opens up the LBRY app and brings it forward. But the app does not get directed to the address clicked, instead it remains at home.

## System Configuration

MacBook Pro
Latest OSx
Safari

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by finer9** [comment]
Can confirm this issue on Win 10 latest LBRY

**Comment by liquidox** [comment]
Works for me on Win10/Chrome clicking the links in the LBRY newsletter.

**Comment by kauffj** [comment]
This should be fixed in 0.13, please re-open if still broken.
