### ISSUE TITLE
Unexpected crash/restart on clicking Help in Menu [OSX] 

### ISSUE THREAD

**Issue by AyiSoli** [lbryio/lbry-app#226]
## The Issue

When I click on "Help" menu and from the dropdown, "Help" Option, the LBRY App reloads unexpectedly. 

### Steps to reproduce
1. Open LBRY App.
2. From Home, or any screen, Click on "**Help**" in the top toolbar
3. From the dropdown menu, click on "Help"
4. The App crashes and reloads from the initial screen. 

### Expected behaviour
On clicking Help, it should show the help contents.

### Actual behaviour
It reloads the app. 

## System Configuration
daemon (lbrynet)	0.11.0rc3
wallet (lbryum)	2.7.25
interface	0.12.0rc7
Platform	Mac OS 16.0.0

## Anything Else

I believe since Help is available within the App, this button could be removed altogether.

## Screenshots
![screen shot 2017-06-11 at 11 54 40 pm](https://user-images.githubusercontent.com/29357634/27013476-14de5668-4f02-11e7-90bd-fcbedc56d51e.png)

**Comment by filipnyquist** [comment]
I'll take a look at this tomorrow morning!

**Comment by kauffj** [comment]
@longle255 fixed this and it's been merged into master. Will be fixed for everyone when we release 0.12.1 (possibly today).
