### ISSUE TITLE
Newly published content requires a restart of the LBRY app to show up in the system.

### ISSUE THREAD

**Issue by AyiSoli** [lbryio/lbry-app#227]
## The Issue

Whenever I upload some new content, it does not show up immediately. Even on confirmation, it does not appear on the  "PUBLISHED" tab. I have to restart LBRY to find my uploaded content on the Published tab.

### Steps to reproduce
1. Create new content: Click on PUBLISH -> Select the files.
2. Select the price, access, licence , and also set the URL
3. Upload it. 
4. Ideally it should now appear under "PUBLISHED" tab when you click on the "Folder" button to the right on "PUBLISH". However it does not appear there.
5. Close LBRY. Make sure all the daemons are closed.
6. Restart LBRY. 
7. Now after loading the home page, click on "FOLDER" and select the Published tab.
8. The content appears now. 
9. Before playing it for the first time, the message "It seems you have moved this file. We are re-building it now" appears for a moment before playing. 

### Expected behaviour
The uploaded content should appear in the Published section after uploading. 

### Actual behaviour
It does not appear instantly. However, it only shows up after a restart. 

## System Configuration

daemon (lbrynet)	0.11.0rc3
wallet (lbryum)	2.7.25
interface	0.12.0rc7
Platform	Mac OS 16.0.0

**Comment by 6ea86b96** [comment]
Will be resolved by https://github.com/lbryio/lbry-app/pull/225 although we could separate the fix from the caching code if it needs to go in faster.

**Comment by tzarebczan** [comment]
@kauffj I'd say this deserves a "fix in next release" tag. Reported by many via slack.

**Comment by tzarebczan** [comment]
@6ea86b96 is it possible this (https://github.com/lbryio/lbry-app/issues/187) will also be fixed in #225 ?

**Comment by 6ea86b96** [comment]
@tzarebczan no #187 won't be fixed in #225, but it will be fixed in #229 when I finished it. It may already be fixed by the changes I made so far. I will have to do some testing.

**Comment by 6ea86b96** [comment]
Unfortunately I'm a little short on time this week though :(

**Comment by 6ea86b96** [comment]
Actually, scratch that, this is not fixed in #225. Needs a little bit of extra work.

**Comment by 6ea86b96** [comment]
This was not quite fixed by the above PR. Most users will notice nothing wrong, but there are errors in the JS console because a pending file is pushed into the store and never removed.

**Comment by 6ea86b96** [comment]
Working on a fix for this in #229

**Comment by kauffj** [comment]
This is fixed in 0.13, just badly :)
