### ISSUE TITLE
Show permanent url for published items

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#228]
More of a feature request, but much needed IMHO. We should show the claimid, which allows for permanent resolution, somewhere on the published page or on the claimed item.  

## The Issue
You'd need to look up the claimid manually using cli.
### Steps to reproduce
1. n/a
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by 6ea86b96** [comment]
Fixed (I think) in #227
