### ISSUE TITLE
Error when publishing with a bid of 0

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-app#23]
Also, nothing seems to happen when I click 'ok', so I have to close the app to be able to do anything.

![pasted image at 2017_03_17 12_06 am](https://cloud.githubusercontent.com/assets/362784/24321993/4b0af296-1131-11e7-8592-b5ac75e96362.png)

**Comment by guytp** [comment]
Confirmed - identical response on Windows 10 x64.  Cannot click OK must kill process.

**Comment by ryliejamesthomas** [comment]
I get the same error in Arch Linux.

**Comment by alexliebowitz** [comment]
We don't _specifically_ handle this, but it looks like at some point recently we switched to passing the error message on from lbrynet in a pretty reasonable-looking dialog box:

![screen shot 2017-05-04 at 2 21 44 am](https://cloud.githubusercontent.com/assets/7283989/25692461/ce177228-3070-11e7-9e02-afb9b3dc5158.png)

Is this good enough to consider the issue resolved?
