### ISSUE TITLE
12.0 Lose focus bug when playing video full screen on dual monitor setup

### ISSUE THREAD

**Issue by trickyhunter2017** [lbryio/lbry-app#230]
## The Issue
When playing a video full screen under Windows 10 on a duel screen setup, if you click on the second monitor, the video playing full screen on the first monitor loses focus and goes behind the windows 10 taskbar.  This hides the video playback controls along the bottom of the screen and prevents you from clicking the full screen icon in order to revert the video back to small mode in the app.  You have to click on the actual video window to get the focus back and can then exit full screen mode.  If a person doesn't realize this, the video is now stuck playing behind the taskbar with no way to stop it and no way to access it's playback controls. 

### Steps to reproduce
1.  Open LBRY app Windows version 12.0 final (Computer setup must be 2x monitors, Windows 10)
2.  Play any video in full screen mode on the first desktop
3.  Click on the second desktop or open a web browser on it etc and the video window on the first desktop will lose focus and disappear behind the Windows taskbar.

### Expected behaviour
When playing video fullscreen, ideally it should:
Remain full screen even when it doesn't have focus (ala VLC media player or youtube in fullscreen mode)
Should not have a grey window bar across the top of the screen
Should not disappear behind the Windows taskbar when a second desktop is clicked or when it doesn't have focus.

### Actual behaviour
Grey bar across top of screen
Playback controls disappear behind Windows task bar if video player loses focus in full screen mode on a duel monitor setup.

## System Configuration

 

- LBRY Daemon version:  0.11.0
- LBRY App version:  0.12.0
- LBRY Installation ID:  AKACRZprLLsQAuMdigzd3tPm3M3mDmKQniNuaf8t7CVtCzg7SKTvDMbXmHjAsZWEVp
- Operating system:  Windows (Windows-10-10.0.14393)
![program manager 2017-06-12 17 05 59](https://user-images.githubusercontent.com/4589923/27045555-288d85de-4f99-11e7-993a-65fe54f0df25.png)

**Comment by trickyhunter2017** [comment]
Additional duel screen, fullscreen video playback test on macOS 10.12.5 working perfectly.  Correct focus, stays full screen when focus is lost, no title bar, dock stays hidden, playback controls available at all times.  Fullscreen means fullscreen.

![the team - lbry 2017-06-12 20-12-56](https://user-images.githubusercontent.com/4589923/27050974-531c00d8-4fac-11e7-9fb6-30d485ba5af8.png)

**Comment by kauffj** [comment]
Thanks for this thorough report. Interesting that it works on macOS but not Windows. I don't think there is any OS-specific code here.

**Comment by trickyhunter2017** [comment]
OK just 'to be sure' 'to be sure' 'to be sure' I ran some more tests with the same downloaded video file using VLC media player 64bit 2.2.6 latest version.  Fullscreen mode, Fullscreen 'Interface' mode and YouTube's HTML5 video player under Firefox 64bit in Fullscreen mode.  None of them go behind the taskbar when the second desktop has focus.  There's something up with the LBRY apps Window layering order under Windows 10.  I'm not a programmer so this is the best I can do.

![01](https://user-images.githubusercontent.com/4589923/27053876-ddcbdece-4fb6-11e7-839b-fc9eebf69e4d.png)

![02](https://user-images.githubusercontent.com/4589923/27054009-536ec696-4fb7-11e7-9bb7-0e1035c33bb1.png)

![03](https://user-images.githubusercontent.com/4589923/27054016-5b0c413a-4fb7-11e7-8524-09fe7b5439ed.png)

**Comment by kauffj** [comment]
Thanks for this, it's really an A+ bug report.

Unfortunately, I still have no idea why :(

We'll figure this out eventually, but to be honest this one probably won't be a priority.

**Comment by kauffj** [comment]
I wonder if it is this issue...

https://github.com/electron/electron/issues/5267

**Comment by trickyhunter2017** [comment]
Hmmm you could be right.  It looks like electron has issues with Windows 10 window management when using more than 1 monitor.  It won't affect most people but the power users will complain about it no doubt.  I tried moving the taskbar to the left side of the screen but it still appears over the video when I use the second desktop.  A work around is to auto-hide the taskbar in Windows settings.  That works.  But again not everyone will want to do that.  No worries about it not being a priority, totally understand, just making you aware of it :D

**Comment by liamcardenas** [comment]
@tzarebczan do you know if this is still an issue / has anyone else mentioned it?

**Comment by kauffj** [comment]
@liamcardenas I suspect this one is an upstream issue in Electron. If it is, it's been fixed there and should already be in our code.

@trickyhunter2017 would be able to check out the latest and see if this is working for you now?

(If we don't hear from @trickyhunter2017, I'd suggest closing this.)

**Comment by tiger5226** [comment]
nothing back from  @trickyhunter2017 , closing issue.
