### ISSUE TITLE
Refreshing page leads to blank screen

### ISSUE THREAD

**Issue by 6ea86b96** [lbryio/lbry-app#233]
**Issue below was fixed, but still has issues on some pages.**

## The Issue

Creating this to remind myself to fix it.

### Steps to reproduce
1. Browse to any page
2. Refresh

### Expected behaviour
The page reloads

### Actual behaviour
You get dumped to a green screen

## Anything Else

We need to switch to `#` based routing to fix.

**Comment by lyoshenka** [comment]
This happened before and @kauffj fixed it. Perhaps the same bug is back?

**Comment by kauffj** [comment]
Actually it happened before and @6ea86b96 fixed it :grin: 

However, do we have to change routing to fix? Not opposed to this, but I believe you can detect reloads through the [`PerformanceNavigation API`](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceNavigation).

**Comment by 6ea86b96** [comment]
oh, well that would be even better :)

**Comment by 6ea86b96** [comment]
Fixed in #274

**Comment by avashlin** [comment]
Hi, This bug has resurfaced in my installation of version 0.13 . 
Same steps to reproduce as the #265  logged issue. Play a video -> click developer -> reload -> blank green screen . 

Lbry install info:
![screenshot from 2017-07-03 17-02-46](https://user-images.githubusercontent.com/8122968/27798422-73bb597c-6011-11e7-951f-041ca7d186b3.png)

**Comment by avashlin** [comment]
@kauffj : doesn't seem like my comment re-opens this issue. tagging you to ensure it doesn't fall under the radar.

**Comment by kauffj** [comment]
I believe this is only happening on a minority of pages.
