### ISSUE TITLE
Create "New Folder" while choosing Download Directory [OSX] [Feature Request]

### ISSUE THREAD

**Issue by AyiSoli** [lbryio/lbry-app#234]
This is more of a feature request that can be added to the folder browser, while selecting the Download Directory

## Feature

1. Settings - > Choose Directory
2. Option to create a new folder can be provided here, beside "Open" and "Cancel".

### Expected behaviour
New folder/directory can be created to save the downloaded data.

  
## Screenshots
![screen shot 2017-06-13 at 12 04 15 pm](https://user-images.githubusercontent.com/29357634/27069070-b46d39fe-5030-11e7-8771-f067215ebaa1.png)

**Comment by seanyesmunt** [comment]
I'll take this one if no one has started on it yet.

**Comment by kauffj** [comment]
Thanks @seanyesmunt! Look for this in 0.13 @AyiSoli.

**Comment by AyiSoli** [comment]
Great! Thanks guys!
