### ISSUE TITLE
LBRY Processes get stuck open

### ISSUE THREAD

**Issue by trickyhunter2017** [lbryio/lbry-app#237]
## The Issue
Debating whether to log this or not as the issue has fixed itself after a reboot.  Upon inital install (of LBRY app 0.12.0 on Windows 7 x64 Pro on a virtualbox machine)  3 of the 4 running processes in memory fail to shut down after application closure.  This stops the user from starting the application again from the shortcut on the desktop.  After much testing, a simple reboot appears to have fixed the problem.

### Steps to reproduce
1.  Install Windows 7 x64 SP1 Professional on an Oracle VirtualBox machine.
2.  Install about 300 Windows updates D: (Many reboots and several hours later.)
2.5 Install VBox guest additions
2.6 Install Firefox x64
3.  Install LBRY app 0.12.0
4.  Run app successfully
5.  Shutdown app using window red X button top right. (Wait 10 - 15 seconds).
6.  Try to restart app using desktop shortcut and fail miserably.
7.  Use task manager and TCPview to see what is going on.
8.  Discover 3 of the 4 running LBRY processes haven't shut down
9. Wait a while for them to close, they never do, so manually shut them down
10. restart app successfully
11. Quit app as before
12.  Wait 20 minutes while watching tcpview.  Established network connections never close.
This behavior will not change until you reboot the machine.

### Expected behaviour
LBRY processes running in memory should shut down correctly after quiting the app for the first time after initial install.  A reboot should not be required in order to get the app processes to shutdown properly. 

### Actual behaviour
3 of the 4 processes running in memory would not close by themselves, the first time I quit the LBRY app and every time I started and quit the LBRY app, until a reboot was performed.
It's possible Windows 7 is a bit flakey as an operating system :/ 

## System Configuration

 

- LBRY Daemon version:  0.11.0
- LBRY App version:  0.12.0
- LBRY Installation ID:  4Et3kiqswznXLHhiYg6rK44vz3Ls6GgmFqYZekrcAfR5ziVEgmNuhSK8opCRn9LEBQ
- Operating system:  Windows (Windows-7-6.1.7601-SP1)

## Anything Else
I took the opportunity to test Nicehash miner for @Jiggytom (see screenshot below) to test (LBRY daemon closing on launch) issues with miners under Windows 7.  LBRY worked fine with it running CPU mining.  Claymore GPU mining may be conlficting with LBRY app but an AMD card is required to test it.  Unfortunately I don't have one.

## Screenshots
![win7_x64 running - oracle vm virtualbox 2017-06-13 20 28 49](https://user-images.githubusercontent.com/4589923/27106775-c14f0c72-508c-11e7-992c-4616f749bf4d.png)

![win7_x64 running - oracle vm virtualbox 2017-06-13 20 20 42](https://user-images.githubusercontent.com/4589923/27106778-c7b8cc6a-508c-11e7-8c47-d1b08055d6c9.png)

![win7_x64 running - oracle vm virtualbox 2017-06-13 20 07 08](https://user-images.githubusercontent.com/4589923/27106782-cd484e3a-508c-11e7-89b3-1f6cd7f2d3db.png)

**Comment by kauffj** [comment]
Does this happen for you every time? Or just sometimes?

**Comment by kauffj** [comment]
(I've seen this issue on other OSes; I don't think it's Windows specific)

**Comment by trickyhunter2017** [comment]
I've just upgraded the Win7 VM Lbry app to the latest 0.13.0 version to test this, a few minutes ago.  The issue does not appear to be happening now.  No reboot was required.  When I close the app as before, the three troublesome processes all close first and the last daemon process takes approx 5 seconds to shut down.  They all seem to shutdown correctly now with the latest version.  This process shutdown behavior is the same on a physical win 10 machine aswell.  

I should point out that I have now taken (as a matter of routine) to right clicking the installer app and selecting 'run as administrator' every time I upgrade the lbry app on a Windows machine.  I don't know if this has any baring on anything but I've been doing it since I had the issue with the daemon not upgrading and I haven't had any upgrade problems since.

**Comment by kauffj** [comment]
Thanks @trickyhunter2017!
