### ISSUE TITLE
Incoming Transactions are not shown to be confirmed in the LBRY UI until restart [OSX] 

### ISSUE THREAD

**Issue by AyiSoli** [lbryio/lbry-app#240]
## The Issue

Whenever I make a new transaction to the LBRY App, it shows up in the balance page. However it does not get confirmed even after confirmation on the network. 
It shows as "Awaiting confirmation" even after switching from Home to Wallet multiple times, playing a video and coming back to wallet, etc it still remains unconfirmed.
On closing the app completely and restarting it, it shows up as confirmed. 

### Steps to reproduce
1. Sent a txn to the LBR-app wallet. It updates the balance immediately. However it remains in "pending/un-confirmed" state.
2. Check whether the txn has confirmed on the network. 
3. When it is confirmed on the network, refresh the page by going to home and coming back to wallet - it remains unconfirmed in the UI (despite network confirmations). 
4. Close LBRY app and restart it.
5. Go to the balance page - Now it shows up as confirmed.   

### Expected behaviour
The transaction should confirm on the LBRY app wallet when it gets confirmed on the blockchain.

### Actual behaviour
The balance is updated immediately, however it remains unconfirmed in the app; 
Once the LBRY-app is restarted, it updates the confirmation status. 

## System Configuration

daemon (lbrynet)	0.11.0
wallet (lbryum)	2.7.25
interface	0.12.0
Platform	Mac OS 16.0.0

## Anything Else
I haven't tested if the balance could be used in a claim even when it is in an unconfirmed state within the LBRY app.

**Comment by 6ea86b96** [comment]
I was unable to replicate this.

**Comment by tzarebczan** [comment]
@AyiSoli please reopen and update to the next major release (not out yet), or RC7 if you are feeling adventurous (publishing is broken).  If you can get it to happen again, please provide more info like tx id and log.
