### ISSUE TITLE
LBRY App not compatible with OSX 10.8.5 or lower.  OSX 10.9 minimum required to run

### ISSUE THREAD

**Issue by trickyhunter2017** [lbryio/lbry-app#244]
## The Issue
Testing the LBRY app compatability with older versions of OSX.  10.9 appears to be the minimum version required in order to run it.  This could be an electron requirement.  This means it won't work on : 

10.8 Mountain Lion
10.7 Lion
10.6 Snow Leopard
10.5 Leopard

Users with older iMacs or OSX versions won't be able to run it.

### Steps to reproduce
1. Install OSX 10.8.5 on a VMWare Fusion VM
2. Download the LBRY app from Github (currently 0.12.0 tested)
3. Try to install it.  Immediately a 'no entry' sign is displayed upon mounting the DMG on the desktop.
4.  Try to install and run the app and the following error message is displayed (See screen shot below).

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

## Screenshots
![os x 10 8 2017-06-15 22-16-21](https://user-images.githubusercontent.com/4589923/27202448-9538f754-5219-11e7-91c9-a9376d331b26.png)

**Comment by liamcardenas** [comment]
We will tip LBC to anyone who looks into this.

**Comment by miikkatu** [comment]
This is indeed an Electron requirement. From Electron docs: "Only 64bit binaries are provided for macOS, and the minimum macOS version supported is macOS 10.9."

[https://github.com/electron/electron/blob/master/docs/tutorial/supported-platforms.md](url)

**Comment by lyoshenka** [comment]
We're not planning to support 10.8.5
