### ISSUE TITLE
Upgrading to v0.12.2rc2 results in 99% of home page content no longer being available

### ISSUE THREAD

**Issue by trickyhunter2017** [lbryio/lbry-app#249]
## The Issue
I saw that 0.12.2 rc2 was available on the github page.  I started the lbry app on my desktop but it did NOT tell me that an update was available (so I quit that).  I then manually downloaded the new RC and manually ran the update, which seemed to go ok.  When I then started the new version, only 1 video thumbnail would load from the homepage.  All the rest say 'this address contains no content'  Unused.  See screenshot below.  I've restarted the app several times, nothing is displayed except 1 video I purchased.  It's important to note that all the free videos are downloaded in my downloads folder and after checking the settings, it is still pointing to that folder so the content exists locally on my machine.

### Steps to reproduce
1.  Manually upgrade 0.12 -> 0.12.2rc2
2. Start lbry app and no content is available on home page except previous purchases.
3. If you try and click on any of the videos it says 'there is nothing at this location'.

### Expected behaviour
All the homepage content should load and resolve.

### Actual behaviour
It's all gone O_o?  Except my previous video purchase.

## System Configuration

 

- LBRY Daemon version: 0.11.0   <- isn't this supposed to be 0.13 ?
- LBRY App version: 	0.12.2rc2
- LBRY Installation ID: 3isBEMXr63RscYGaxCm5ixJG7NFXVjmWTV29gQgFTA625XWK7mRtr3g2DsT1kJSpY8
- Operating system: Windows (Windows-10-10.0.14393)

## Anything Else
I notice on the release page it says 'Upgraded to lbry daemon 0.13, including updating API signatures'
but in the app settings page it says the daemon is still 0.11.0  Could it have failed to upgrade the daemon?  And that's why all the content is missing?

I have confirmed that the app and daemon are running in memory. (Screenshot below.) and they all close and shutdown ok when I quit the app.

## Screenshots
![home 2017-06-16 09 54 38](https://user-images.githubusercontent.com/4589923/27219712-9664b472-527a-11e7-9b84-63f95374a27c.png)

![lbry___thelastjedi-trailer 2017-06-16 11 04 20](https://user-images.githubusercontent.com/4589923/27222288-9a2e3796-5283-11e7-8bb4-42ea8ae91af5.png)

![task manager 2017-06-16 10 16 23](https://user-images.githubusercontent.com/4589923/27220414-f465e526-527c-11e7-9916-697a31cdd942.png)

![tcpview - sysinternals_ www sysinternals com 2017-06-16 10 27 57](https://user-images.githubusercontent.com/4589923/27220914-a4b629e4-527e-11e7-8e13-19ec26fce3d7.png)

Rebooted the machine and tried again, this time:

![error 2017-06-16 16 22 26](https://user-images.githubusercontent.com/4589923/27233257-c7b7b8b8-52b0-11e7-9b02-6b550ce6870d.png)

![lbry 2017-06-16 16 27 10](https://user-images.githubusercontent.com/4589923/27233271-ce273750-52b0-11e7-84b1-8566eedbc3b9.png)

Will try to revert back to 0.12.0

**Comment by kauffj** [comment]
Yes, this behavior is happening since your daemon did not update. If you close all LBRY processes and run it again, it should work, but if you continue to see daemon v0.11 that explains the issue.

Also, RCs are pre-release versions not necessarily ready for mass usage. So you will only be prompted to upgrade once this is marked as a release.
