### ISSUE TITLE
UX: Page titles in search bar don't stand out enough

### ISSUE THREAD

**Issue by jasperjansz** [lbryio/lbry-app#252]
## The Issue
Only a couple days in I noticed that the page title is in the search bar. This is hardly noticeable, unless you know it's there. Especially coupled with the fact that some links in the header are just icons.

### Expected behaviour
Page titles should tell the user at a glance or when he's quickly scanning what the page is about and where they are. 

### Actual behaviour
Instead the user has to actively focus his attention on the search bar. That is, IF he knows that's where the page title is.

## System Configuration

- LBRY Daemon version: 0.11.0
- LBRY App version: 0.12.0
- LBRY Installation ID: 2tCTvcMLmPUE46D8mHVAVJXUxy8U4HX6xdV7TKQU25jsj3H6G2EnoUmxXEVhdb8hoa
- Operating system: OS X Sierra

**Comment by kauffj** [comment]
I agree! Would love to hear suggestions on this one. Is there a style change that could make the address bar work better? Repeat it below? I did try this and didn't like it, but maybe there is a better way.
