### ISSUE TITLE
Seeking in a MP3 doesn't work until the file plays all the way through

### ISSUE THREAD

**Issue by benhohner** [lbryio/lbry-app#253]
## The Issue
Seeking in a MP3 (possibly other audio files too) doesn't work until the file plays all the way through

### Steps to reproduce
1. Download lbry://curvedspace-scatter
2. Play file
3. Try to seek, seeking fails
4. Finish listening to file
5. Seeking now works.

### Expected behaviour
Users should be able to seek as soon as they've downloaded the whole file (if not as the file is downloaded, but I know we have some issues with that ATM)

### Actual behaviour
User isn't able to seek until after the file plays all the way to the end.

## System Configuration
daemon (lbrynet)	0.11.0
wallet (lbryum)	2.7.25
interface	0.12.0
Platform	Windows (Windows-10-10.0.15063)
Installation ID	2BX4AhDAHSJoPeyAjAU24B5H6qgRPUgWf92uX3iwLMvxPHPZSq9Vw4FmyXgysLG2hx
- Operating system: Win 10 x64

**Comment by 6ea86b96** [comment]
@benhohner this is because in some files the metadata is at the end and so unavailable when streaming.

**Comment by benhohner** [comment]
@6ea86b96 I'm aware there's that issue when streaming, but this happens after the entire file has already been downloaded in a previous browsing session, and I'm rewatching it.

**Comment by 6ea86b96** [comment]
@kauffj this one appears to be fixed.
