### ISSUE TITLE
lbrynet-cli does not provide proper usage information

### ISSUE THREAD

**Issue by blackknight36** [lbryio/lbry-app#26]
## The Issue
The CLI app does not give proper usage messages when a command is issued.  There are also several tracebacks reported as shown below.

./lbrynet-cli get
Something went wrong, here's the usage for get:
{u'help': u"\nDownload stream from a LBRY name.\n\nArgs:\n    'name': (str) name to download\n    'file_name'(optional): (str) a user specified name for the downloaded file\n    'stream_info'(optional): (str) specified stream info overrides name\n    'timeout'(optional): (int) download timeout in number of seconds\n    'download_directory'(optional): (str) path to directory where file will be saved\n    'wait_for_write'(optional): (bool)  defaults to True. When set, waits for the file to\n        only start to be written before returning any results.\nReturns:\n    (dict) Dictionary contaning information about the stream\n\n    {\n        'completed': (bool) true if download is completed,\n        'file_name': (str) name of file,\n        'download_directory': (str) download directory,\n        'points_paid': (float) credit paid to download file,\n        'stopped': (bool) true if download is stopped,\n        'stream_hash': (str) stream hash of file,\n        'stream_name': (str) stream name ,\n        'suggested_file_name': (str) suggested file name,\n        'sd_hash': (str) sd hash of file,\n        'name': (str) name claim attached to file\n        'outpoint': (str) claim outpoint attached to file\n        'claim_id': (str) claim ID attached to file,\n        'download_path': (str) download path of file,\n        'mime_type': (str) mime type of file,\n        'key': (str) key attached to file,\n        'total_bytes': (int) file size in bytes, None if full_status is false\n        'written_bytes': (int) written size in bytes\n        'message': (str), None if full_status is false\n        'metadata': (dict) Metadata dictionary\n    }\n\n"}
Here's the traceback for the error you encountered:
Traceback (most recent call last):
  File "site-packages/lbrynet/lbrynet_daemon/DaemonRequest.py", line 94, in requestReceived

  File "site-packages/twisted/web/server.py", line 190, in process

  File "site-packages/twisted/web/server.py", line 241, in render

  File "site-packages/lbrynet/lbrynet_daemon/auth/server.py", line 208, in render

--- <exception caught here> ---
  File "site-packages/twisted/internet/defer.py", line 150, in maybeDeferred

  File "site-packages/twisted/internet/defer.py", line 1436, in unwindGenerator

exceptions.TypeError: jsonrpc_get() takes at least 2 arguments (1 given)

**Comment by lyoshenka** [comment]
Hey there. What version are you using (run `lbrynet-cli version`). I believe this was fixed recently.

**Comment by kauffj** [comment]
@lyoshenka this is fixed in `master` but I do not think it is in a released binary, or only in one tagged pre-release.

**Comment by blackknight36** [comment]
@lyoshenka I grabbed the OS X packages from the web site last night so it is the latest released version.

**Comment by kauffj** [comment]
0.11 daemon fixes this.
