### ISSUE TITLE
Multiple LBRY processes spawn when opening multiple clients (2 X number of clients) 

### ISSUE THREAD

**Issue by avashlin** [lbryio/lbry-app#260]
## The Issue
Opening multiple clients are allowed, so each client should have it's own set of processes and manage the memory accordingly. 
Multiple processes (potentially duplicates) spawn on LBRY client startup. I assume that this is not the intended behavior, please see screenshots

### Steps to reproduce
1. Open 3 instances of LBRY client
2. Close 2
3. Observe system monitor on linux
4. More than 1 process running
5. Open more LBRY clients
6. For each new client 2 extra instances of lbry is shown in system monitor

### Expected behaviour
Each LBRY client instance should run in its own sandbox and processes should not be shared to avoid issues like this. Alternatively, a user should only be allowed to run one concurrent instance of the client

### Actual behaviour
Processes in system monitor increase by 2 for each new LBRY client instance

## System Configuration

 
![screenshot from 2017-06-20 15-26-07](https://user-images.githubusercontent.com/8122968/27335477-d19d4fb8-55cc-11e7-80f7-311b7ddbfe7c.png)

- LBRY Daemon version: 0.11.0
- LBRY App version: interface (0.12.0) , wallet (2.7.25)
- LBRY Installation ID: ALtB6iFFp4azA6HTcBJ6WSqwxWPiFnsMGGNgBiEmDZxmFLvjSssyX75XZK93sRs7mo
- Operating system: Linux (Linux-4.4.0-81-generic-x86_64-with-Ubuntu-16.04-xenial)

## Screenshots

With 4 clients open : 
![screenshot from 2017-06-20 15-23-30](https://user-images.githubusercontent.com/8122968/27335402-8df53aaa-55cc-11e7-920b-98d08748fd20.png)

After following the above steps : 
![screenshot from 2017-06-20 15-09-26](https://user-images.githubusercontent.com/8122968/27335302-4b386fd4-55cc-11e7-8c61-8da4a8358e67.png)

**Comment by kauffj** [comment]
As far as I understand it, this is correct.
