### ISSUE TITLE
UX: show informative dialog box or daisy wheel when downloading

### ISSUE THREAD

**Issue by avashlin** [lbryio/lbry-app#264]
## The Issue
I opened a video on the LBRY client, it said the content was unavailable. I then clicked 'try anyways' and clicked the download button. It says connecting... . To a normal end user, they might think the interface is frozen, it might be a better experience if there was a dialog box that popped up telling me that my download is in progress or a daisy wheel that shows me that something is happening.

### Steps to reproduce
1. open video
2. faced with 'content unavailable' 
3. click 'try anyways'
4. click 'download'
5. download changes to connecting...
6. No visible cues are shown to indicate that my download is in progress

### Expected behaviour
Tell us what should happen
Some sort of visible cue should be displayed to tell users that their download is in progress

### Actual behaviour
Tell us what happens instead
No visible cues are shown to the user to indicate that their download is progressing

## System Configuration

 
![screenshot from 2017-06-20 15-26-07](https://user-images.githubusercontent.com/8122968/27337418-aada8bc4-55d2-11e7-9e7e-8d36eecc86ae.png)

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
There's been some progress here, but it can still feel like nothing is happening after clicking download or stream. Part of the problem is that a `get` call can block for up to 30 seconds, and provides no details in the interim.

**Comment by avashlin** [comment]
How about a distraction whilst waiting for the `get` call to resolve? Something along the lines of having a splash display with the featured content you are promoting for the week? Or if advertisements are in the future plans of lbry - it can act as a smoke screen for the background tasks (with the option of disabling it based on user preference)
