### ISSUE TITLE
Language and "Show unavailable content in search results" settings don't save

### ISSUE THREAD

**Issue by avashlin** [lbryio/lbry-app#267]
### Steps to reproduce
1. open lbry app
2. go to settings
3. change either language or "Show unavailable content in search results" setting
4. press the home button
5. go back to settings
6. observe that the settings have not saved since the change

### Expected behaviour
Tell us what should happen
the setting should save as per the user's selection
### Actual behaviour
Tell us what happens instead
The settings don't get saved

## System Configuration

 
![screenshot from 2017-06-20 15-26-07](https://user-images.githubusercontent.com/8122968/27359767-dcf29e76-561d-11e7-8fec-270a6edd7697.png)

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
Language is gone in 0.13 (it wasn't supposed to be there yet), and all setting should now save correctly. Please re-open if you're seeing this in 0.13 or later.

Thanks!
