### ISSUE TITLE
Allow configuring of max_key_fee daemon config

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-app#268]
Related lbry issue: https://github.com/lbryio/lbry/issues/721

**Comment by 6ea86b96** [comment]
Ran into some problems implementing this on #278

**Comment by lyoshenka** [comment]
@kauffj whats next here. it's in "needs review". who needs to review it?

**Comment by kauffj** [comment]
@lyoshenka lbryio/lbry#761 needs to be merged and released

**Comment by lyoshenka** [comment]
Looks like https://github.com/lbryio/lbry/pull/781 (which replaces https://github.com/lbryio/lbry/pull/761) has been merged. What's next?
