### ISSUE TITLE
Insufficient Funds Error When Publishing

### ISSUE THREAD

**Issue by guytp** [lbryio/lbry-app#27]
When trying to post a video with insufficient credits for bid the below error appears.  There are three issues with this error:

1. It is not user friendly
2. The check doesn't come back until a long time after hitting publish (I'm guessing the whole upload happens first which for a multi-GB file is a big waste of time)
3. Popup error window cannot be closed whole process must be killed (see https://github.com/lbryio/lbry-app/issues/23)

Daemon: 0.9.1
lbryum: 2.7.13
Interface 0.9.2rc2
Platform: Win10-10.0.14393 x64

The following error occurred when attempting to publish your file: Traceback (most recent call last): File "site-packages\twisted\internet\defer.py", line 1445, in unwindGenerator File "site-packages\twisted\internet\defer.py", line 1299, in _inlineCallbacks File "site-packages\lbrynet\lbrynet_daemon\Publisher.py", line 56, in make_claim File "site-packages\twisted\internet\defer.py", line 1445, in unwindGenerator --- <exception caught here> --- File "site-packages\twisted\internet\defer.py", line 1299, in _inlineCallbacks File "site-packages\lbrynet\core\Wallet.py", line 648, in claim_name lbrynet.core.Error.InsufficientFundsError:

![image](https://cloud.githubusercontent.com/assets/13474957/24444994/59bf79ec-1460-11e7-95a8-80109c171ae7.png)

**Comment by alexliebowitz** [comment]
@kauffj: Presumably the right way to handle this is to subscribe to the balance and check if the user has enough credits at form submission. I can handle this but it should be done on the redux branch, of course.
