### ISSUE TITLE
Regression on NSFW content

### ISSUE THREAD

**Issue by 6ea86b96** [lbryio/lbry-app#271]
## The Issue

NSFW explanation text is now also obscured.

### Steps to reproduce
1. Load the homepage and check out number 4 of the community content

### Expected behaviour
The content should be obscured and there should be a message explaining why and how to turn off nsfw in settings.

### Actual behaviour
The content and the message are obscured.

## Screenshots

![2017-06-22 at 20 59](https://user-images.githubusercontent.com/20863631/27438410-5d42b30a-578f-11e7-876a-31532a08bdc7.jpg)

**Comment by kauffj** [comment]
Fixed in #e3bbb6fcef
