### ISSUE TITLE
Download progress doesn't show in downloaded file list

### ISSUE THREAD

**Issue by 6ea86b96** [lbryio/lbry-app#279]
## The Issue

Download progress doesn't show in downloaded file list

### Steps to reproduce
1. Start a file downloading
2. Go to the downloaded files folder

### Expected behaviour
Download progress should be displaying

### Actual behaviour

The "OPEN" link is displaying

## System Configuration

```
{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "build": "release",
    "ip": "43.249.39.215",
    "lbrynet_version": "0.13.1",
    "lbryschema_version": "0.0.7",
    "lbryum_version": "2.8.4",
    "os_release": "16.6.0",
    "os_system": "Darwin",
    "platform": "Darwin-16.6.0-x86_64-i386-64bit",
    "processor": "i386",
    "python_version": "2.7.13"
  }
}
```

## Anything Else

I suspect this could be related to not passing `full_status: true` when fetching file infos somewhere, so not having the downloaded percentage.

## Screenshots

Expected:

![2017-06-23 at 22 16](https://user-images.githubusercontent.com/20863631/27488606-d1092e54-5861-11e7-9c5c-52296d294f97.jpg)

Actual:

![2017-06-23 at 22 18](https://user-images.githubusercontent.com/20863631/27488624-de6fd084-5861-11e7-912f-e93750cb595c.jpg)

**Comment by kauffj** [comment]
Do you really have to pass full_status to get the percentage? That seems like the real issue, and I can't imagine the written_bytes being an expensive operation...

**Comment by 6ea86b96** [comment]
Will look into the full status thing. I think the actual issue here is because the URI in the downloaded file list is different to the URI in the featured content (because I added the claim ID recently for us to have permanent URIs). We figure out which files are downloading using `fileInfo.urisDownloading`. Seems like it would better to switch this to `claims.downloadingByClaimId` or `fileInfo.downloadingByOutpoint`.

**Comment by kauffj** [comment]
We could also consider storing claims only by ID, this would probably eliminate these key mismatch issues.
