### ISSUE TITLE
Doesn't work on Vista

### ISSUE THREAD

**Issue by techtonik** [lbryio/lbry-app#28]
Installing LBRY.Setup.0.9.1.exe on Windows Vista and running LBRY shortcut produces this:

![image](https://cloud.githubusercontent.com/assets/515889/24490374/fb499af2-152a-11e7-8f12-9a12ddfa7cb3.png)

And nothing else happens.

**Comment by lyoshenka** [comment]
@techtonik sorry, we don't do any testing on Vista and we don't officially support it. My best suggestion would be to try compiling from source and see if that works. Alternatively (if you're adventurous) you could install Virtualbox and create a Linux VM.
