### ISSUE TITLE
"Hot Right Now" reward claim buggy behaviour

### ISSUE THREAD

**Issue by akinwale** [lbryio/lbry-app#288]
## The Issue
I keep getting an error message as shown in the screenshot below when I try to claim the "Hot Right Now" reward. However, it appears the reward got credited to my wallet twice.
https://www.dropbox.com/s/5tvi7jm6hcqm3pu/hot-right-now.png?dl=0

### Steps to reproduce
1. Watch one of the Hot Right Now videos.
2. Click Claim Reward.

### Expected behaviour
It should show a message that the Reward has been claimed.

### Actual behaviour
It shows an error dialog that "this reward has already been awarded to this person". However, I can still click the Claim Reward button after dismissing the dialog.

## System Configuration
*daemon (lbrynet)*
0.11.0

*wallet (lbryum)*
2.7.25

*interface*
0.12.0

*Platform*
Windows (Windows-10-10.0.15063)

## Anything Else
It appears two transactions were created with the reward to my wallet despite the error messages. The transaction hashes are:
dc15fcea6e52a8042b51a82942d9ea59c444cdd93c45f229b71e2ed89318cc3a
684f9368695c3f0eef840ed203203dca65a1663a5d55da2d504aa511a42c5926

## Screenshots
https://www.dropbox.com/s/5tvi7jm6hcqm3pu/hot-right-now.png?dl=0
https://www.dropbox.com/s/63wkt250pb2etsc/hot-right-now-txs.png?dl=0

**Comment by 6ea86b96** [comment]
I just randomly ran into this while downloading some content I saw flying by in the Slack #content room.

First a `CLAIM_REWARD_STARTED` action is fired, not sure why or from where yet.
![2017-07-03 at 12 16](https://user-images.githubusercontent.com/20863631/27778946-8b7cfbb0-5fe9-11e7-8486-55a916e434b4.jpg)

Then the reward is successfully claimed (this is now the 3rd time I've received this reward). However, the `reward` in the action data has a name that is not recognized in the list of possible rewards in redux (`featured_download_20170702`)
![2017-07-03 at 12 18](https://user-images.githubusercontent.com/20863631/27778975-ce0568f0-5fe9-11e7-9e89-583b1287117e.jpg)

And so everything blows up:
![2017-07-03 at 12 19](https://user-images.githubusercontent.com/20863631/27778992-f8bad580-5fe9-11e7-8418-fc07b469d34c.jpg)

The reward is credited and the balance is updated the next time `UPDATE_BALANCE` runs:
![2017-07-03 at 12 21](https://user-images.githubusercontent.com/20863631/27779032-4cbc2a4e-5fea-11e7-9a8c-513a9ac6e304.jpg)

I _think_ the claim reward started action was fired when I started downloading `lbry://@UCBerkeley/ucb-VY6F88U9Cl0`

**Comment by tzarebczan** [comment]
@lyoshenka maybe this helps you reproduce the issue?

**Comment by lyoshenka** [comment]
Just finished coding api changes that will fix this. They need to be reviewed, then the relevant app changes need to be made, then once the api changes go live this will be fixed.

**Comment by lyoshenka** [comment]
its fixed
