### ISSUE TITLE
Download directory not checked for existence

### ISSUE THREAD

**Issue by Djhg2000** [lbryio/lbry-app#29]
## The Issue
When changing the download directory string, lbry-app seems to assume it's a valid path.

### Steps to reproduce
1. Go to the settings page
2. Append something to the download directory string (for instance "/LBRY")
3. Try to watch something

### Expected behaviour
The full path should be checked for existence. If it fails, throw a GUI visible error in lbry-app and possibly ask if the directory should be created.

### Actual behaviour
An error is printed on stdout if launced from a terminal, otherwise the stream silently fails with either the message "Requesting stream" or, on a single for me non-repeatable occasion, something about having acquired 0 blocks out of the total amount.

## System Configuration
 

- LBRY Daemon version: 0.9.1
- LBRY App version: 0.9.1
- LBRY Installation ID: A1tVXWpgt4vqV9eUZz7Q
- Operating system: Linux (Linux-4.11.0-041100rc3-generic-x86_64-with-Ubuntu-16.04-xenial)

## Anything Else

Optionally check for write permissions by creating a dummy file?

**Comment by kauffj** [comment]
The app now uses a select folder dialog.
