### ISSUE TITLE
Video playback controls displayed on video description page

### ISSUE THREAD

**Issue by trickyhunter2017** [lbryio/lbry-app#295]
## The Issue
Video playback controls flash briefly at the bottom of the screen when you try to play an already downloaded video.  If the app can't retrieve the metadata, the video fails to play and the playback controls are displayed permanently at the bottom of the page.  See screenshot below.  

### Steps to reproduce
1.  Install the latest 0.12.2rc7 app, Windows client on Windows 10
2.  Play any already downloaded video
3.  Issue visible on top left of hompage, first vdieo - Cassually Explained: How to make a successful youtube channel.  On other videos it flashes briefly at the bottom of the page.

### Expected behaviour
Video playback controls should not be visible on the video description page.

### Actual behaviour
You'll see the controls either flash briefly or be displayed permanently at the bottom of the page.
(See screenshot below.)

## System Configuration

 

- LBRY Daemon version:  0.13.1
- LBRY App version: 0.12.2rc7
- LBRY Installation ID: 6hR14gSUQpdL8aVk5s9eM4hiHjHzMRKT8PFYd2wGJ3kSrGHaJ2SymZ1oZDPvEQaGzm
- Operating system: Windows (Windows-10-10.0.14393)

## Anything Else

Clearing the application cache didn't help.
Closing and restarting the app didn't help.
I ensured no LBRY processes were running in memory between closing and restarting the app.

## Screenshots

![lbry___ casuallyexplained_casually-successful 2017-06-27 16 59 48](https://user-images.githubusercontent.com/4589923/27599297-3775e2b2-5b60-11e7-8c26-c80ded3f4b43.png)

**Comment by tzarebczan** [comment]
I'm able to confirm this happens - very brief but does occur.

**Comment by akinwale** [comment]
I was able to reproduce this on Ubuntu 16.04. It is very brief. Working on a fix.

**Comment by kauffj** [comment]
I believe this was fixed.
