### ISSUE TITLE
Existing channel is shown as stub.

### ISSUE THREAD

**Issue by hackrush01** [lbryio/lbry-app#299]
### Steps to reproduce
1. Search for `lbry://@oscopelabs`

### Expected behaviour
The message "This channel page is a stub" should not be displayed.

### Actual behaviour
The message "This channel page is a stub" is displayed.

## System Configuration

 

Latest clone from github at the time of writing, commit SHA -> e42aa21

## Screenshots

![stub channel](https://user-images.githubusercontent.com/17583974/27612978-bd608eda-5bb6-11e7-98d9-f47c0be32a9d.png)

**Comment by tzarebczan** [comment]
Thanks for logging! Need to find out from @kauffj what they would like written here, if anything.
