### ISSUE TITLE
A Javascript error occured in the main process

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-app#30]
(I migrated, also known as copy/pasted, this issue from [here](https://github.com/lbryio/lbry/issues/585).)

### Steps to reproduce
1. just start the App in KDE Manjaro rolling release 17
2. then close the app
3. the error apear after 2-3 seconds on screen

### Expected behaviour
App should close normally, without any error apearint

### Actual behaviour
After closing the App in Manjaro KDE 17.0 Stable Rolling release, this error apear:

A Javascript error occured in the main process

Uncaught Exception:
TypeError: Cannot read property 'loadURL' of null
    at ChildProcess.subpy.on (/opt/LBRY/resources/app/main.js:58:10)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

## System Configuration

 

About

Your copy of LBRY is up to date.

daemon (lbrynet)	0.9.1
wallet (lbryum)	2.7.13
interface	0.9.1
Platform	Linux (Linux-4.10.4-1-MANJARO-x86_64-with-ManjaroLinux-17.0-Gellivara)

## Screenshots

![auswahl_395](https://cloud.githubusercontent.com/assets/5913218/24585546/85e25500-178d-11e7-8e3c-47e070eec14b.png)

**Comment by Snarkly** [comment]
I'm having this same problem. I'm using Linux Mint 18.1 Serena Cinnamon 64-bit. This error message pops up a second or two right after I close LBRY. 
![lbry](https://cloud.githubusercontent.com/assets/8492776/24625619/a6738aa0-187d-11e7-86a1-1cb0596e60e4.png)

**Comment by PetSte** [comment]
I've got the same problem since updating to the latest LBRY version (0.9.1). I'm running LBRY on Windows 10.

**Comment by alexliebowitz** [comment]
@kauffj: I can no longer reproduce this on Linux, either on a dev build or RC8. Is it still happening for you?

**Comment by PetSte** [comment]
Not sure if I can reply to this mail, but I'll try. I just reproduced the problem on my Windows 10. So for me, it's still there.




-------- Oorspronkelijk bericht --------
Van: alexliebowitz <notifications@github.com>
Datum: 04-05-17 11:04 (GMT+01:00)
Aan: lbryio/lbry-app <lbry-app@noreply.github.com>
Cc: PetSte <peterstevens92@hotmail.com>, Comment <comment@noreply.github.com>
Onderwerp: Re: [lbryio/lbry-app] A Javascript error occured in the main process (#30)


@kauffj<https://github.com/kauffj>: I can no longer reproduce this on Linux, either on a dev build or RC8. Is it still happening for you?

**Comment by alexliebowitz** [comment]
@PetSte: 0.10.0 [just came out](https://github.com/lbryio/lbry-app/releases/tag/v0.10.0) with many changes, including some in parts of the code related to this. Could you give it another shot with 0.10.0? Thanks.

**Comment by PetSte** [comment]
Alex,

After downloading v10 manually (from Github),  like you asked, lbry doesn't seem to recognize me anymore. I'm asked to enter my email and early acces verification code, and I get the error 'could not authenticate user'. I'm positive the code is correct.

So now I can't ue LBRY or acces my wallet anymore. Any solutions?


-------- Oorspronkelijk bericht --------
Van: alexliebowitz <notifications@github.com>
Datum: 05-05-17 08:13 (GMT+01:00)
Aan: lbryio/lbry-app <lbry-app@noreply.github.com>
Cc: PetSte <peterstevens92@hotmail.com>, Mention <mention@noreply.github.com>
Onderwerp: Re: [lbryio/lbry-app] A Javascript error occured in the main process (#30)


@PetSte<https://github.com/PetSte>: 0.10.0 just came out<https://github.com/lbryio/lbry-app/releases/tag/v0.10.0> with many changes, including some in parts of the code related to this. Could you give it another shot with 0.10.0? Thanks.

**Comment by Snarkly** [comment]
I just upgraded and I'm having the same problem PetSte is having.

**Comment by kauffj** [comment]
@PetSte @Snarkly :disappointed: 

Can you send your email addresses to jeremy@lbry.io?

If you're comfortable using the [command line interface](https://github.com/lbryio/lbry/releases) you can still move your credits. Otherwise, you'll have to wait until we get a fix out.

If you are comfortable using the CLI, it'd be helpful if you could send me the output of the `status` command as well.

And sending a wallet address wouldn't hurt either :wink:

**Comment by Snarkly** [comment]
I sent you my email using proton mail. I also open LBRY using the command terminal and I took this screenshot for you. There were a few errors I noticed in the command terminal.
![lbry](https://cloud.githubusercontent.com/assets/8492776/25775801/c1ba8e9a-327b-11e7-8272-5fe905dad211.png)

**Comment by Snarkly** [comment]
Thanks for the verification code kauffj, it seemed to work fine. Also when I closed LBRY I noticed I didn't get the javascript error I was getting before.

**Comment by PetSte** [comment]
Was this a special verification code or did you simply lose/mistake your own code? If it's the former, could you send me one as well, Jeremy? I've sent you my email address earlier.


-------- Oorspronkelijk bericht --------
Van: Jeffery Mullins <notifications@github.com>
Datum: 09-05-17 03:31 (GMT+01:00)
Aan: lbryio/lbry-app <lbry-app@noreply.github.com>
Cc: PetSte <peterstevens92@hotmail.com>, Mention <mention@noreply.github.com>
Onderwerp: Re: [lbryio/lbry-app] A Javascript error occured in the main process (#30)


Thanks for the verification code kauffj, it seemed to work fine. Also when I closed LBRY I noticed I didn't get the javascript error I was getting before.

**Comment by kauffj** [comment]
@PetSte no new code, you should be able to get in fine. I take it you are still seeing this even on the latest version? If so, I'll try to dig deeper.

**Comment by PetSte** [comment]
I don't get the Javascript error, but that's probably only because I can't seem to login. I'm still getting the 'could not authenticate user' error.

**Comment by kauffj** [comment]
0.12 will drop the necessity of codes and fix existing verification issues.
