### ISSUE TITLE
Top menu not suppressed in full screen video mode

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#308]
## The Issue
When playing a video in the app full screen, the Edit / Help / Developer menu bar is stiill shown. 
### Steps to reproduce
1. Go to claim with video (lbry://@IGNonLBRY/linked-ep5)
2. Click Play, go full screen
3. Menu bar visible

### Expected behaviour
Video should be in full screen

### Actual behaviour
Menu bar shown

## System Configuration

 

- LBRY Daemon version:
- LBRY App version: 0.12.2.rc9
![toolbar](https://user-images.githubusercontent.com/8120721/27690334-13838ff8-5caf-11e7-95f7-cebb97b3a2c7.png)

- LBRY Installation ID:
- Operating system: Windows 10

**Comment by kauffj** [comment]
https://github.com/lbryio/lbry-app/commit/d8e867aa5ae8e9872b7943a0fd8593f9fc68d826
