### ISSUE TITLE
Select boxes missing borders in Windows (at least on Publish page)

### ISSUE THREAD

**Issue by CjMapope** [lbryio/lbry-app#309]
The Issue

License text seems not properly displayed

Steps to reproduce
1. Navigate to "Publish" tab
2.Take a look at the license drop down bar
3. Error is apparent, looks funky, not showing first option or the border right :/

Expected behaviour
Tab should have border and also display first option as per "identity" bar just below it.

Actual behaviour
Border nor first option is displayed

System Configuration
- LBRY Daemon version: 0.13.1
- LBRY App version: 0.12.2rc9
- LBRY Installation ID: 97A47fSMf3SLaUojhbP99hxfpvZYxv78Da8ZBHj342ZG7dFByguVR2wiiVi1Xm2wc3
- Operating system: Windows (Windows-10-10.0.15063)

## Anything Else

Screenshots

![licenseee](https://user-images.githubusercontent.com/12862793/27691368-0838c252-5ca1-11e7-8c49-ee7adafb2272.PNG)

**Comment by tzarebczan** [comment]
![screenshot from 2017-06-28 17-51-04](https://user-images.githubusercontent.com/8120721/27692082-d19424ae-5cb3-11e7-925a-e5655b6b7824.png)

This is a reference from linux

**Comment by joemarchese** [comment]
![access license](https://user-images.githubusercontent.com/11649609/28726949-3de68d56-7391-11e7-8054-0d94b76c6221.PNG)

I think the first option isn't displaying because there's an extra blank <option></option>. _See screenshot_

**Comment by tzarebczan** [comment]
Blank is normal, that's not the problem.  I was trying to point out that it's difficult to see that there even is a drop down because it's not differentiated from the rest of the form (besides the arrow on the right)

**Comment by liamcardenas** [comment]
This was closed by #436, thanks @btzr-io!
