### ISSUE TITLE
Volume control resets when you going from one video to another

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#310]
## The Issue
When watching a video and adjusting the volume, the setting is lost when going to the next video. 
### Steps to reproduce
1. Watch Video 1
2. Adjust volume
3. Go to video 2, volume is back to 100%

### Expected behaviour
Volume should persist

### Actual behaviour
Volume resets to full

## System Configuration

 

- LBRY Daemon version:
- LBRY App version: 0.12.2RC9
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
https://github.com/lbryio/lbry-app/commit/444f2308772f49b5209b21caa6a393e19c5c4958
