### ISSUE TITLE
Retain page scroll position on backwards navigation

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#312]
## The Issue
The home page loses its place when you go back to it. If the home page had hundreds of options on it, it would be really annoying to have to scroll all the way down to wherever you were last browsing before you clicked on something.

### Steps to reproduce
1. Scroll down on home page, enter a video/media
2. Click back
3. Now you at back at the top of the home page

### Expected behaviour
Home page should return to where you were before going into media

### Actual behaviour
Home page goes back to top

## System Configuration

 

- LBRY Daemon version:
- LBRY App version: 0.12.2RC9
- LBRY Installation ID:
- Operating system:

**Comment by akinwale** [comment]
Should only the vertical scroll position be maintained? Or should the horizontal scroll position for each individual category be maintained as well?

**Comment by kauffj** [comment]
Vertical only

**Comment by kauffj** [comment]
There is a PR for this.
