### ISSUE TITLE
Published items duplicates with #Pending

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#313]
## The Issue
@6ea86b96 is aware of this one, happens when you publish a file without an identity. If publishing with an identity, don't get console error but issue still occurs. 
### Steps to reproduce
1. Publish file, click OK confirmation, watch console
2. leave and come back to Publishes - see 2 files
3. After file confirms, pending is still there

### Expected behaviour
There should be 1 file

### Actual behaviour
two entries get created

## System Configuration

 

- LBRY Daemon version:
- LBRY App version: 0.12.2RC9
- LBRY Installation ID:
- Operating system:

## Anything Else

warning.js:36 Warning: flattenChildren(...): Encountered two children with the same key, `2:$lbry://penguins1pub#pending-2`. Child keys must be unique; when two children share a key, only the first child will be used.
    in section (created by FileList)
    in FileList (created by Connect(FileList))
    in Connect(FileList) (created by FileListPublished)
    in main (created by FileListPublished)
    in FileListPublished (created by Connect(FileListPublished))
    in Connect(FileListPublished) (created by Router)
    in Router (created by Connect(Router))
    in Connect(Router) (created by App)
    in div (created by App)
    in div (created by App)
    in App (created by Connect(App))
    in Connect(App)
    in div
    in Provider
![publish issue - 2 files](https://user-images.githubusercontent.com/8120721/27697488-60669a82-5cc2-11e7-8e1e-d83ea06e6b8c.png)

​

**Comment by 6ea86b96** [comment]
Working on this as part of https://github.com/lbryio/lbry-app/pull/229

**Comment by kauffj** [comment]
I introduced this via a hack fix for another bug related to invalid characters in the pending publish metadata:

#b815f78a50bba1c4e7115370fb53cb06a5b4a909

The fix for this is just to put correct dummy metadata in, or to drop/alter the way pending publishes work.

**Comment by 6ea86b96** [comment]
I have something almost working adding dummy pending publishes to the store https://github.com/lbryio/lbry-app/pull/229/files#diff-313e02014d06fe554d4dd5ea2c2e7139R368. Another problem I then encountered is that the fileInfo returned by the `file_list` command does not have a `channel_name` until after the claim has been accepted, so I was ending up with my dummy info in the store with a channel, then another file with a pending claim in the store with no channel. Didn't get much time to dig into that yet.

**Comment by 6ea86b96** [comment]
Fastest solution to get something ready to merge IMO would be to drop pending publishes for now and get the basic publishing/markdown stuff good to go. Then create a new PR for pending publishes.

**Comment by 6ea86b96** [comment]
I'll split it out into 2 PRs in the morning.

**Comment by kauffj** [comment]
This is fixed in a PR, and will go live in the next version.
