### ISSUE TITLE
Show auth token in app

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-app#314]
As a user, I'd like to see my auth token so I can make external calls to the API as myself.

**Comment by kauffj** [comment]
What's the story for this?

**Comment by lyoshenka** [comment]
Updated story above. @6ea86b96 said he'd do it, but we never formally scheduled it.

**Comment by tzarebczan** [comment]
We should also show linked email address if possible.

**Comment by 6ea86b96** [comment]
PR in #369. The email address doesn't seem to be available locally as far as I can tell.

**Comment by kauffj** [comment]
Email address is just getting added to API and will come in the `rewards3` branch. Closing this as @6ea86b96 PR covers it.
