### ISSUE TITLE
Refactor Published page to only rely on claim_list_mine

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-app#315]
It is possible for content to exist in `claim_list_mine` without being in `file_list` (see #263). 

Additionally, `claim_list_mine` already includes metadata and sufficient information to render a FileTile.

Therefore, Publish ought to be refactored to only use `claim_list_mine`. 

Additionally, since we can expect these UIs to further diverge, I think it would be fine to reduce the shared logic between Downloaded and Published.

**Comment by 6ea86b96** [comment]
It looks like file info returned by `file_list` before the claim is confirmed is missing the `channel_name`. Switching to rely on `claim_list_mine` would fix this.

**Comment by kauffj** [comment]
Fixed in #346
