### ISSUE TITLE
When a downloading file is deleted it needs to be removed from the downloading file list

### ISSUE THREAD

**Issue by 6ea86b96** [lbryio/lbry-app#326]
## The Issue

Currently if a downloading file is deleted the app still keeps it in the list of `downloadingUris`, the download never completes and the progress bar gets stuck

### Steps to reproduce
1. Start downloading a file.
2. Delete it.

### Expected behaviour
The dock progress bar should disappear.

### Actual behaviour
The dock progress bar gets stuck

**Comment by lyoshenka** [comment]
@6ea86b96 this is in "needs review"? is there a PR for this?

**Comment by 6ea86b96** [comment]
Forgot to link the PR #370 which has already been merged. @lyoshenka
