### ISSUE TITLE
Require minimum daemon version in app

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-app#330]
Story: As a user, I want to know if the running daemon will not work with the app, so that I don't get weird bugs.

**Comment by kauffj** [comment]
https://github.com/lbryio/lbry-app/commit/444f2308772f49b5209b21caa6a393e19c5c4958

**Comment by tzarebczan** [comment]
Also related to: https://github.com/lbryio/lbry.io/pull/183

**Comment by kauffj** [comment]
Fixed in https://github.com/lbryio/lbry-app/commit/38fd451e72c60b0373a8e337bb1de1da37f7942a
