### ISSUE TITLE
Publishing a file with Unicode characters in the filename prevents the Downloads & Purchases view from displaying items

### ISSUE THREAD

**Issue by akinwale** [lbryio/lbry-app#334]
## The Issue
After publishing a file with the filename `Bassnectar - Reaching Out ★ [Unlimited].mp3` and restarting the application, the Downloaded and Published views are stuck with the "Loading" message and they do not display any items.

I also get the following error output in the developer tools console.
```
"{
  "code": -32500,
  "data": {
    "traceback": [
      "Traceback (most recent call last):",
      "  File \"site-packages\\twisted\\internet\\defer.py\", line 1355, in gotResult",
      "    ",
      "  File \"site-packages\\twisted\\internet\\defer.py\", line 1299, in _inlineCallbacks",
      "    ",
      "  File \"site-packages\\lbrynet\\lbrynet_daemon\\Daemon.py\", line 952, in _get_lbry_files",
      "    ",
      "  File \"site-packages\\twisted\\internet\\defer.py\", line 1445, in unwindGenerator",
      "    ",
      "--- <exception caught here> ---",
      "  File \"site-packages\\twisted\\internet\\defer.py\", line 1299, in _inlineCallbacks",
      "    ",
      "  File \"site-packages\\lbrynet\\lbrynet_daemon\\Daemon.py\", line 856, in _get_lbry_file_dict",
      "    ",
      "  File \"ntpath.py\", line 85, in join",
      "    ",
      "exceptions.UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 26: ordinal not in range(128)",
      ""
    ]
  },
  "message": "'ascii' codec can't decode byte 0xe2 in position 26: ordinal not in range(128)"
}"
```

### Steps to reproduce
1. Publish a file that contains Unicode characters in the filename similar to the one above.
2. Restart the lbry application.
3. Click on the "Downloads & Purchases" icon and observe.

### Expected behaviour
The Downloaded and Published views should display items that have been downloaded and published.

### Actual behaviour
The Downloaded and Published views are stuck displaying the "Loading" message, and no items are displayed.

## System Configuration
- LBRY Daemon version: 0.13.1
- LBRY App version: 0.13.0
- LBRY Installation ID: 8qNojwfT9CVjk1rufVgg85Aw9krtAztVLVCbb78tnwrvXDEWHPdAcBMcvgn8Mag6Uc
- Operating system: Windows (Windows-10-10.0.15063)

## Screenshots
https://www.dropbox.com/s/b8wg9164twe9oyl/lbry-downloads-and-purchases.png?dl=0

**Comment by kauffj** [comment]
Please see:

lbryio/lbry#692

lbryio/lbry#750

**Comment by tzarebczan** [comment]
I was just about to give Shockr a heads up about that, it should be fixed in the next daemon release. Think you can try running it now with the app.
