### ISSUE TITLE
Can't actually delete media, gets deleted from account and stays on network

### ISSUE THREAD

**Issue by 98farhan94** [lbryio/lbry-app#336]
## The Issue
When published items are deleted from Published section they stay on the network, and you lose all rights to manage them with the reserve LBC not getting refunded to your account.

The file shows up in claim_list_mine but not in file_list.

### Steps to reproduce
1. Publish media, note down media URI.
2. Delete it from Published section.
3. Navigate to media URI, it still exists, has your handle, and you cannot manage it any more.

### Expected behaviour
The media should get deleted from account as well as LBRY network and the LBC should be refunded.

### Actual behaviour
The media gets removed from the account but stays on LBRY, you don't get LBC and you can't manage the media anymore.

## System Configuration

App: Version 0.13.0 (0.13.0.1389)

    "lbrynet_version": "0.13.1",
    "lbryschema_version": "0.0.7",
    "lbryum_version": "2.8.4",
    "os_release": "16.6.0",
    "os_system": "Darwin",
    "platform": "Darwin-16.6.0-x86_64-i386-64bit",
    "processor": "i386",
    "python_version": "2.7.13"

## Anything Else
Here's the one I published although it shows my handle, I have no control over it and can't find it in my Published section: lbry://catfidget

I tread clearing app cache and reloading from developer, didn't fix it.

**Comment by tzarebczan** [comment]
Yep, deleting it doesn't actually mean removing the claim..this is the current functionality. There will be some simple claim management added soon. Can we close this?

**Comment by 98farhan94** [comment]
Okay, wasn't sure if that's how it's supposed to work.
