### ISSUE TITLE
Retain previous screen sizing on startup (LBRY starts maximized)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#338]
## The Issue
When LBRY is run, the app always goes into full screen mode.  We've had a user that mentioned this should not happen or should be configurable.  Is it possible to remember the previous window size upon next start up?  

If this is the intended functionality to maximize Home page content viewing, so feel free to close. 

### Steps to reproduce
1. Launch LBRY
2. Goes full screen

### Expected behaviour
LBRY should either not go in full screen mode or remember previous app close window size

### Actual behaviour
Always goes into full screen mode

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system: Windows

**Comment by randulo** [comment]
Yes, this is annoying when you have a large screen. Recalling window size is an excellent solution. Thanks for entering this.

**Comment by tzarebczan** [comment]
Actually, on Windows it does seem to keep the window size to the setting which LBRY was closed. Can someone confirm on Mac? I'll check Ubuntu later.

**Comment by kauffj** [comment]
Maximize is called on every run. It's called here: https://github.com/lbryio/lbry-app/blob/fce702f737909d21e9b7581051690f356a82bd56/app/main.js#L155

To address this ticket, size should be saved locally on close and set in the above linked function.

**Comment by akinwale** [comment]
Should the saved width and height override the minWidth and minHeight properties respectively?

**Comment by randulo** [comment]
If I were coding this, I'd make sure there was a minimum, because I have seen app windows that became so small by accident, they couldn't be made larger. The minimum could be 800x600 if the remembered size was too small. That size window is actually usable, if not optimal.

**Comment by kauffj** [comment]
Agreed, please retain the minimum @akinwale.

**Comment by tzarebczan** [comment]
Per suggestion from a community member: https://github.com/mawie81/electron-window-state
