### ISSUE TITLE
Can't Abandon Claim: Tx fee higher than claim amount

### ISSUE THREAD

**Issue by 98farhan94** [lbryio/lbry-app#343]
## The Issue
When a claim is created with a fractional LBC low enough to be lower than the Tx fee, you cannot abandon the claim.

### Steps to reproduce
1. Create a claim with 0.00001 LBC amount allotted to it.
2. Publish.
3. Try to abandon claim.

### Expected behaviour
Claim should abandon.

### Actual behaviour
"Cannot abandon claim because Tx fee is higher than claim amount."

## System Configuration

 

    "build": "release",
    "lbrynet_version": "0.13.1",
    "lbryschema_version": "0.0.7",
    "lbryum_version": "2.8.4",
    "os_release": "16.6.0",
    "os_system": "Darwin",
    "platform": "Darwin-16.6.0-x86_64-i386-64bit",
    "processor": "i386",

## Screenshots

Claim Details:
<img width="406" alt="screen shot 2017-07-10 at 3 43 41 am" src="https://user-images.githubusercontent.com/5463117/27998035-1b373b48-6522-11e7-88c0-38fa5e5bb658.png">

Claim Abandon Attempt:
<img width="577" alt="screen shot 2017-07-10 at 3 44 02 am" src="https://user-images.githubusercontent.com/5463117/27998037-268409ea-6522-11e7-8a6e-fa02e2576e66.png">

Error in Log File:
<img width="562" alt="screen shot 2017-07-10 at 3 44 10 am" src="https://user-images.githubusercontent.com/5463117/27998038-30a919a6-6522-11e7-8638-37ee4f1f8d72.png">

**Comment by kauffj** [comment]
This issue was moved to lbryio/lbry#768
