### ISSUE TITLE
Lbry windows app refusing to launch after some time or several launches

### ISSUE THREAD

**Issue by olokos** [lbryio/lbry-app#353]
## The Issue
Windows application refuses to launch after several cycles of opening and closing it.
https://gyazo.com/c94ed91b40ab0831c14c7e199720dea0
### Steps to reproduce
1. Install lbry
2. Register/login/try to use it
3. Close and reopen the application a few times
4. Eventually, reboot your computer a few times

### Expected behaviour
Tell us what should happen
Lbry application should connect, catch up to blockchain and work as intended
### Actual behaviour
Tell us what happens instead
It errors out every single launch preventing me from using it

## System Configuration

- LBRY App version: 0.13.0.1168
- LBRY Installation ID: No idea where to find this as I can't launch the application whatsoever anymore
- Operating system: Windows 10 Pro x64

## Anything Else
I've been told on slack that the fix would be to uninstall and reinstall the application, I've done that several times but the issue always returns.

## Screenshots
https://gyazo.com/c94ed91b40ab0831c14c7e199720dea0

**Comment by tzarebczan** [comment]
Before launching, can you check if LBRY.exe or lbrynet-daemon.exe are running in the task manager? We are aware of some issues which cause the process to hang, and if you re-run LBRY in this state, you typically get the error you are seeing.  Sometimes it can take a couple seconds to shut down completely also, so be patient before relaunching. 

A reboot normally fixes the issue for you?

**Comment by kauffj** [comment]
@tzarebczan please re-open if you can work with @olokos to determine reproducible steps and/or root cause.

**Comment by tzarebczan** [comment]
Will do. @olokos please let me know if this is happening if LBRY is already running in the background.

**Comment by olokos** [comment]
They're not actually, I double checked it.  Reboot doesn't seem to change a thing, I've been having issues with LBRY since the beginning.

https://gyazo.com/7a4cc223130e54b3c1fbc8007d36f741
Here's the issue I'm getting now and my PC was freshly rebooted yesterday and I haven't launched LBRY.

**Comment by tzarebczan** [comment]
That one we've definitely seen before but cannot reproduce consistently. This means the lbry-daemon file has disappeared from the program files directory. We aren't sure what is removing it yet, possibly some Anti-virus software or windows itself. I've noticed its happened to me when my PC shut down unexpectedly. A reinstall fixes the problem. 

Right now, we still don't have enough here to go and debug... A developer wouldn't be able to fix it without reproducing consistently. 

Can you try reinstalling now and follow the steps I laid out earlier in terms of checking if any lbry* processes are running? We are aware of some issues that cause the daemon to hang, which we are still investigating.

**Comment by olokos** [comment]
Well, I just uninstalled LBRY, installed it back again and it seems to autostart right after I install it, it takes quite a while after start now just saying Connecting. Seems to be stuck there. I'm a developer myself so if you need me to perform some advanced steps - let me know and I'll most likely do that.

After what I just described I had 2x LBRY.exe and 2x lbry-deamon.exe processes running. Killing LBRY.exe still left lbry-deamon.exe running

**Comment by tzarebczan** [comment]
Having 2x LBRY.exe and daemon processes is normal. Can you send us the log files  (https://lbry.io/faq/how-to-find-lbry-log-file) so we can further help troubleshoot? I've been using LBRY on Windows 10 for a couple months now and have not seen this issue, nor has it been reported by anyone else.  I'm thinking it has something to do with your local setup - possible port/firewall or permissions related. Thanks for helping us troubleshoot!

**Comment by olokos** [comment]
https://pastebin.com/4eY9TCmV

There's not too many issues with my firewall and ports that I'm aware of. I am running some servers on my PC from time to time, so they're mostly opened when required, but if you see a problem here then let me know and I'll switch to DMZ on router and open up my firewall entirely

**Comment by tzarebczan** [comment]
It remains closed because it's not something a developer can look into without someone being able to reproduce it effectively on our end. 

From your last log, we are able to get some additional info:
 lbrynet.core.utils:101: Failed to connect to lbry.io:80. Maybe the internet connection is not working

Looks like your PC/internet is not getting a connection to lbry.io - maybe something blocking it on your end? I haven't seen this message or complaint before. When this happens, can you try going to lbry.io on your browser?

**Comment by olokos** [comment]
It's a major issue preventing to use LBRY entirely and most users just couldn't care less if the application that they try to use doesn't even start and just forget about it forever, they don't even bother to report it.

It's a windows application so there's tons of variables and different things which don't neccesairly have to be reproducible by everybody, especially with so small developer base, but will prevent 20% people from using it, which can stop LBRY growth in the long run. It might just be an issue connected with Bitdefender antivirus for example and it will prevent each Bitdefender user from using it. It's just an example to explain this scenario better.

I've never had any issues with lbry.io. Pinging it is also working perfectly.

I've tried disabling both Bitdefender's and Windows Firewall, it worked, after turning it back on, force closing LBRY it still keeps working, so it's either Windows or Bitdefender firewall.

At first glance solution would be quite simple, create a new windows firewall rule opening LBRY ports.

It didn't really require rocket science to figure it out.

**Comment by tzarebczan** [comment]
Upon installation, lbry does ask for firewall permissions. So it was probably related to Bitdefender. 

I'll make sure this is part of the troubleshooting guide. Thanks! Come over to slack.lbry.io and I'll tip you for your efforts and testing!

**Comment by olokos** [comment]
Didn't ask me at all for that or at least not explicitly. Pay close attention to both windows firewall and bitdefender.

**Comment by olokos** [comment]
I'm olokos on slack, I've made messages to #help #tech and #general

**Comment by tzarebczan** [comment]
Thanks! I think we sorted the startup issues!

**Comment by olokos** [comment]
You're welcome. I'm looking forward to next update. :)

**Comment by tzarebczan** [comment]
This still occurs from time to time when LBRY processes do not shut down properly and LBRY is launched again.

**Comment by kauffj** [comment]
@tzarebczan when you say "this occurs" - do you mean the daemon disappearing? I am not 100% clear on the issue. Can you re-open this as a summary of what we know if there's something that needs to be fixed here, even if we don't understand it fully?

**Comment by kauffj** [comment]
Nm, I see you did re-open this. Can you edit the original issue to be a summary of the problem and what's known?

**Comment by tzarebczan** [comment]
Will do, I'll create a new issue for it and link this one.
