### ISSUE TITLE
Correctly handle multiple rewards of the same type

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-app#359]
Some rewards (e.g. `featured_download` and `referral`) may be claimed more than once. Each instance of the reward claim should be listed on the rewards page. Also, having claimed this  type of reward in the past should not prevent you from claiming it again.

That said, we most likely want to remove all the "Claim Reward" buttons on that page. The app should just know when you are eligible for a reward, and claim it for you. If you're concerned about the app making a mistake, it can in addition try to claim every reward in the background periodically.

**Comment by lyoshenka** [comment]
keep in mind that the api will only return one featured_download reward by default. if you want to test your work, pass the `?multiple_rewards_per_type=1` flag to `reward/list`

**Comment by kauffj** [comment]
This is blocked by an internal API issue.

**Comment by lyoshenka** [comment]
We just talked about this today, when I told you it's not blocked by anything. If something changed since then, please link to the blocking issue here so I can fix it.

**Comment by lyoshenka** [comment]
Unblocked

**Comment by kauffj** [comment]
This is finished in `invite_and_rewards` branch.
