### ISSUE TITLE
Bandwidth Limits not functional

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#372]
## The Issue
When setting a BW limit in App > Settings, it either does not get saved, or if it does, it is not functional (does not limit) as per discussions with @kaykurokawa.  

### Steps to reproduce
1. Go to Settings
2. Set BW limit
3. Nothing happens or radio button does not work

### Expected behaviour
Should allow for BW limit settings and enforce them

### Actual behaviour
Does not allow for settings and does not enforce.

## System Configuration

 

- LBRY Daemon version: 0.14.2rc6
- LBRY App version: 0.13.0
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
These are removed in the `master` version of the app, and will be gone in the next release. They cannot be restored until the daemon is modified to properly support them.

**Comment by tzarebczan** [comment]
Do you want me to reopen in lbry repo or are we keeping track already?

**Comment by kauffj** [comment]
I don't believe there is an issue in `lbry`.
