### ISSUE TITLE
Minimize LBRY App to Tray

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#374]
## The Issue
Would be a nice feature to have LBRY minimize to the tray (Windows) or better yet, have the option to via tray icon.  Not sure if this is possible in Mac/Linux. 
### Steps to reproduce
1. Minimize LBRY
2. Stays in taskbar

### Expected behaviour
Lbry should support minimizing to tray

### Actual behaviour
Stays in taskbar

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by hackrush01** [comment]
This is almost complete, I shall make a PR soon.
