### ISSUE TITLE
can't play .mov MPEG

### ISSUE THREAD

**Issue by okwme** [lbryio/lbry-app#377]
### Steps to reproduce
1. publish .mov file recorded with Apple iPhone
2. try to play
3.

### Expected behaviour
Tell us what should happen

video should play

### Actual behaviour
Tell us what happens instead
LBRY can't play that file

## System Configuration

 

daemon (lbrynet) | 0.13.1
-- | --
2.8.4
0.13.0
Mac OS 16.6.0

{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "build": "release",
    "ip": "91.65.221.116",
    "lbrynet_version": "0.13.1",
    "lbryschema_version": "0.0.7",
    "lbryum_version": "2.8.4",
    "os_release": "16.6.0",
    "os_system": "Darwin",
    "platform": "Darwin-16.6.0-x86_64-i386-64bit",
    "processor": "i386",
    "python_version": "2.7.13"
  }
}
- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
Unfortunately, .mov is not supported by HTML5, so this will likely not be fixed by us. These files are still downloadable, and can be played in your local player.
