### ISSUE TITLE
Claim ID is truncated from navigation bar on back action

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#385]
## The Issue
When viewing a permanent URL, then navigating away and coming back (using back button), the permanent URL changes to the vanity one. 
### Steps to reproduce
1. Go to lbry://nine#caa44977f1726b18f39f2cca0bacbef6773d6404
2. Click Home
3. Click back - ends up at lbry://nine

### Expected behaviour
Should go back to lbry://nine#caa44977f1726b18f39f2cca0bacbef6773d6404

### Actual behaviour
Goes to lbry://nine

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by 6ea86b96** [comment]
Fixed in #395
