### ISSUE TITLE
typing in search while streaming disrupts stream

### ISSUE THREAD

**Issue by reillysmith** [lbryio/lbry-app#393]
## The Issue
While watching a video, if you start typing or editing the search bar (for example, the whole hash was in the result but I wanted to copy-paste just the base name), auto-search will initiate and override the play window, stopping playback to change the screen to search results.
### Steps to reproduce
1. Stream a video
2. Edit what's in the URL bar
3. Wait for state change

### Expected behaviour

Freely type without disruption to my stream.

Or, if steam is to be disrupted, maintain it with a mini-player or tabbed window, etc.
### Actual behaviour

Automated results override all other window activity even before hitting "enter" key.

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by wilsonk** [comment]
It seems as though this has been fixed in v0.16? Should this ticket be closed? Hopefully :)

**Comment by wilsonk** [comment]
Woops, sorry I must have jumped the gun on this one (ie. didn't wait long enough for the search function to auto engage). My bad :(

**Comment by kauffj** [comment]
#579 will fix this and is being worked on, so I'm going to close this one.

**Comment by btzr-io** [comment]
<img width=500 src="https://user-images.githubusercontent.com/14793624/30778881-a52cee18-a09d-11e7-8735-491d3494c8ae.gif" />

**Comment by tzarebczan** [comment]
No longer an issue on the redesign.
