### ISSUE TITLE
lbrynet-daemon.exe disappears randomly

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#396]
## The Issue
We've seen this in the past, but I've decided to make an issue for it as it seems to keep happening. The best way to try to reproduce it is crash your PC unexpectedly while LBRY is running. After restart, the daemon file is missing from C:\Program Files (x86)\LBRY\resources\app\dist and when starting LBRY, you get an error message (see below).  LBRY.exe gets stuck in this case because it can't find a daemon and must be manually closed.

### Steps to reproduce
1. Run LBRY
2. force crash PC
3. Start LBRY after reboot

### Expected behaviour
Daemon does not get deleted

### Actual behaviour
daemon is deleted

## System Configuration

 

- LBRY Daemon version: 0.14.2
- LBRY App version: 0.14rc2
- LBRY Installation ID:
- Operating system:

## Screenshots

![27206445-b6c3d40c-5205-11e7-9606-cdaf8d4ed7c6](https://user-images.githubusercontent.com/8120721/28685840-1d365d62-72d7-11e7-9770-d85cb205892a.png)

**Comment by akinwale** [comment]
@tzarebczan I'm curious so that I can reproduce, how do you force the crash?

**Comment by MSFTserver** [comment]
@akinwale http://www.wikihow.com/Force-a-Blue-Screen-in-Windows

**Comment by tzarebczan** [comment]
@akinwale just force shutdown the PC (hold power button) while LBRY is running. Or if you are running a VM, force close the VM without saving. I haven't tried this recently nor have I really tried to reproduce it, I just know it happened to me the couple of times my PC did a hard shutdown.

**Comment by tzarebczan** [comment]
@kauffj mentioned he may have fixed a scenario where this could occur. Will keep an ear open to see if its still happening often.

**Comment by tzarebczan** [comment]
@IGassmann the current app behavior now when this happens (removing lbrynet-daemon) is the green loading screen that gets stuck at "Starting daemon" indefinitely. How can we improve this behavior?

That being said, have not heard of any reports of this happening.

**Comment by lyoshenka** [comment]
hasn't happened in a while, closing this. if you can repro, we'll look again.
