### ISSUE TITLE
Fix linting errors

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-app#397]
![errors](http://i.imgur.com/oBgK8MV.png)

**Comment by lyoshenka** [comment]
ASAR fix should be a separate ticket. I know we turned it off for a reason, but I don't know what that reason is.

**Comment by liamcardenas** [comment]
@IGassmann I'm making you aware of this old ticket in case its relevant to your current efforts, otherwise I will close it.

**Comment by IGassmann** [comment]
Those are electron linting errors. I fixed the asar one when I was restructuring the file structure. Still have to check out the others.

**Comment by IGassmann** [comment]
I'll use my time on this issue to refactor the main process to follow electron's best practices and get the code closer to the functional paradigm.
