### ISSUE TITLE
Failed to watch paid video

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-app#403]
Windows 10, app version 0.14.1. 

To reproduce:

- click on Skate Yrself Clean
- click play
- get confirm popup
- click confirm
- nothing happens. play arrow is back on the video
- click play again
- get confirm again
- click confirm
- no more play arrow, no video playing

**Comment by kauffj** [comment]
Fixed.

If you try this again and you are now seeing an error related to max key fees, please let me know.
