### ISSUE TITLE
Update README and/or build.sh to properly install yarn

### ISSUE THREAD

**Issue by likewei92** [lbryio/lbry-app#410]
besides node and npm

**Comment by filipnyquist** [comment]
I´ve look into this and see what´s the best way to include it.

**Comment by filipnyquist** [comment]
@likewei92 We already have yarn as a dependency and its downloaded and installed in the prebuild script
https://github.com/lbryio/lbry-app/blob/master/build/prebuild.sh#L91

To check and install all needed dependencies use `FULL_BUILD=true ./build.sh`

**Comment by tzarebczan** [comment]
Also, someone tried on Fedora25 and if failed until libsecret-devel was installed.

**Comment by likewei92** [comment]
@tzarebczan thanks, I was trying on Solus and failed at a libsecret step. Will try again and let you know soon.

Btw isn't better to list the dependencies so it can be distribution agnostic rather than running a prebuild script that apt-get installs stuff you need?

**Comment by btzr-io** [comment]
### Keytar
> **On Linux**
> Currently this library uses `libsecret` so you may need to install it before running npm install
   
- Debian/Ubuntu: `sudo apt-get install libsecret-1-dev`
- Red Hat-based: `sudo yum install libsecret-devel`
- Arch Linux: `sudo pacman -S libsecret`

**Comment by tzarebczan** [comment]
I've submitted a PR to get the setup steps updated: https://github.com/lbryio/lbry-app/pull/483
