### ISSUE TITLE
LBRY App does not prompt with Welcome message or for email input

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#414]
## The Issue
When clearing auth_token on an existing install and then starting LBRY, LBRY does not issue the welcome message nor does it prompt for email. Help screen shows email not connected. Rewards say "Verified account is required".  Only fix is to restart LBRY or Reload (ctrl - R or Developer > Reload). 

This also did happen to Jason on a fresh install of 0.14, not sure if it's been fixed since. I just did a fresh install and got my welcome message.

### Steps to reproduce
1. Close LBRY, clear auth_token
2. Start LBRY
3. No welcome message

### Expected behaviour
Welcome message and email prompt

### Actual behaviour
Nothing, app stuck in terms of getting to next stage with rewards. 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system: Win 10

**Comment by tzarebczan** [comment]
There were 2 users who reported this issue on a clean install today. Reload fixes it

**Comment by kauffj** [comment]
This one was tricky to debug. I pushed a fix for this that should at least show a pop-up when authentication failed. Has this issue only been happening to people who have installed at least once before?

**Comment by tzarebczan** [comment]
From what I understood, it was happening on brand new installs. I'd say at least 10 people reported either in Slack or email. Each time, a reload fixed it.

**Comment by kauffj** [comment]
Should be fixed in 0.14.3.
