### ISSUE TITLE
Videos inappropriately aligned if 4:3 or vertical

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#419]
## The Issue
Take this video as an example: lbry://nightofthelivingdead#e59cb8ee903d9c38c2563e2200026aec1be638fd 

The streaming screen could look a bit better in terms of aesthetics for videos with odd resolutions. It almost looks like it's cutting off. Maybe center or size the player accordingly? See screenshot below

### Steps to reproduce
1. Stream lbry://nightofthelivingdead#e59cb8ee903d9c38c2563e2200026aec1be638fd
2.
3.

### Expected behaviour
Can be displayed better

### Actual behaviour
looks broken

## System Configuration

 

- LBRY Daemon version: 0.14.2
- LBRY App version: 0.14.2
- LBRY Installation ID:
- Operating system: Windows 10

## Screenshots

![video cutting off](https://user-images.githubusercontent.com/8120721/28845392-d856486c-76d5-11e7-90fd-f5fe30e6babc.JPG)

**Comment by kauffj** [comment]
Duplicate of #409

**Comment by kauffj** [comment]
I suppose yours is better.
