### ISSUE TITLE
Unable to abandon claim

### ISSUE THREAD

**Issue by oakey22** [lbryio/lbry-app#420]
### Steps to reproduce
1.Make a claim
2. Remove file from download folder
3. Abandon claim through App

### Expected behaviour
Should still give me the option to abandon the claim

### Actual behaviour
I do not get the ... to let me abandon the claim, i just get Download button.

## System Configuration

 

```
App | 0.14.2
-- | --
0.14.2
3.1.4
gfugfqpsfpsewz@divermail.com
Linux (Linux-4.4.0-83-generic-x86_64-with-Ubuntu-16.04-xenial)

```

**Comment by tzarebczan** [comment]
For step 2, download folder in the OS, or download folder in lbry? Did you mean Publishes area?

**Comment by oakey22** [comment]
Its when i delete the file from the Download folder in the OS.

**Comment by tzarebczan** [comment]
This doesn't seem to happen in Windows, but this does: https://github.com/lbryio/lbry-app/issues/400

**Comment by tzarebczan** [comment]
@oakey22 if you run a lbrynet-cli claim_list_mine - does that claim return there? Also, is the claim under an identity? Instead of going through Publishes screen to the claim link, can you try going through your identity - which should give you the direct URI.

**Comment by oakey22** [comment]
I am unable to replicate this now for some reason. So i am closing it
