### ISSUE TITLE
Lbry app crashes at startup on Ubuntu 14.04-based system

### ISSUE THREAD

**Issue by stragu** [lbryio/lbry-app#421]
### Steps to reproduce
1. install v. 0.14.2-1590
2. launch the app

### Expected behaviour
App would stay up

### Actual behaviour
Splash appears, blockchain downloaded fine on first start, then the interface appears for a second and the app closes. On subsequent launches, same thing happens: interface opens, then disappears instantaneously.

When launched from the command line, output is:

```
Checking for lbrynet daemon
lbrynet daemon is already running
/opt/LBRY/lbry: relocation error: /opt/LBRY/resources/app/node_modules/keytar/build/Release/keytar.node: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERmm, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
```

## System Configuration

 

- LBRY Daemon version: 
```
  "id": null,                                                                                                  
  "jsonrpc": "2.0",                                                                                            
  "result": {                                                                                                  
    "build": "release",                                                                                        
    "ip": "130.102.82.120",
    "lbrynet_version": "0.14.2",
    "lbryschema_version": "0.0.9",
    "lbryum_version": "3.1.4",
    "os_release": "3.13.0-125-lowlatency",
    "os_system": "Linux",
    "platform": "Linux-3.13.0-125-lowlatency-x86_64-with-Ubuntu-14.04-trusty",
    "processor": "x86_64",
    "python_version": "2.7.12"
```
- LBRY App version: 0.14.2-1590
- LBRY Installation ID: 
- Operating system: KXStudio 14.04 (based on Ubuntu 14.04) with KDE 4:4.13.3-0ubuntu0.1

**Comment by tzarebczan** [comment]
This is a known issue because lbry requires gnome keyring installed in order to generate an authentication token. Can you try installing it and re running? We will look towards a solution that doesn't require the keyring in the future: https://github.com/lbryio/lbry-app/issues/386

Please reach out to help@lbry.io or #help channel next time if you require technical support.

**Comment by tzarebczan** [comment]
Check this thread, might adress the error. https://askubuntu.com/questions/777803/apt-relocation-error-version-glibcxx-3-4-21-not-defined-in-file-libstdc-so-6

Also, make sure the keyring is running: https://askubuntu.com/questions/898694/gnome-keyring-daemon-not-starting-up-properly

**Comment by stragu** [comment]
The keyring is definitely running (checked in my system monitor).

However, I managed to fix it somehow.

If anyone is running into the same issue, I managed to downgrade `libstdc++6` from version `7.1.0-5ubuntu2~14.04` (provided by `ppa:ubuntu-toolchain-r/test`)  to version `5.4.0-6ubuntu1~16.04.4` (from the Xenial updates, downloaded from [packages.ubuntu.com](https://packages.ubuntu.com/xenial-updates/libstdc++6). I had to use version 5.4.0 because downgrading to the older Trusty stock version 4.8.4 would throw an error of the type `version GLIBCXX_3.4.21 not found` when launching `lbry`.

To install the downloaded package, I had to use `sudo dpkg --auto-deconfigure -i <package-name>` because `libkolabxml1`needed de-configuring in the process.

If you do downgrade `libstdc++6`, you might want to hold it so it doesn't automatically upgrade further down the line, with the following command:  `sudo apt-mark hold libstdc++6`

Thanks @tzarebczan for the pointers!

**Comment by Arrowana** [comment]
Why is this closed? I am experiencing the same issue

**Comment by tzarebczan** [comment]
What error are you seeing? It seemed like it was a versioning issue specific to this user... Maybe because they had other packages installed previously.

Feel free to post your log file or try the troubleshooting steps above.

**Comment by Arrowana** [comment]
I am now getting the following error message:

> /opt/LBRY/lbry: relocation error: /tmp/.org.chromium.Chromium.eq33ez: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERmm, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference

while I had this error at the beginning:

> version GLIBCXX_3.4.21 not found

I am trying to resolve the issue but would like to avoid breaking dependencies for other software like @stragu
