### ISSUE TITLE
LBRY fails to install on a custom ubuntu 14 installation

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry-app#423]
## The Issue
Installing LBRY fails due to unresolved libraries (i think). 

The ubuntu installation seems custom (by reading the kernel name) but I think it might underline an existing problem

> samarau [14:04] 
> Hello. I've just installed LBRY on ubuntu 14.04. I get an error: /opt/LBRY/lbry: relocation error: /opt/LBRY/resources/app/node_modules/keytar/build/Release/keytar.node: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERmm, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
> What may be the problem?
> 
> fillerino [14:06] 
> @14bd4beb you know anything about this, seems like a dep problem?
> 
> fillerino
> @samarau https://askubuntu.com/questions/777803/apt-relocation-error-version-glibcxx-3-4-21-not-defined-in-file-libstdc-so-6 might help :slightly_smiling_face:
> askubuntu.com
> apt: relocation error: version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
> Since trying to upgrade to 16.04 xenial, I'm getting $ apt apt: relocation error: /usr/lib/x86_64-linux-gnu/libapt-pkg.so.5.0: symbol
>  
> nikooo777 
> uh that's a nasty error i think
> try `sudo apt install g++ gcc`
> 
> samarau [14:13] 
> First message solved my issue.
> Perhaps you should compile LBRY statically to avoid stuff like that.
> 

### Steps to reproduce
1. match the configuration mentioned below
2. try installing lbry
3. incur in the error

### Expected behaviour
LBRY should install on any supported system

### Actual behaviour
LBRY fails to install due to the missing linked library

## System Configuration

```
{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "build": "release",
    "ip": "46.53.209.143",
    "lbrynet_version": "0.14.2",
    "lbryschema_version": "0.0.9",
    "lbryum_version": "3.1.4",
    "os_release": "3.19.0-32-generic",
    "os_system": "Linux",
    "platform": "Linux-3.19.0-32-generic-x86_64-with-LinuxMint-17.3-rosa",
    "processor": "x86_64",
    "python_version": "2.7.12"
  }
}
```

## Anything Else
The user suggests compiling LBRY statically

**Comment by kauffj** [comment]
Fairly certain this is #386

**Comment by tzarebczan** [comment]
Think this helps in some cases: https://askubuntu.com/questions/777803/apt-relocation-error-version-glibcxx-3-4-21-not-defined-in-file-libstdc-so-6
