### ISSUE TITLE
Developer menu item showing on all installs

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-app#428]
It should only be shown if development mode is enabled (possibly developer mode is enabled for all installs).

**Comment by hackrush01** [comment]
How does one enable developer mode explicitly?

**Comment by kauffj** [comment]
It looks like this is the check being used in most places:

```lbry.getClientSetting("showDeveloperMenu")```

**Comment by hackrush01** [comment]
So should this be a setting in the `Settings` page to enable or disable the developer mode?

**Comment by kauffj** [comment]
I think the setting for toggling developer mode can go away in favor of using `process.env.NODE_ENV` (which is already used in several places). I think we should retain the ability to set alternative search servers and move this into normal settings, at the bottom.

**Comment by hackrush01** [comment]
Ok, so what I understand is
- [ ] Remove `ui/js/page/developer.js`
- [ ] Remove the option for toggling dev mode(the devs would use keyboard shortcuts to open console and refresh app)
- [ ] Remove force update
- [ ] Keep alt search server stuff.

**Comment by kauffj** [comment]
Correct except for #2. The dev mode would be toggled by setting an environment variable.

**Comment by hackrush01** [comment]
Gothca. Thanks.

**Comment by btzr-io** [comment]
is this still an issue?

**Comment by tzarebczan** [comment]
The menu bar was reinstated in the last version, but requires pressing Alt on windows machines or mousing over the menu bar on Linux (not sure about Mac).

Sounds like there are some remaining issues which were discussed in the thread, so I'll leave it open for now.

**Comment by btzr-io** [comment]
Ok, `win.setMenuBarVisibility(visible)` only works for  windows and linux

**Comment by liamcardenas** [comment]
@tzarebczan this is not happening for me in macOS
<img width="366" alt="screen shot 2017-12-14 at 6 38 18 pm" src="https://user-images.githubusercontent.com/5027235/34024257-05b41982-e0fe-11e7-9401-4659c82f052b.png">

can you check windows and if it doesn't show we should close this.

**Comment by tzarebczan** [comment]
See my last comment - this was fixed a while ago by hiding the Dev menu by default, but I wasn't sure if we wanted a settings option/environmental variable somewhere to enable show by default.

But I'd say yes, let's close for now. The users that generally need to get there know how to. Can always pop it into a faq too.
