### ISSUE TITLE
Withdrawal through app forces you to leave 1LBC in wallet

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#429]
## The Issue
When trying to send LBC for the entire amount in your wallet, the app tells you 1LBC must be left in the wallet. We should have a button that allows for max to be sent, while taking into account the TX fee. 

Workaround is to use the https://lbryio.github.io/lbry/cli/#send_amount_to_address cli call

### Steps to reproduce
1. Go to wallet, send an amount that's .5 less than your total
2. get error message about "after this transaction you would have less than 1 LBC in your wallet"

![balance](https://user-images.githubusercontent.com/8120721/28930782-0ae860fe-7842-11e7-9126-c06aba00a2c3.JPG)

### Expected behaviour
Able to withdraw all LBC

### Actual behaviour
Have to leave 1

## System Configuration

 

- LBRY Daemon version: 0.14.2
- LBRY App version: 0.14.2
- LBRY Installation ID:
- Operating system: Windows

**Comment by liamcardenas** [comment]
@kauffj what do you think we should do about this? Do you know why this was added to the app?

**Comment by kauffj** [comment]
This is fixed, according to both source and my quick test.

Though in my test I did encounter https://github.com/lbryio/lbry-app/issues/398
