### ISSUE TITLE
Prompt/show user minimum LBC deposit amounts for Publish and Claims

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#432]
## The Issue
The minimum deposit about that is able to be abandoned right now seems to be anything higher than 0.000096. This is most likely because the tx fee for publish/unpublish is 0.000096.  I guess the minimum amount would depend on the outcome of this discussion: https://github.com/lbryio/lbry/issues/768

The channels, the publish fee is 0.000178 so that would be the minimum.

### Steps to reproduce
1. Go to Publish
2. Cannot tell what the minimum amount is
3. Can publish something for 0.000095 that cannot be abandoned

### Expected behaviour
The App should either not allow something under 0.000097 or show what the minimum is.

### Actual behaviour
Allows amounts that later cannot be abandoned

## System Configuration

 

- LBRY Daemon version: 0.14.2
- LBRY App version: 0.14.2
- LBRY Installation ID:
- Operating system:

**Comment by btzr-io** [comment]
I think a prompt / modal would be annoying :upside_down_face:

**Comment by btzr-io** [comment]
![minimum](https://user-images.githubusercontent.com/14793624/28996935-0520583a-79c7-11e7-838b-1f4928a98839.gif)

**Comment by btzr-io** [comment]
![minimum](https://user-images.githubusercontent.com/14793624/28998280-37da3ecc-79e4-11e7-9cfa-6d4ed5212279.gif)

**Comment by tzarebczan** [comment]
@btzr-io  - thanks for your efforts, but I think we will need to scratch this for now as the fee is dynamic based on the tx size and there's no way to currently get these values. I'll open a separate issue for that and then maybe this could be revisited. 

@kauffj would it make sense to set a fixed fee for now, or should we circle back with @kaykurokawa regarding: https://github.com/lbryio/lbry/issues/768 ?

**Comment by btzr-io** [comment]
ok, so should I close my `PR` ?

**Comment by kauffj** [comment]
I'm closing this. There is no intention for there to be a minimum. It's not a matter of dynamic calculations.

I'm open to ways we can better communicate some portion of a transaction is unrecoverable.
