### ISSUE TITLE
Uninstall LBRY.exe needs to be run as Administrator?

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#433]
## The Issue
When simply running Uninstall LBRY.exe from the C:\Program Files (x86)\LBRY directory, nothing get's uninstalled. Not sure if there is anything we can do about this since the file is in a protected Windows folder, but thought we should file it anyway.  

Works fine when run as administrator. 

### Steps to reproduce
1. Run Uninstall LBRY.exe from C:\Program Files (x86)\LBRY directory

### Expected behaviour
Uninstall LBRY

### Actual behaviour
Nada

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by liamcardenas** [comment]
@tzarebczan still an issue?

**Comment by tzarebczan** [comment]
Nah, I'd say let's close it.
