### ISSUE TITLE
Download to Play Text below play button on video thumb nail

### ISSUE THREAD

**Issue by MSFTserver** [lbryio/lbry-app#435]
## The Issue

below the play button on the app there should be text that says download to play to not confuse people as to why everything downloads when they just hit the play button, a lot of new people get confused seeing the play button, then below the video frame they see Download, i feel they get confused as to thinking they can directly stream it without downloading but im assuming from very brief experience here its much like torrent network for downloading and watching files

**Comment by MSFTserver** [comment]
heres a fix that i use in my themes its all .css fixes
`.icon-play:before {
    content: "Download to ""\f04b";
    display: flex;
}
span.icon.icon-fixed-width.icon-play {
    left: -100px;
}`

**Comment by MSFTserver** [comment]
RESULT:
![image](https://user-images.githubusercontent.com/18357967/29000166-986d0db2-7a18-11e7-9d4c-2defad5b3cab.png)

**Comment by kauffj** [comment]
You are supposed to be able to stream the videos, not have to download them. Or rather, you're supposed to be able to start streaming without having downloaded the full file.

I do agree that some people find it confusing that they also download the file when they expect to stream it, and we should probably clarify this and add a setting to not do it.

But I'm disinclined to add this to the UI in this fashion.

**Comment by kauffj** [comment]
Made this one so we keep track: https://github.com/lbryio/lbry-app/issues/442
