### ISSUE TITLE
Contributors guide

### ISSUE THREAD

**Issue by btzr-io** [lbryio/lbry-app#437]
## The Issue
I can't find any contributors guide / guidelines, would be useful for new contributors like me.

### Expected behavior
A detailed list of guidelines  for new contributors  such as:
- Work flow
- Code standard ( indent / style )
- Commit messages
...

**Comment by MSFTserver** [comment]
Agreed, would be very helpful for everyone including the dev team

**Comment by btzr-io** [comment]
Also it should be  easy to find / access,  Like a section in `Readme.md`:

**Comment by MSFTserver** [comment]
don't forget contribute.lbry.io or lbry.io/contribute

**Comment by kauffj** [comment]
Great idea @btzr-io! We'll do this. Would you or @MSFTserver be able to share any contributor guidelines from any other projects that you think are particularly well done?

**Comment by btzr-io** [comment]
@kauffj Check butter project:
https://github.com/butterproject/butter-desktop/blob/master/CONTRIBUTING.md#contributing-to-butter

**Comment by btzr-io** [comment]
Any news / advances about this ?? ^^
