### ISSUE TITLE
Duplicated function handleCreateChannelClick

### ISSUE THREAD

**Issue by btzr-io** [lbryio/lbry-app#440]
## The Issue
Unused function `handleCreateChannelClick(event)` inside [publishForm/view.jsx#L382](https://github.com/lbryio/lbry-app/blob/master/ui/js/component/publishForm/view.jsx#L382)

 Moved to [publishForm/internal/channelSection.jsx#L55](https://github.com/lbryio/lbry-app/blob/master/ui/js/component/publishForm/internal/channelSection.jsx#L55)

**Comment by kauffj** [comment]
Merged.
