### ISSUE TITLE
Inputs allow negative value

### ISSUE THREAD

**Issue by btzr-io** [lbryio/lbry-app#441]
## The Issue
The claim deposit input inside `publish` page allows a negative value.

### Steps to reproduce
1. Open publish page
2. Go to Content URL > deposit
3. Add a negative value.

### Expected behaviour
It should probably allow  `0` or `minimum` but not negative.

### Actual behaviour
A negative value it's assigned,

## System Configuration

 

Configuration | Version
-- | --
App | 0.14.3
Daemon (lbrynet) | 0.14.2
Wallet (lbryum) | 3.1.4
Platform | Linux (Linux-4.10.0-28-generic-x86_64-with-elementary-0.4.1-loki)

## Screenshots

![negative](https://user-images.githubusercontent.com/14793624/29000040-4ddc2b30-7a1c-11e7-8667-11319d807e00.gif)

**Comment by btzr-io** [comment]
https://github.com/lbryio/lbry-app/issues/398

**Comment by tzarebczan** [comment]
Don't think #398 has anything to do with this one.

**Comment by btzr-io** [comment]
ok, I was just pointing out a similar issue, they are kind of related because both of them are: `ux` issue )

**Comment by btzr-io** [comment]
> Less then two. I understand that this is not critical issue. I think you can change it to something like "pending" instead of negative value.

**Comment by kauffj** [comment]
Fixed in Publish page, as well as in all LBC/USD hybrid inputs.

**Comment by btzr-io** [comment]
are you sure?? ^^ what about? -> #471

**Comment by kauffj** [comment]
Merged #471.

**Comment by btzr-io** [comment]
Also I think would be better set  default prop `min` -> 0

**Comment by kauffj** [comment]
If the`min` isn't a multiple of `step`, Chrome has some undesirable behavior when using the arrows (e.g. it will step 5 down to 4.91, with min=0.01 and step=0.1).
