### ISSUE TITLE
UI enhancement: Add forward history navigation

### ISSUE THREAD

**Issue by jsigwart** [lbryio/lbry-app#443]
### Steps to reproduce
1. Open LBRY
2. Do a few searches or view a few videos, then push the back arrow
3. See if you can go the other way in your history (forward). I dare you. ;)

### Expected behaviour
Tell us what should happen
There should be a -> arrow on the interface next to the <- arrow so you can go back and forth in your browsing history.

### Actual behaviour
Tell us what happens instead
You can go backwards in history. That's it.

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
Fixed in #481
