### ISSUE TITLE
Use css vars for theming

### ISSUE THREAD

**Issue by btzr-io** [lbryio/lbry-app#444]
## The Issue
To make a theme I need to compile  all scss into > `all.css` every time a change it's made.
Also I can't edit vars from `developer-tools` ( because its get compiled to css values ), so
this make a tedious process for testing / creating new themes.

### Steps to reproduce
1. Copy all `scss` styles.
2. Modify vars.
3. Build / compile `scss` > `all.css`

### Expected behaviour
Enable editing themes (vars) inside `developer-tools`

### Actual behaviour
> To make a theme I need to compile  all scss into > `all.css` every time a change it's made.
Also I can't edit vars from `developer-tools` ( because its get compiled to css values ), so
this make a tedious process for testing / creating new themes.

## System Configuration
Configuration | Version
-- | --
App | 0.14.3
Daemon (lbrynet) | 0.14.2
Wallet (lbryum) | 3.1.4
Platform | Linux (Linux-4.10.0-28-generic-x86_64-with-elementary-0.4.1-loki)

**Comment by btzr-io** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables

**Comment by MSFTserver** [comment]
Example: 
```
:root {
  --red: #b00;
  --blue: #4679bd;
  --grey: #ddd;
}
body {
  color: var(--red);
  background: var(--grey);
}
```

**Comment by btzr-io** [comment]
We can override the current `scss` vars like this:
```
   $color-main: var(--color-main);
   $color-bg: var(--color-bg);
```

**Comment by MSFTserver** [comment]
![image](https://spee.ch/9/Custum-Create-Your-Own.png)
https://spee.ch/9/Custum-Create-Your-Own.png

**Comment by kauffj** [comment]
Merged in branch `v16`, to be next release.
