### ISSUE TITLE
Check Address is valid before sending

### ISSUE THREAD

**Issue by MSFTserver** [lbryio/lbry-app#445]
## The Issue
issue comes about when trying to send funds to a non legit account like "aaaaaaaa"
### Steps to reproduce
1.enter address aaaaaaaaaa
2.enter amount
3.send

### Expected behaviour
i would expect this to do an api call to see if this address is existence and has funds linked to it or if it does not have a public or private key don't send the funds, and have error pop up if it doesnt work 
### Actual behaviour
it claims it sent the funds to the non existence account

## System Configuration

 

- LBRY Daemon version: 0.14.2
- LBRY App version: 0.14.3
- LBRY Installation ID: 9JKT6nrdGYoFKshVLmjnbfUdqNvHRkzWmsLXk5xNdbXzGEwpraZ6MVg1KoD5jrBrf2
- Operating system: Windows 10

**Comment by tzarebczan** [comment]
We may be able to do some semantic checks on the address (length, etc) but checking if the address exists or if it has public / private keys is impossible.

**Comment by MSFTserver** [comment]
even just an error saying it didnt send would be nice at this point even if it doesn exist and it doesnt send it says it sent and its in my queue

**Comment by MSFTserver** [comment]
![image](https://user-images.githubusercontent.com/18357967/29005962-79f4be4c-7a9b-11e7-9da2-371530124975.png)

**Comment by kauffj** [comment]
This issue exists in the daemon as well, and there are likely changes required for both. Here's the daemon ticket: https://github.com/lbryio/lbry/issues/828

**Comment by kauffj** [comment]
On the app side of this, the proper solution is probably one of:
- Create a component, `FormFieldWalletAddress`, that verifies the value is a valid address on blur/submit
- Modify `FormField` to take a `regexp` parameter, that matches on blur/submit, and submit the proper regexp as defined in `lbryuri`.

**Comment by akinwale** [comment]
I think we can run a base58 address validation check at the very least. Perhaps, something like https://github.com/wzbg/base58check/blob/master/index.js#L30-L47 which would require the use of an external module.

**Comment by kauffj** [comment]
Per discussion in meeting, the correct resolution for this is still https://github.com/lbryio/lbry-app/issues/445#issuecomment-320525524

**Comment by kauffj** [comment]
Merged, will be released in 0.15.1.
