### ISSUE TITLE
Publishes page does not refresh after file confirms

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#450]
## The Issue
Original issue being separated out from: https://github.com/lbryio/lbry-app/issues/390

After publishing, Publishes Page does not refresh after the file is confirmed (stays in pending confirmation)

A user reported that the file is seen on the Downloads page until it confirms. 

### Steps to reproduce
1. Publish something, wait patiently at the Publishes screen
2. After 5 minutes, click the claim.  Notice that it still says "pending confirmation"

### Expected behaviour
File should updated after it is included in a block

### Actual behaviour
File shows pending 

## System Configuration

 

- LBRY Daemon version: 0.14.2
- LBRY App version: 0.14.3
- LBRY Installation ID:
- Operating system: Windows

## Screenshots

![then updates with claim id](https://user-images.githubusercontent.com/8120721/28638169-07c938c0-7212-11e7-9071-bd5b7f1acc3d.PNG)

**Comment by kauffj** [comment]
Iceboxing this in the hopes the API gets fixed rather than addressing this in the app.

**Comment by liamcardenas** [comment]
@kauffj is there no solution for this via api?

**Comment by kauffj** [comment]
The `file_list` change I was working on integrates the pending publish behavior with Redux, which I believe will fix this. So when 0.19 is out, I think we'll have this.

**Comment by tzarebczan** [comment]
This works better in the redesign, but have run into it still getting stuck in pending a few times. I think we have narrowed it down to a publish after a file is edited. 

Closing this in favor of:  https://github.com/lbryio/lbry-app/issues/1520
