### ISSUE TITLE
URI Description Length (Add Max Character Count)

### ISSUE THREAD

**Issue by MSFTserver** [lbryio/lbry-app#452]
## The Issue
when setting a long description inside the app it will say it has published and is pending but looking at the transaction history no trans has been made but the video pop up in published area saying still pending but the daemon has already rejected it for having to long of a description 
### Steps to reproduce
1. Create a Long Description for a URI (for this i used a nice Wiki Article to test)
2. After pressing publish it says the file is pending for approval 
4. the video file stays in published saying pending
5. no tx records for that publish
### Expected behaviour
it should have a max character count so we dont go over this limit or if the daemon throws that character count error for the app to also throw a error and delete the file from pending as it will never make it and it should throw a try to re-upload error

### Actual behaviour
the file doesn't get published and stays in published section saying pending for about 5minuntes
no errors outputs for this yet....

## System Configuration

 

- LBRY Daemon version: 0.14.2
- LBRY App version: 0.14.3
- LBRY Installation ID: 9JKT6nrdGYoFKshVLmjnbfUdqNvHRkzWmsLXk5xNdbXzGEwpraZ6MVg1KoD5jrBrf2
- Operating system: Windows 10

## Screenshots

![image](https://user-images.githubusercontent.com/18357967/29046704-7ceaa444-7b7d-11e7-936b-c61f7f094296.png)
![image](https://user-images.githubusercontent.com/18357967/29046734-9a299812-7b7d-11e7-8556-d3e5ad987033.png)
![image](https://user-images.githubusercontent.com/18357967/29046748-abcb952a-7b7d-11e7-97ad-d7192074ddb0.png)
![image](https://user-images.githubusercontent.com/18357967/29046761-b774d4b8-7b7d-11e7-8913-ac51e8941d65.png)
![image](https://user-images.githubusercontent.com/18357967/29046623-2780c560-7b7d-11e7-94bf-1f2e54e7e1f6.png)
![image](https://user-images.githubusercontent.com/18357967/29046646-3a0dd4d4-7b7d-11e7-8f9c-a5475da3b7fa.png)

**Comment by kauffj** [comment]
This issue was moved to lbryio/lbry#847
