### ISSUE TITLE
Experimental features

### ISSUE THREAD

**Issue by btzr-io** [lbryio/lbry-app#456]
## The Issue
Allow users to test new features right away from the settings section (`UI`)
Without having to wait for the next / stable release.

### Expected behaviour
- Add a section in settings to allow users to active / disable `experimental` features.
- Show a warning that this my not work or can cause undesired behavior.
- Allow to report bugs...

**Comment by btzr-io** [comment]
See it as a safe Sandbox for `users` ^^

**Comment by kauffj** [comment]
I think the RC system is sufficient for handling this for now.
