### ISSUE TITLE
Content has a tiny LBC fee but shown as Free in app (requires payment)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#461]
## The Issue
If the content fee is a small LBC value, like 0.01, it is shown as Free on the app even though it requires a payment.  Take this instance this published item:  lbry://pascalcoinwalletb21202#e5a47c49c9d8b7a58dfb719992248265adfa75a3 the fee was set to 0.01 LBC but if navigating with app, it is shown as free.  When you go to purchase it, you get a pop-up that says "This will purchase [content] for free credits". 

Not sure what the threshold is exactly, but we need to be more precise with our fees. 

### Steps to reproduce
1. Publish content with a small LBC fee value
2. Content will show up as free
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

## Screenshots

![free credits](https://user-images.githubusercontent.com/8120721/29141266-7d67c4d4-7d1b-11e7-868d-6b5f01f2306b.JPG)

**Comment by btzr-io** [comment]
The problem is that price is getting formated `toFixed` ^^

**Comment by btzr-io** [comment]
Obviously: 0.01999  is not the same as 0.0

**Comment by btzr-io** [comment]
I know this: `0.0018893955352` looks ugly but I think the `app` should be transparent about prices :stuck_out_tongue:

**Comment by btzr-io** [comment]
Alternative ->  show a small button to display full price:
```
0.1 [...]
```

**Comment by btzr-io** [comment]
![fix-price](https://user-images.githubusercontent.com/14793624/29154090-1a1504c6-7d4f-11e7-8047-b7c6460bbc72.gif)

**Comment by kauffj** [comment]
I added a "<" symbol for when we are below the smallest renderable value and reduced the default precision to 2. Right now 0.01 LBC is less than a penny, so I'm not particularly concerned with more precision.

**Comment by tzarebczan** [comment]
@btzr-io -
Found an issue when downloading lbry://eight on the latest master. I like how it shows <0.01 LBC as the price, but when streaming/downloading, there is no confirmation box to purchase the content even though 0.01 LBC is charged. 

There is also this change going in soon: https://github.com/lbryio/lbry/pull/835 so not sure if that fixes/affects it.

**Comment by btzr-io** [comment]
I can't recreate this issue, I get an error which prevent me to purchase anything lower than `0.01` ^^

**Comment by tzarebczan** [comment]
@kauffj When they go to purchase the content, you want it also to show <0.01 LBC or show the exact price of the content in the purchase confirmation screen?

**Comment by kauffj** [comment]
Confirmation dialog should show the full price. It would also be a good idea to put the full price as a title attribute on the element when showing "<0.01" so the full price can be seen on mouseover.

**Comment by kauffj** [comment]
Fixed in https://github.com/lbryio/lbry-app/commit/c03c0de0a2b7c3b12b6041f7a851997f0e4229c2
