### ISSUE TITLE
Confirm Identity section does not work!

### ISSUE THREAD

**Issue by Synergyst** [lbryio/lbry-app#468]
I have installed a fresh copy of the LBRY client on Windows(the problem is likely to exist on any platform..) and attempted to add my card as a proof of identity.

Steps to reproduce error:
1. Type card number after reading 'To ensure you are a real person, we require a valid credit or debit card. There is no charge at all, now or in the future. Read More'
2. Add one of my bank debit cards to the information fields
3. Click verify
4. 'Card declined.'

Expect: I expect to not have my debit card that I use for purchases on other sites declined when trying to verify my identity on LBRY.

What actually happens: My card is declined.

I am running the latest version of the .exe installer from the LBRY website at the time of posting.

**Comment by tzarebczan** [comment]
Are you behind proxy or VPN? Which country are you in?  Please send an email to help@lbry.io with the last 4 digits and the answers to the above questions.

**Comment by Synergyst** [comment]
I have given 2 days for a reply email and have yet to receive one..
I attempted to re-verify my account following the steps given above with the same result..

Is there a reason why this is not working?

**Comment by tzarebczan** [comment]
Just following up, did someone reply to your email? If not, please send another as it may have gotten lost.

**Comment by Synergyst** [comment]
I eventually received a reply after my last post.

This can be closed now as the issue was resolved.
