### ISSUE TITLE
Blur Text on hover on Linux

### ISSUE THREAD

**Issue by oakey22** [lbryio/lbry-app#473]
Hover over tile on app and the description becomes blurred

### Expected behaviour
Should stay high definition

### Actual behaviour
Blurred Text

## System Configuration
Running Ubuntu 16.04

https://spee.ch/b/blur-text-lbry.jpg

**Comment by tzarebczan** [comment]
think this is fixed by https://github.com/lbryio/lbry-app/pull/413 but it's not part of a new app build yet.
