### ISSUE TITLE
Feature Request: Publish Upload Progress

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#475]
## The Issue
As a Publisher, when I upload files to LBRY, the current process is fairly uninformative after the Publish button is clicked. There is no indication that the file is being processed or when it's finished uploading (besides the URI being available).  This is a bigger issue with larger files as they take some time to upload.  

Feel free to add/comment. 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
This isn't an app issue. If you want, you can re-open on lbryio/lbry as "Make publish and get calls asynchronous"
