### ISSUE TITLE
First Publish / Channel Surfing Rewards incorrect error on unverified accounts

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#477]
## The Issue
When using an unverified account, the First Publish and Channel surfing Rewards return their own respective errors as opposed to saying "Only verified and approved accounts can claim rewards".  There should a consistent message across all Rewards for unverified accounts.

### Steps to reproduce
1. Try to claim First Publish or Channel surfing rewards on unapproved accounts
2. Get "Please publish something to claim this reward" / "Please create a channel identity first"

### Expected behaviour
Get "Only verified and approved accounts can claim rewards" on all rewards (except for referrals which is disabled? )

### Actual behaviour
See above

## System Configuration

 

- LBRY Daemon version: 0.14.2
- LBRY App version: 0.14.3
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
Moved.

**Comment by lyoshenka** [comment]
Reopening, as this is an app issue, not an api issue.

**Comment by tzarebczan** [comment]
This was fixed, now shows popup about verifying humanness
