### ISSUE TITLE
channel content list is backward

### ISSUE THREAD

**Issue by reillysmith** [lbryio/lbry-app#479]
## The Issue
most recent claims show on last page, not front page
### Steps to reproduce
1. publish 20 pieces of content to a channel
2. observe pagination order
3.

### Expected behaviour
Newest videos should be on top of the channel

### Actual behaviour
Newest videos (in tx order) show up from end of channel pages

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
This is fixed in lbryio/lbryum#152 and will be added without any further app changes (next app containing a 0.16.x daemon release will have it)
