### ISSUE TITLE
Provide an AppImage for Linux distributions 

### ISSUE THREAD

**Issue by Serkan-devel** [lbryio/lbry-app#48]
It might be great in the long run to provide the <a href="http://appimage.org/">Appimage</a> format next to `.deb` and `.rpm`.
While I'd still like to see #44 to be a thing, it would come with even more advantages.

Based off of https://github.com/MrAlex94/Waterfox/issues/127

- Works for most Linux distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, <a href="http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80">make it executable</a>, and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Just one format for all major distributions
- Works out of the box, no installation of runtimes needed (unlike Snap and Flatpak)
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs (unlike Flatpak)
- Can use the same AppImages when dual-booting multiple distributions

<a href="https://github.com/probonopd/AppImageKit/wiki/AppImages">Here is an overview</a> of projects that are already distributing upstream-provided, official AppImages.

It might also be great to provide the source files in a `.tar.gz` format too if it isn't possible.

**Comment by kauffj** [comment]
I think the AppImage format is great and we've looked at it, but we're stretched too thin to tackle this right now. One day!

**Comment by probonopd** [comment]
@kauffj `electron-builder` can do it automatically for you...

**Comment by kauffj** [comment]
@lyoshenka had concerns about supporting an additional build type, but if it's truly no additional overhead maybe we can. Assigning to him.

**Comment by lyoshenka** [comment]
Marking as feature-request and closing for now.

**Comment by Serkan-devel** [comment]
bump
