### ISSUE TITLE
Unfinished Video Picking Up Where Last Left Off

### ISSUE THREAD

**Issue by LanceDwight** [lbryio/lbry-app#491]
## The Issue
When returning to rewatch an unfinished video in the "Downloads & Purchases" folder, the video starts at 00:00 instead of picking up where it last left off.  You can see this feature implemented on YouTube.

### Steps to reproduce
1. Open the "Downloads & Purchases" folder
2. Click on a video that was not watched to the end.
3.

### Expected behavior
The video should pick up where it left off (e.g. starting at 03:55, instead of at 00:00).

### Actual behavior
The video starts playing at 00:00.

## System Configuration

 

- LBRY Daemon version: 0.14.2
- LBRY App version: 0.14.3
- LBRY Installation ID: 6brrRDZLjVxYTPHoA9N8Ah5FtmSZ6pwpk94rtFhW5KVD1jiVxa8eKQLKYD8tJ76zTm
- Operating system: Mac OS 16.7.0

Mac OS 16.7.0
--

Mac OS 16.7.0
--

Mac OS 16.7.0
--

Mac OS 16.7.0
--

**Comment by btzr-io** [comment]
Maybe this should be fixed first: https://github.com/lbryio/lbry-app/issues/389 ?

**Comment by lyoshenka** [comment]
done
