### ISSUE TITLE
4:3 aspect ratio videos left justify in player

### ISSUE THREAD

**Issue by reillysmith** [lbryio/lbry-app#492]
## The Issue
4:3 videos move left justified instead of centered
### Steps to reproduce
1. load /nightofthelivingdead, or any superman cartoon or 4:3 aspect ratio video
2. observe lack of centering
3. (full screen does center)

### Expected behaviour
video aligns with player

### Actual behaviour
video left justifies

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

## Screenshots

![43aspect-fail](https://user-images.githubusercontent.com/6074888/29623093-1c454734-87da-11e7-8109-3b9f2cb26601.PNG)

**Comment by tzarebczan** [comment]
This should be fixed in the next release:
https://github.com/lbryio/lbry-app/issues/419
