### ISSUE TITLE
Daemon fails to start if download directory moved

### ISSUE THREAD

**Issue by Makgolli** [lbryio/lbry-app#495]
## The Issue
Version: LBRY_0.14.3_amd64
Operating System: OpenSUSE Leap 42.2

Bug: Lbry desktop closes with message " The Daemon has failed to start...Goodbye"
There is no explanation as to the cause of the problem

Steps to recreate:
a) Move or rename the download directory before starting the application

Work around:

1) Restore or recreate the original download directory from the command line.
2) Start the desktop app normally.
3) From settings, change the download directory to the new desired location
4) Close the app.
5) Delete the old location in (1)
6) Restart the LBRY app
### Expected behaviour
Tell us what should happen
The app should open with a warning, allowing the user to change to directory from within the app.

### Actual behaviour
Tell us what happens instead

The App shuts down with the message " The Daemon has failed to start...Goodbye"

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
This issue was moved to lbryio/lbry#877

**Comment by kauffj** [comment]
@Makgolli thanks for reporting this. Please track https://github.com/lbryio/lbry/issues/877 if you want to know when this resolved.
