### ISSUE TITLE
Allow purchase confirmations to be bypassed

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-app#497]
As a user, I want to be able to not be asked to confirm extremely cheap purchases. Especially after #490 removes this check for prices below 0.01.

This PR would involve:
- Adding a setting to track a price below which the user is not shown a confirmation dialog on purchase
- Re-factor settings page to group this setting with maximum purchase price.
- Update `doPurchaseUri` action to not display the modal when making a purchase below the price

My first proposed name for this setting is "Single-Click Purchase Price" or "Automatic Purchase Price" but I do not really like either of these.

**Comment by btzr-io** [comment]
I think amazon have something similar...

**Comment by btzr-io** [comment]
![amazon](https://user-images.githubusercontent.com/14793624/29743814-217c9602-8a56-11e7-9375-f457f88c14e5.jpeg)
