### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by McFarJ** [lbryio/lbry-app#498]
Gah. I'm somewhat new to Linux, but still, the Linux installation process clearly isn't self explanatory...

## The Issue
Won't install

### Steps to reproduce
1. Use Ubuntu 16.04
2. Download the LBRY .deb file from lbry.io/get
2. It won't install via Software Centre, so use the terminal
3. This is what happens: 
$ sudo dpkg -i LBRY_0.14.3_amd64.deb
Selecting previously unselected package lbry.
(Reading database ... 246199 files and directories currently installed.)
Preparing to unpack LBRY_0.14.3_amd64.deb ...
Unpacking lbry (0.14.3-1608) ...
dpkg: dependency problems prevent configuration of lbry:
 lbry depends on libappindicator1; however:
  Package libappindicator1 is not installed.
dpkg: error processing package lbry (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5.1) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160824-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Errors were encountered while processing:
 lbry
4. Nothing appears to install.

### Expected behaviour
Install

### Actual behaviour
Doesn't Install

## System Configuration
Up to date Ubuntu 16.04 (64-bit)
Intel® Core™ i7-4700MQ CPU @ 2.40GHz × 8 
7.5 GiB memory
146.6 GB hard disk space

 

It appears as though I'm missing something called 'libappindicator1'
Doing a little searching myself on 'libappindicator1', it appears I can force the application to continue installing despite the complaint, doing something like: dpkg --configure -a --force-depends 
But I'm new to Linux and don't want to screw things up... Help?
Sorry if I'm missing something obvious.

**Comment by tzarebczan** [comment]
We are aware of the error and have it logged as a separate issue: https://github.com/lbryio/lbry-app/issues/474

Lbry should still install even with that error. Did you see if LBRY was installed in the start menu?

**Comment by McFarJ** [comment]
*jaw drops*
Upon searching, it now shows up as installed. I suppose it's in the realm of possibility I was mistyping during my earlier searches. So, sorry for the duplication of issue.
*leaves in shame*

**Comment by tzarebczan** [comment]
Haha no worries, thanks for checking out LBRY!

**Comment by wallermadev** [comment]
In future this error can mean a dependency was missing

You can try install it with 

`apt-get install -f`
