### ISSUE TITLE
History error when navigating forward from deeper in the history stack

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-app#499]
to recreate the history issue:

1. Open published
1. Click one of the links
1. Back
1. Click some other link
1. Back

**Comment by btzr-io** [comment]
@kauffj what's the regression?

**Comment by btzr-io** [comment]
`lbry://theinternetsownboy`

**Comment by btzr-io** [comment]
this ? -> https://github.com/lbryio/lbry-app/issues/480

**Comment by kauffj** [comment]
Click a link that opens an http address. I see errors on the console when I do this.

**Comment by btzr-io** [comment]
@kauffj  I can't recreated the issue, I try the links from: wallet -> transactions

**Comment by btzr-io** [comment]
What error are you getting ? :confused:

**Comment by hackrush01** [comment]
There's one more error I was getting: [video](https://gfycat.com/DecentAgreeableHumpbackwhale)

**Comment by btzr-io** [comment]
@hackrush01 what's wrong ? ^^

**Comment by btzr-io** [comment]
> There's one more error I was getting

you mean it's gone ? becaus ^^

**Comment by btzr-io** [comment]
I'll look in the code but I don't understand what's the issue yet ^^

**Comment by btzr-io** [comment]
![wtf](https://user-images.githubusercontent.com/14793624/29745712-e82bc5d8-8a7f-11e7-9a04-c666aaddea78.gif)

Well this obviously  wasn't there :stuck_out_tongue:

**Comment by btzr-io** [comment]
@hackrush01  provided this information in slack
> to recreate the history issue:
>1) Open published
>2) Click one of the links
>3) Back
>4) Click some other link
>5) Back

> It takes you through all the previously clicked links instead of taking you to publioshed

**Comment by btzr-io** [comment]
possible fix, needs to be test it: https://github.com/lbryio/lbry-app/pull/504/commits/4e3f86521e3b7eb2da1bd586a2cd948b11d6863b ^^

**Comment by kauffj** [comment]
@btzr-io I didn't test this really, but by inspection I'm not sure this is the right solution. Do we actually need two separate arrays for back and forward? Can't I do this with just one history array and a position? Then when the user navigates forward from a position other than the top of the history stack, you delete the history past your current position.

**Comment by kauffj** [comment]
@btzr-io I didn't test this really, but by inspection I'm not sure this is the right solution. Do we actually need two separate arrays for back and forward? Can't I do this with just one history array and a position? Then when the user navigates forward from a position other than the top of the history stack, you delete the history past your current position.

**Comment by kauffj** [comment]
@btzr-io apologies for sending you on a wild-goose chase here, since the issue as originally reported is only happening in `invites_and_rewards` (I will fix it there.)

I'm going to update this ticket to just address the case laid out here: https://github.com/lbryio/lbry-app/issues/499#issuecomment-325177376

**Comment by btzr-io** [comment]
@kauffj  I tried a different approach but didn't work,this was the only way

**Comment by btzr-io** [comment]
> Then when the user navigates forward from a position other than the top of the history stack, you delete the history past your current position.

**Comment by btzr-io** [comment]
I'll try your suggestion but it may get messy :upside_down_face:

**Comment by btzr-io** [comment]
Also the docs aren't really clear about this:

**Comment by btzr-io** [comment]
@kauffj fixed this in -> https://github.com/lbryio/lbry-app/commit/f6976c3feb5a049e5071d027f520a11dbba3b4f0

**Comment by btzr-io** [comment]
@tzarebczan this was fixed and merged by @kauffj and it's already in  `v0.15.0`

**Comment by tzarebczan** [comment]
Closing, thanks.
