### ISSUE TITLE
gui message: could not authenticate user

### ISSUE THREAD

**Issue by arainflake** [lbryio/lbry-app#50]
## The Issue
when loading up the version 10 for the gui for lbry, it stops at the message

LBRY Early Access
An error was encountered that we cannot continue from.

At least we're earning the name beta.

Message: Could not authenticate user

and gives me the option to reload, but wont succeed in anything else

### Steps to reproduce
1.run lbry gui from the wisker menu
2.
3.

### Expected behaviour
Tell us what should happen
it should open the menu for the gui, just the same way it did for the 9.2 version

### Actual behaviour
Tell us what happens instead

## System Configuration

 

{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "build": "rc",
    "lbrynet_update_available": false,
    "lbrynet_version": "0.10.0",
    "lbryum_version": "2.7.18",
    "os_release": "4.4.0-72-generic",
    "os_system": "Linux",
    "platform": "Linux-4.4.0-72-generic-x86_64-with-LinuxMint-18.1-serena",
    "processor": "x86_64",
    "python_version": "2.7.12",
    "remote_lbrynet": "0.9.1"
  }
}

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

## Anything Else

the thing is, just a few hours earlier i had the 9.2 version, and it was working ok but the search wasnt working, but realised that a newer version was out and thought that getting that version would probably fix it, so i downloaded that, and let the packadge manager handle the upgrade, which it did without error, then loaded the new gui and then the above problem happens

however, everything still works fine on the command line, and my wallet still has my starter 25 LBC, so im not sure what to do, lol...
![lbry gui error](https://cloud.githubusercontent.com/assets/27785632/25206354/7d68ab1c-2535-11e7-951a-f5303dd789c1.png)

**Comment by lyoshenka** [comment]
@alexliebowitz is our frontend expert, he'll take a look.

**Comment by kauffj** [comment]
This should be working.
