### ISSUE TITLE
Cannot read property publisherSignature of undefined

### ISSUE THREAD

**Issue by btzr-io** [lbryio/lbry-app#505]
## The Issues
App gets broken after clicking in downloads and publishes

### Steps to reproduce
1. Run build from last master.
2. Click on downloads and publishes

### Expected behaviour
It should show downloads tab content.
### Actual behaviour
Navigation don't work after this, and multiple errors are thrown:
```
Uncaught TypeError: Cannot read property 'publisherSignature' of undefined
    at eval (webpack:///./js/component/fileList/view.jsx?:111:45)
   ...
```
``` 
Couldn't set selectedTextBackgroundColor from default ()
```

## System Configuration
Last build from master -> https://github.com/lbryio/lbry-app/commit/fb2b37c4f176e927d6c5174e979091bef3abfc3f

**Comment by wallermadev** [comment]
Have debugged this and provided information in slack -- thanks for opening a issue @btzr-io 

Going to take a look at this now will submit a PR.

**Comment by btzr-io** [comment]
Fixed -> https://github.com/lbryio/lbry-app/pull/507
