### ISSUE TITLE
Sticky LBRY player on select files that downloaded okay

### ISSUE THREAD

**Issue by AJJPSMUSIC** [lbryio/lbry-app#51]
## The Issue
Sticky LBRY player on select files that downloaded okay
### Steps to reproduce
1. Load lbry://@AJJPS/ajjpsthecall
2. Press play and wait for decentralized package
3. Stays on black screen, controls will take instructions but player is stuck

### Expected behaviour
Tell us what should happen
File replay
### Actual behaviour
Tell us what happens instead
Nothing

## System Configuration
Win7 x64 Nvidia GeForce 
 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

## Anything Else

`ReactDOM.js:73 Download the React DevTools and use an HTTP server (instead of a file: URL) for a better development experience: https://fb.me/react-devtools
warning.js:36 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
printWarning @ warning.js:36
warning.js:36 Warning: Line: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.
printWarning @ warning.js:36
http://localhost:5279/lbryapi Failed to load resource: net::ERR_CONNECTION_REFUSED
http://localhost:5279/lbryapi Failed to load resource: net::ERR_CONNECTION_REFUSED
http://localhost:5279/lbryapi Failed to load resource: net::ERR_CONNECTION_REFUSED
http://localhost:5279/lbryapi Failed to load resource: net::ERR_CONNECTION_REFUSED
http://localhost:5279/lbryapi Failed to load resource: net::ERR_CONNECTION_REFUSED
http://localhost:5279/lbryapi Failed to load resource: net::ERR_CONNECTION_REFUSED
http://localhost:5279/lbryapi Failed to load resource: net::ERR_CONNECTION_REFUSED
http://localhost:5279/lbryapi Failed to load resource: net::ERR_CONNECTION_REFUSED
http://localhost:5279/lbryapi Failed to load resource: net::ERR_CONNECTION_REFUSED
http://localhost:5279/lbryapi Failed to load resource: net::ERR_CONNECTION_REFUSED
file:///C:/Users/AJJPS/AppData/Local/Programs/LBRY/resources/app/dist/undefined Failed to load resource: net::ERR_FILE_NOT_FOUND
watch.js:189 Stream between 0 and undefined.
watch.js:189 Stream between 24 and undefined.
watch.js:189 Stream between 217327604 and undefined.
mp4-remuxer.js:321 Uncaught TypeError: Cannot read property 'slice' of undefined
    at mp4-remuxer.js:321
    at _combinedTickCallback (internal/process/next_tick.js:67)
    at process._tickCallback (internal/process/next_tick.js:98)
(anonymous) @ mp4-remuxer.js:321
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
`

**Comment by lyoshenka** [comment]
@AJJPSMUSIC thanks for the detailed bug report. @alexliebowitz is our UI expert, he'll take a look at this and get back to you.

**Comment by kauffj** [comment]
The video player was switched. Please let us know if you are still experiencing this issue in the new player.

**Comment by AJJPSMUSIC** [comment]
@kauffj After testing it for a week, any further issue that was worth mentioning has been fixed with the newest update of LBRY I got today. All is good, well done for the work put in by everyone !!
