### ISSUE TITLE
New Videos Added When App is Open Price Doesnt Change

### ISSUE THREAD

**Issue by MSFTserver** [lbryio/lbry-app#511]
## The Issue
When the app is open when there is a new video added to the front page the prices stay the same as the last video fee that was in its place, so if the last video was free and the new video is not free the price will remain as free and the user may not know that front page has update within the time of them opening the app depending when it was launched. the user must refresh to get new prices but as for me i happened the open the app minutes before 2 new videos got put on the front page thinking they were free i downloaded them, lost 50 LBC thinking it was free but hopefully we can get this straightened out
### Steps to reproduce
1. leave app open
2. wait for new video to go on front page
3. price doesn't update assuming the price is free when it could well in fact not be

### Expected behavior
Tell us what should happen
the price to automatically update with the new video all the other stuff description, author, picture all get loaded but the new price,
or have a pop when a new videos come on to have the user refresh the page
### Actual behaviour
Tell us what happens instead
the app assumes the download and charges the uses the fee of the download but never a pop-up telling the user that they have purchased any content only to find lost funds and transaction they wouldn't have know about in there transactions list.

## System Configuration

 

- LBRY Daemon version: 0.14.2
- LBRY App version: 0.14.3
- LBRY Installation ID: 23frRChSLELdXoLLuYRZm21yXrAhiV3LeUud4S9qXmxetNLKmaTDX6Zxr9nGdcyuV5
- Operating system: Windows (Windows-2012ServerR2-6.3.9600)

## Screenshots

![image](https://user-images.githubusercontent.com/18357967/29765054-746d6182-8b8e-11e7-85b9-637696d1ccc9.png)
![image](https://user-images.githubusercontent.com/18357967/29765076-8b25f2f4-8b8e-11e7-8f98-059b0c861b6d.png)

**Comment by tzarebczan** [comment]
This is probably part of a larger issue: https://github.com/lbryio/lbry/issues/547

**Comment by tzarebczan** [comment]
The more general issue here is that users are not being shown the correct price for content unless LBRY is refreshed or cache is cleared.  This can cause much frustration if a user sees the video as free but it ends up charging them LBC.  In the case above, it was a large LBC value of 49.  

Are there any short term / temporary workaround solutions to fix this?

**Comment by MSFTserver** [comment]
only thing i can think of for a work around for now would be to implement a pop-up that asks a user to refresh the page when new content is there im not sure how goes about caching but it seems the description and everything else gets updated but the price so maybe the caching of the price could just be done away with?

**Comment by kauffj** [comment]
There are fixes to be made here app side, but I suspect they are insufficient without changes on the daemon side as well.

The changes to be made app side have been merged into #392.
