### ISSUE TITLE
Back Button - Does not ignore double clicks on destination buttons

### ISSUE THREAD

**Issue by oakey22** [lbryio/lbry-app#518]
### Steps to reproduce
1.Click Settings Button (Top Right)
2.Click Home Button twice
3.Click Back

### Expected behaviour
Should go back to the setting folder and not stay on the home screen.
### Actual behaviour
Does not move off the home screen. I see this as a problem as i know a lot of people who will double click icons and buttons.

App | 0.15.0rc2
-- | --
0.15.1
3.1.6
gfugfqpsfpsewz@divermail.com
 
Linux (Linux-4.4.0-92-generic-x86_64-with-Ubuntu-16.04-xenial)

**Comment by tzarebczan** [comment]
If you click back again, does it go back to settings? I think it tracks each click, so it would need to take into account the scenario where the same button /action /screen is clicked twice.

**Comment by oakey22** [comment]
Yes it goes back if you double click, like you say it's tracking each click and does not account for a double click. I know my parents and a few of my friends always double click nearly everything lol.

**Comment by MSFTserver** [comment]
yes youd have implement a check to see if there are two in a row that are the same and filter them out so its a list with no repeats

**Comment by MSFTserver** [comment]
essentially double clicking logs it twice in the history so you have to press the back button twice to get passed the doubled up history

**Comment by gyroninja** [comment]
I can not reproduce this bug on the latest version pushed to git.

**Comment by MSFTserver** [comment]
well thats where the issue arises @gyroninja simply press any menu button twice and youll have to press the back button twice or the first time it reloads the page again cause you clicked twice and it logged it to history twice

**Comment by btzr-io** [comment]
@gyroninja @MSFTserver The new history logic don't allow history duplication ^^

**Comment by btzr-io** [comment]
@tzarebczan I guess you can close this 
unless someone can recreate the bug in master, but that should be impossible :stuck_out_tongue:

**Comment by MSFTserver** [comment]
👍

**Comment by oakey22** [comment]
I am getting this problem on the 0.15.0.rc2 version released yesterday. Has the fix been implemented since then?

**Comment by kauffj** [comment]
This was real. Fixed in a911336

**Comment by btzr-io** [comment]
@kauffj I think there is an issue with the home page, the first time location is `/discover?`
and after that you get -> `/discover`

**Comment by oakey22** [comment]
working in version 0.15.0
