### ISSUE TITLE
lbry app 15.0 crash on start 

### ISSUE THREAD

**Issue by polminer** [lbryio/lbry-app#521]
lbry app 15.0 crash on start 

Win 10. 64

## Screenshots

![3269](https://user-images.githubusercontent.com/26439658/29948789-8bf02ea6-8eb9-11e7-9521-2256adeb21e6.png)

**Comment by polminer** [comment]
After I closed Claymore miner, Lbry app starts working well.

**Comment by MSFTserver** [comment]
@polminer this is know issue with claymore conflicting ports for now simply do this and should work 
https://lbry.io/faq/how-to-change-port
