### ISSUE TITLE
Add a message about token security to auth_token display

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-app#523]
As a user, I don't want to ever share my token with anyone, or else they can impersonate me.

We need a message next to the auth token field that says something like "Auth token is for API use only. Never share it with anyone. Keep it secret - treat it like your password."

**Comment by MSFTserver** [comment]
the access token im assuming?

**Comment by MSFTserver** [comment]
something like this?
![image](https://user-images.githubusercontent.com/18357967/29991310-9353f10c-8f39-11e7-8f29-177d8a267723.png)

**Comment by MSFTserver** [comment]
Pull-Request https://github.com/lbryio/lbry-app/pull/524

**Comment by kauffj** [comment]
https://github.com/lbryio/lbry-app/commit/19165895533dc3c6b5a092b2c22d14730d11bb14
