### ISSUE TITLE
App should indicate whether I'm reward-approved

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-app#529]
As a user, I want to know if I'm approved to claim rewards. If I'm not and I want rewards, I should see what I can do to get approved. Then I won't be confused about my status, and won't pester support team about it.

**Comment by finer9** [comment]
This one is very important to #verification and will help the mods greatly

**Comment by MSFTserver** [comment]
isnt that what this page for
![image](https://user-images.githubusercontent.com/18357967/30034193-90e937de-9154-11e7-9387-0cb635631284.png)

**Comment by MSFTserver** [comment]
but yea should add a display on the rewards tab with eligibility

**Comment by MSFTserver** [comment]
![image](https://user-images.githubusercontent.com/18357967/30036838-64629e0a-916b-11e7-8c75-039ec41e165a.png)
hows something like this?

**Comment by tzarebczan** [comment]
@MSFTserver that looks good to me! Can we add a link to the verification page if they are not eligible?

**Comment by MSFTserver** [comment]
yea that can be done

**Comment by MSFTserver** [comment]
i could be wrong but if they arnt eligible isnt there a big box that pops up on the first row to verify or is that on the rewards page....if its only on the rewards page it should be added to the overview page to

**Comment by MSFTserver** [comment]
@tzarebczan about the link, how you prefer to have it, id most likely have to include the Eligible text twice and pass it in with the the function that determines if they are eligible and on the one they arnt eligble make it hyperlink

**Comment by finer9** [comment]
@lyoshenka can you comment on why it would be hard to display a yes/no approval after the YTsync script?

**Comment by tzarebczan** [comment]
@MSFTserver you don't see anything about verification until verification until you get to the Rewards tab.  

Maybe instead of the hyperlink, just direct them to the Rewards tab / hyperlink below? Not sure, maybe @kauffj has a better suggestion.

**Comment by MSFTserver** [comment]
i could take out the the how many credits you have thing if they arnt eligible and add something to direct them

**Comment by tzarebczan** [comment]
Showing the available number of credits also entices them to check the Rewards tab...

**Comment by MSFTserver** [comment]
i just thought of that thats why i edited it and added the or lol

**Comment by MSFTserver** [comment]
but i could add on to it "You are Not Eligible but you have XX unclaimed rewards waiting click here for verification or something"
but ill wait for jeremy to, see what he thinks

**Comment by tzarebczan** [comment]
@kauffj / @lyoshenka  comments on the above?

**Comment by kauffj** [comment]
There is already a display area at the top of rewards that is in one of three states:
a. Prompts you to begin/resume verification
b. Says you are "under review" (happens when user has taken required steps but is still flagged as not eligible)
c. Empty (= you are approved).

What users in what reward state are getting confused as to their status?

I agree with improving the feedback with regards to YouTube and sync, but most of that can't happen without reward endpoint changes.
