### ISSUE TITLE
Material design ( UI enhancement )

### ISSUE THREAD

**Issue by btzr-io** [lbryio/lbry-app#531]
If the app is going to have a material design look at least it should follow the guidelines:
https://material.io/guidelines/material-design/introduction.html#

### Frameworks
http://materializecss.com/
https://getmdl.io/index.html

**Comment by kauffj** [comment]
The app started as a quickly hacked together piece of crap, but adopted Material Design fairly quickly, but also fairly imperfectly.

You are welcome and encouraged to submit individual PRs or tickets to help standardize and improve the UI.

However, I don't think this is actionable as-is, so I'm closing it.

**Comment by btzr-io** [comment]
@kauffj ok agree, I haven't seen the current first run but I remember the old one: wasn't really clear,
I guess this then:
> Let the user know why is important to backup the wallet,

And maybe ask to do it right from the start?
