### ISSUE TITLE
App intro screen ( UI / UX enhancement )

### ISSUE THREAD

**Issue by btzr-io** [lbryio/lbry-app#532]
### Feature
An intro screen to  help `first-time` users get started with `lbry` / `lbry-app`. 
( Only show the first time you run the app )

### Stuff 
- A simple introduction to the `app` / `lbry`.
- A brief explanation of  the confusing things ( Rewards, claims, and don't forget verification ... )
- Let the user know why is important to backup the wallet 
( and maybe add the backup button near this ) `?`
- A basic configuration to get started. ( Max purchase price, Share Diagnostic Data ...) 
- Add a Skip / Next button.

### References
https://material.io/guidelines/growth-communications/onboarding.html

**Comment by kauffj** [comment]
@btzr-io in MD context, this would be Quickstart onboarding. Also, if you've seen the current first run, we do provide an introductory message, as well as onboarding content when the user first does something credit related.

I we do need more welcome and introductory content, but I think the best UX comes from introducing new things to people as they need to learn or know about them, not by putting everything on them upfront.

Could you open specific, separate tickets for the areas that need a better introduction?

**Comment by btzr-io** [comment]
@kauffj ok agree, I haven't seen the current first run but I remember the old one: wasn't really clear,
I guess this then:
> Let the user know why is important to backup the wallet,

And maybe ask to do it right from the start?

**Comment by btzr-io** [comment]
@kauffj ok agree, I haven't seen the current first run but I remember the old one: wasn't really clear,
I guess this then:
> Let the user know why is important to backup the wallet,

And maybe ask to do it right from the start?
