### ISSUE TITLE
Publishing Logic Cleanup

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-app#540]
Publishing could use the following design changes, as inspired by #526:

- Publish form accepts pre-filled state from outside
- Publish page handles the edit logic and passes pre-fill state to the form
- Publish form drops the logic handling loading values. The link on a name clash simply becomes a navigate to the proper URL.
- Navigation logic is claim ID based rather than name based (we want to support multiple publishes to the same name, though we don't atm).
- Update the title displayed in the address bar based on the action being an edit.

**Comment by kauffj** [comment]
Related for the ambitious: #373 #528 #493

**Comment by btzr-io** [comment]
All that could be handle more eassy if we split: `publish / edit / new channel `
https://github.com/lbryio/lbry-app/issues/528#issuecomment-327068051
