### ISSUE TITLE
Bind enter key press to form submission as appropriate

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#542]
## The Issue
If you try to use the Enter key to send credits on the Send screen or send an invite on the Invites screen, the page reloads and nothing happens

### Steps to reproduce
1. Go to Send screen, enter amount and address, press Enter
2. Go to invite screen, enter email to invite, press Enter
3.

### Expected behaviour
Enter key should be allowed to confirm action

### Actual behaviour
Enter key refreshes page. 

## System Configuration

 

- LBRY Daemon version: 0.15.1
- LBRY App version: 0.15.1
- LBRY Installation ID:
- Operating system: Windows

**Comment by kauffj** [comment]
@tzarebczan re-titled to the solution I'd like to see.

**Comment by btzr-io** [comment]
should all forms have this behavior (  publish form... ) ?

**Comment by kauffj** [comment]
Publish probably shouldn't?

(It should only be happening when an input or label is not focused, regardless)
