### ISSUE TITLE
Receive and Invites screens missing icon in address bar

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#543]
## The Issue
The Recieve and Invites screens are missing their respective icons in the LBRY App address bar. The other screens each have an icon. 

Per Jeremy: 
```
Those are the two new icons that are supposed to be in the new icon set, it must still be bundling the old one somehow
i.e. we upgraded from font-awesome 4.3 -> 4.7 and those were added in between
```
### Steps to reproduce
1. Go to Receive tab, no icon
2. Go to Invites tab, no icon

### Expected behaviour
Icons are consistent

### Actual behaviour
No Icon

## System Configuration

 

- LBRY Daemon version: 0.15.2
- LBRY App version: 0.15.1
- LBRY Installation ID:
- Operating system: Windows

**Comment by btzr-io** [comment]
![fix-543](https://user-images.githubusercontent.com/14793624/30246023-7964cd9e-95aa-11e7-84c6-181129829403.gif)

**Comment by kauffj** [comment]
I believe we have desired icons for this. This can be resolved simply by properly bundling Font Awesome 4.7 or higher.
