### ISSUE TITLE
Can not publish in 0.15.1 - Channel name hangs

### ISSUE THREAD

**Issue by oakey22** [lbryio/lbry-app#544]
### Steps to reproduce
1. Go to Publish and try and publish something

### Expected behaviour
Should load the list of channel names

### Actual behaviour
Just hangs on listing the channel names and never loads them up. Can not enter any info in the lbry://....... box either till the channel names are resolved.

https://spee.ch/a6bb8f325ba66e1d1aadec58a1d5e833d5c688ec/nochannelname.png

**Comment by oakey22** [comment]
getting this in the developer tools

`Uncaught (in promise) TypeError: Cannot read property 'name' of undefined
    at file:///opt/LBRY/resources/app/dist/js/bundle.js:35181:26
    at Array.map (native)
    at ChannelSection.render (file:///opt/LBRY/resources/app/dist/js/bundle.js:35180:29)
    at file:///opt/LBRY/resources/app/dist/js/bundle.js:74359:21
    at measureLifeCyclePerf (file:///opt/LBRY/resources/app/dist/js/bundle.js:73639:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (file:///opt/LBRY/resources/app/dist/js/bundle.js:74358:25)
    at ReactCompositeComponentWrapper._renderValidatedComponent (file:///opt/LBRY/resources/app/dist/js/bundle.js:74385:32)
    at ReactCompositeComponentWrapper._updateRenderedComponent (file:///opt/LBRY/resources/app/dist/js/bundle.js:74309:36)
    at ReactCompositeComponentWrapper._performComponentUpdate (file:///opt/LBRY/resources/app/dist/js/bundle.js:74287:10)
    at ReactCompositeComponentWrapper.updateComponent (file:///opt/LBRY/resources/app/dist/js/bundle.js:74208:12)
(anonymous) @ channelSection.jsx:111
render @ channelSection.jsx:111
(anonymous) @ ReactCompositeComponent.js:795
measureLifeCyclePerf @ ReactCompositeComponent.js:75
_renderValidatedComponentWithoutOwnerOrContext @ ReactCompositeComponent.js:794
_renderValidatedComponent @ ReactCompositeComponent.js:821
_updateRenderedComponent @ ReactCompositeComponent.js:745
_performComponentUpdate @ ReactCompositeComponent.js:723
updateComponent @ ReactCompositeComponent.js:644
receiveComponent @ ReactCompositeComponent.js:546
receiveComponent @ ReactReconciler.js:124
updateChildren @ ReactChildReconciler.js:109
_reconcilerUpdateChildren @ ReactMultiChild.js:206
_updateChildren @ ReactMultiChild.js:310
updateChildren @ ReactMultiChild.js:297
_updateDOMChildren @ ReactDOMComponent.js:942
updateComponent @ ReactDOMComponent.js:760
receiveComponent @ ReactDOMComponent.js:722
receiveComponent @ ReactReconciler.js:124
updateChildren @ ReactChildReconciler.js:109
_reconcilerUpdateChildren @ ReactMultiChild.js:206
_updateChildren @ ReactMultiChild.js:310
updateChildren @ ReactMultiChild.js:297
_updateDOMChildren @ ReactDOMComponent.js:942
updateComponent @ ReactDOMComponent.js:760
receiveComponent @ ReactDOMComponent.js:722
receiveComponent @ ReactReconciler.js:124
_updateRenderedComponent @ ReactCompositeComponent.js:753
_performComponentUpdate @ ReactCompositeComponent.js:723
updateComponent @ ReactCompositeComponent.js:644
receiveComponent @ ReactCompositeComponent.js:546
receiveComponent @ ReactReconciler.js:124
_updateRenderedComponent @ ReactCompositeComponent.js:753
_performComponentUpdate @ ReactCompositeComponent.js:723
updateComponent @ ReactCompositeComponent.js:644
receiveComponent @ ReactCompositeComponent.js:546
receiveComponent @ ReactReconciler.js:124
_updateRenderedComponent @ ReactCompositeComponent.js:753
_performComponentUpdate @ ReactCompositeComponent.js:723
updateComponent @ ReactCompositeComponent.js:644
receiveComponent @ ReactCompositeComponent.js:546
receiveComponent @ ReactReconciler.js:124
_updateRenderedComponent @ ReactCompositeComponent.js:753
_performComponentUpdate @ ReactCompositeComponent.js:723
updateComponent @ ReactCompositeComponent.js:644
performUpdateIfNecessary @ ReactCompositeComponent.js:560
performUpdateIfNecessary @ ReactReconciler.js:156
runBatchedUpdates @ ReactUpdates.js:150
perform @ Transaction.js:143
perform @ Transaction.js:143
perform @ ReactUpdates.js:89
flushBatchedUpdates @ ReactUpdates.js:172
closeAll @ Transaction.js:209
perform @ Transaction.js:156
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
enqueueUpdate @ ReactUpdates.js:200
enqueueUpdate @ ReactUpdateQueue.js:24
enqueueSetState @ ReactUpdateQueue.js:218
ReactComponent.setState @ ReactBaseClasses.js:64
onStateChange @ connectAdvanced.js:205
notify @ Subscription.js:26
notifyNestedSubs @ Subscription.js:62
onStateChange @ connectAdvanced.js:202
notify @ Subscription.js:26
notifyNestedSubs @ Subscription.js:62
onStateChange @ connectAdvanced.js:202
dispatch @ createStore.js:173
(anonymous) @ store.js:40
(anonymous) @ index.js:14
dispatch @ applyMiddleware.js:35
callback @ content.js:431`

**Comment by tzarebczan** [comment]
Anything change recently? Have you tried clearing cache in the settings screen? Can you also check the daemon (lbrynet) version in Help.

**Comment by oakey22** [comment]
the only thing i changed was upgrading to the new app.

App | 0.15.1
Daemon (lbrynet)  |  0.15.2
Platform | Linux (Linux-4.4.0-93-generic-x86_64-with-Ubuntu-16.04-xenial)

**Comment by oakey22** [comment]
Tried 0.15.0 and it is the same, i am now back on 0.15.1

I used the lbrynet-cli channel_list_mine and it displays all my channel names.

**Comment by tzarebczan** [comment]
And you've tried clearing the cache too? Can you provide your latest lbrynet.log file to see if there are any clues there.

**Comment by oakey22** [comment]
I tried clearing the cache, the log is added to this post, i also edited out my balance

**Comment by unclejed613** [comment]
I'm having a similar problem with 0.15.1.  When I try to publish, the channel drop down is all blacked out.  clearing the cache fixes it until the next time I publish, so I have to clear the cache and restart the app every time I want to publish.  I'm running the app on Ubuntu linux.

**Comment by tzarebczan** [comment]
@unclejed613 I think your issue is a little different - probably more rendering related. Are you using a VM or a regular desktop? If you open up developer tools ( Developer > Tools from the top menu bar), do you see any errors these while clicking the drop down?

**Comment by tzarebczan** [comment]
@oakey22 - I do see something related to UPNP failures in your log, but it most likely wouldn't cause this issue. Do you have UPNP enabled on your router? It's trying to use port 4444 by default. It may cause some streaming issues if it fails. 

Otherwise, same question to you, are you using a VM or is this a regular desktop? I wonder if its somehow related to some graphical issues.

**Comment by btzr-io** [comment]
Related issues with dropdown render: 
https://github.com/electron/electron/issues/7289
https://github.com/electron/electron/issues/4322
https://github.com/avocode/avocode/issues/1158

**Comment by oakey22** [comment]
I have checked the router and UPNP is enabled, i am also running this on linux desktop. 

I dont get a black box, i just get nothing other than Anonymous and New channel, neither do anything and i get the updating channels ... all the time underneath

**Comment by tzarebczan** [comment]
@oakey22 - does this still happen in v16?

**Comment by oakey22** [comment]
Still happening in v16RC7 for me

**Comment by tzarebczan** [comment]
Rouse is also having the same issue, I'll try to troubleshoot with him.

**Comment by tzarebczan** [comment]
@kauffj below is the line it's happening on > 35209 in bundle.js

```
        this.props.channels.map(function (_ref) {
          var name = _ref.name;
          return _react2.default.createElement(
            "option",
            { key: name, value: name },
            name
          );
        }),
        _react2.default.createElement(
          "option",
          { key: "new", value: "new" },
          __("New channel...")
        )
      ));
```

**Comment by oakey22** [comment]
Can confirm that this is working now with the above change
