### ISSUE TITLE
Date is Americanised

### ISSUE THREAD

**Issue by oakey22** [lbryio/lbry-app#546]
### Steps to reproduce
1. Click on any thumbnail on the main screen
2.look at the "Published on" date

### Expected behaviour
I  am from the UK and we have our date format DD-MM-YYYY so i would expect to have an option to specify where you are from or choose the format and this alters. Maybe have this in the settings.

### Actual behaviour
Date is MM-DD-YYYY, as seen in the picture this can be misleading and confusing for days below the 13th. 

## Anything Else

App | 0.15.1
-- | --
0.15.2
3.1.6
gfugfqpsfpsewz@divermail.com
 
Linux (Linux-4.4.0-93-generic-x86_64-with-Ubuntu-16.04-xenial)

## Screenshots
https://spee.ch/8afeb8a00bf3c13d0e63e660d6028e49728a4a27/lbry-date.jpg

**Comment by btzr-io** [comment]
Looks like a simple fix -> `date.toLocaleString('en-GB')`  
The problem would be to implement a simple ui / ux ^

**Comment by btzr-io** [comment]
> i would expect to have an option to specify where you are from or choose the format and this alters. Maybe have this in the settings.
Looks like just needs to pass this ->  `window.navigator.language`

**Comment by btzr-io** [comment]
@oakey22 can you open the Developer Tools: ` ctrl + shift + I ` 
and run this in the console? -> `app.i18n.getLocale()`

**Comment by oakey22** [comment]
I get this when ran in console

```
app.i18n.getLocale()
"en"
```

**Comment by oakey22** [comment]
and 

`window.navigator.language
"en-US"`

**Comment by btzr-io** [comment]
Oh yeah,there is only on language supported at the moment -> `en-US` :stuck_out_tongue: 
until that's fixed I guess this is the only option for now:
> Have an option to specify where you are from or choose the format and this alters.

**Comment by btzr-io** [comment]
Alternative solution just change the format to -> `May 13 2017, 12:00 AM`

**Comment by liamcardenas** [comment]
@kauffj do you know if https://github.com/lbryio/lbry-app/issues/538 will fix this? if so, I will close this one.

**Comment by kauffj** [comment]
@liamcardenas it will not. `<DateTime>` would need to be internationalized. It is, however, basically already set up to do so.

**Comment by miikkatu** [comment]
Is this fixed already, maybe as a side effect of some other change? For me, the date is shown like this: "Published on January 25, 2018". Not like in the screenshot of this issue.

**Comment by tzarebczan** [comment]
@oakey22 can you share an updated screenshot how it looks in the latest version. I tried changing my regional settings but it still shows "February x, 2018" - wouldn't that be correct for all region settings?

**Comment by miikkatu** [comment]
0.20.0

<img width="478" alt="date" src="https://user-images.githubusercontent.com/16205520/35823774-5bcadefc-0ab9-11e8-86b4-98c82c52aa41.png">

**Comment by oakey22** [comment]
Working for me now, thatnks guys

says December 17th 2017

**Comment by tzarebczan** [comment]
Going to close this, thanks for confirming @oakey22 !

@liamcardenas, please open a new issue for the <DateTime> internationalization convo if you feel its warranted.
