### ISSUE TITLE
Channel not re-populated when editing existing claim

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#553]
## The Issue
When editing/re-publishing existing content using the "Use data from my existing claim" option on the Publish page, the channel from the previous publish is not populated in the dropdown. The result also creates some inconsistencies in the Publishes page (will be logged in a separate issue as this is a valid scenario). 

### Steps to reproduce
1. Publish content to a channel, wait for confirmation
2. Edit content by going back to Publish, typing in the URL and clicking "Use data from my existing claim" option
3. Notice that the channel is not updated

### Expected behaviour
Channel should be populated if available

### Actual behaviour
Channel is not populated and not included in the publish

## System Configuration

 

- LBRY Daemon version: 0.15.2
- LBRY App version: 0.15.1
- LBRY Installation ID:
- Operating system: Windows

**Comment by btzr-io** [comment]
@tzarebczan this is fixed in `v16`, 
do we need a temp fix for `15.x.x` ?

**Comment by tzarebczan** [comment]
I think that's a question for @kauffj, but think we are going with a v16 release next.

**Comment by kauffj** [comment]
Confirmed, this is fixed.
