### ISSUE TITLE
App updates for new search service

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-app#557]
The new search service will return channel names and offer type based filtering. The app must be updated to accommodate these features (and possible signature changes).

**Comment by filipnyquist** [comment]
The current apiDoc is located at: https://lbryio.github.io/lighthouse/

**Comment by kauffj** [comment]
Nice docs!

**Comment by lyoshenka** [comment]
Search server is live at lighthouse.lbry.io:50005

**Comment by kauffj** [comment]
@lyoshenka is there any reason we put it on a weird port?

**Comment by lyoshenka** [comment]
Ports above 1024 dont require root to bind. Plus that's the port lighthouse
was on before.
