### ISSUE TITLE
Launching LBRY results in Javascript error occurs if LBRY is hung in background

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#560]
## The Issue
Originally stemming from https://github.com/lbryio/lbry-app/issues/353#issuecomment-328855723, we still see this error come up in help requests. It seems to happen when LBRY.exe gets stuck running in the background and then it is started up again by the user.   I've seen instances where I've closed LBRY but the processes don't end, just can't reproduce reliably. 

I guess the main concern would be to find out why it is getting stuck in the first place (harder), but maybe we can error more gracefully and tell the user what to do (possible?). 

I can get this to reproduce on Windows if I run the app, and while it's loading (in the first second or two), close it down. And then when I try to re-open LBRY, this is the error I get:
![destroyed](https://user-images.githubusercontent.com/8120721/30400909-61a5501c-98a6-11e7-8343-a8106137e728.JPG)

### Steps to reproduce
1. Close LBRY (but it doesn't shut down properly)
2. Run LBRY again
3. error

### Expected behaviour
If LBRY.exe is already running, try to kill it or warn user to. 

### Actual behaviour
Hard javascript error

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
Possibly related: https://github.com/lbryio/lbry/issues/860

I think one of two things is happening here:
- App launches, sees a running daemon, choose not to launch a daemon, but that daemon is still scheduled to close and closes
- App launches, launches daemon, daemon fails to start due to lbry#860

**Comment by kauffj** [comment]
@tzarebczan can you reliably make this happen?

**Comment by tzarebczan** [comment]
@kauffj yea, using the quickly close LBRY when it's starting trick. That gets lbry.exe stuck in the background and then the error occurs when you start it again.

I'm sure there are other reasons why Lbry.exe could get stuck in the background (just happened to me earlier when upgrading.... Got stuck after closing it) but these are more difficult to pinpoint.

**Comment by liamcardenas** [comment]
We will tip LBC for anyone who figures out what's going on here. Bigger tips if you fix the problem, obviously.

**Comment by tzarebczan** [comment]
I'll see if I can still reproduce this now that we have minimize to tray.

**Comment by lyoshenka** [comment]
Next step: Tom's gonna repro this

**Comment by tzarebczan** [comment]
Can't produce this anymore after @IGassmann 's refactoring changes. Closing.
