### ISSUE TITLE
Exclude blocked content from app

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-app#565]
List of blocked outpoints is at https://api.lbry.io/file/list_blocked

**Comment by liamcardenas** [comment]
@lyoshenka can we get some dummy data in the list?

**Comment by lyoshenka** [comment]
You can install the api locally, then pass an env var to the app to tell it where to find the api (see lbryio.js line 13). Then you can make the api do whatever you want, or put whatever dummy data in the db you want. API setup instructions are in the internal apis readme.

**Comment by tzarebczan** [comment]
@lyoshenka would we need to block this separately from a search/trending perspective? Seems like trending would need to take it into account separately so it can still show the top 10 trending without blocked content.  Let me know if I should open an issue.  

Also, how would this work from a hosting perspective? Shouldn't LBRY nodes (at least ones running our official software) have to abide by this blacklist as well?  What should happen on the daemon side if a file is blocked?

**Comment by finer9** [comment]
As per convo with @kauffj we need to prioritize getting blocks in the app

**Comment by tzarebczan** [comment]
@liamcardenas when you start working on this, ping @kauffj as he would like to provide input on the language used in the app when content is blocked.

**Comment by tzarebczan** [comment]
The goal is to release this change with the current app release (and not the redesign) this week

To be clear, if blocked content shows up on a tile on the homepage (i.e. in community section), we would still see the tile/thumbnail, but the show page (when clicking on it) would have the new blocked component.  Would we want to block the thumbnail as we do for NSFW as well? 

@kauffj can you work on the explanation in the meantime?

**Comment by kauffj** [comment]
The most immediate need is to block show pages. I think we should likely make other changes, but the changes to the show page should be shipped as soon as they are releasable.
