### ISSUE TITLE
Seeing app hang during startup on "Fetching Content..."

### ISSUE THREAD

**Issue by eriknelson** [lbryio/lbry-app#572]
## The Issue
Seeing the app during startup on "Fetching Content...".

### Steps to reproduce
1. Built from source (tag v0.15.1), installed libsecret/libsecret-devel & keytar
2. Launch app
3. See it hang

### Expected behaviour
App should start, or ideally display an error message with missing dependency.

### Actual behaviour
App does not start, sits at "Fetching Content..."

## System Configuration

- LBRY Daemon version: 0.15.2
- LBRY App version: 0.15.1
- LBRY Installation ID: 5UUaNbdMGcZ1w1H9cYoLd68K6X2E2ZLoYngKzm3QSWZ3nvpDfhRNic7bnqNYdm6fCY
- Operating system: Linux (Linux-4.12.12-300.fc26.x86_64-x86_64-with-fedora-26-Twenty_Six)

## Anything Else
Seeing these logs in stdout after launching the app from the cli:

```
** Message: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secre
ts was not provided by any .service files                  
(node:23772) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: The name org.freed
esktop.secrets was not provided by any .service files      
(node:23772) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that ar
e not handled will terminate the Node.js process with a non-zero exit code.                                            
** Message: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secre
ts was not provided by any .service files                  
(node:23772) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: The name org.freed
esktop.secrets was not provided by any .service files      
** Message: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secre
ts was not provided by any .service files                  
(node:23772) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: The name org.freed
esktop.secrets was not provided by any .service files      
2017-09-17 09:10:05,036 INFO     lbrynet.daemon.Daemon:1061: Get version info: {"lbrynet_version": "0.15.2", "platform"
: "Linux-4.12.12-300.fc26.x86_64-x86_64-with-fedora-26-Twenty_Six", "os_system": "Linux", "python_version": "2.7.12", "
os_release": "4.12.12-300.fc26.x86_64", "lbryum_version": "3.1.6", "ip": "Could not determine IP", "lbryschema_version"
: "0.0.10", "processor": "x86_64", "build": "release"}     
** Message: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secre
ts was not provided by any .service files                  
(node:23772) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: The name org.freed
esktop.secrets was not provided by any .service files  
```
I'm running i3 on this machine, and had no problems starting the app on another machine running a vanilla gnome desktop. I'm guessing the i3 machine is missing some kind of secret management package / daemon that I otherwise would have on a Gnome desktop, but I'm unsure what that might be. Happy to provide additional details if needed.

**Comment by tzarebczan** [comment]
It's most likely the gnome-keyring. Up to you if you want to try installing. 

Already reported in this https://github.com/lbryio/lbry-app/issues/422 and the issue mentioned there.

**Comment by eriknelson** [comment]
@tzarebczan thanks, that was it. For Fedora with my setup, I needed to install `gnome-keyring` and then configure my DM (lightdm) to start and unlock gnome-keyring using PAM, which required an additional package (`gnome-keyring-pam`).

Would it make sense to add some kind of validation to the app that confirms `org.freedesktop.secrets` is available, and to have an explicit error notification? I bet there are enough users who don't have this configured that it might be worth it.

**Comment by tzarebczan** [comment]
Glad you got it up and running, sorry for your trouble. 

We have the issue logged in github, the real solution would be to use some kind of token generation that works across all Linux platforms. You shouldn't have to install some gnome software when it doesn't even apply to your system.

Send us an email to help@lbry.io to claim a little tip for getting this far and for the suggestion.

**Comment by eriknelson** [comment]
> You shouldn't have to install some gnome software when it doesn't even apply to your system.

+1, a dependency on a particular DE setup doesn't make a lot of sense. #386 is the tracking issue? I might be willing to take a stab at it if I get some time.

**Comment by eriknelson** [comment]
Going to close this as a duplicate.

**Comment by tzarebczan** [comment]
Yes, #386 would be the one to use.

Thanks!
