### ISSUE TITLE
Allow claims to be revoked from TransactionList

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-app#581]
As a user, I may want to use TransactionList to see past supports, publishes, claims, etc. It would be convenient to have the ability to reclaim credits from this screen.

**Comment by hackrush01** [comment]
I will get to this once I figure the rest of abandon related stuff. One of them is directly related to abandoning claims(with supports and tips).

**Comment by tzarebczan** [comment]
Good progress so far, but I'm sure there will be some confusion going forward. When an action is taken, the icon disappears and a new transaction is created (which is not apparent immediately). 

Other areas of possible confusion:
1) users won't understand why they can take action in some cases but not others - i.e. a publish and then an update - the publish has no action available, but the update does. 

2) Previously revoked/claimed items won't show an action - the only history is the resulting transaction. Maybe some indication an action was already taken?

**Comment by kauffj** [comment]
@hackrush01 shouldn't this make publishes revokeable?

**Comment by tzarebczan** [comment]
It does... Maybe you misunderstood what I was saying? But if you publish and then update, the update is now revokeable but the publish isn't (since the bid for the claim is now at a different address)

**Comment by kauffj** [comment]
Yep, nm.

**Comment by lyoshenka** [comment]
Merged
