### ISSUE TITLE
Display Date of Publish for content

### ISSUE THREAD

**Issue by Rob-pw** [lbryio/lbry-app#59]
"regarding data displayed with content, date of publish would be quite useful. F.ex you are watching an episode on crypto currencies and hear some news ... you don't know how old they are, which is the key info in that case" - thorpe

**Comment by kauffj** [comment]
This would require writing a function to convert from the claim `height` attribute to a date and time.

**Comment by btzr-io** [comment]
Would be nice to use a `relative-time` as format for the date / time 
https://github.com/rxaviers/relative-time
