### ISSUE TITLE
Offer thumbnailing via spee.ch

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-app#592]
Allow a user to select an image and upload it to spee.ch, so that they do not need to enter a URL for the thumbnail.

See [spee.ch repo](https://github.com/lbryio/spee.ch) for spee.ch API details.

**Comment by daovist** [comment]
I think I can solve this now that I am more familiar with Redux. I checked it out and the file structure is pre /src/renderer changes and I'm not sure how to move everything. I know the relevant code well enough I could just make a new branch.

**Comment by IGassmann** [comment]
Awesome! Feel free to just make a new branch. I'm assigning the issue to you. Thanks for your help!

**Comment by jamesbiller** [comment]
@kauffj @daovist 

I had a couple of content creators tell me that they were confused about how to upload an image.

Having a button that takes them to spee.ch (or eventually spee.ch integration) would be fantastic. 

Something like:

 1. "Upload your image here to create a URL" > Spee.ch Button (Do we want to include Imgur button when spee.ch is down?)

2. "Copy & Paste the URL here to embed the image" > 'Thumbnail' upload line

Copying and pasting URLs isn't something that most people are used to doing (I was just made aware of imgur only a few months ago).

We need to make it as easy as possible for people to attach their cover image to their file.

**Comment by tzarebczan** [comment]
@jamesbiller this is already a work in progress on https://github.com/lbryio/lbry-app/pull/1248 - they will be able to upload to spee.ch directly from the app. Does not include an imgur fallback option - not sure that's something we want to have.

**Comment by kauffj** [comment]
I definitely want to get #1248 finished and merged. And even with #1248 both options will exist, spee.ch will never be mandatory to use.

However, we are likely to add the ability to use spee.ch even if we're not at 99% reliability. Part of the reason we push/dogfood spee.ch is to help get it to 100%.

**Comment by tzarebczan** [comment]
Closed via https://github.com/lbryio/lbry-app/pull/1248
