### ISSUE TITLE
Transaction history doesn't match balance after attempting to claim a reward

### ISSUE THREAD

**Issue by ChronosCrypto** [lbryio/lbry-app#593]
### Steps to reproduce
1. Create new account
2. Claim "Go for a Stream" reward
3. Be told that the requirements for the reward haven't been met yet
4. View a video to qualify for reward
5. Restart application
6. Claim reward
7. Be told that the reward has already been claimed
8. Notice +2 LBC in transaction history, and the reward is gone, but balance is not increased.

### Expected behaviour
Reward should be claimable on step 6. Transaction history should match balance.

### Actual behaviour
Transaction history shows the +2 LBC transaction, but the balance does not reflect it, and the reward disappears.

## System Configuration

See screenshot.

## Anything Else
The account in the screenshot has exactly 5 transactions. The balance is not correct based on the transaction history, as a result of this bug.

## Screenshots
![balance and txn history](https://user-images.githubusercontent.com/7016946/30615309-62a26076-9d43-11e7-8bce-05bf1629b94c.PNG)
![version](https://user-images.githubusercontent.com/7016946/30615368-96069fea-9d43-11e7-8219-4d09efe4ed49.PNG)

**Comment by tzarebczan** [comment]
We are working on improving the wallet transaction list details. Your missing LBC are most likely being reserved in the channel or claims you created (the two negative tx which show the fee). The next version will show the amounts as well.
Check out lbry.io/faq/how-to-publish for more publishing details.
