### ISSUE TITLE
Inconsistencies in the Txn list.

### ISSUE THREAD

**Issue by hackrush01** [lbryio/lbry-app#594]
Two issues:

1. All tips are shown as negative amounts, same with supports. Whereas these should be positive, or negative depending on where is it accessed from(-ve for sender, +ve for receiver).

2. All transactions which are basically dust(fee only txns) are also shown in the UI.

What's causing them

1. Not all amount can be assumed to be negative
https://github.com/lbryio/lbry-app/blob/master/ui/js/selectors/wallet.js#L58

2. It should be `tx.value` instead of `tx.amount`
https://github.com/lbryio/lbry-app/blob/master/ui/js/selectors/wallet.js#L24

_Disclaimer: Preliminary diagnosis, conducted at 3 AM, subject to market risks._

**Comment by tzarebczan** [comment]
Thanks @hackrush01 . Can confirm 1 needs to be fixed. 

For #2, the only type of TX that I can think (which would cause a problem at the moment) where tx fee = amount (or at least how its shown now) is a claim abandon. I think we need to add a new category for Abandoned Claims. The amount should show the LBC amount going back into the wallet, along with the publish fee as the fee.

**Comment by tzarebczan** [comment]
First one is fixed in latest RC, 2nd one still needs to be looked at. I'll open a separate ticket for the abandon scenario.

**Comment by kauffj** [comment]
@hackrush01 see https://github.com/lbryio/lbry-app/blob/master/ui/js/selectors/wallet.js#L24

They're supposed to be filtered there.
