### ISSUE TITLE
Ensure consistent ratio for thumbnails

### ISSUE THREAD

**Issue by MSFTserver** [lbryio/lbry-app#595]
**Ticket addendum**. The proper solution for this ticket is likely not to expand the images, but to keep the ratio used consistent (or at least ensure all the ratios used look good).

 

## The Issue
thumbnail sizes in browsing section displays them as squares but doesnt properly resize the thumbnail and cuts off sides of the images
### Steps to reproduce
1. browse any videos in the search bar
2. notice some videos thumbnails are cut off
3. go to link thumbnails are displayed normally

### Expected behaviour
Tell us what should happen
thumbnails to auto resize to squares or change them to rectangles
### Actual behaviour
Tell us what happens instead
thumbnails just get cut off and it looks horrible imo

## System Configuration

 

- LBRY Daemon version: 0.15.2
- LBRY App version: 0.15.1
- LBRY Installation ID: 4xUNfNEDfK5irh7vPgMgvBUoxjAosAmJK4m5n5idPiw6hMGmj8feMYKWWvcfAokPM8
- Operating system: Windows (Windows-2012ServerR2-6.3.9600)

### Before
![image](https://user-images.githubusercontent.com/18357967/30652990-b3cd599c-9dde-11e7-878b-f03e84370ac6.png)

### After
![image](https://user-images.githubusercontent.com/18357967/30653462-fb5da9dc-9ddf-11e7-8bb5-e4d53cff2f8d.png)

**Comment by btzr-io** [comment]
@MSFTserver I'll add this in `redesign` todo list

**Comment by kauffj** [comment]
@btzr-io see amendment at top

**Comment by seanyesmunt** [comment]
This will be fixed with the redesign
