### ISSUE TITLE
Price not repopulated during edit of claim

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#599]
## The Issue
When editing a claim that had a price, the price is not repopulated into the Publish screen. This happens on both the Publish > Edit existing claim entry and the Edit Claim button from the claim page.  This happens for both LBC and USD prices. 

### Steps to reproduce
1. Edit content that had a price set via Edit Claim button or Publish screen
2. Notice that the price is not repopulated

### Expected behaviour
Price should populate from existing claim

### Actual behaviour
Price is set to free 

## System Configuration

 

- LBRY Daemon version: 0.16.1
- LBRY App version: 0.16
- LBRY Installation ID:
- Operating system: Windows/Linux

**Comment by btzr-io** [comment]
@tzarebczan so this was working before?

**Comment by tzarebczan** [comment]
It was broken in v14 and 15 too. No one ever caught it haha.

**Comment by btzr-io** [comment]
All my published content it's free content :stuck_out_tongue:

**Comment by tzarebczan** [comment]
This is fixed in the redesign.
