### ISSUE TITLE
Cannot edit claim 2nd time around via Edit Claim button

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#600]
## The Issue
The Edit Claim button doesn't seem to re-populate any claim data when trying to edit a claim that was recently edited.  Developer>Reload or clearing the cache don't help, need to restart the app again to be able to edit via the button. You are able to edit via the Publish screen after typing the URL > Copy existing claim data. 

Note- after the first edit, updated claim info is not shown on the claim page until the app is reloaded (via Developer Reload) - this issue is waiting on https://github.com/lbryio/lbry-app/issues/392 

### Steps to reproduce
1. Edit an existing claim, wait for blockchain confirmation
2. Try to edit the claim again using the Edit claim button
3. It goes to Publish page, but no data is populated

### Expected behaviour
Should be able to edit the claim

### Actual behaviour
Tell us what happens instead

## System Configuration

 

- LBRY Daemon version: 0.16.1
- LBRY App version: 0.16.0
- LBRY Installation ID:
- Operating system: Windows/Linux

**Comment by btzr-io** [comment]
@tzarebczan I can't recreate this in last master, can you confirm this ?

**Comment by btzr-io** [comment]
> Never mind, after the third edit I was able to recreate this issue

**Comment by tzarebczan** [comment]
Per @btzr-io, if it does work and you get it to edit a 2nd time, it shows old claim data which in part may be related to https://github.com/lbryio/lbry-app/issues/392.  The real question is why is fileinfo is blank after an update sometimes. I'll see if I can reproduce with the debugging info. 

Some notes from Slack chat: 

not that simple, I found the main issue which is also causing other issues...
[12:16] 
 ```Object
fileInfo : null
outpoint: "024839f1be1f118de633361e894faf1cfff25d507160f58023bbdb7df8644592:0"
Object
type : "FETCH_FILE_INFO_COMPLETED"
```
[12:17] 
to edit a claim you need to pass `fileInfo.claimId`
[12:17] 
but as you can see is returning null after the `re-publish` :confused:
[12:18] 
this also prevents me to remove or unclaim it

https://github.com/lbryio/lbry-app/blob/master/ui/js/actions/file_info.js#L44
btzr [6 days ago] 
did some more deep debugging ^^
btzr [6 days ago] 
it fails when you search for a `file_list` and pass the `outpoint` of the updated claim

**Comment by tzarebczan** [comment]
This might be fixed after https://github.com/lbryio/lbry-app/issues/693 changes, will confirm.

**Comment by tzarebczan** [comment]
This is no longer an issue after v19 daemon.
