### ISSUE TITLE
UI glitch after accessing a video without enough credits

### ISSUE THREAD

**Issue by mirgee** [lbryio/lbry-app#605]
## The Issue
A UI glitch (see screenshot below) appears after trying to play a searched video without enough credits.

### Steps to reproduce
1. Make sure you don't have much credits
2. Search for a video
2. Click on a search result you don't have enough credits for
3. Try to play the video
3. Click on Not now

### Expected behaviour
Page of the video, like this:
![screenshot from 2017-09-22 10-28-29](https://user-images.githubusercontent.com/11699479/30745707-8863e6f2-9fa7-11e7-96ac-e388636afbb1.png)

### Actual behaviour
Black dot, like this:
![screenshot from 2017-09-22 10-26-10](https://user-images.githubusercontent.com/11699479/30746896-b1bc9716-9fab-11e7-8c0c-bdbac573227d.png)

## System Configuration
![screenshot from 2017-09-22 15-03-37](https://user-images.githubusercontent.com/11699479/30746924-c3127e40-9fab-11e7-9ec9-39cd7cbbd956.png)

{
  "build": "dev",
  "installation_id": "6QapiUUrkTfiks6jiQnecv8pXixxm1LncbgGB32x6nXpQ1aipjikPboVJM4UxsXruR",
  "lbrynet_version": "0.16.1-2-g875d512",
  "lbryschema_version": "0.0.11rc1",
  "lbryum_version": "3.1.7rc5",
  "os_release": "4.10.0-35-generic",
  "os_system": "Linux",
  "platform": "Linux-4.10.0-35-generic-x86_64-with-Ubuntu-16.04-xenial",
  "processor": "x86_64",
  "python_version": "2.7.12"
}

## Anything Else
This doesn't happen to a video accessed or accessible from feature page, only to other videos found through search.

**Comment by tzarebczan** [comment]
So the video spins and the play button disappears? I'll try to reproduce later. 

Anything in the console or network logs?

**Comment by mirgee** [comment]
@tzarebczan The screenshot didn't upload for some reason, hope it's better now. Spinning and play button disappearing is what happens on videos through featured. This is probably intended and acceptable. The actual behavior after search is not.

**Comment by tzarebczan** [comment]
@btzr-io thanks for looking at this. Did you get it to stop spinning in the case of not enough funds too?

**Comment by btzr-io** [comment]
@tzarebczan nope, not a css bug...

**Comment by btzr-io** [comment]
@mirgee could you provide the link of the video ? 
you can also test this branch:  https://github.com/lbryio/lbry-app/tree/fix-play

**Comment by btzr-io** [comment]
@tzarebczan I'm not able to recreate the background glitch, but I was able to stop the spinning  ^^

**Comment by MSFTserver** [comment]
@btzr-io i noticed this also happens when videos fail to download you could some videos you know wont work

**Comment by btzr-io** [comment]
@MSFTserver any example ( link ) to test it ?

**Comment by btzr-io** [comment]
@tzarebczan the `UI` glitch isn't limited to videos and looks like is a different issue...

**Comment by tzarebczan** [comment]
@mirgee - please take a look at https://lbry.io/faq/tips :)
