### ISSUE TITLE
ShapeShift integration into LBRY app

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#609]
## The Issue
Since LBRY is a blockchain based project, lots of LBRY users are cryptocurrency enthusiasts who could benefit from having the ability to acquire more LBRY Credits through the LBRY app using Shap[eshift to convert from many different other cryptocurrencies. 

Other possibly helpful projects:
https://github.com/ExodusMovement/shapeshift.io
https://github.com/OpenBazaar/OpenBazaar-Client/pull/1844
https://github.com/abitfan/shapeshiftio
https://github.com/hunterlong/shapeshift
https://github.com/Achse/php-shapeshift-io-api

Shapeshift API:
https://info.shapeshift.io/

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by oakey22** [comment]
Oh I do love this idea, would be fantastic to have this

**Comment by seanyesmunt** [comment]
I'll take this one up.
