### ISSUE TITLE
Unresponsive header

### ISSUE THREAD

**Issue by btzr-io** [lbryio/lbry-app#613]
## The Issue
As pointed out by some users at slack:

![image](https://user-images.githubusercontent.com/14793624/30791119-a83e7a38-a16d-11e7-8a4a-a7284c642c2f.png)
> When it's shrunk the text pops out and you get, well, that

### Steps to reproduce
1. Resize window to `min-width`.

### Expected behaviour
The header should be responsive and don't have a weird behavior 
when you resize the window.

**Comment by btzr-io** [comment]
Fixed ^

**Comment by tzarebczan** [comment]
Thanks @btzr-io !
