### ISSUE TITLE
Published files Sort by Title not working correctly

### ISSUE THREAD

**Issue by jsigwart** [lbryio/lbry-app#614]
## The Issue
Published files list correctly by Date, but not by Title

### Expected behavior
When I go into my Published files, I should be able to view the files alphabetically when I select the Title option.

### Actual behaviour
Please see my screen shot. When I display my videos by Title, they are not in alphabetical order. I'm not sure how they're being displayed. There are two videos that start with "Betty" and then the video that starts with "A Little" is displayed between them. I thought maybe it was skipping the A, but even so, it still isn't in any kind of alphabetical order.

## System Configuration

 

- LBRY Daemon version: 0.16.1
- LBRY App version: App | 0.16.0
- LBRY Installation ID: 5eFxsAfhBFTKA5byNFVkGL5Lu5owWzQFthzKjRkxN2iUzWh2XNKLJAiv82mxAcq3AU
- Operating system: Mac OS X 15.6.0 

## Screenshots

<img width="926" alt="screen shot 2017-09-24 at 10 07 38 pm" src="https://user-images.githubusercontent.com/1363664/30793263-85b20cc0-a175-11e7-9a2c-145245d12d7e.png">

**Comment by kauffj** [comment]
See https://github.com/lbryio/lbry-app/pull/661#issuecomment-336563648
