### ISSUE TITLE
Free download gets modal popup saying "This will purchase X for free credits"

### ISSUE THREAD

**Issue by jsigwart** [lbryio/lbry-app#615]
## The Issue
Purchase modal popup appears for free items asking if you want to buy the item for free credits.

### Steps to reproduce
1. Click to download a free video
2. Watch for popup

### Expected behaviour
Tell us what should happen
I should not be asked if I want to spend nothing for downloading free content.

### Actual behaviour
Tell us what happens instead
Purchase modal popup appears for free items asking if you want to buy the item for free credits.

## System Configuration

 

- LBRY Daemon version: 0.16.1
- LBRY App version: App | 0.16.0
- LBRY Installation ID: 5eFxsAfhBFTKA5byNFVkGL5Lu5owWzQFthzKjRkxN2iUzWh2XNKLJAiv82mxAcq3AU
- Operating system: Mac OS X 15.6.0 

## Screenshots

<img width="1224" alt="screen shot 2017-09-24 at 10 35 36 pm" src="https://user-images.githubusercontent.com/1363664/30793828-4d2c6ff4-a179-11e7-93d9-3c976688591d.png">

**Comment by tzarebczan** [comment]
@jsigwart are you able to reproduce this consistently? Does it happen on all free videos? It's not happening to me on Windows. WIll try on Linux in a bit.  What is your max purchase price setting in the Settings area?

**Comment by jsigwart** [comment]
Yes, this happens with every item I try to download, free or paid. Screen grab of my settings attached.
<img width="819" alt="screen shot 2017-09-26 at 7 52 38 am" src="https://user-images.githubusercontent.com/1363664/30867079-cbc5229a-a28f-11e7-8f75-c2b6407011b5.png">

**Comment by jsigwart** [comment]
I tried turning on the Single-click purchasing setting, and setting it to the minimum 0.1 LBC and cleared the application cache. I still am getting the warnings to purchase all items including free ones.

**Comment by tzarebczan** [comment]
Ah, this is probably a regressive issue from https://github.com/lbryio/lbry-app/pull/541 / https://github.com/lbryio/lbry-app/issues/497 

Didn't realize you were running from Master. 

paging @alexliebowitz
