### ISSUE TITLE
Kill npm and other build clean up

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-app#616]
2 package managers is pretty dumb.

In addition, our set up steps require manual installation of modules that ought to be installable via configuration files.

There was a time when the setup process was:

- Install package manager
- Checkout project
- Run `./build.sh`

We ought to get back to this standard.

**Comment by lyoshenka** [comment]
npm is only used for `npm rebuild node-sass` ([1](https://github.com/lbryio/lbry-app/blob/dafe9bb87d6dc3f2438aca22f8a47643dee8fc4f/build/build.sh#L69), [2](https://github.com/lbryio/lbry-app/blob/ce0dd5ae62e5daab09523aa49831ca707d521c34/build/build.ps1#L24)) and for [installing yarn on windows](https://github.com/lbryio/lbry-app/blob/ce0dd5ae62e5daab09523aa49831ca707d521c34/build/build.ps1#L7). If we can replace both and the build script still works, we will have killed npm.

Yarn does not support `rebuild` yet. See https://github.com/yarnpkg/yarn/issues/756
