### ISSUE TITLE
Setting Max Purchase Price to blank (and then No Limit) produces errors

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#624]
## The Issue
If you set the Max Purchase Price in Settings to blank, you get this error:  `float argument required, not NoneType` (LBC setting)/  `float argument required, not unicode `(USD setting) when purchasing content. 

If you leave it blank and change the setting to No Limit, you still get the above errors.  

### Steps to reproduce
1. Blank out the Max Purchase Price in Settings
2. Try to purchase a video
3. Error
4. Set to no limit
5. Error

### Expected behaviour
LBRY app should not allow blank value, set blank to 0

### Actual behaviour
Not user-friendly behavior with the error messages

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
Just fixed, will be out in 0.16.1 shortly.
