### ISSUE TITLE
Editing Video Information requires new bid.

### ISSUE THREAD

**Issue by KamilPiekutowski** [lbryio/lbry-app#627]
### Steps to reproduce
1. Create and publish video.
2. Click on edit and change some data.
3. Check out the Terms box and click publish.

### Expected behaviour
If this has been published before and deposit paid, it should not attempt to charge
again every time the info is edited.

### Actual behaviour
It is trying to charge deposit bid again.

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system: Ubuntu 16.04 LTS

**Comment by MSFTserver** [comment]
if it doesn't charge you again you have no fee to send to the blockchain, after you set a new amount the old claim amount is returned to you

**Comment by tzarebczan** [comment]
Your old bid is returned and new one is added. You only really pay the tx fee. I have a ticket to fix how it shows in TX explorer.

**Comment by tzarebczan** [comment]
Lbry works by saving claims. In order to save or update the claim, a transaction must be performed on the blockchain.

**Comment by KamilPiekutowski** [comment]
Is there more readable version of bundle.js or I am looking at the wrong file?
I would like to see if I can add another line to the card__inner div.
