### ISSUE TITLE
Determine and communicate minimum Publish deposit

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#628]
## The Issue
This issue stems from https://github.com/lbryio/lbry-app/issues/604 / https://github.com/lbryio/lbry/issues/920.  A new form component was recently added which doesn't allow a bid less than 0.01 (0.16 release) and 0.1 (master).  

When you click publish, you don't get any feedback besides highlighting of the bid field (not easy to see sometimes). When you mouse over the LBC value for the bid, you see a tooltip that says - "Please enter a valid value...two nearest values are 0 and 0.01"

Steps here would be to:
1) Determine what the minimum LBC bid for publishing should be and clearly communicate that to users. This discussion is relevant for the minimum: https://github.com/lbryio/lbry/issues/768
2) App needs to notify users when their bid is invalid according to the minimum
3) Mention publishing fees on Publish page

### Steps to reproduce
1. Go to publish page
2. publish something but put deposit as .001
3. pressing publish just highlights the div but no error

### Expected behaviour
App should alert user that something is wrong with the bid

### Actual behaviour
App just highlights the bid field

## System Configuration

 

- LBRY Daemon version: 0.16.1
- LBRY App version: 0.16.0
- LBRY Installation ID:
- Operating system: Windows

**Comment by kauffj** [comment]
This is fixed. It still doesn't give the minimum as required by transaction fees, but this is variable and can't be known unless `lbry` adds an API call to provide it.
