### ISSUE TITLE
App fails to launch

### ISSUE THREAD

**Issue by Feanor78** [lbryio/lbry-app#629]
### Steps to reproduce
1. Start the app through the Windows 10 start menu
2.
3.

### Expected behaviour
The app should open

### Actual behaviour
The app doesn't open

## System Configuration

![image](https://user-images.githubusercontent.com/13907896/30926170-4d2a8e90-a382-11e7-8b6f-4b898517bce6.png)

![image](https://user-images.githubusercontent.com/13907896/30926185-54b6165c-a382-11e7-85da-35f1c4e51a9e.png)

**Comment by tzarebczan** [comment]
@Feanor78 - can you see if these steps help (for both Dlls): https://answers.microsoft.com/en-us/windows/forum/windows_10-files/nodedll-missing-error-on-loading-slack-on-windows/46de0309-d630-403f-90f8-fbe90952192d

Haven't seen this one yet.

**Comment by kauffj** [comment]
I'm closing this since there's nothing actionable a dev can do here. Please re-open if you have additional details, or if it happens again.

**Comment by tzarebczan** [comment]
I think Brinck got it fixed after a Windows Reinstall
