### ISSUE TITLE
Channel without claims shows "fetching content...", console error

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#636]
## The Issue
Going to a channel without any claims (lbry://@blankchanneltest) makes it seem like the app is trying to pull something back but can't.  The console produces an error:
```
Uncaught (in promise) TypeError: claims.forEach is not a function
    at reducers.(anonymous function) (webpack:///./js/reducers/claims.js?:149:12)
    at reducer (webpack:///./js/reducers/claims.js?:224:23)
    at combination (webpack:///./~/redux/es/combineReducers.js?:124:29)
    at batchingReducer (webpack:///./js/store.js?:108:16)
    at eval (webpack:///./~/redux-persist/es/autoRehydrate.js?:33:16)
    at dispatch (webpack:///./~/redux/es/createStore.js?:170:22)
    at eval (webpack:///./~/redux-logger/dist/redux-logger.js?:1:7760)
    at eval (webpack:///./js/store.js?:96:16)
    at eval (webpack:///./~/redux-thunk/lib/index.js?:14:16)
```

### Steps to reproduce
1. Open lbry://@blankchanneltest in LBRY
2. App shows "fetching content..."
3. Console will show error

### Expected behaviour
App should say that no content exists yet

### Actual behaviour
App looks like its fetching, but console errors

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by btzr-io** [comment]
@tzarebczan is this fixed on ->  `0.16.1rc1` ?

**Comment by btzr-io** [comment]
if not I'll send a PR ^

**Comment by kauffj** [comment]
It is not fixed.

Also, FYI, 0.16.1rc1 is a "draft", which means it is not public. You can only see it since you're a collaborator on this repo.

**Comment by btzr-io** [comment]
so my`PR` is not working ?

**Comment by tzarebczan** [comment]
@btzr-io I just tried on rc1, had same result as reported on this issue.

**Comment by btzr-io** [comment]
@tzarebczan yeah this is fixed in  `fix-empty-channels` (#638) ^

**Comment by btzr-io** [comment]
<img width=400 src="https://user-images.githubusercontent.com/14793624/31047157-95529248-a5c2-11e7-9e98-71a6ac5b2a04.gif" />

**Comment by kauffj** [comment]
Oops! My previous message was quite unclear. I meant it was not fixed in the RC.

AFAIK, your fix works. @tzarebczan you can test this in master if you like, or just wait for 0.17 rc.
