### ISSUE TITLE
Channel Subscriptions

### ISSUE THREAD

**Issue by Plasmmer** [lbryio/lbry-app#64]
The barebones version of this feature consist of the following changes:

- [ ] A button on channel and file pages that allows a user to subscribe and unsubscribe to a channel.
- [ ] User subscriptions are written and stored to local state (and optionally to api.lbry.io).
- [ ] The landing page is modified to indicate recent content from subscribed channels.

**Comment by btzr-io** [comment]
Same issue -> https://github.com/lbryio/lbry-app/issues/715
