### ISSUE TITLE
User request: support for shorter channel names

### ISSUE THREAD

**Issue by jsigwart** [lbryio/lbry-app#645]
## The Issue
Channel names need to be a minimum of five characters. Why can't we have shorter named channels?

### Steps to reproduce
1. Try to create a channel with fewer than five characters

### Expected behavior
User feedback: "My band name is three characters and that's what I want my channel to be! Why can't I do that?"

### Actual behavior
Channel name must be five or more characters, so folks wanting to create shorter channel names are out of luck.

**Comment by kauffj** [comment]
Thanks for filing this! This was actually fixed in `lbyschema` 2 months ago, but the check had not been dropped app side.
