### ISSUE TITLE
Drop all instances (3) of XMLHttpRequest for Fetch API

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-app#650]
The [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) is cleaner, simpler and supports promises.

**Comment by thujeevan** [comment]
Wish to work on this. What are the things to be considered while implementing this?

**Comment by sovanna** [comment]
@thujeevan did you worked on something yet?

**Comment by kauffj** [comment]
If you just search the `js` folder for `XMLHttpRequest` you will find 3 places it is used. These could be re-written to use `fetch` and promises, resulting in cleaner and more standardized code.

**Comment by thujeevan** [comment]
@kauffj I understand what to be done. Wanted to know anything specifically considered. Was having trouble in building step initially.

@sovanna Working on it.

**Comment by sovanna** [comment]
aaa, I worked on it yesterday. I'm going to stop and let you continue.
If it can help, here my work:
- [commit on lybrio.js](https://github.com/sovanna/lbry-app/commit/b8a472e262abc246d0a62c9c5a85fd180cedb600)
- [commit on settings.js](https://github.com/sovanna/lbry-app/commit/34c78bd55c284700222199ae1a591d7d5fb1747b)

miss the last place in jsonrpc.js

**Comment by thujeevan** [comment]
@kauffj something wrong with the fetch implementation in the PR. It doesn't seem to work. Not sure what am I missing. Sadly, I couldn't find any tests also. Any method to debug this code?

@sovanna Would you mind to CR and let me know any issues?

**Comment by kauffj** [comment]
@thujeevan All of them don't work? What do you see in the console? To debug I would suggest using combination of debug toolbar and code modifications or logging statements. With a proper dev setup, you should be able to change code and CTRL+R in the app for very tight feedback.

Also, I do not think this code should require additional dependencies (which I noticed in your PR).

**Comment by thujeevan** [comment]
@kauffj Thanks for the info, got it to work. Please have a look at the PR. Drop the unnecessary deps.
