### ISSUE TITLE
Further improvements to FileSelector

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-app#656]
- [ ] The new file chooser is mildly confusing without a `readonly` styling
- [ ] The width of the input cuts off the path when there is space to render

**Comment by tzarebczan** [comment]
This affects the Settings > Choose directory page too right? Right now, the paths in both places are cut off by the form field - can this be fixed in this issue as well?

**Comment by kauffj** [comment]
Yes, the component in both places is the same.

**Comment by btzr-io** [comment]
> Disabled text fields are uneditable. They have a dotted input line and less opacity so that they appear less tappable.

https://material.io/guidelines/components/text-fields.html#text-fields-states
