### ISSUE TITLE
FileTile v2.0

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-app#657]
File Tiles currently have the following issues:

- [ ] Hover style / action behavior is different than cards
- [ ] Poor usage of space
- [x] URI is likely unnecessary to include, or give prominence to
- [ ] Should possibly allow directly taking secondary actions from cards

**Comment by btzr-io** [comment]
> Hover style / action behavior is different than cards
I guess this is ok  ^

**Comment by seanyesmunt** [comment]
I'm going to close this. The file tile will be removed and only the file card will be used. Extended functionality can be build into that. Ex: and edit button
