### ISSUE TITLE
Home page shows "index.html" in menu bar

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#658]
## The Issue
Home page menu bar shows index.html. Probably related to some recent search changes which put the search icon in the address bar instead of home.  It should show "Home" or possibly "Discover".
![homepage](https://user-images.githubusercontent.com/8120721/31407408-db965df8-add2-11e7-81e7-a4662b3d8177.PNG)

**Comment by sircodesalittle** [comment]
I'll do some investigating.

**Comment by tzarebczan** [comment]
It was introduced here: https://github.com/lbryio/lbry-app/commit/18450209b77e63ddb047c805ceb8edbaea1d2fd2#diff-9a6a461f504e63bae49576c6db1d1592 because we wanted to add the search icon/text on the home page, but it also tied to the menu bar.  Correct me if I am wrong, but the fix would be to independently set the Title bar in the case of Home.

**Comment by btzr-io** [comment]
I don't think it needs to show "Home" or "Discover", the title it's already handle on the `search-bar`
