### ISSUE TITLE
Total items incorrect in channel search results tile

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#659]
## The Issue
Looks like there is a bug in search results and showing how many claims are in the channel. For example, a channel with 1 claim shows: "This is a channel with over 10 items inside of it."

It stems from: https://github.com/lbryio/lbry-app/blob/master/ui/js/selectors/content.js#L40 / https://github.com/lbryio/lbry-app/blob/master/ui/js/component/channelTile/view.jsx#L38 which tries to take the number of pages in the channel and multiply it by 10 - which is incorrect.  Need it to get the total number of claims in a channel.  It should be able to show the exact amount, no need to say "over x items".  Unless this was meant to be a quick approximation without going deep into the channel details, not sure. 

### Steps to reproduce
1. search wqwqwqwq
2. check channel results - lbry://@wqwqwqwqwqwqwq#a4c06b2c73362a3120a99c0fa9a36886109284e5
only has 1 item in it but the results show 10

### Expected behaviour
Show correct # of claims in channel

### Actual behaviour
Shows incorrect # of claims

## System Configuration

 

- LBRY Daemon version: 0.17rc3
- LBRY App version: 0.17RC1
- LBRY Installation ID:
- Operating system:

**Comment by btzr-io** [comment]
Would be nice if this kind on info comes directly from the `channel_claim` ( along with subscriptions  count once is implemented) instead of resolving channel again it's slow and don't show relevant data :stuck_out_tongue:

**Comment by tzarebczan** [comment]
@btzr-io - claims_in_channel is returned during the resolve of the channel. Is that what you are referring to with channel_claim, or something else?

**Comment by kauffj** [comment]
This will be fixed in next RC.

**Comment by kauffj** [comment]
And yes, the way it was done originally was dumb.

**Comment by kauffj** [comment]
Fixed in 0.17.0rc2, to be made public shortly.
