### ISSUE TITLE
image error in published main file display

### ISSUE THREAD

**Issue by CjMapope** [lbryio/lbry-app#66]
## The Issue
Thumbnail is not displayed correctly upon selecting published item, whereas **is** shown correctly under **all** published items
### Steps to reproduce
1. Publish content
2. Check under Published, thumbnail is correct
3. Click said published item, error appears, no thumbnail :(

### Expected behaviour
Thumbnail should be displayed as per screenshot "1"

### Actual behaviour
Thumbnail is not displayed tho correctly published, as per screenshot "2"

## System Configuration

- LBRY Daemon version: daemon (lbrynet)    0.10.0
- LBRY App version: Version 0.10.0 (0.10.0.787)
- LBRY Installation ID: 87CKm9XupPBoHgD3yGsG6pPayX9F2q2WXjVTDKRDUL5B5Xi6x6mMpKhAAkMHXscCHa
- Operating system:  macOS sierra

## Anything Else
Reported for user @heymattsokol in Slack
-these uploads are .zip files, not videos
-each zip contains the mp3s of the album thumbnail is a .jpeg

## Screenshots
<img width="1031" alt="1" src="https://cloud.githubusercontent.com/assets/12862793/25452671/9ed40ae6-2a83-11e7-81d8-98bded344658.png">
<img width="1037" alt="2" src="https://cloud.githubusercontent.com/assets/12862793/25452681/a769f198-2a83-11e7-9511-f135365d7449.png">

**Comment by lyoshenka** [comment]
oops

**Comment by lyoshenka** [comment]
We're redesigning our UI, and it's possible that this issue is already fixed. @alexliebowitz is our UI expert. He'll take a look to make sure.

**Comment by alexliebowitz** [comment]
Yep, looks like this is working in the current UI (quite possibly thanks to your report). Thanks!
