### ISSUE TITLE
Transaction List - Categorize Rewards incoming tx

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#660]
## The Issue
Currently, incoming LBRY Rewards payments are not categorized in the transaction list. Think we should add a new category for Rewards and in details show the reward title and hyperlink to the Rewards page. 

### Expected behaviour
Show Rewards as "Reward"

### Actual behaviour
Shows Rewards as "receive", no indication it was a reward. 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by lyoshenka** [comment]
@hackrush01 you connected this to https://github.com/lbryio/lbry-app/pull/691. That PR was merged. Does that mean we can close this issue? At first glance it looks like the two are not the same.

**Comment by hackrush01** [comment]
@lyoshenka I think this can be closed as now the rewards txns are now marked in the txn list and clicking it(the rewards description) redirects to the rewards page, which lists out all the rewards.
