### ISSUE TITLE
Further search improvements

### ISSUE THREAD

**Issue by btzr-io** [lbryio/lbry-app#664]
### Update
Related issue -> https://github.com/lbryio/lbry-app/issues/677

## The Issue
- [ ] Look for improvements in the display and ordering of videos and channels
- [ ] Hide NSFW content if user is already hiding it
- [ ] Add Pagination
- [ ] Add type based filtering once lighthouse supports it

**Comment by tzarebczan** [comment]
Also, we can slowly begin to enable filters. Have an option to show only channels vs claims for instance. File type would be another, but the list can go on..we need to decide what we want to expose/need exposed.

**Comment by btzr-io** [comment]
Do we really need to display empty channels ?

**Comment by filipnyquist** [comment]
@btzr-io @tzarebczan waller and i are thinking about adding filtering server side, how does that sound?

**Comment by kauffj** [comment]
Yes, please add a type field that would allow users to just search content or channels.

We ought to apply a large negative weight to empty channels, but not exclude them.

**Comment by tzarebczan** [comment]
@filipnyquist yep, think it would be a combination of search side + app side options.

**Comment by kauffj** [comment]
Updated to enumerate the changes. I disagree that channels should always come first. Results should be intermingled based on relevancy.

**Comment by kauffj** [comment]
Channel search tiles need a huge improvement, obviously.
