### ISSUE TITLE
Unable to scroll down at edge of screen

### ISSUE THREAD

**Issue by oakey22** [lbryio/lbry-app#666]
## The Issue
Unable to click the cursor at the edge of the screen and scroll down,  the new scroll bar is too narrow to do this.

### Steps to reproduce
1.go to edge of screen and left click mouse and hold
2. drag down to scroll down
3.

### Expected behaviour
Should have a large enough area to select the scrollbar at the edge of the screen
### Actual behaviour
nothing happens as it is outside the scrollbar area

 This is in the 17.0rc1 app

You have to download the gif as it does not show the edge in the browser
https://spee.ch/d6ce9bf793686485ce23a8a09bde67b1b1adba68/scrollbar.gif

**Comment by btzr-io** [comment]
Well that's the expected behavior, to scroll you actually have to click the scrollbar not the edge of the screen :stuck_out_tongue:

**Comment by btzr-io** [comment]
I'll check if we can use padding instead of margin...

**Comment by btzr-io** [comment]
Also there is an indicator when the scrollbar can be dragged:  the scrollbar thumb background changes on hover depending on the theme, can get lighter or dark...
