### ISSUE TITLE
Form labels potentially interpreted as disabled fields

### ISSUE THREAD

**Issue by hackrush01** [lbryio/lbry-app#667]
## The Issue
Sub-titles for headings in Publish page are shown as gray.

### Steps to reproduce
1. Open publish page in app

### Expected behaviour
They should be black, as gray color gives the feel that the button/option is disabled.

## System Configuration
Latest app running from master

## Screenshots
https://imgur.com/a/Te3bR

**Comment by kauffj** [comment]
@hackrush01 do you mean the form labels? Or the text directly below the headers?

@btzr-io this did make me notice that we have both `form-row__label` and `form-field__label`, which are now styled the same way as of https://github.com/lbryio/lbry-app/commit/45b2bc6aa852d24a196d358fd10a8c31e3384d8b

**Comment by hackrush01** [comment]
@kauffj I mean the sub-labels, like `File`, `Title`, `Thumbnail URL`, `Description` in attached image 1, and `Free`, `Choose Price` and `Deposit` in attached imaged 2. Also, I seem to recall they were proper in the earlier releases.

**Comment by kauffj** [comment]
@btzr-io thought you may be interested in this feedback. Perhaps the color of help text is not appropriate for form labels.

**Comment by btzr-io** [comment]
> Hover states give the input line more opacity, helping make text fields more noticeable on desktop.
https://material.io/guidelines/components/text-fields.html#text-fields-states
