### ISSUE TITLE
Cannot publish new content in latest RC

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#668]
## The Issue
Publish button is greyed out if trying to publish new content. Edits work (besides the known issues)

### Steps to reproduce
1. Go to Publish, fill out all fields
2. Publish greyed out

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by btzr-io** [comment]
Just because the current form validation sucks -> https://github.com/lbryio/lbry-app/issues/564

**Comment by tzarebczan** [comment]
Nah, it was an issue with multiresolve. There's a hack now, but this is not a problem.

This issue should be to fix the hackaround.

**Comment by btzr-io** [comment]
>Publish button is greyed out 

I mean this should be handle in the form validation ^
