### ISSUE TITLE
Search address bar function is confusing to new users

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#671]
## The Issue
Many users who initially try to search will type in the term(s) and then click enter. When this happens, it goes to the exact claim typed.  The search function works as expected when something is typed, but enter is not clicked.  

Would be awesome if we could add some type of hint to clear this up in the App or find some other UX friendly way to convey the search functionality.

**Comment by btzr-io** [comment]
why don't just type the exact `uri`?

**Comment by btzr-io** [comment]
I mean don't auto add the `lbry://` to the search...

**Comment by tzarebczan** [comment]
Both features are needed... They are 2 different use cases for the same component.

**Comment by btzr-io** [comment]
What I mean is that -> always do search unless user type the exact uri `lbry://cats`:
- User `search-query:` cats -> multiple relevant results...
-  User `search-query:`  lbry://cats -> Go to `uri`...

**Comment by tzarebczan** [comment]
I think it's useful to be able to type @lbryio and get the exact claim without going through a 2nd click. I thought it was a feature lol. I could be wrong. I'll defer to @kauffj

**Comment by btzr-io** [comment]
@tzarebczan then I guess we can add an exception for channels

**Comment by tzarebczan** [comment]
And any inputs with the full claim information (claimname#claim_id  or claimname:sequence)?

**Comment by kauffj** [comment]
I have mixed feelings about the behavior of enter. We are trying to teach people about the concept of addresses, and that the bar is both an address bar and a search bar.

**Comment by wilsonk** [comment]
From a new user point of view it is really odd to not just be able to type in "flame"->hit enter and get back some results of videos that have "flame" in their title or description or the publishers name.

I understand that we may want to teach people about addresses, but it will be very hard for really new (or overall novice internet) users to grasp this without getting frustrated.

I think requiring '@' or 'lbry://' or '...#...' or '... : ...' to do an address lookup is the way to go. Any other search terms followed by the enter key will just to a simple search. Do a regex on the incoming string and it should be good to go.

This is in line with a web browser where you can type in the exact address of 'http://myfakesite.com' or just a couple words and hit enter to get a search to run. 

Just my two cents. 

Thanks
Kelly

**Comment by kauffj** [comment]
To be clear, I don't disagree at all that this is confusing and I think a change is warranted.

I just don't know precisely what it is, because I also think it's important that people have an easy and intuitive way to get directly to a URL, and having to type `lbry://` before everything is not that.

In a more standard browser omnibar, we can tell the difference between a search and a URL by whether or not a TLD is included. In the case of LBRY URLs, there's no equivalent.

**Comment by aayanl** [comment]
add a big search bar, then a tiny go bar, like the old safari browser but the inverse

**Comment by aayanl** [comment]
http://blogote.com/wp-content/uploads/2011/09/safari_mac_browser.jpg

**Comment by hackrush01** [comment]
Instead we could have a key combo(e.g. CTRL + Enter) to go directly to the
claim, and hitting only Enter would initiate a search. And we could make a
tooltip pop-up whenever the user clicks on the wunderbar too, as a
reminder, as this is not particularly intuitive.

-Regards
-Amit Tulshyan

**Comment by kauffj** [comment]
CTRL + enter is too obscure. Keep throwing ideas out though, we'll get there.

Maybe we need to focus on what aspect of the UI/UX is causing people to think they need to hit enter in the first place?

If you were showed search results immediately after typing, maybe no one would hit enter?

**Comment by aayanl** [comment]
They hit enter because thats what google trained them yo do. If people want
to directly go to a link, they can prepend lbry:// that way we can keep
enter for search.

**Comment by kauffj** [comment]
@aayanl Google has trained them that if they hit enter they magically get what they want, whether that was a domain or search.

Also, when typing in Chrome, I never see results until I hit enter. In our app, you will see results just from typing, so it's possibly that if they came even faster, people would stop hitting enter.

**Comment by nikooo777** [comment]
i think the best approach is to follow what most of the browsers do.

That is:

- If an address is typed (and this is easy to detect here since we have the prefix `lbry://`) then once enter is pressed it should bring up the claim right away.
- if anything else is typed and enter is pressed, then a search should be performed

in addition, having a live-search as you type is good, however I wouldn't go as far as thinking we can train people in doing something they have never done when we have giants such as google/mozilla/apple that push for other standards.

my 2 cents

**Comment by kauffj** [comment]
@seanyesmunt I believe our search service now has an autocomplete endpoint, which you can use to help improve the searching user experience.

https://lbryio.github.io/lighthouse/

(this may need to be merged first https://github.com/lbryio/lighthouse/pull/42)

**Comment by lyoshenka** [comment]
its merged. example: https://lighthouse.lbry.io/autocomplete?s=lbry

**Comment by seanyesmunt** [comment]
Nice

**Comment by seanyesmunt** [comment]
This will continued to be improved, but the basic implementation is in the redesign branch
