### ISSUE TITLE
Allow access to Developer Tools / Reload functionality

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#672]
## The Issue
In v17, the menu bar was removed which takes away the ability easily access the Developer Tools or the Reload function.  Not sure what the best way to re-introduce this feature as it can be helpful to for troubleshooting / debugging purposes. Maybe some "Advanced" setting in the menu which allows you to access both of the functions? Or maybe bring back the keyboard shortcuts and list them in settings/help?

**Comment by btzr-io** [comment]
Do we need this in the header ?

**Comment by MSFTserver** [comment]
@btzr-io not in the header but i think he means like adding an setting to set it so we can get these menus back or atleast the right click or shft+right click to view the old options as youll have to set an environmental variable to get the dev tools and reload

**Comment by MSFTserver** [comment]
setting the environmental also only launches the devtools once so if you exit you need to restart

**Comment by kauffj** [comment]
@btzr-io I just want everyone to be able to open it via the keyboard short cut for debugging purposes. It does not need to be in either the top menu or the right click context menu. I actually thought I was only removing it from those places, not disabling it entirely.

**Comment by btzr-io** [comment]
@kauffj same shorcut: `CTRL+SHIFT+I`  or just something more simple like `F12` ?

**Comment by kauffj** [comment]
@btzr-io https://spee.ch/whynotboth.jpg

**Comment by btzr-io** [comment]
> In v17, the menu bar was removed

This also affects the copy / paste behavior on macos, See: https://github.com/lbryio/lbry-app/issues/685

**Comment by btzr-io** [comment]
@kauffj why the `menu-bar` was removed ?
IMO Looks worth to have it ^^

**Comment by kauffj** [comment]
This was definitely unintended. Reviewing PRs shortly...

**Comment by kauffj** [comment]
#688 is merged, this will be in next release
