### ISSUE TITLE
Copy-paste keyboard hotkeys into and out of app UI

### ISSUE THREAD

**Issue by reillysmith** [lbryio/lbry-app#685]
## The Issue
Cmd-C, Cmd-V and similar do not work inside app. Right clicking to copy-paste still works.
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by hackrush01** [comment]
I couldn't exactly reproduce it, could you be more specific as to what you couldn't copy/paste in app. I tried to copy a random snippet from a video's description and paste it in the search bar, and it worked. I tried on Linux based OS.

**Comment by reillysmith** [comment]
El Capitan 10.11.6, cmd-C and cmd-V do nothing going into or out of the app. For example, non-responsive when I want to copy-paste a URL from LBRY, or a paste a description into the app while publishing.

**Comment by tzarebczan** [comment]
I believe it's Mac that's affected only. Tested it on Windows and Linux

**Comment by kauffj** [comment]
@btzr-io any idea on this one? thought it might be related to `user-select`, but idk

**Comment by btzr-io** [comment]
I can't recreate this in `linux`, but I'll do some research...

**Comment by btzr-io** [comment]
Not related to `user-select`:
http://codedmaster.com/2017/01/24/getting-electron-copy-paste-shortcuts-for-mac-builds/

**Comment by kauffj** [comment]
These are back in the menu, so this should be fixed.
