### ISSUE TITLE
LBRY app locks up on "Downloaded" tab

### ISSUE THREAD

**Issue by 8mirw8** [lbryio/lbry-app#689]
### Steps to reproduce
1. Create a channel with less than 4 characters
2. Download and publish content
3. Try and run LBRY and view downloaded content

### Expected behaviour
LBRY app should allow you to view your published content.
### Actual behaviour
After some time the LBRY app may become unresponsive when you click on the Folder icon for "Downloaded & Published"

## System Configuration

 
![image](https://user-images.githubusercontent.com/29604420/31805169-80228214-b5aa-11e7-87ae-387bbb12e1b1.png)

![image](https://user-images.githubusercontent.com/29604420/31805385-f6274f48-b5ab-11e7-8973-f6ae1cb28956.png)

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

## Screenshots
![image](https://user-images.githubusercontent.com/29604420/31805133-1b574022-b5aa-11e7-828d-b3decab4d516.png)

**Comment by tzarebczan** [comment]
Thx for filing, great find! Took care of reward via slack. 

Workaround is to abandon the channel

**Comment by hackrush01** [comment]
#690 should fix this.

**Comment by kauffj** [comment]
Will be live in next app release (presumably 0.18).
