### ISSUE TITLE
Change App links to Discord

### ISSUE THREAD

**Issue by jsigwart** [lbryio/lbry-app#692]
## The Issue
App and website are still directing people to Slack and this needs to be changed.

### App:
- Help Section: Under "Get Live Help" is button to Slack
- Rewards Section sends verifications to Slack

## Anything Else
Website also needs to be changed, but will document that separately or just change it myself.

**Comment by tzarebczan** [comment]
We will be creating a https://chat.lbry.io re-direct that we can use for Discord invites (or any other chat URL if it changes in the future).  Once that's up, we can update the app links (and website) accordingly.

**Comment by kauffj** [comment]
This is fixed in the app, and has been fixed in the top website navigation.

I believe it needs to be fixed in several other places on the website, which is now handled by this ticket:

https://github.com/lbryio/lbry.io/issues/242
