### ISSUE TITLE
Do not use daemon API command file_list with argument outpoint 

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbry-app#693]
https://github.com/lbryio/lbry-app/blob/2746627fb15f617725192a51cc8f6ba4f053915a/ui/js/actions/file_info.js#L38

I would like to deprecate the outpoint argument from daemon API command file_list as it is incorrect to attach claim information to files. Files can and do exist without being attached to claims (i.e., on reflector hosts). 

doFetchFileInfo(uri) should instead resolve the uri, check the sd_hash for the claim, and use file_list with argument sd_hash to get the correct file. 

See discussion here: https://github.com/lbryio/lbry/issues/944

**Comment by tzarebczan** [comment]
Thanks for creating this, I was about to open one up.  I'm sure there will be many touchpoints to this change.

Other related issues which this should take into account/fix: https://github.com/lbryio/lbry/issues/951 (more generic is download problems for updated claims for users who downloaded the original)
https://github.com/lbryio/lbry-app/issues/600 (updating claim bug)

**Comment by kauffj** [comment]
@kaykurokawa This change is fine with me app-side. Feel free to deprecate or remove this daemon side.

**Comment by jackrobison** [comment]
The filters for file list as of 0.19.0 are: `sd_hash`, `file_name`, `stream_hash`, `rowid`, `claim_id`, `outpoint`, `txid`, `nout`, `channel_claim_id`, `channel_name`, and `claim_name`

Files do not have to be associated to a claim, if they aren't the claim related fields are `None`.

**Comment by tzarebczan** [comment]
@jackrobison / @kaykurokawa should we close this issue? I guess we can't/won't be removing outpoint information from files.
