### ISSUE TITLE
front page row alignment

### ISSUE THREAD

**Issue by MSFTserver** [lbryio/lbry-app#696]
## The Issue

row doesnt adjust for smaller app window sizes and chops off end of last cards

### Steps to reproduce
1. open the app
2. shrink it a little or a lot
3. scroll the end of row and it starts cut it off

### Expected behaviour
cards should adjust and not be cut off
### Actual behaviour
cards dont adjust and get cut off

## System Configuration

 

- LBRY Daemon version:
- LBRY App version: v0.17.0
- LBRY Installation ID:
- Operating system: windows

## Screenshots

![image](https://user-images.githubusercontent.com/18357967/31921993-5861c65c-b827-11e7-88ed-f979a4c70624.png)
![image](https://user-images.githubusercontent.com/18357967/31922012-6fb18784-b827-11e7-9a7f-21c7049795e8.png)

**Comment by liamcardenas** [comment]
while this is definitely a valid issue, it is going to be handled via the homepage redesign https://github.com/lbryio/lbry-app/issues/849
