### ISSUE TITLE
Prove Humanity

### ISSUE THREAD

**Issue by f1reflyyyylmao** [lbryio/lbry-app#703]
## The Issue
It's very hard to proof that one is a human being with the current options, hence there's no possibility to get into the reward system/guided tour.

### Steps to reproduce
1. Don't upload videos to youtube, be a consumer only
2. Don't have a credit card and don't want to get one (Not from the US, happy with my normal bank card)
3. Don't use discord because their ToS are horrifying and one doesn't want to support their business model

### Expected behaviour
I think irc should be an option for proofing that one is a valid human. Every project ever has community/support irc, why doesn't this one? Freenode etc are free to use after all

### Actual behaviour
It's not possible to proof that i'm a human in front of a computer

**Comment by tzarebczan** [comment]
@f1reflyyyylmao - sorry you are having issues with verification. Shoot me an email over to hello@lbry.io and we'll get you set up. 

We'll be moving towards performing a verification request within the app, so that should bridge the gap you are referring to.
