### ISSUE TITLE
In-app video plays upside down

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#705]
## The Issue
A LBRY user reported an issue where their uploaded video is playing upside down in the app but plays correctly externally. Might be related to https://github.com/lbryio/lbry-app/issues/539

The content: lbry://viddywell#08911a725c14d17fb36c66642c420c1c96853df6
![upside](https://user-images.githubusercontent.com/8120721/32118672-894332d2-bb20-11e7-9e18-0588677447d8.JPG)

### Steps to reproduce
1. View lbry://viddywell#08911a725c14d17fb36c66642c420c1c96853df6 in app
2. Video is upside down
3. Play externally, shows correctly

### Expected behaviour
Determine correct rotation if possible

### Actual behaviour
Plays upside down

## System Configuration

 

- LBRY Daemon version: 0.17.1
- LBRY App version: 0.17.1
- LBRY Installation ID:
- Operating system: Windows

**Comment by kauffj** [comment]
Strongly suspect this is identical to #539.

**Comment by lyoshenka** [comment]
Closing this. Reopen if #539 is fixed and this still happens.
