### ISSUE TITLE
Text cut off on new user message

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#709]
## The Issue
See screenshot below. Not sure when this started to occur - possibly with some of the recent css/font changes? 
![formatting](https://user-images.githubusercontent.com/8120721/32342018-90381896-bfd5-11e7-97ce-2c42dd9c75be.JPG)

### Expected behaviour
format properly

### Actual behaviour
text cut off

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
Fixed in c33b7df7
