### ISSUE TITLE
Ensure no claim data is being referenced from file_xxx API calls

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-app#717]
When https://github.com/lbryio/lbry/issues/981 is merged, `file_list` and any other API calls that return a file structure will no longer include claim data.

The app needs to ensure it is not using or expecting claim data on file info.

**Comment by tzarebczan** [comment]
Related to https://github.com/lbryio/lbry-app/issues/693? 

We have a couple bugs filed around file_list related issues also, especially when updating claims.

**Comment by kauffj** [comment]
Duplicate of #693, whoops
