### ISSUE TITLE
Trackpad scrolling

### ISSUE THREAD

**Issue by LanceDwight** [lbryio/lbry-app#718]
## The Issue

Currently, in order to view the out-of-sight featured videos on the homepage, you must click on the left or right arrows. 

Please add trackpad gesture control so users can swipe side-to-side on the trackpad to scroll through these videos. This was a feature found on earlier LBRY versions for Mac users.

### Steps to reproduce
1.
2.
3.

### Expected behaviour

When hovering over a featured video on the homepage, the user should be able to swipe to right-left to scroll to the other featured videos located to the right (and out of sight).

### Actual behaviour

In order to see the out-of-sight videos, users must click on the arrow button(s).

- LBRY App version: Version 17.1

**Comment by tzarebczan** [comment]
Thanks for filing this @LanceDwight, sent you a couple LBC on Discord :)

What do you think about some keyboard shortcuts as well?

**Comment by LanceDwight** [comment]
Thanks, Tom! 

Also, keyboard shortcuts for increasing playback speed, full-screening the video, etc., might be helpful to some users. Were you thinking of suggesting keyboard shortcuts for something other than ones impacting video playback?

**Comment by hackrush01** [comment]
@tzarebczan I think this is the same as #510, should we close one of them?

**Comment by seanyesmunt** [comment]
Closing this in favor of #510
