### ISSUE TITLE
Inconsistent thumbnail sizes in 'Trending' section

### ISSUE THREAD

**Issue by wilsonk** [lbryio/lbry-app#721]
## The Issue
One can game the trending section somewhat by using a very long channel name to make the size of the thumbnail bigger than others in that section.
### Steps to reproduce
1.View trending section today (Nov 9, 2017)

### Expected behaviour
All thumbnails should be the same size

### Actual behaviour
Thumbnails with large channel names are larger than the rest

## System Configuration

 

- LBRY Daemon version: 0.17.1
- LBRY App version:0.17.1
- LBRY Installation ID: 26bru4Kjp3i3VM5KTFVV3ESEkDWEb9CCA2ate4L9XJYTr8PHUK4jPDQqz4JsG73Wfr

- Operating system: Linux (Linux-4.4.0-97-generic-x86_64-with-Ubuntu-16.04-xenial)

## Screenshots

![screenshot_2017-11-09_11-45-19](https://user-images.githubusercontent.com/38802/32623539-bd36c6e4-c543-11e7-845e-38d2c4c83e4b.png)

**Comment by wilsonk** [comment]
Sorry, maybe that isn't the channel name being too long that is the problem, but the actual size of the file name. Perhaps that forces the 'red ship/free' icon to be pushed onto the next line which then makes the thumbnail longer not wider.

Easier to game the system this way, but with the ellipses eliding the file name size it might be easier to fix?

**Comment by wilsonk** [comment]
Hmm, maybe I will eventually get this right!  It actually looks like a combination of both the long file name and channel name may be the problem...??

**Comment by seanyesmunt** [comment]
I think we should remove the card design. It can be tough to deal with when trying to keep boxes the same height.

If we remove the card we could increase the visible text limit and not have to worry about different container heights. Something like this redesign http://lab.zzk.fr/lbry/

**Comment by oakey22** [comment]
@seanyesmunt i absolutely love that design, so professional looking

**Comment by akinwale** [comment]
Created a PR to fix this since it kept bothering me.

Also, @seanyesmunt that new design is amazing! You should show the entire team.

**Comment by liamcardenas** [comment]
@tzarebczan can you verify this is working?
