### ISSUE TITLE
No pause on internal app player when opening external

### ISSUE THREAD

**Issue by oakey22** [lbryio/lbry-app#726]
start watching a movie like lbry://pubg-second-place-champ#07a4d9c9cc03f0245d111ffef6de558e83da4cb2
then click open
the original video carries on playing in the app, then the video is opened again  in the external player which starts playing
then in app video needs to pause as the external player is opened

App | 0.18.0rc1
-- | --
0.18.0rc1
3.1.11rc8
gfugfqpsfpsewz@divermail.com
 
Linux (Linux-4.4.0-97-generic-x86_64-with-Ubuntu-16.04-xenial)

**Comment by liamcardenas** [comment]
@daovist is working on this

**Comment by liamcardenas** [comment]
This issue have been completed in PR #880
