### ISSUE TITLE
When you use the scroll bar in main app screen it also moves the view in download folder and vice versa

### ISSUE THREAD

**Issue by LavRadis** [lbryio/lbry-app#729]
**Working on this?** See [hint here](https://github.com/lbryio/lbry-app/issues/729#issuecomment-343507699)

## The Issue
When you scroll down in main app screen, the view in the "downloads and purchase"s is also moved when you go there. It also happens in reverse, when you move scroll in downloads view and go back to the main screen. 

### Steps to reproduce
1. Move scroll down in the main screen
2. Go to Downloads section
3. You will notice that the view focus is not on top at last downloaded video, but it has moved down

It also works in reverse. Did not check for all app sections and views. 

### Expected behaviour

Moving scroll in one view should not affect other sections of the app.

### Actual behaviour

You move scroll in one section, the focus moves in other also.

## System Configuration

LBRY Daemon version: 0.18.0rc1
LBRY App version: 0.18.0rc1
LBRY Installation ID: 7tYN144rHXrspzJG9xLP28fi1JztXnbpKro6DBJEQyzBmXTyDgqRLfYsUvHYFVmMe2
Operating system: Win 10

## Screenshots

They are attached to this issue report. 

![lbry view 1](https://user-images.githubusercontent.com/10566738/32664392-62c322cc-c631-11e7-80b3-2f0ace3a5853.jpg)
![lbry view 2](https://user-images.githubusercontent.com/10566738/32664394-62e9bca2-c631-11e7-82c0-cdd27d74b594.jpg)

**Comment by LavRadis** [comment]
It also happens when you move scroll in the wallet. When you go to the main window it has also moved.

**Comment by LavRadis** [comment]
It happens when you move the settings scroll bar also. Looks like all the areas of the app are affected.

**Comment by kauffj** [comment]
Clue for whoever works on this:

You most likely to change the scrolling behavior in the `doNavigate` function of `actions/navigation.js` so that the Y position is not retained on navigation to new pages not in the history stack.

**Comment by btzr-io** [comment]
fixed in #732
