### ISSUE TITLE
Automatic dark mode

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-app#733]
We should offer an option to switch to the dark mode automatically. This would automatically switch to dark mode after some time (9pm). Extended functionality could be allowing the user to set the time at which the theme switches over.

Something like this (terrible mock up)
<img width="348" alt="screen shot 2017-11-13 at 5 15 09 pm" src="https://user-images.githubusercontent.com/16882830/32752356-dc68683c-c896-11e7-8d96-4f4e70c1fb84.png">

**Comment by liamcardenas** [comment]
Can you make sure to explain what automatic dark mode is in app?

**Comment by seanyesmunt** [comment]
Yeah. Will definitely have some explanation next to the toggle.

**Comment by MSFTserver** [comment]
I'm about to start looking at the app again if this isn't being worked on id be glad to help shouldnt be hard detecting a user's local time settings a theme to trigger certain times using a cache system since its web based app

**Comment by seanyesmunt** [comment]
Yeah I think this would be a great feature to have. Agreed that it
shouldn't be too difficult.

**Comment by Arrowana** [comment]
I would like to implement this, I might take a bit of time as this will be my first feature implementation (not familiar with electron).

The theme dropdown will be greyed-out when "automatic dark mode" is enabled (checked).

**Comment by Arrowana** [comment]
I have the basic idea working
https://github.com/Arrowana/lbry-app/commit/8eb7f589889285defeb11dd4889704a9ca6186fd

I am not sure about the required value I added in the settings store: isNight
There isn't any appropriate place where this could be stored

**Comment by seanyesmunt** [comment]
@Arrowana Awesome! Can you make a PR for you changes? I have a few comments but it looks great.

**Comment by tzarebczan** [comment]
Closed via https://github.com/lbryio/lbry-app/pull/950
