### ISSUE TITLE
Poor error message for no support/tip amount input

### ISSUE THREAD

**Issue by oakey22** [lbryio/lbry-app#738]
Click support a claim and then click Send without inputting an amount, you get an error of 

"Something went wrong"

This should say " Please input an amount" or something along those lines.

This is on the new 0.18.0 version

![image](https://user-images.githubusercontent.com/22527575/32748376-025edf36-c8b4-11e7-8da1-a902413e67cc.png)

**Comment by tzarebczan** [comment]
Thanks @oakey22! Sent you a couple LBC for filing the issue.

I've run across this in the past, never got a chance to file it.

**Comment by IGassmann** [comment]
This issue will be waiting for [that issue](https://github.com/lbryio/lbry/issues/1004). The error message should be returned by the API so it can be used in the app.

**Comment by liamcardenas** [comment]
@IGassmann it looks like "that issue" is done, can you get to this soon?

**Comment by liamcardenas** [comment]
oh i see this is already in "next"! nice

**Comment by tzarebczan** [comment]
API call now returns, is this what was expected? 
```
{
  "error": {
    "code": -32500,
    "data": [
      "  File \"site-packages\\twisted\\internet\\defer.py\", line 1299, in _inlineCallbacks",
      "    ",
      "  File \"site-packages\\lbrynet\\daemon\\Daemon.py\", line 2719, in jsonrpc_wallet_send",
      "    ",
      "lbrynet.core.Error.NullFundsError: "
    ],
    "message": "NullFundsError"
  },
  "id": 426,
  "jsonrpc": "2.0"
}
```

**Comment by tzarebczan** [comment]
I think we should just disable the send box unless something is typed. @seanyesmunt can we get this done for the redesign please?
