### ISSUE TITLE
content address extends outside of visible area in card

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-app#741]
## The Issue
When going to an address that is very long, content may extend passed the edge of the card

### Steps to reproduce
1. Navigate to lbry://@seanyesmunt#2fa8ecba445648eae50cb6e98948e67a417c9017/thisisaverylongstringthatiscutoff
2. Notice content extending off the page
3. Publish new content
4. Go to the new content page before the publish is done, see it extend off the page

### Expected behaviour
I should be able to see the entire address
Long addresses should probably wrap, maybe there is a better way, does it need to be in a card?
Since the address is in the search bar, do we need the address here?

### Actual behaviour
The address is cut off

## Screenshots
<img width="400" alt="screen shot 2017-11-14 at 9 00 37 am" src="https://user-images.githubusercontent.com/16882830/32783603-514f4732-c91a-11e7-87c2-223d5d7780c0.png">

<img width="400" alt="screen shot 2017-11-14 at 9 01 56 am" src="https://user-images.githubusercontent.com/16882830/32783695-a78ce33e-c91a-11e7-92cd-7160ad60ab0e.png">

**Comment by amitnndn** [comment]
Since this is a small fix, I am fixing this as a part of  #1569 PR.

**Comment by tzarebczan** [comment]
Closing per #1569
