### ISSUE TITLE
insufficient funds for deposit error

### ISSUE THREAD

**Issue by MSFTserver** [lbryio/lbry-app#748]
## The Issue
i had a user report they tried to make deposit of 10lbc and they only had 7lbc without realizing it, but the error message said [object object] instead of proper insufficient funds readout
### Steps to reproduce
1. go to publish 
2. enter deposit with more than balance
3. throws error [object object]

### Expected behaviour

it should throw proper errors
### Actual behaviour

looks like some json parsing issue

## System Configuration

 

- LBRY Daemon version: v.0.18.0
- LBRY App version: v.0.18.0
- LBRY Installation ID: 5kkPJX88NgHEhRihDHwJZSrxqissMNZ67xUUDxVKBcxWFKzPHRHmtTiMd9QccCqnL6
- Operating system: windows 10

## Screenshots

![image](https://user-images.githubusercontent.com/18357967/32818565-e10738cc-c978-11e7-9a0d-88f7725e2005.png)

**Comment by MSFTserver** [comment]
would also help if changed the default from 10lbc

**Comment by tzarebczan** [comment]
Probably the same as https://github.com/lbryio/lbry-app/issues/427 but this is really a daemon side issue per that thread.

**Comment by MSFTserver** [comment]
ahhh ok i think we should still switch the default amount to the lowest possible just so users now thats its the lowest and they shouldnt run into this issue if they dont change the default amount

**Comment by MSFTserver** [comment]
even if they do they at that point they would have most likely noticed they didnt have that much but its easily overlooked by new users on first publishes

**Comment by liamcardenas** [comment]
Interesting, @seanyesmunt what do you think about this? Certainly there are some issues on the app end in terms of displaying the proper error message (as @MSFTserver pointed out, probably an issue reading json) and explaining/modifying the default behavior.

i'm going to assign this to you Sean, obviously feel free to unassign it

**Comment by tzarebczan** [comment]
https://github.com/lbryio/lbry/issues/855 let's see what Alex says. Can we still capture the daemon output even with the exception? I'm sure we can but we'd wanna know what the daemon will return exactly.

I'm all for making this a priority, comes up alot.

**Comment by seanyesmunt** [comment]
@kauffj Is there any reason we can't just check the users wallet balance app side for this? It would be a quick fix while we figure out a better solution for the daemon interaction. Added to to the channel creation to see what it would look like here https://github.com/lbryio/lbry-app/pull/794/files

**Comment by kauffj** [comment]
@seanyesmunt yes an app side check could be added. But we should still figure out what's going on here, since other errors could likely generate this same outcome (I'm guessing we're rendering an `Error` object rather than printing it's message, but haven't looked).

**Comment by seanyesmunt** [comment]
👍

Yeah we will definitely need to fix the daemon error handling. But it will
be nice to have a somewhat better error presented for now.

**Comment by kauffj** [comment]
Fixed in #794

**Comment by tzarebczan** [comment]
Once the daemon side is fixed(the exception, plus the update balance issue), this will need to be reverted because the daemon needs to take into account already claimed LBC when updating claims.
