### ISSUE TITLE
Minor issue: copy function does not work on a part of LBRY app main screen text

### ISSUE THREAD

**Issue by LavRadis** [lbryio/lbry-app#751]
## The Issue
I wanted to select and copy a part of a text explaining "Community top bids" for a "Whatis this?" link window, but it doesn't copy it. The text is selectable, a menu appears and after selecting "Copy" there is nothing to paste. 

### Steps to reproduce
1. Click "What's this?" link on "Community top bids section"
2. Try to copy the text
3. Paste does nothing

### Expected behaviour
Copy should work on all selectable text.

### Actual behaviour
Copy does not work when you click it on the menu. 

## System Configuration

- LBRY Daemon version: 0.18.0
- LBRY App version: 0.18.0
- LBRY Installation ID: 7tYN144rHXrspzJG9xLP28fi1JztXnbpKro6DBJEQyzBmXTyDgqRLfYsUvHYFVmMe2
- Operating system: Win 10

## Anything Else
Probably a minor issue, reported it "just in case".

## Screenshots
![copy paste lbry](https://user-images.githubusercontent.com/10566738/32861571-60ddcc14-ca55-11e7-8fc9-b62234b529e9.jpg)

**Comment by seanyesmunt** [comment]
@LavRadis  Can you try on `0.18.2`?

Seems to work for me, I think it was fixed recently

**Comment by LavRadis** [comment]
Tried it now on 18.2 still same, no copy. could it be only me and my machine? other texts form the app home page works, only that frame doesn't.

**Comment by seanyesmunt** [comment]
Hmm, that is pretty weird that copy/paste works in there areas. I'll try to
see if I can reproduce on another machine.

**Comment by LavRadis** [comment]
I think this is the only frame/pop-up of such type in the entire app. Maybe the best solution would be to just re-design it into more uniform solution, like a link to an external FAQ. This is why I wanted to copy it in the first place, to start making the FAQ on the topic.

**Comment by tzarebczan** [comment]
I'd day bottom of the backlog for now. I'll see if I have time to reproduce it tomorrow, but it's not a high priority at this time.

**Comment by liamcardenas** [comment]
@tzarebczan did you ever have time to reproduce this?

**Comment by tzarebczan** [comment]
@liamcardenas it works fine when you CTRL-C it, but doesn't work when you right click > copy. 

I tried it on the scenario listed in the steps (more info popup from Community Top Bids)

**Comment by tzarebczan** [comment]
This should be fixed in the redesign.
