### ISSUE TITLE
Integrate React and Redux devtools into Electron

### ISSUE THREAD

**Issue by IGassmann** [lbryio/lbry-app#752]
The Chrome DevTools extensions for React and Redux are also available in Electron through the [Electron DevTools Installer](https://github.com/MarshallOfSound/electron-devtools-installer).

It would be useful to enable these tools for easier debugging and inspection.

**Comment by liamcardenas** [comment]
Yes, this was on my todo list. Can you get this working next (after you finish what you are working on)?
