### ISSUE TITLE
When scrolling on the home page, there are flashes of un-rendered content at the bottom

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-app#753]
## The Issue
When scrolling on the discover page (more noticeable when scrolling quickly), there can be flashes of content that isn't fully rendered at the bottom of the screen.

### Steps to reproduce
1. On the Discover page
2. Scroll semi-quickly
3. Look at the bottom of the screen when scrolling

### Expected behaviour
Scrolling should mimic a webpage. The content should be "rendered" and ready to be viewed before scrolling.

### Actual behaviour
I see a white rectangle at the bottom as content is dynamically rendered

## System Configuration

 

- LBRY App version: 0.18.2
- Operating system: macOS High Sierra

## Screenshots
Snippet from recording my screen and scrolling
<img width="400" alt="screen shot 2017-11-16 at 1 13 29 pm" src="https://user-images.githubusercontent.com/16882830/32907964-0a81b396-cad0-11e7-88de-451b10308a7f.png">

**Comment by seanyesmunt** [comment]
@tzarebczan Interested if you see this on Windows. I would guess this issue is on all OS's, but not sure.

**Comment by liamcardenas** [comment]
@seanyesmunt I think this should go to the icebox because after the redesign this might fix itself. It's also not a major.

Feel free to move this back to the backlog if you want.

**Comment by tzarebczan** [comment]
I think this is fixed, reopen if it still happens.
