### ISSUE TITLE
Seeing a blank green screen when refreshing when viewing "overview" page

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-app#755]
## The Issue
Not really sure whats happening, needs more exploration. Will update with more details later.

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

## Screenshots
<img width="500" alt="screen shot 2017-11-17 at 11 21 05 am" src="https://user-images.githubusercontent.com/16882830/32957579-1a7b4f7c-cb8a-11e7-8db0-c698263d8f95.png">

**Comment by kauffj** [comment]
@seanyesmunt Fairly confident it is from one of the two map calls introduced or modified in this PR https://github.com/lbryio/lbry-app/pull/697/files

@hackrush01 may know the fix without needing to examine too deeply, since this is from his code

**Comment by liamcardenas** [comment]
@hackrush01 can you look into this?

**Comment by seanyesmunt** [comment]
This seems to be fixed

**Comment by liamcardenas** [comment]
Great, closing.
