### ISSUE TITLE
Set user-agent in Electron

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-app#760]
As the spee.ch maintainer, I'd like to track when images are loaded by the LBRY app vs a normal browser, so I can have better analytics.

If Electron's useragent is set to something like `Mozilla/5.0 ... LBRY v0.18.0 ...`, then speech will know that the request comes from the app.

Some maybe-useful links:
- https://stackoverflow.com/questions/35672602/how-to-set-electron-useragent
- https://github.com/electron/electron/issues/7218

Test by making a request to https://httpbin.org/user-agent and see what it returns.

**Comment by lyoshenka** [comment]
@billbitt filed it for you :-)

**Comment by lyoshenka** [comment]
whats the useragent string so @billbitt can filter for it?

**Comment by kauffj** [comment]
@lyoshenka it's already filed https://github.com/lbryio/spee.ch/issues/285

**Comment by billbitt** [comment]
:+1:
