### ISSUE TITLE
Write CONTRIBUTING.md and update documentation

### ISSUE THREAD

**Issue by IGassmann** [lbryio/lbry-app#764]
Write and update the project documentation to ease the process of contributing and keep a consistent codebase.

**Comment by kauffj** [comment]
To clarify, we already have one CONTRIBUTING.md, which exists here:

https://github.com/lbryio/lbry.io/blob/master/content/faq/contributing.md

If every repo is to have a CONTRIBUTING.md, it seems likely that there will be a good amount of shared content between repos. The question then becomes:

- Is CONTRIBUTING.md the shared part, with the per-repo stuff in a separate file?
or
- CONTRIBUTING.md is repo-specific, but includes some reference at the top that provides a link to general context and information about contributed to LBRY.

**Comment by IGassmann** [comment]
It would be better to have CONTRIBUTING.md as repo-specific due to the fact that Github uses this file to notify the user that the project has some guidelines: [https://help.github.com/articles/setting-guidelines-for-repository-contributors/](https://help.github.com/articles/setting-guidelines-for-repository-contributors/)

Also, contributors usually expect to find that file in the same repo that they want to contribute. We can reference the page [https://lbry.io/faq/contributing
](https://lbry.io/faq/contributing
) for common guidelines.

**Comment by kauffj** [comment]
:+1:
