### ISSUE TITLE
We need an android lbry version

### ISSUE THREAD

**Issue by kevplayer54** [lbryio/lbry-app#77]
## The Issue
Need android lbry version

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by Plasmmer** [comment]
I think its forgot to remove the template description =/

**Comment by lyoshenka** [comment]
Thanks for the feature request. We'd like to use github for issues and bugs only, and we track feature requests internally. I'm going to move this into our internal database.

**Comment by Plasmmer** [comment]
@lyoshenka, but, are you saving all the suggestions?

**Comment by lyoshenka** [comment]
Yep, we are. I also tagged them all `feature-request` here on Github, in case there's further discussion here and we need to come back to them.
