### ISSUE TITLE
Quiting from the top menu bar doesn't work (File > Quit)

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-app#772]
<img width="419" alt="screen shot 2017-11-21 at 6 38 25 pm" src="https://user-images.githubusercontent.com/16882830/33102594-8167dad4-ceeb-11e7-9917-08fbfd41e97f.png">

## The Issue
safeQuit is not a function

### Steps to reproduce
1. Click "File" then "Quit" from the menu bar

Probably added here https://github.com/lbryio/lbry-app/commit/6d01122967169479c225201a66f9ebe675834e90

@IGassmann can you look at this?

**Comment by hackrush01** [comment]
I think putting `module.exports` in the first line would fix this issue.

-Regards
-Amit Tulshyan

**Comment by IGassmann** [comment]
@hackrush01 Yes it solves. It's because ´setMenu´ is called before the export.

I don't like that we are forced to put the export on top. There should be a better way, but for the time being, I'll put it back there.
