### ISSUE TITLE
Support Hot Module Replacement for development

### ISSUE THREAD

**Issue by IGassmann** [lbryio/lbry-app#774]
Support HMR (hot reload) for development. Ideally also have it for Electron's main process.

**Comment by IGassmann** [comment]
Issue currently being blocked by electron-webpack's issues: [#71](https://github.com/electron-userland/electron-webpack/issues/71) and [#69](https://github.com/electron-userland/electron-webpack/issues/69).

**Comment by kauffj** [comment]
We can go down to a single index.html file

**Comment by IGassmann** [comment]
We already have only one [index.html file](https://github.com/lbryio/lbry-app/blob/master/src/renderer/dist/index.html). The problem being is that it isn't a generated one. Electron-webpack makes use of the [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin) that generates an index.html for the project. We could switch to this generated file, but then we would have to find a way to link the favicons and fonts.

**Comment by kauffj** [comment]
I thought this was about `warning.html` and `upgrade.html`, which I believe are still used.

The favicons can presumably be dropped (more of a legacy from when the app was accessed via your browser).

Surely there must be some way for the fonts to be loaded? They could be loaded in Javascript, if nothing else.

**Comment by IGassmann** [comment]
Oh `warning.html` and `upgrade.html`shouldn't be a problem since they aren't entry points for the renderer process. I will then go for a generated `index.html`. I just need to have [this issue](https://github.com/electron-userland/electron-webpack/issues/71) resolved so I can have the compiled CSS file linked to the generated ìndex.html`.

**Comment by loopmode** [comment]
You could use https://github.com/jantimon/favicons-webpack-plugin for icons

Fonts could be included by importing them into scss or css and importing that in js.

**Comment by IGassmann** [comment]
@loopmode Awesome, thanks for sharing this.

**Comment by IGassmann** [comment]
Hey @loopmode! Forgot to offer you. If you'd like an LBC tip for your help, please see [lbry.io/faq/tips](lbry.io/faq/tips).

**Comment by loopmode** [comment]
@IGassmann actually I enjoyed reading the introduction of your app. 
I got interested in blockchain stuff when it came out, but never got deeper into it. 
But I happen to be a digital artist and a web developer with growing experience in electron apps, so.. I might even contribute "for real" next year. :)

**Comment by IGassmann** [comment]
@loopmode That would be great!
