### ISSUE TITLE
Enforce BEM accross the app

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-app#777]
We are trying to use BEM practices for css classes. There are a lot of places we aren't doing this, so it can be hard to tell how you should name new classes.

We need to go through the entire app and enforce BEM, and enforce it in all PR's going forward.

**Comment by etisdew** [comment]
If this might be a good place to introduce myself to the project and may I discuss this issue with you on discord? @etisdew

**Comment by seanyesmunt** [comment]
Hey @etisdew! Just sent you a friend request on Discord

**Comment by tzarebczan** [comment]
@etisdew be sure to check out lbry.io/faq/contributing too!

**Comment by kauffj** [comment]
@seanyesmunt have you been standardizing this as part of design work?

**Comment by seanyesmunt** [comment]
Yes. Looking much better now

**Comment by kauffj** [comment]
Nice! Added to epic, maybe this will be a freebie once the design is done :)
