### ISSUE TITLE
Toggle Payment Prompt Threshold

### ISSUE THREAD

**Issue by reillysmith** [lbryio/lbry-app#779]
## The Issue
Payment prompt for negligible priced items can be streamlined/toggled
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen
Items less than a certain LBC should not trigger an "Are you sure?" -type payment confirmation if I'm okay with it.

Default: do not prompt if USD < or = $0.05 for an item.
Settings>Toggle Payments: Do not prompt if < = $X.xx (select your threshold).

### Actual behaviour
Tell us what happens instead
All prices from $0.0001 to $10 will interrupt the UX with a pop-up confirmation.

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
This already exists in settings :)

**Comment by reillysmith** [comment]
I had no idea. So that introduces two other problems:
- The flow leading to that potentially game-changing knowledge isn't correct. ( @liamcardenas )
- I think the default should be a threshold and not "always prompt me" because being prompted for a penny is still ridiculous. It costs more than a penny of time to show them the pop-up asking them if they want to spend a penny.

I propose the default is $0.10 or $0.05.
