### ISSUE TITLE
Users should be able to create channels outside of the publish flow

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-app#786]
As a user, it would be nice to be able to create a channel outside of the current publish flow. Some sort of "Create Channel" page would be really nice.

**Comment by reillysmith** [comment]
see also: https://github.com/lbryio/lbry-app/issues/787

**Comment by seanyesmunt** [comment]
I’ll just close this one

**Comment by reillysmith** [comment]
Unless that's bad procedure, let me know.

**Comment by seanyesmunt** [comment]
Oh. No that’s fine. Just make that one dependent on this issue then. Should be good. 👍

**Comment by liamcardenas** [comment]
I'm going to close this so we can consolidate issues
