### ISSUE TITLE
User got [object Object] error when uploading a video

### ISSUE THREAD

**Issue by Feanor78** [lbryio/lbry-app#793]
## The Issue
A user tried to upload a video and got an error message - link here: https://twitter.com/willkriski/status/935567877524029440
### Steps to reproduce
1. User uploaded video, got error message

### Expected behaviour
Video should be published

### Actual behaviour
[object Object] error happened

## System Configuration

 

- LBRY Daemon version: Not sure, got the error info over Twitter
- LBRY App version:
- LBRY Installation ID:
- Operating system:

## Screenshots

![image](https://user-images.githubusercontent.com/13907896/33335824-2d02e9f6-d43c-11e7-9c5c-6fef4b919bf7.png)

**Comment by tzarebczan** [comment]
Most likely the same as https://github.com/lbryio/lbry-app/issues/748
