### ISSUE TITLE
File cards are cutoff on the home page after resizing the app

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-app#795]
## The Issue
When scrolling all the way to the right on the trending section, the last video is cut off slightly

<img width="400" alt="screen shot 2017-11-28 at 11 16 34 pm" src="https://user-images.githubusercontent.com/16882830/33357757-4864f936-d492-11e7-81e9-9ba1c26ae095.png">

### Steps to reproduce
1. Load the app home page
2. Make the the app smaller by dragging one of the edges
3. Click on the ">" arrow until you reach the end
4. See cutoff file

### Expected behaviour
I should be able to see the entire card

**Comment by seanyesmunt** [comment]
This only happens for small screen sizes

**Comment by tzarebczan** [comment]
Fixed in the redesign.
