### ISSUE TITLE
Get more credits modal error

### ISSUE THREAD

**Issue by liamcardenas** [lbryio/lbry-app#801]
## The Issue
When the user has no credits and, in the wallet, clicks the "send tab", a modal pops up. when you click any button on the modal you get an error

<img width="1380" alt="screen shot 2017-11-29 at 4 39 32 pm" src="https://user-images.githubusercontent.com/5027235/33407040-669bdcc0-d524-11e7-8bd1-499c4fedec03.png">

### Steps to reproduce
1. have no credts
2. go to wallet
3. go to send tab
4. click button on modal

### Expected behaviour
It should not have an error

### Actual behaviour
See above

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system: OSX

## Screenshots

See above

**Comment by tzarebczan** [comment]
Which version are you on? Don't think this occurs on 0.18.2, so it might be a regressive issue.

**Comment by liamcardenas** [comment]
@tzarebczan you are right, this is no longer an issue. Odd (I don't think I was on an old version but this is clearly no longer a problem).
