### ISSUE TITLE
Win10: An App Default Was Reset" error for aac & m4a files on startup

### ISSUE THREAD

**Issue by icheyne** [lbryio/lbry-app#807]
### Steps to reproduce
1. Start lbry.io
2. See two errors:
* An App Default Was Reset for aac files
* An App Default Was Reset for m4a files

## System Configuration
- LBRY Daemon version: 0.18.0
- LBRY App version: 0.18.2
- LBRY Installation ID: 6he7dX74BiDuqUdEowvF1QVk9xj6LtS9LGdxWF9oBkDssUajXSGczDSiZYc2KreYCi
- Operating system:Windows (Windows-10-10.0.15063)

## Anything Else
I'm tempted to fix it with this, but it's just a workaround.
http://www.winhelponline.com/blog/windows-10-resetting-file-associations/

It could be that this is not a lbry.io bug but this has happed several times today when I'm starting lbry.io.

**Comment by tzarebczan** [comment]
@icheyne thanks for the report. I'll move this over to the correct repo.

Are you certain that the trigger is when you visit https://lbry.io ? What happens if you go to other sites with videos like youtube.com / hulu.com?

**Comment by tzarebczan** [comment]
Issue moved to [lbryio/lbry.io #263](https://github.com/lbryio/lbry.io/issues/263) via [**ZenHub**](https://www.zenhub.com/)
