### ISSUE TITLE
Add link to channel in the description of videos in that channel

### ISSUE THREAD

**Issue by Feanor78** [lbryio/lbry-app#814]
When a video is added under a channel, it would be great if the video's description was automatically appended with a link back to the channel it's in. That way if someone wants to watch a full season of a show or something, they can just pop back to the channel at the end of the episode. This would probably be obsolete with playlists, but in the meantime it would be helpful for users.

**Comment by hackrush01** [comment]
The channel name under the(before the publish date) is clickable. That could be used to navigate to the channel page. It is currently colored grey, but I think I remember it being green, to indicate it was clickable. Maybe we should bring that back.

**Comment by Feanor78** [comment]
I just noticed that, and was coming back to edit this and say "the channel name should be underlined and a different color than surrounding text to indicate it's a link" haha

**Comment by hackrush01** [comment]
Should be a small change, let me look into it.
