### ISSUE TITLE
Update JSON-RPC Expected Response Codes

### ISSUE THREAD

**Issue by liamcardenas** [lbryio/lbry-app#817]
As per https://github.com/lbryio/lbry/pull/1019, JSON-RPC will return a status code 200 and errors that comply with http://www.jsonrpc.org/specification#error_object

(additionally, it uses the error class name if no error message is provided)

This may have been handled already on the app side. We need to look into it and if not we need to handle this updated response.

**Comment by liamcardenas** [comment]
Ok, after going down a rabbit hole chasing down a the "trim" error (that nobody else other than myself gets -- as seen in the pics below), I have confirmed that this is working in the app

v18
<img width="1440" alt="screen shot 2017-12-06 at 5 10 56 pm" src="https://user-images.githubusercontent.com/5027235/33693686-00fa4476-daa9-11e7-802a-4b1430d71c80.png">

v19rc9
<img width="1440" alt="screen shot 2017-12-06 at 5 14 16 pm" src="https://user-images.githubusercontent.com/5027235/33693694-0e99ea96-daa9-11e7-8133-22eb5300f4dd.png">

As you can see, we are now expecting the new format and therefore there are lots of issues with v18. These issues are solved with v19rc9

Closing this, @kauffj @jackrobison

**Comment by kauffj** [comment]
@liamcardenas that trim error is real, I fixed it in branch.
