### ISSUE TITLE
Description is cleared if it was pasted through right click > paste

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#818]
## The Issue
This one was fun to nail down. Basically, if you paste a description using a right click>paste action, the description is cleared when you touch any other fields, including the last publish action. 

### Steps to reproduce
1. Right Click > paste some text into description
2. Change the channel / bid amount
3. Description is cleared

### Expected behaviour
don't clear the description

### Actual behaviour
the description is cleared

## System Configuration

 

- LBRY Daemon version: 0.18.0
- LBRY App version:0.18.2
- LBRY Installation ID:
- Operating system:

**Comment by liamcardenas** [comment]
@tzarebczan is this referring to the description while publishing?

**Comment by tzarebczan** [comment]
Yep, sorry for not directly stating that.

**Comment by tzarebczan** [comment]
Closing in favor of: https://github.com/lbryio/lbry-app/issues/1664
