### ISSUE TITLE
Settings page throws error on development

### ISSUE THREAD

**Issue by IGassmann** [lbryio/lbry-app#839]
## The Issue
The settings page throws an error when accessed using `webpack-dev-server`.

### Steps to reproduce
1. `yarn dev`
2. Open settings on app

## Anything Else
This happens because the action for listing themes try to access a filesystem path. Since on development the app is running on a web server, the path can't be accessed.

**Comment by lyoshenka** [comment]
closed by https://github.com/lbryio/lbry-app/pull/865
