### ISSUE TITLE
What are we using for analytics for the app?

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-app#844]
The LBRY app is open source and it is likely other people will fork it and take it in other directions. We want to make that as easy to do as possible.

Ideally, any analytics code would be cleanly separated from all other logic (e.g. if it were possible for analytics to dispatch events only by detecting/monitoring state changes?). Failing this, we should seek other patterns that minimize analytics calls being strewn throughout the code, and make it easy for them to be removed (or turned off).

**Comment by seanyesmunt** [comment]
I think it would be best to use middleware for any analytics events that are fired in response to state changes. 

Keep them out of the actions and reducers

**Comment by kauffj** [comment]
One pattern could be a separate reducer specific to analytics that adds analytics events to a processing queue when it observes actions that we want to record.

**Comment by liamcardenas** [comment]
Finished (and merged) with my latest PR, all analytics code is contained in one set up file. Nobody will need to worry about it.
