### ISSUE TITLE
Homepage Redesign

### ISSUE THREAD

**Issue by liamcardenas** [lbryio/lbry-app#849]
Latest design ideas:
![](http://lab.zzk.fr/lbry/redesign/app/homepage.jpg)
![](http://lab.zzk.fr/lbry/redesign/app/homepage+hero.jpg)
![](http://lab.zzk.fr/lbry/redesign/app/homepage+menu.jpg)
![](http://lab.zzk.fr/lbry/redesign/app/homepage+nightmode.jpg)
![](http://lab.zzk.fr/lbry/redesign/app/homepage+menu-open.jpg)
![](http://lab.zzk.fr/lbry/redesign/app/homepage-overview.jpg)

http://lab.zzk.fr/lbry/

**Comment by liamcardenas** [comment]
As I mentioned here https://github.com/lbryio/lbry-app/issues/510

I assume there will be trackpad scrolling on the homepage, correct?

**Comment by seanyesmunt** [comment]
I don't think so. I would like to avoid horizontal scrolling in the app.

**Comment by real-rouse** [comment]
I think vertical scrolling is better than horizontal scrolling.
I would rather click a category, e.g "Trending". and let all publications of that category fill the screen, so I can scroll down, down, down! Just like a webpage.

**Comment by seanyesmunt** [comment]
@real-rouse agreed 100%. Infinite scroll will be implemented at some point. Just not with this initial redesign
