### ISSUE TITLE
[redesign] Search refactoring

### ISSUE THREAD

**Issue by liamcardenas** [lbryio/lbry-app#850]
Latest design ideas:
![](http://lab.zzk.fr/lbry/redesign/app/homepage-search.jpg)
![](http://lab.zzk.fr/lbry/redesign/app/homepage-search+filter.jpg)

Also from @seanyesmunt:
![screenshot from 2017-12-11 14-39-21](https://user-images.githubusercontent.com/5027235/33857588-2617c5b8-de81-11e7-9673-661f85f505bd.png)

**Comment by seanyesmunt** [comment]
The new search experience will be quite a bit different. This will mostly be figuring how best to present this new search page.

Probably a full screen modal of sorts
