### ISSUE TITLE
[Bug] After upload a video and stay in the "Published" tab, it don't gets updated

### ISSUE THREAD

**Issue by Plasmmer** [lbryio/lbry-app#87]

**Comment by alexliebowitz** [comment]
Did it ever finally update (or disappear from the file manager)? If so, did it require a refresh or restarting the app?

**Comment by kauffj** [comment]
Duplicate of #227 and fixed in pull request.

**Comment by Plasmmer** [comment]
Not. #227 is a duplicate because my issue is the #87, logically it started first, despite #227 is more detailed.
