### ISSUE TITLE
LBRY API heartbeat to support Network Reward

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#871]
## The Issue
To support https://github.com/lbryio/internal-apis/issues/138#issuecomment-350000354, the LBRY app would need to ping the API server once a day so that the user is able to leave their LBRY app running and still qualify for the reward.

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tiger5226** [comment]
Keeping issues together. see #761
