### ISSUE TITLE
upgraded version v0.19 of app isn't launching.  also v0.18 stopped starting

### ISSUE THREAD

**Issue by painbank** [lbryio/lbry-app#872]
## The Issue

The LBRY app fails to start up.

### Steps to reproduce
1.  Remove older version v0.18 (18 was failing too) and Install v0.19 of the LBRY app.
2. Launch app.

### Expected behaviour

App should start up and connect.  If it fails, an alert informing the user of what to do to resolve or how report the issue.  Should not shut down until the user acknowledges it.

### Actual behaviour

Tries to catchup to the blockchain and then crashes out.  no errors reported to user.

## System Configuration

OSX Sierra - v10.12.6
macbook pro

{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "build": "release",
    "ip": "12.178.153.2",
    "lbrynet_version": "0.18.0",
    "lbryschema_version": "0.0.14",
    "lbryum_version": "3.1.11",
    "os_release": "16.7.0",
    "os_system": "Darwin",
    "platform": "Darwin-16.7.0-x86_64-i386-64bit",
    "processor": "i386",
    "python_version": "2.7.13"
  }
}

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

## Anything Else

from the lbrynet.log:

> 2017-12-12 16:06:43,153 ERROR    lbryum.interface:70: Failed to connect to (2, 1, 6, '', ('54.243.19.249', 50001))
> Traceback (most recent call last):
>   File "site-packages/lbryum/interface.py", line 65, in get_simple_socket
>   File "socket.py", line 228, in meth
> error: [Errno 60] Operation timed out
> 2017-12-12 16:06:43,200 ERROR    lbrynet.daemon.DaemonControl:100: Failed to start lbrynet-daemon
> Traceback (most recent call last):
>   File "site-packages/lbrynet/daemon/DaemonControl.py", line 97, in start_server_and_listen
> FirstError: FirstError[#1, [Failure instance: Traceback (failure with no frames): <type 'exceptions.ValueError'>: Failed to connect to network.
> ]]

**Comment by tzarebczan** [comment]
@painbank - I reached out to you on Discord. Looks like something may be blocking connectivity to the network on your end. Closing this for now.
