### ISSUE TITLE
Prevent get credits modal on negative balance / when sending amount greater than wallet balance

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#873]
## The Issue
Related to https://github.com/lbryio/lbry-app/issues/398 (which is still waiting on a daemon fix), the wallet balance may go negative (due to large utxo being spent/queuing system in the daemon) and the user gets a modal popup.  We should suppress this popup if the balance is negative. The balance returns to normal after a few seconds.

![negativebalance](https://user-images.githubusercontent.com/8120721/34019601-c6bfb6b4-e0fd-11e7-890e-cd2ea0d2c5af.PNG)

### Steps to reproduce
1. send larger LBC amount to wallet
2. Spend the LBC
3. try again

### Expected behaviour
Don't get prompted

### Actual behaviour
Tell us what happens instead

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
I don't think this is the app's job to fix. The daemon needs to not return a negative balance incorrectly.

We've had a PR open for this for several months, but it has some flaws as I understand it: https://github.com/lbryio/lbry/pull/747

**Comment by tzarebczan** [comment]
This is fixed in the redesign.
