### ISSUE TITLE
Error when publishing with exact amount in wallet or 0 bid

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#874]
## The Issue
There was a recent app side patch to address a deposit error when you don't have enough LBC, but it doesn't take into account the scenario if the bid is exactly equal to the wallet balance. This is most likely because there is a tx fee associated with the publish (no way to calculate this right now as it depends on what UTXOs the tx uses - this is something we'd need added to the daemon logic where the balance calculation should really reside).

![image](https://user-images.githubusercontent.com/18357967/32818565-e10738cc-c978-11e7-9a0d-88f7725e2005.png)

### Steps to reproduce
1. Have 1 LBC in wallet
2. Publish with 1 LBC bid
3. See error

### Expected behaviour
Insufficient balance error

### Actual behaviour
Ugly error

## System Configuration

 

- LBRY Daemon version: 0.18.0
- LBRY App version: 0..19.1
- LBRY Installation ID:
- Operating system: Windows

**Comment by liamcardenas** [comment]
So the solution is to get a daemon fix, correct? I am going to mark this as protocol dependent. Otherwise, we can just arbitrarily set a limit below your balance that is the maximum you can send. i.e. max send limit is your balance - .1 LBC (or whatever the upper limit of likely fees are)

**Comment by tzarebczan** [comment]
The UX around this has improved, no longer an issue in the redesign. Final adjustments will be made when the daemon can provide fee estimates.
