### ISSUE TITLE
Feature request: add "copy address to clipboard" button in the wallet

### ISSUE THREAD

**Issue by LavRadis** [lbryio/lbry-app#875]
## The Issue
Almost all wallets have "copy address to clipboard" button. It is just more convenient and safer (if you miss selecting the entire address while copying) 

### Expected behaviour
Just a simple button that copies current address to clipboard

## Anything Else
@liamcardenas and @lavradis could work on this

**Comment by liamcardenas** [comment]
@LavRadis is working on this

**Comment by seanyesmunt** [comment]
This should be really easy to add. There is a copybutton prop (called
something different) that I added for the shapeshift deposit address.

**Comment by kauffj** [comment]
I was curious how easy this was, and I found it was so simple that I just did it.

**Comment by tzarebczan** [comment]
Way to steal @LavRadis 's thunder... :p

**Comment by tzarebczan** [comment]
@LavRadis you should look at https://github.com/lbryio/lbry-app/issues/702 next - @seanyesmunt recently added this to the Shapeshift process so maybe it's not too difficult :)
