### ISSUE TITLE
Screen reloads when opening LBRY links with app running

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#882]
## The Issue
This may be windows specific - we get an ugly transition when lbry:// hyperlinks are launched while the app is running. See below. The transition is normally a lot faster (this is on a vm), but still noticeable.   Happens if the app is minimized to tray as well. This did not happen in v0.18.2.

![open link](https://user-images.githubusercontent.com/8120721/34171852-e892f134-e4bd-11e7-958e-dd3b9727a213.gif)

### Steps to reproduce
1. Have LBRY running
2. Click lbry:// link from https://lbry.io/news/rerez (channel link)
3. Notice re-opening of app. 

### Expected behaviour
Instant open to channel

### Actual behaviour
Ugly reload

## System Configuration

 

- LBRY Daemon version:0.18.0
- LBRY App version:0.19.1
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
@tzarebczan this is a production install, right?

**Comment by tzarebczan** [comment]
Correct, updated the ticket with version info.

**Comment by tzarebczan** [comment]
This doesn't seem to happen anymore.
