### ISSUE TITLE
Media Playback Redux State

### ISSUE THREAD

**Issue by liamcardenas** [lbryio/lbry-app#883]
- convert video pause settings to more generic media
- use [av listeners](https://www.w3schools.com/tags/ref_av_dom.asp) to store pause/play status, and [playback position](https://www.w3schools.com/tags/av_event_timeupdate.asp) in redux state
- remove [inaccurate pause state change](https://github.com/lbryio/lbry-app/pull/880#pullrequestreview-84569363)

**Comment by daovist** [comment]
I'm on top of it.
