### ISSUE TITLE
The following error occurred when attempting to publish your file: Cannot read property 'error' of undefined

### ISSUE THREAD

**Issue by ExtendLord** [lbryio/lbry-app#884]
## The Issue
Can't upload a video.
It says
"The following error occurred when attempting to publish your file: Cannot read property 'error' of undefined"
### Steps to reproduce
1.Go to publish
2.Create a Channel name
3.Choose file(Chose an MKV video), title thumbnail URL and Description,License(Any).
4.I agree
5.Publish

### Expected behaviour
Upload the video

### Actual behaviour
Showed an error.

## System Configuration

- LBRY Daemon version: 0.18.0
- LBRY App version: 0.19.1
- LBRY Installation ID: 7KtQWfMkeMqFyEHTdogwyNtBHmpAtSDrgBSnGD7y8j4hCmQXw6V9smewnoiQLWontg
- Operating system: Windows 10 pro x64 10.0.16299

## Screenshots

![image](https://user-images.githubusercontent.com/26222159/34184170-fe032872-e526-11e7-9b56-e894cce024bd.png)

**Comment by tzarebczan** [comment]
Did you recently just get the Lbc credits in your balance? We're aware of some issues publishing related to the bid amount, and it's most likely the same as this one: https://github.com/lbryio/lbry-app/issues/874

Check out the publishing guide at lbry.io/faq/how-to-publish

**Comment by tzarebczan** [comment]
Glad to hear it, thanks for trying out the app! Come join us on Discord (https://chat.lbry.io) for easier access to help and possibly contribute (https://lbry.io/faq/contributing)

**Comment by ExtendLord** [comment]
@tzarebczan I'm in the group already.
