### ISSUE TITLE
feature request and bug report

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry-app#889]
## The Issue
design application is now good, but need additional features so this can be better again. the features I mean are:
1. addition of subscriber feature number: this is meant for publisher to know how many subscriber he has in LBRY App.
2. Adding Menu Button "My Channel" or can also add it to the menu button "@" next to the tab menu subscribtion
3. Adding likes and unlike buttons on the bottom of the video player to make it even more cool.
4. when I publish the file in LBRY App. and clicking the language selection for the content I publish. it only consists of 7 default languages. but the content that I publish it speak Indonesian. (lbry: // @ Chris45 # b9dd2a4f193393b59ceac7a0dedef3bfef7ba82d / reviewlbryapp) it's my content link. please add "other" option and content box, so other users can fill it in accordance with the language of the content they publish.
5. if possible and in the future: LBRY app must go international. meaning is translate LBRY app to various languages ​​in the world. because according to my understanding not everyone knows English well.

Bug:
on my computer that has a 1028 * 768 resulution there is a bit of a truncation when I shift to the right of any content that is on the LBRY App homepage. so sometimes normal, sometimes truncated
there is a Screenshot for this:

that's the idea and feedback from me.thanks you so much

## System Configuration

 

- LBRY Daemon version: 0.18.0
- LBRY App version: 0.19.1
- LBRY Installation ID: 4HrrogG8zemVjZ4bbuggKehjmeZF6eUuX5pVqQijahpAVFpNrt2iuscGmGMfvwXu6j
- Operating system: Windows (Windows-10-10.0.15063)

## Screenshots

![image](https://user-images.githubusercontent.com/26609573/34232069-348609f6-e611-11e7-9797-5e8e6966cca8.png)
![image](https://user-images.githubusercontent.com/26609573/34232082-46111b0c-e611-11e7-8918-ae790541546c.png)

**Comment by tzarebczan** [comment]
@ykris45 thanks for submitting these, but GitHub issues should be for a specific feature request (with details) or a specific bug/issue. 

Feel free to open any you feel strongly about and we'll review.
