### ISSUE TITLE
The dameon has unexpectedly shutdown. 0.91.1

### ISSUE THREAD

**Issue by ScoobyJD** [lbryio/lbry-app#898]
The dameon has unexpectedly shutdown.

### Steps to reproduce
1. Install newest release and try to open

### Expected behaviour
It should work

### Actual behaviour
It didnt

## System Configuration

 

WHAT!?

- LBRY Daemon version: 0.91.1
- LBRY Installation ID: ?
- Operating system: Windows 10

**Comment by tzarebczan** [comment]
Please see https://lbry.io/faq/startup-troubleshooting for typical startup issues. 

Come chat with us on Discord - https://chat.lbry.io in #help if you need further assistance.
