### ISSUE TITLE
Uncaught Exception / cannot read property `match` of undefined random JS errors

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry-app#900]
## The Issue
My Windows install didn't have an email connected to the account so I went to settings->help and I linked my email.
Upon pasting my token into the app i received the following message: https://scrn.storni.info/Help_2017-12-23_15-16-2512.png

![help_2017-12-23_15-16-2512](https://user-images.githubusercontent.com/8120721/34949701-da267414-f9de-11e7-94c2-06c3cd99b721.png)

### Steps to reproduce
1. link an email to lbry
2. solve the captcha
3. paste the JWT in the app and continue
4. raise an exception

### Expected behaviour
The application should continue running normally

### Actual behaviour
The application rises an exception each time I open the settings->help tab

## System Configuration

```
{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "build": "release",
    "ip": "***.***.177.176",
    "lbrynet_version": "0.18.0",
    "lbryschema_version": "0.0.14",
    "lbryum_version": "3.1.11",
    "os_release": "10",
    "os_system": "Windows",
    "platform": "Windows-10-10.0.15063",
    "processor": "Intel64 Family 6 Model 94 Stepping 3, GenuineIntel",
    "python_version": "2.7.14"
  }
}
```

**Comment by tzarebczan** [comment]
Was this on 0.19.2?

**Comment by nikooo777** [comment]
yes. the very latest.  tried verifying niko at- storni dot info if you want to verify. Tho i'm sure i already had an account on that address so something must have happened there

**Comment by tzarebczan** [comment]
Anything in console or the network tab?

**Comment by nikooo777** [comment]
Couldn't check as it suddenly started working after a while. 
It went even after a restart of the app and it continued to pop up for 3 times every 10 minutes or so before settling.

**Comment by tzarebczan** [comment]
@nikooo777 can I close this?

**Comment by nikooo777** [comment]
If i was an exception to the rule sure

**Comment by liamcardenas** [comment]
Very odd, I am tempted to close this because no one else has had this issue, but maybe its worth looking into... I think I will keep it open for now.

Thanks for logging this!

**Comment by tzarebczan** [comment]
I ran into this today on a machine that's not linked to any emails. It would get stuck on looking up version info - I think it has something to do with the install ID or the auth token not being available for whatever reason. 

Could not find anything in Console/Network tab that would cause it to happen. I did find my LBRY app in a frozen state before this occurred and I relaunched it without closing the daemon. 

I'll do some more troubleshooting tomorrow.

**Comment by tzarebczan** [comment]
I got this randomly on 2 machines yesterday/today, but it wasn't associated with the About section not loading and it went away after clicking out of it.

**Comment by painbank** [comment]
had this happen to me yesterday.  after waking up the mac book pro laptop from overnight sleep.
<img width="609" alt="screen shot 2017-04-10 at 9 39 55 am" src="https://user-images.githubusercontent.com/58357/35106871-6a3ffc18-fc3d-11e7-98fc-ae2c056536b3.png">

**Comment by painbank** [comment]
<img width="427" alt="screen shot 2018-01-17 at 11 40 41 am" src="https://user-images.githubusercontent.com/58357/35106892-828f7d7a-fc3d-11e7-876f-ded1a6b87652.png">

**Comment by tzarebczan** [comment]
Have not seen this occur in over a month, will close in the next week or two if it doesn't happen anymore.

**Comment by nikooo777** [comment]
hasn't resurfaced anymore. Closing this. If it happens again please reopen
