### ISSUE TITLE
Consider changing "Support" to "Tip" on claim pages

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#905]
## The Issue
Some users may be confused about what "support" means and even though it has a gift icon, they may not realize it's a tipping mechanism at first.

During some first run experiments, some users thought this was the support area for help :)

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
Agreed. This should be changed to tip.

**Comment by liamcardenas** [comment]
thoughts @reillysmith?

I think this is part of a larger discussion

**Comment by tzarebczan** [comment]
This is complete in the redesign.
