### ISSUE TITLE
Add LBC symbol next to LBC values throughout app

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#908]
## The Issue
Add LBC symbol next to everywhere that LBC appears in the app. Right now, the values may be confusing to new users who don't know what LBC or credits are. 

https://github.com/lbryio/lbry-app/issues/251 is for deciding the actual symbol, but it should be defined in one place anyway so that should not block this improvement.

**Comment by idontcar3** [comment]
allright i wanna do that, but... whats the chosen symbol hahaha there are too many

**Comment by liamcardenas** [comment]
related #251

**Comment by lyoshenka** [comment]
@idontcar3 just make sure it's defined in one place, then we can change it if necessary. pick any symbol you like, or use "LBC" if you're not sure

**Comment by seanyesmunt** [comment]
I would just use "LBC" for now. But if it is in a self contained component
it will be easy to change to a symbol (once we decide on one)

**Comment by kauffj** [comment]
@seanyesmunt `<CurrencySymbol>` exists (tho is seldom used)

**Comment by seanyesmunt** [comment]
I guess for now this issue should just use `CurrencySymbol` everywhere we
use LBC

**Comment by tzarebczan** [comment]
This is fixed in the redesign, https://github.com/lbryio/lbry-app/issues/251 still applies.
