### ISSUE TITLE
UI suggestions

### ISSUE THREAD

**Issue by Feanor78** [lbryio/lbry-app#912]
Some suggestions on UI improvement from some user testing done over the holidays:

1. Make it clearer that the search bar is the search bar, but if you press "enter" it will take you directly to the claim location you typed in. Maybe by default it should just be a search bar, and the first result returned would be the exact claim location searched for?

2. Instead of autofilling the "tip amount" box with a grayed-out 1.00, autofill it with text along the lines of "enter tip amount here", or clarify error message that results from clicking "tip" when there is no value in the tip amount box (something like "please tell us how much you'd like to tip" instead of a generic error).

**Comment by tzarebczan** [comment]
https://github.com/lbryio/lbry-app/issues/671

https://github.com/lbryio/lbry-app/issues/738

Both are on my wishlist night (just added the tag to the search one). 

Feel free to add comments to those!

**Comment by seanyesmunt** [comment]
👍

**Comment by liamcardenas** [comment]
Thanks for the input! Let's continue this conversation on the aforelinked issues :)
