### ISSUE TITLE
Cannot send tip, transaction failed

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#917]
## The Issue
Looks like this https://github.com/lbryio/lbry-app/commit/7cd25e777aded97a7609e084ccff4ae0c8240a94#diff-3382ad8a365bcbe5fdac5b0508c405c7R158 recent code change broke the tip function. It should be claim_id and not claimID.  

This is the current error: 
```
 "error": {
    "code": -32602,
    "message": "Extraneous parameters for wallet_send command: claimId"
  },
  "id": 113,
  "jsonrpc": "2.0"

```

being passed as:
```
"wallet_send"
params:
{claimId: "008401a48cecef2a13cf5376b696169bb36b18c6", amount: 1}
```

### Steps to reproduce
1. Try to support a claim
2.
3.

### Expected behaviour
Support goes through

### Actual behaviour
Support fails to send

## System Configuration

 

- LBRY Daemon version:0.18.0
- LBRY App version: 0.19.3
- LBRY Installation ID:
- Operating system:

**Comment by liamcardenas** [comment]
@IGassmann can you look into this?

**Comment by tzarebczan** [comment]
Tested the fix, LGTM
