### ISSUE TITLE
The latest app ask user to verify again. 

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry-app#919]
## The Issue
when one of the users updates the app to the latest version. LBRY application The latest version asks the user to verify the account when the user has been manually verified by LBRY Mods an hour ago. and should be when the user installs LBRY APP version 0.19.0 and verified, then when he updates the app to a higher version then no need to ask about verification again. and keep a check on the "reward eligble" section.
## System Configuration

 

- LBRY Daemon version: 0.18.0
- LBRY App version: 0.19.3
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
The user's rewards were disabled for duplicate accounts, reached out on Discord.
