### ISSUE TITLE
Claiming reward leaves reward still visible, and gives error. 

### ISSUE THREAD

**Issue by kcseb** [lbryio/lbry-app#923]
http://hfimg.pw/i/3g89q.png | http://hfimg.pw/i/adysu.png

Small issue. 

Sometimes, a reward will be claimed, only to remain ghosted and unclaimable

Recreate? Not exactly sure. It just happened after updating the LBRY application. 

It doesn't really effect much, but it just is a bit bothersome to have a reward that you cannot claim, and just sits there.

**Comment by tzarebczan** [comment]
@kcseb thanks for the report, but it's already filed under https://github.com/lbryio/lbry-app/issues/596
