### ISSUE TITLE
Clicking on PDF thumbnail triggers the blob PDF download and "Save As" menu

### ISSUE THREAD

**Issue by LavRadis** [lbryio/lbry-app#931]
## The Issue
I accidentally clicked on the PDF file thumbnail and the "save as" menu opened with "blob" pdf file download. 

### Steps to reproduce
1. Find a PDF file
2. Click on the thumbnail image 
3. "Save As" menu will appear with blob:pdf XXXXXXXXXXXXX.pdf file

### Expected behaviour
This should not happen? Files should be downloaded in the default download folder.

### Actual behaviour
When it appeared the first time I finished with two same pdf files with different names in two different locations.
Confirmed it in two different pdf files from different publishers, happened to Tom also

## System Configuration

- LBRY Daemon version: 0.18.0
- LBRY App version: 0.19.4
- LBRY Installation ID: 7tYN144rHXrspzJG9xLP28fi1JztXnbpKro6DBJEQyzBmXTyDgqRLfYsUvHYFVmMe2
- Operating system: Win 10

## Screenshots
![lbry pdf](https://user-images.githubusercontent.com/10566738/34693083-b14ef654-f4c2-11e7-99df-6d63765565a0.jpg)

**Comment by tzarebczan** [comment]
https://github.com/feross/render-media is supposed to support pdf, so not sure what's going on here, but we should definitely not be prompting to save as. 

Thanks for filing this @LavRadis, will send you a tip on Discord :)

**Comment by btzr-io** [comment]
External fix https://github.com/feross/render-media/pull/38

This would prevent electron from opening the menu, however electron isn't able to render pdf inside a subframes ( iframe / object ) yet :disappointed:

**Comment by btzr-io** [comment]
The next step would be to found a way to display .pdf files using a basic viewer / reader
See https://github.com/lbryio/lbry-app/issues/620#issuecomment-375822739
