### ISSUE TITLE
Add github.com/ollm/OpenComic so lbry-app has a built-in manga/comic reader

### ISSUE THREAD

**Issue by Googolplexbyte** [lbryio/lbry-app#932]
I think LBRY would be a good place to host manga and having an inbuilt reader would streamline the process.

Not sure if I've recommended the best software for it, but if open, free, and uses Electron just like the lbry-app.

**Comment by tzarebczan** [comment]
Thanks for opening this @Googolplexbyte. I'll send you some more LBC on Reddit :)

**Comment by Googolplexbyte** [comment]
You're too kind.

Happy to do it.

**Comment by btzr-io** [comment]
@tzarebczan We should merge this issue with #1377

**Comment by btzr-io** [comment]
@tzarebczan Yes!
> .cbr, .cbz, .cbt, .cba, .cb7

https://en.wikipedia.org/wiki/Comic_book_archive

**Comment by tzarebczan** [comment]
Closing this and leaving https://github.com/lbryio/lbry-app/issues/1377 open.
