### ISSUE TITLE
Phone Verification

### ISSUE THREAD

**Issue by liamcardenas** [lbryio/lbry-app#941]
Add the ability to verify phone numbers for reward eligibility

**Comment by MSFTserver** [comment]
can you block google voice numbers? just a concern as I could create 100 google voice phone numbers

**Comment by filipnyquist** [comment]
This might also need a api endpoint on api.lbry.io which handles the phone verification.

**Comment by ykris45** [comment]
https://github.com/lbryio/lbry-app/pull/946 referenced PR
