### ISSUE TITLE
When disk is full an error message pops up when trying to download but message isn't informative

### ISSUE THREAD

**Issue by Arrowana** [lbryio/lbry-app#944]
## The Issue
Error message is not helpful when disk is full, resulting in poor user experience when trying to stream/download a new video

### Steps to reproduce
1. Fill the disk space where the download LBRY download folder is set
2. Try to stream or download a video

### Expected behaviour
Error should be something like "Disk is full, please free up some disk space" or something like this

### Actual behaviour
Dialog appears with error:
> Error
> We're sorry that LBRY has encountered an error. This has been reported and we will investigate the problem.

when clicking on show more, it isn't helping either

> Error message: Failed to download lbry://backpropagation-calculus-appendix-to#0e8aae9a057e1bee194220f5daa0b94ebd802a5d, please try again. If this problem persists, visit https://lbry.io/faq/support for support.

I was well aware my disk was almost full, so I deleted a few files then the message disappeared.

## System Configuration

- LBRY Daemon version: 0.18.0
- LBRY App version: 0.19.4
- LBRY Installation ID: 8eqyvVbGDFpoufTAEDzUfXXUNn417DXGUxtX2vc7SZHL7TG7LzM2SgfD2w15sMTR5f
- Operating system: Ubuntu 14.04 64 bits

**Comment by tzarebczan** [comment]
We have a similar issue open for this on the daemon side, will close this one. 

https://github.com/lbryio/lbry/issues/994
