### ISSUE TITLE
[Feature] Basic Shortcuts on Watchpage.

### ISSUE THREAD

**Issue by samiguven** [lbryio/lbry-app#95]
Hi Team,

Basic shortcuts on the watchpage (video page) will enhance UX. I mean the most basic ones:

- [Space]: Play/Pause video
- [UpArrow]: Volume Up
- [DownArrow]: Volume Down
- [RightArrow]: Fast Forward
- [LeftArrow]: Fast Backward
- [F]: Toggle Fullscreen
- [Esc]: Exit Fullscreen

Best,
Sami

**Comment by lyoshenka** [comment]
Thanks for the feature request. We'd like to use github for issues and bugs only, and we track feature requests internally. I'm going to move this into our internal database.
