### ISSUE TITLE
Migrate to AppImage

### ISSUE THREAD

**Issue by IGassmann** [lbryio/lbry-app#953]
We should make the move to AppImage because of the following reasons:
 - Add [support to auto-update](https://github.com/electron-userland/electron-builder/tree/master/packages/electron-updater) for Linux.
- Incorporate necessary [dependencies inside the package](https://github.com/electron-userland/electron-builder/issues/1082).
- Supported by practically all Linux distributions.
- Supported by our [building tool](https://www.electron.build/configuration/linux#LinuxConfiguration-target).

**Comment by TheAssassin** [comment]
@IGassmann what happened to the issue? I don't see any AppImage downloads.

**Comment by IGassmann** [comment]
This issue was a duplicate of https://github.com/lbryio/lbry-app/issues/332. AppImage builds are coming with the next release.

**Comment by TheAssassin** [comment]
I see. Thanks.

**Comment by IGassmann** [comment]
After discussing the fact that you need to change the file permission to launch an AppImage package, it was decided to rollback our changes and not use AppImage. Our app will still be distributed as a `.deb` package for the time being.

That step is not intuitive and might result in an unpleasant experience for our users.

A possible solution for supporting non-deb distributions in the future will be to use snap builds.

**Comment by probonopd** [comment]
It's easy to make an AppImage executable:
https://discourse.appimage.org/t/how-to-make-an-appimage-executable/80

Besides, this is not an AppImage issue but I agree that desktop environments should handle ELF executables that are missing the executable bit more gracefully. Only the desktop environments can change that, so please open issues with them if you think this area needs improvement.

Please see https://github.com/AppImage/AppImageKit/issues/374.
