### ISSUE TITLE
UI glitch: recipient address field is smaller then the address 

### ISSUE THREAD

**Issue by LavRadis** [lbryio/lbry-app#958]
## The Issue

The "Recipient Address" field in the wallet is not long enough for certain addresses and it cuts off a small part of a beginning or end character. It could lead to confusion and wrong entry of the address.  

### Steps to reproduce
1. Just paste "bGSAgQZDvpLwQaVHuyVn1PUmR8HKwt9huB" in the recipient address field
2.
3.

### Expected behaviour
The text field should show the entire address clearly. 

### Actual behaviour
It looks like the recipient address field is not long enough for certain addresses. 

## System Configuration

- LBRY Daemon version: 0.18.0
- LBRY App version: 0.19.4
- LBRY Installation ID: 7tYN144rHXrspzJG9xLP28fi1JztXnbpKro6DBJEQyzBmXTyDgqRLfYsUvHYFVmMe2
- Operating system: Win 10

## Anything Else
I've tried to fix this by locally editing the app.asar file and increasing the field size from 60 to various sizes but with no success. 

## Screenshots

![lbry address field issue](https://user-images.githubusercontent.com/10566738/35165098-442c4958-fd4d-11e7-8554-cedef1602f2f.jpg)

**Comment by liamcardenas** [comment]
Thanks for submitting the issue @LavRadis!

@tzarebczan do you think this is an issue that needs to be fixed? I think this might also be taken care of in the redesign.

**Comment by seanyesmunt** [comment]
I think it's fine for now, it won't let you submit if it isn't a valid address.

**Comment by tzarebczan** [comment]
this is fixed in the redesign, @LavRadis please confirm/reopen.
