### ISSUE TITLE
Malformed LBRY URL causes app to show blank green screen

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#959]
## The Issue
If a user clicks a hyperlink such as lbry://badlink, (with a comma, or possibly other characters), the LBRY app shows a blank green screen. Need to refresh the app with ctrl-shift-R to reload.

### Steps to reproduce
1. Click https://open.lbry.io/badlink%2C and open with LBRY app
2. Notice blank green screen

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## System Configuration

 

- LBRY Daemon version: 018.0
- LBRY App version: 0.19.4
- LBRY Installation ID:
- Operating system:

**Comment by liamcardenas** [comment]
@IGassmann im going to take this for grooming because i need a few more issues, feel free to work on it, though

**Comment by miikkatu** [comment]
Commenting out this bit in lbryURI.js prevents the green screen. It seems that a URL is handled correctly, the thrown exception shows in the console, but the processing stops there.

Without this bit below, a bad URL just leads to the search page with "There's nothing at this location." message.

`const nameBadChars = (channelName || name).match(regexInvalidURI);
  if (nameBadChars) {
    throw new Error(
      __(
        `Invalid character %s in name: %s.`,
        nameBadChars.length === 1 ? '' : 's',
        nameBadChars.join(', ')
      )
    );
  }`

**Comment by kauffj** [comment]
Great research @miikkatu! We'd be happy to send you a tip for this. See: https://lbry.io/faq/tips

Additionally, I see you're a React dev. If you're interested in contributing more regularly, you learn more here: https://lbry.io/faq/contributing
