### ISSUE TITLE
[Feature] Playlists

### ISSUE THREAD

**Issue by samiguven** [lbryio/lbry-app#96]
Hi Team,

Playlists will be useful for content with episodes or music videos.

Best,
Sami

**Comment by Plasmmer** [comment]
Please, can you share your issues in the [#feedback](https://lbry.slack.com/messages/C544Q2RFS/) channel?

**Comment by lyoshenka** [comment]
Thanks for the feature request. We'd like to use github for issues and bugs only, and we track feature requests internally. I'm going to move this into our internal database.
