### ISSUE TITLE
[Bug] Splashscreen with infinite loading and 3 instances of app

### ISSUE THREAD

**Issue by Plasmmer** [lbryio/lbry-app#97]
<img src="http://image.prntscr.com/image/a711322fa78247288571f40eec9f14d6.png"/>

**Comment by Plasmmer** [comment]
[log.txt](https://github.com/lbryio/lbry-app/files/961778/log.txt)

**Comment by Plasmmer** [comment]
When I started app as administrator:
<img src="http://image.prntscr.com/image/7db16222cc714774a18b7f7e57b068cb.png"/>

**Comment by Plasmmer** [comment]
Chrome's console log:
[log.txt](https://github.com/lbryio/lbry-app/files/961913/log.txt)

**Comment by wallermadev** [comment]
Seems to be the app is failing to connect to the daemon running locally as i saw it in the screenshot you posted on slack it seems something is refusing you access to that port on your machine.

**Comment by wallermadev** [comment]
Issue resolved :)

**Comment by nikooo777** [comment]
this indeed happens when the daemon crashes or isn't running.
Just putting it here in case someone else happens here

**Comment by alexliebowitz** [comment]
Still a bug since we need to handle this case much more gracefully. Thanks for the report.

**Comment by kauffj** [comment]
It will now properly error out if it gets stuck. I'm closing this, though please open a new ticket if you continue to experience errors with daemon launching.
