### ISSUE TITLE
Ability to export wallet transactions to CSV format

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#976]
## The Issue
As an app user, I'd like a way to export all my wallet transactions and details to a csv file. This would allow users to perform an external analysis for various purposes.

**Comment by btzr-io** [comment]
@tzarebczan feature merged in https://github.com/lbryio/lbry-app/commit/c6daff53c5b3281db5892ae176c9aa93662763b4,
are you going to close this issue after the release :upside_down_face: ?

**Comment by tzarebczan** [comment]
Thanks @btzr-io , closing now. @liamcardenas , can you get some credits over to Baltazar for this PR? He's available on Discord.
