### ISSUE TITLE
Published claims are shown out of order

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#986]
## The Issue
Because of https://github.com/lbryio/lbry/issues/1098, newly published content does not show at the top of the Published list. This causes confusion because the user may think that their item was not published correctly.  

Currently, the app takes the output of claim_list_mine and reverses it, which produces incorrect results. We should order the published claims by height when using the "date" ordering mechanism. 

### Steps to reproduce
1. Publish a few items
2. Notice that new publishes may not show at the top of the list

### Expected behaviour
Newly published items should be at the top of the Published list

### Actual behaviour
Newly published items show randomly

## System Configuration

 

- LBRY Daemon version: 0.18.2
- LBRY App version: 0.20.0
- LBRY Installation ID:
- Operating system: Windows

**Comment by Jeremy1026** [comment]
pull request opened for this, https://github.com/lbryio/lbry-app/pull/1018
