### ISSUE TITLE
Figure out how to encourage subscriptions

### ISSUE THREAD

**Issue by liamcardenas** [lbryio/lbry-app#995]
We could:
- have subscriptions next to headers on the homepage
- have a popup on the subscription box on the file page encouraging people to subscribe
- have a row on the homepage that says "Who to follow"

**Comment by kauffj** [comment]
These are all decent ideas. The second one should happen for sure, though not necessarily a popup.

Two other ideas:
- Offer a reward for subscribing to n channels.
- Offer a reward for accessing a piece of content to a channel you are subscribed to within n time units of it being published.

**Comment by kauffj** [comment]
Whoops, I responded to this not seeing it was closed ;) I guess all 3 of these have already happened!
